;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 11/04/2007 14:40:57
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2838			GOTO	_main
$0004	$	_delayonems:
;ugeneral.ppas,3 :: 		procedure DelayOneMS;
;ugeneral.ppas,5 :: 		Delay_ms(1);
$0004	$3003			MOVLW	3
$0005	$1303			BCF	STATUS, RP1
$0006	$1283			BCF	STATUS, RP0
$0007	$00AB			MOVWF	STACK_11
$0008	$30FF			MOVLW	255
$0009	$00AA			MOVWF	STACK_10
$000A	$0BAB			DECFSZ	STACK_11, F
$000B	$280D			GOTO	$+2
$000C	$2810			GOTO	$+4
$000D	$0BAA			DECFSZ	STACK_10, F
$000E	$280D			GOTO	$-1
$000F	$280A			GOTO	$-5
$0010	$3096			MOVLW	150
$0011	$00AA			MOVWF	STACK_10
$0012	$0BAA			DECFSZ	STACK_10, F
$0013	$2812			GOTO	$-1
$0014	$0000			NOP
$0015	$	ugeneral_L_0:
;ugeneral.ppas,6 :: 		end;
$0015	$0008			RETURN
$0016	$	_delayms:
;ugeneral.ppas,11 :: 		Count:Word;
;ugeneral.ppas,13 :: 		for Count:=0 to Value-1 do
$0016	$1303			BCF	STATUS, RP1
$0017	$1283			BCF	STATUS, RP0
$0018	$018E			CLRF	_delayms_local_count
$0019	$018F			CLRF	_delayms_local_count+1
$001A	$3001			MOVLW	1
$001B	$020C			SUBWF	FARG_DelayMS, 0
$001C	$0090			MOVWF	FLOC_DelayMS+2
$001D	$3000			MOVLW	0
$001E	$1C03			BTFSS	STATUS, C
$001F	$3F01			ADDLW	1
$0020	$020D			SUBWF	FARG_DelayMS+1, 0
$0021	$0091			MOVWF	FLOC_DelayMS+3
$0022	$	ugeneral_L_2:
$0022	$080F			MOVF	_delayms_local_count+1, 0
$0023	$0211			SUBWF	FLOC_DelayMS+3, 0
$0024	$1D03			BTFSS	STATUS, Z
$0025	$2828			GOTO	L_DelayMS_0
$0026	$080E			MOVF	_delayms_local_count, 0
$0027	$0210			SUBWF	FLOC_DelayMS+2, 0
$0028	$	L_DelayMS_0:
$0028	$1C03			BTFSS	STATUS, C
$0029	$2837			GOTO	ugeneral_L_5
;ugeneral.ppas,14 :: 		DelayOneMS;
$002A	$2004			CALL	_delayonems
$002B	$080F			MOVF	_delayms_local_count+1, 0
$002C	$0611			XORWF	FLOC_DelayMS+3, 0
$002D	$1D03			BTFSS	STATUS, Z
$002E	$2831			GOTO	L_DelayMS_1
$002F	$0810			MOVF	FLOC_DelayMS+2, 0
$0030	$060E			XORWF	_delayms_local_count, 0
$0031	$	L_DelayMS_1:
$0031	$1903			BTFSC	STATUS, Z
$0032	$2837			GOTO	ugeneral_L_5
$0033	$	ugeneral_L_3:
$0033	$0A8E			INCF	_delayms_local_count, 1
$0034	$1903			BTFSC	STATUS, Z
$0035	$0A8F			INCF	_delayms_local_count+1, 1
$0036	$2822			GOTO	ugeneral_L_2
$0037	$	ugeneral_L_5:
$0037	$	ugeneral_L_1:
;ugeneral.ppas,15 :: 		end;
$0037	$0008			RETURN
$0038	$	_main:
;BidirectionalLEDFlasher.ppas,3 :: 		UGeneral;
;BidirectionalLEDFlasher.ppas,6 :: 		TRISA:=$FF;
$0038	$30FF			MOVLW	255
$0039	$1303			BCF	STATUS, RP1
$003A	$1683			BSF	STATUS, RP0
$003B	$0085			MOVWF	TRISA
;BidirectionalLEDFlasher.ppas,7 :: 		TRISB:=$00;
$003C	$0186			CLRF	TRISB, 1
;BidirectionalLEDFlasher.ppas,9 :: 		while True do
$003D	$	BidirectionalLEDFlasher_L_2:
;BidirectionalLEDFlasher.ppas,11 :: 		PORTB.0:=0;
$003D	$1283			BCF	STATUS, RP0
$003E	$1006			BCF	PORTB, 0
$003F	$	BidirectionalLEDFlasher_L_7:
;BidirectionalLEDFlasher.ppas,12 :: 		PORTB.1:=1;
$003F	$	BidirectionalLEDFlasher_L_8:
$003F	$1486			BSF	PORTB, 1
$0040	$	BidirectionalLEDFlasher_L_9:
;BidirectionalLEDFlasher.ppas,14 :: 		if PORTA.0=0 then
$0040	$3001			MOVLW	1
$0041	$0505			ANDWF	PORTA, 0
$0042	$00A1			MOVWF	STACK_1
$0043	$0821			MOVF	STACK_1, 0
$0044	$3A00			XORLW	0
$0045	$1D03			BTFSS	STATUS, Z
$0046	$284D			GOTO	BidirectionalLEDFlasher_L_11
$0047	$	BidirectionalLEDFlasher_L_10:
;BidirectionalLEDFlasher.ppas,15 :: 		DelayMS(500)
$0047	$30F4			MOVLW	244
$0048	$008C			MOVWF	FARG_DelayMS
$0049	$3001			MOVLW	1
$004A	$008D			MOVWF	FARG_DelayMS+1
$004B	$2016			CALL	_delayms
$004C	$2851			GOTO	BidirectionalLEDFlasher_L_12
;BidirectionalLEDFlasher.ppas,16 :: 		else
$004D	$	BidirectionalLEDFlasher_L_11:
;BidirectionalLEDFlasher.ppas,17 :: 		DelayMS(1);
$004D	$3001			MOVLW	1
$004E	$008C			MOVWF	FARG_DelayMS
$004F	$018D			CLRF	FARG_DelayMS+1
$0050	$2016			CALL	_delayms
$0051	$	BidirectionalLEDFlasher_L_12:
;BidirectionalLEDFlasher.ppas,19 :: 		PORTB.0:=1;
$0051	$	BidirectionalLEDFlasher_L_13:
$0051	$1406			BSF	PORTB, 0
$0052	$	BidirectionalLEDFlasher_L_14:
;BidirectionalLEDFlasher.ppas,20 :: 		PORTB.1:=0;
$0052	$1086			BCF	PORTB, 1
$0053	$	BidirectionalLEDFlasher_L_16:
;BidirectionalLEDFlasher.ppas,22 :: 		if PORTA.0=0 then
$0053	$3001			MOVLW	1
$0054	$0505			ANDWF	PORTA, 0
$0055	$00A1			MOVWF	STACK_1
$0056	$0821			MOVF	STACK_1, 0
$0057	$3A00			XORLW	0
$0058	$1D03			BTFSS	STATUS, Z
$0059	$2860			GOTO	BidirectionalLEDFlasher_L_18
$005A	$	BidirectionalLEDFlasher_L_17:
;BidirectionalLEDFlasher.ppas,23 :: 		DelayMS(500)
$005A	$30F4			MOVLW	244
$005B	$008C			MOVWF	FARG_DelayMS
$005C	$3001			MOVLW	1
$005D	$008D			MOVWF	FARG_DelayMS+1
$005E	$2016			CALL	_delayms
$005F	$2864			GOTO	BidirectionalLEDFlasher_L_19
;BidirectionalLEDFlasher.ppas,24 :: 		else
$0060	$	BidirectionalLEDFlasher_L_18:
;BidirectionalLEDFlasher.ppas,25 :: 		DelayMS(1);
$0060	$3001			MOVLW	1
$0061	$008C			MOVWF	FARG_DelayMS
$0062	$018D			CLRF	FARG_DelayMS+1
$0063	$2016			CALL	_delayms
$0064	$	BidirectionalLEDFlasher_L_19:
;BidirectionalLEDFlasher.ppas,26 :: 		end;
$0064	$283D			GOTO	BidirectionalLEDFlasher_L_2
;BidirectionalLEDFlasher.ppas,27 :: 		end.
$0065	$2865			GOTO	$
