;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 28/01/2007 14:19:57
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2A85			GOTO	_main
$00DF	$	_i2c_slave_receivebyte:
;ui2c.ppas,232 :: 		function I2C_Slave_ReceiveByte:Byte;
;ui2c.ppas,234 :: 		PIR1.SSPIF:=False;
$00DF	$1303			BCF	STATUS, RP1
$00E0	$1283			BCF	STATUS, RP0
$00E1	$118C			BCF	PIR1, 3
$00E2	$	ui2c_L_146:
;ui2c.ppas,235 :: 		while (PIR1.SSPIF=0) or (SSPSTAT.BF=0) do begin end;
$00E2	$	ui2c_L_148:
$00E2	$1303			BCF	STATUS, RP1
$00E3	$1283			BCF	STATUS, RP0
$00E4	$3000			MOVLW	0
$00E5	$198C			BTFSC	PIR1, 3
$00E6	$3001			MOVLW	1
$00E7	$00F1			MOVWF	STACK_1
$00E8	$0871			MOVF	STACK_1, 0
$00E9	$3A00			XORLW	0
$00EA	$30FF			MOVLW	255
$00EB	$1D03			BTFSS	STATUS, Z
$00EC	$3000			MOVLW	0
$00ED	$00F2			MOVWF	STACK_2
$00EE	$3001			MOVLW	1
$00EF	$1683			BSF	STATUS, RP0
$00F0	$0514			ANDWF	SSPSTAT, 0
$00F1	$00F1			MOVWF	STACK_1
$00F2	$0871			MOVF	STACK_1, 0
$00F3	$3A00			XORLW	0
$00F4	$30FF			MOVLW	255
$00F5	$1D03			BTFSS	STATUS, Z
$00F6	$3000			MOVLW	0
$00F7	$00F0			MOVWF	STACK_0
$00F8	$0872			MOVF	STACK_2, 0
$00F9	$04F0			IORWF	STACK_0, 1
$00FA	$0870			MOVF	STACK_0, 0
$00FB	$1D03			BTFSS	STATUS, Z
$00FC	$28E2			GOTO	ui2c_L_148
$00FD	$	ui2c_L_149:
;ui2c.ppas,236 :: 		Result:=SSPBUF;
$00FD	$1283			BCF	STATUS, RP0
$00FE	$0813			MOVF	SSPBUF, 0
$00FF	$1683			BSF	STATUS, RP0
$0100	$00A0			MOVWF	_i2c_slave_receivebyte_local_result
;ui2c.ppas,237 :: 		SSPSTAT.SSPOV:=False;
$0101	$1314			BCF	SSPSTAT, 6
$0102	$	ui2c_L_153:
;ui2c.ppas,238 :: 		PIR1.SSPIF:=False;
$0102	$1283			BCF	STATUS, RP0
$0103	$118C			BCF	PIR1, 3
$0104	$	ui2c_L_155:
$0104	$	ui2c_L_144:
$0104	$1683			BSF	STATUS, RP0
$0105	$0820			MOVF	_i2c_slave_receivebyte_local_result, 0
$0106	$00F0			MOVWF	STACK_0
;ui2c.ppas,239 :: 		end;
$0107	$0008			RETURN
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00EA			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00E9			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00EB			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0871			MOVF	STACK_1, 0
$000E	$1683			BSF	STATUS, RP0
$000F	$00AE			MOVWF	STSAVED_1
$0010	$0870			MOVF	STACK_0, 0
$0011	$00AD			MOVWF	STSAVED_0
;I2CMonitor.ppas,34 :: 		PortValue,OutputValue,I2CCommand,ReceivedData:Byte;
;I2CMonitor.ppas,36 :: 		if PORTC.0 then
$0012	$3001			MOVLW	1
$0013	$1283			BCF	STATUS, RP0
$0014	$0507			ANDWF	PORTC, 0
$0015	$00F2			MOVWF	STACK_2
$0016	$0872			MOVF	STACK_2, 0
$0017	$1903			BTFSC	STATUS, Z
$0018	$2851			GOTO	I2CMonitor_L_2
$0019	$	I2CMonitor_L_1:
;I2CMonitor.ppas,38 :: 		if INTCON.RBIE and INTCON.RBIF then
$0019	$3000			MOVLW	0
$001A	$198B			BTFSC	INTCON, 3
$001B	$3001			MOVLW	1
$001C	$00F3			MOVWF	STACK_3
$001D	$3001			MOVLW	1
$001E	$050B			ANDWF	INTCON, 0
$001F	$00F2			MOVWF	STACK_2
$0020	$0872			MOVF	STACK_2, 0
$0021	$0573			ANDWF	STACK_3, 0
$0022	$00F0			MOVWF	STACK_0
$0023	$0870			MOVF	STACK_0, 0
$0024	$1903			BTFSC	STATUS, Z
$0025	$2850			GOTO	I2CMonitor_L_5
$0026	$	I2CMonitor_L_4:
;I2CMonitor.ppas,40 :: 		PortValue:=PORTB;
$0026	$0806			MOVF	PORTB, 0
$0027	$00EC			MOVWF	_interrupt_local_portvalue
;I2CMonitor.ppas,41 :: 		INTCON.RBIF:=0;
$0028	$100B			BCF	INTCON, 0
$0029	$	I2CMonitor_L_8:
;I2CMonitor.ppas,43 :: 		if TransmitWriteCount<TransmitBufferSize then
$0029	$3040			MOVLW	64
$002A	$0220			SUBWF	_transmitwritecount, 0
$002B	$1803			BTFSC	STATUS, C
$002C	$284F			GOTO	I2CMonitor_L_10
$002D	$	I2CMonitor_L_9:
;I2CMonitor.ppas,45 :: 		OutputValue:=$30;
$002D	$3030			MOVLW	48
$002E	$00ED			MOVWF	_interrupt_local_outputvalue
;I2CMonitor.ppas,46 :: 		if PortValue.6 then
$002F	$3000			MOVLW	0
$0030	$1B6C			BTFSC	_interrupt_local_portvalue, 6
$0031	$3001			MOVLW	1
$0032	$00F2			MOVWF	STACK_2
$0033	$0872			MOVF	STACK_2, 0
$0034	$1903			BTFSC	STATUS, Z
$0035	$2837			GOTO	I2CMonitor_L_13
$0036	$	I2CMonitor_L_12:
;I2CMonitor.ppas,47 :: 		OutputValue.0:=1;
$0036	$	I2CMonitor_L_15:
$0036	$146D			BSF	_interrupt_local_outputvalue, 0
$0037	$	I2CMonitor_L_16:
$0037	$	I2CMonitor_L_13:
$0037	$	I2CMonitor_L_14:
;I2CMonitor.ppas,48 :: 		if PortValue.7 then
$0037	$3000			MOVLW	0
$0038	$1BEC			BTFSC	_interrupt_local_portvalue, 7
$0039	$3001			MOVLW	1
$003A	$00F2			MOVWF	STACK_2
$003B	$0872			MOVF	STACK_2, 0
$003C	$1903			BTFSC	STATUS, Z
$003D	$283F			GOTO	I2CMonitor_L_18
$003E	$	I2CMonitor_L_17:
;I2CMonitor.ppas,49 :: 		OutputValue.1:=1;
$003E	$	I2CMonitor_L_20:
$003E	$14ED			BSF	_interrupt_local_outputvalue, 1
$003F	$	I2CMonitor_L_21:
$003F	$	I2CMonitor_L_18:
$003F	$	I2CMonitor_L_19:
;I2CMonitor.ppas,51 :: 		TransmitBuffer[TransmitWriteIndex]:=OutputValue;
$003F	$3021			MOVLW	_transmitbuffer
$0040	$00F0			MOVWF	STACK_0
$0041	$0861			MOVF	_transmitwriteindex, 0
$0042	$07F0			ADDWF	STACK_0, 1
$0043	$0870			MOVF	STACK_0, 0
$0044	$0084			MOVWF	FSR
$0045	$086D			MOVF	_interrupt_local_outputvalue, 0
$0046	$0080			MOVWF	INDF
;I2CMonitor.ppas,52 :: 		Inc(TransmitWriteCount);
$0047	$0AA0			INCF	_transmitwritecount, 1
;I2CMonitor.ppas,53 :: 		Inc(TransmitWriteIndex);
$0048	$0AE1			INCF	_transmitwriteindex, 1
;I2CMonitor.ppas,54 :: 		if TransmitWriteIndex=TransmitBufferSize then
$0049	$0861			MOVF	_transmitwriteindex, 0
$004A	$3A40			XORLW	64
$004B	$1D03			BTFSS	STATUS, Z
$004C	$284E			GOTO	I2CMonitor_L_23
$004D	$	I2CMonitor_L_22:
;I2CMonitor.ppas,55 :: 		TransmitWriteIndex:=0;
$004D	$01E1			CLRF	_transmitwriteindex, 1
$004E	$	I2CMonitor_L_23:
$004E	$	I2CMonitor_L_24:
;I2CMonitor.ppas,56 :: 		end
$004E	$2850			GOTO	I2CMonitor_L_11
;I2CMonitor.ppas,57 :: 		else
$004F	$	I2CMonitor_L_10:
;I2CMonitor.ppas,59 :: 		PORTB.0:=1; // Buffer overflow.
$004F	$	I2CMonitor_L_25:
$004F	$1406			BSF	PORTB, 0
$0050	$	I2CMonitor_L_26:
;I2CMonitor.ppas,60 :: 		end;
$0050	$	I2CMonitor_L_11:
;I2CMonitor.ppas,61 :: 		end;
$0050	$	I2CMonitor_L_5:
$0050	$	I2CMonitor_L_6:
;I2CMonitor.ppas,62 :: 		end
$0050	$28D0			GOTO	I2CMonitor_L_3
;I2CMonitor.ppas,63 :: 		else
$0051	$	I2CMonitor_L_2:
;I2CMonitor.ppas,65 :: 		if PIE1.SSPIE and PIR1.SSPIF then
$0051	$3000			MOVLW	0
$0052	$1683			BSF	STATUS, RP0
$0053	$198C			BTFSC	PIE1, 3
$0054	$3001			MOVLW	1
$0055	$00F3			MOVWF	STACK_3
$0056	$3000			MOVLW	0
$0057	$1283			BCF	STATUS, RP0
$0058	$198C			BTFSC	PIR1, 3
$0059	$3001			MOVLW	1
$005A	$00F2			MOVWF	STACK_2
$005B	$0872			MOVF	STACK_2, 0
$005C	$0573			ANDWF	STACK_3, 0
$005D	$00F0			MOVWF	STACK_0
$005E	$0870			MOVF	STACK_0, 0
$005F	$1903			BTFSC	STATUS, Z
$0060	$28D0			GOTO	I2CMonitor_L_28
$0061	$	I2CMonitor_L_27:
;I2CMonitor.ppas,67 :: 		if (SSPSTAT.D_A=0) then // Command.
$0061	$3000			MOVLW	0
$0062	$1683			BSF	STATUS, RP0
$0063	$1A94			BTFSC	SSPSTAT, 5
$0064	$3001			MOVLW	1
$0065	$00F2			MOVWF	STACK_2
$0066	$0872			MOVF	STACK_2, 0
$0067	$3A00			XORLW	0
$0068	$1D03			BTFSS	STATUS, Z
$0069	$28CD			GOTO	I2CMonitor_L_31
$006A	$	I2CMonitor_L_30:
;I2CMonitor.ppas,69 :: 		if SSPSTAT.R_W then
$006A	$3000			MOVLW	0
$006B	$1914			BTFSC	SSPSTAT, 2
$006C	$3001			MOVLW	1
$006D	$00F2			MOVWF	STACK_2
$006E	$0872			MOVF	STACK_2, 0
$006F	$1903			BTFSC	STATUS, Z
$0070	$2872			GOTO	I2CMonitor_L_34
$0071	$	I2CMonitor_L_33:
;I2CMonitor.ppas,75 :: 		end
$0071	$28CB			GOTO	I2CMonitor_L_35
;I2CMonitor.ppas,76 :: 		else
$0072	$	I2CMonitor_L_34:
;I2CMonitor.ppas,78 :: 		if SSPSTAT.BF then
$0072	$3001			MOVLW	1
$0073	$0514			ANDWF	SSPSTAT, 0
$0074	$00F2			MOVWF	STACK_2
$0075	$0872			MOVF	STACK_2, 0
$0076	$1903			BTFSC	STATUS, Z
$0077	$28C9			GOTO	I2CMonitor_L_37
$0078	$	I2CMonitor_L_36:
;I2CMonitor.ppas,80 :: 		if PORTB.2 then PORTB.2:=0 else PORTB.2:=1; // Test!!!
$0078	$3000			MOVLW	0
$0079	$1283			BCF	STATUS, RP0
$007A	$1906			BTFSC	PORTB, 2
$007B	$3001			MOVLW	1
$007C	$00F2			MOVWF	STACK_2
$007D	$0872			MOVF	STACK_2, 0
$007E	$1903			BTFSC	STATUS, Z
$007F	$2882			GOTO	I2CMonitor_L_40
$0080	$	I2CMonitor_L_39:
$0080	$1106			BCF	PORTB, 2
$0081	$	I2CMonitor_L_43:
$0081	$2883			GOTO	I2CMonitor_L_41
$0082	$	I2CMonitor_L_40:
$0082	$	I2CMonitor_L_44:
$0082	$1506			BSF	PORTB, 2
$0083	$	I2CMonitor_L_45:
$0083	$	I2CMonitor_L_41:
;I2CMonitor.ppas,81 :: 		MandatoryByte:=SSPBUF; // Make sure this is not optimized out!
$0083	$0813			MOVF	SSPBUF, 0
$0084	$00E2			MOVWF	_mandatorybyte
;I2CMonitor.ppas,82 :: 		SSPSTAT.SSPOV:=False;
$0085	$1683			BSF	STATUS, RP0
$0086	$1314			BCF	SSPSTAT, 6
$0087	$	I2CMonitor_L_47:
;I2CMonitor.ppas,84 :: 		I2CCommand:=I2C_Slave_ReceiveByte;
$0087	$20DF			CALL	_i2c_slave_receivebyte
$0088	$0870			MOVF	STACK_0, 0
$0089	$1283			BCF	STATUS, RP0
$008A	$00EE			MOVWF	_interrupt_local_i2ccommand
;I2CMonitor.ppas,87 :: 		0:
$008B	$	I2CMonitor_L_50:
$008B	$086E			MOVF	_interrupt_local_i2ccommand, 0
$008C	$3A00			XORLW	0
$008D	$1D03			BTFSS	STATUS, Z
$008E	$28A7			GOTO	I2CMonitor_L_51
$008F	$	I2CMonitor_L_49:
;I2CMonitor.ppas,89 :: 		ReceivedData:=I2C_Slave_ReceiveByte;
$008F	$20DF			CALL	_i2c_slave_receivebyte
$0090	$0870			MOVF	STACK_0, 0
$0091	$1283			BCF	STATUS, RP0
$0092	$00EF			MOVWF	_interrupt_local_receiveddata
;I2CMonitor.ppas,91 :: 		if TransmitWriteCount<TransmitBufferSize then
$0093	$3040			MOVLW	64
$0094	$0220			SUBWF	_transmitwritecount, 0
$0095	$1803			BTFSC	STATUS, C
$0096	$28A6			GOTO	I2CMonitor_L_53
$0097	$	I2CMonitor_L_52:
;I2CMonitor.ppas,93 :: 		TransmitBuffer[TransmitWriteIndex]:=ReceivedData;
$0097	$3021			MOVLW	_transmitbuffer
$0098	$00F0			MOVWF	STACK_0
$0099	$0861			MOVF	_transmitwriteindex, 0
$009A	$07F0			ADDWF	STACK_0, 1
$009B	$0870			MOVF	STACK_0, 0
$009C	$0084			MOVWF	FSR
$009D	$086F			MOVF	_interrupt_local_receiveddata, 0
$009E	$0080			MOVWF	INDF
;I2CMonitor.ppas,94 :: 		Inc(TransmitWriteCount);
$009F	$0AA0			INCF	_transmitwritecount, 1
;I2CMonitor.ppas,95 :: 		Inc(TransmitWriteIndex);
$00A0	$0AE1			INCF	_transmitwriteindex, 1
;I2CMonitor.ppas,96 :: 		if TransmitWriteIndex=TransmitBufferSize then
$00A1	$0861			MOVF	_transmitwriteindex, 0
$00A2	$3A40			XORLW	64
$00A3	$1D03			BTFSS	STATUS, Z
$00A4	$28A6			GOTO	I2CMonitor_L_56
$00A5	$	I2CMonitor_L_55:
;I2CMonitor.ppas,97 :: 		TransmitWriteIndex:=0;
$00A5	$01E1			CLRF	_transmitwriteindex, 1
$00A6	$	I2CMonitor_L_56:
$00A6	$	I2CMonitor_L_57:
;I2CMonitor.ppas,98 :: 		end;
$00A6	$	I2CMonitor_L_53:
$00A6	$	I2CMonitor_L_54:
;I2CMonitor.ppas,99 :: 		end;
$00A6	$28C9			GOTO	I2CMonitor_L_48
$00A7	$	I2CMonitor_L_51:
;I2CMonitor.ppas,101 :: 		1:
$00A7	$	I2CMonitor_L_59:
$00A7	$086E			MOVF	_interrupt_local_i2ccommand, 0
$00A8	$3A01			XORLW	1
$00A9	$1D03			BTFSS	STATUS, Z
$00AA	$28C9			GOTO	I2CMonitor_L_60
$00AB	$	I2CMonitor_L_58:
;I2CMonitor.ppas,103 :: 		repeat
$00AB	$	I2CMonitor_L_61:
;I2CMonitor.ppas,104 :: 		ReceivedData:=I2C_Slave_ReceiveByte;
$00AB	$20DF			CALL	_i2c_slave_receivebyte
$00AC	$0870			MOVF	STACK_0, 0
$00AD	$1283			BCF	STATUS, RP0
$00AE	$00EF			MOVWF	_interrupt_local_receiveddata
;I2CMonitor.ppas,106 :: 		if TransmitWriteCount<TransmitBufferSize then
$00AF	$3040			MOVLW	64
$00B0	$0220			SUBWF	_transmitwritecount, 0
$00B1	$1803			BTFSC	STATUS, C
$00B2	$28C2			GOTO	I2CMonitor_L_67
$00B3	$	I2CMonitor_L_66:
;I2CMonitor.ppas,108 :: 		TransmitBuffer[TransmitWriteIndex]:=ReceivedData;
$00B3	$3021			MOVLW	_transmitbuffer
$00B4	$00F0			MOVWF	STACK_0
$00B5	$0861			MOVF	_transmitwriteindex, 0
$00B6	$07F0			ADDWF	STACK_0, 1
$00B7	$0870			MOVF	STACK_0, 0
$00B8	$0084			MOVWF	FSR
$00B9	$086F			MOVF	_interrupt_local_receiveddata, 0
$00BA	$0080			MOVWF	INDF
;I2CMonitor.ppas,109 :: 		Inc(TransmitWriteCount);
$00BB	$0AA0			INCF	_transmitwritecount, 1
;I2CMonitor.ppas,110 :: 		Inc(TransmitWriteIndex);
$00BC	$0AE1			INCF	_transmitwriteindex, 1
;I2CMonitor.ppas,111 :: 		if TransmitWriteIndex=TransmitBufferSize then
$00BD	$0861			MOVF	_transmitwriteindex, 0
$00BE	$3A40			XORLW	64
$00BF	$1D03			BTFSS	STATUS, Z
$00C0	$28C2			GOTO	I2CMonitor_L_70
$00C1	$	I2CMonitor_L_69:
;I2CMonitor.ppas,112 :: 		TransmitWriteIndex:=0;
$00C1	$01E1			CLRF	_transmitwriteindex, 1
$00C2	$	I2CMonitor_L_70:
$00C2	$	I2CMonitor_L_71:
;I2CMonitor.ppas,113 :: 		end;
$00C2	$	I2CMonitor_L_67:
$00C2	$	I2CMonitor_L_68:
;I2CMonitor.ppas,114 :: 		until ReceivedData=0;
$00C2	$	I2CMonitor_L_62:
$00C2	$086F			MOVF	_interrupt_local_receiveddata, 0
$00C3	$3A00			XORLW	0
$00C4	$1D03			BTFSS	STATUS, Z
$00C5	$28C7			GOTO	I2CMonitor_L_64
$00C6	$	I2CMonitor_L_65:
$00C6	$28C8			GOTO	I2CMonitor_L_63
$00C7	$	I2CMonitor_L_64:
$00C7	$28AB			GOTO	I2CMonitor_L_61
$00C8	$	I2CMonitor_L_63:
;I2CMonitor.ppas,115 :: 		end;
$00C8	$28C9			GOTO	I2CMonitor_L_48
$00C9	$	I2CMonitor_L_60:
$00C9	$	I2CMonitor_L_48:
;I2CMonitor.ppas,117 :: 		end;
$00C9	$	I2CMonitor_L_37:
$00C9	$	I2CMonitor_L_38:
$00C9	$1303			BCF	STATUS, RP1
$00CA	$1283			BCF	STATUS, RP0
;I2CMonitor.ppas,118 :: 		end;
$00CB	$	I2CMonitor_L_35:
$00CB	$1303			BCF	STATUS, RP1
$00CC	$1283			BCF	STATUS, RP0
;I2CMonitor.ppas,119 :: 		end;
$00CD	$	I2CMonitor_L_31:
$00CD	$	I2CMonitor_L_32:
$00CD	$1303			BCF	STATUS, RP1
$00CE	$1283			BCF	STATUS, RP0
;I2CMonitor.ppas,121 :: 		PIR1.SSPIF:=False;
$00CF	$118C			BCF	PIR1, 3
$00D0	$	I2CMonitor_L_73:
;I2CMonitor.ppas,122 :: 		end;
$00D0	$	I2CMonitor_L_28:
$00D0	$	I2CMonitor_L_29:
;I2CMonitor.ppas,123 :: 		end;
$00D0	$	I2CMonitor_L_3:
$00D0	$	I2CMonitor_L_0:
;I2CMonitor.ppas,124 :: 		end;
$00D0	$	L_Interrupt_end:
$00D0	$1683			BSF	STATUS, RP0
$00D1	$082E			MOVF	STSAVED_1, 0
$00D2	$00F1			MOVWF	STACK_1
$00D3	$082D			MOVF	STSAVED_0, 0
$00D4	$00F0			MOVWF	STACK_0
$00D5	$1283			BCF	STATUS, RP0
$00D6	$086B			MOVF	?savePCLATH, 0
$00D7	$008A			MOVWF	PCLATH
$00D8	$0869			MOVF	?saveFSR, 0
$00D9	$0084			MOVWF	FSR
$00DA	$0E6A			SWAPF	?saveSTATUS, 0
$00DB	$0083			MOVWF	STATUS
$00DC	$0EFF			SWAPF	STACK_15, 1
$00DD	$0E7F			SWAPF	STACK_15, 0
$00DE	$0009			RETFIE
$0108	$	_i2c_init:
;i2c_c34.ppas,7 :: 		
;i2c_c34.ppas,9 :: 		
$0108	$1303			BCF	STATUS, RP1
$0109	$1683			BSF	STATUS, RP0
$010A	$1314			BCF	SSPSTAT, 6
$010B	$	i2c_c34_L_2:
;i2c_c34.ppas,10 :: 		
$010B	$1394			BCF	SSPSTAT, 7
$010C	$	i2c_c34_L_4:
;i2c_c34.ppas,11 :: 		
$010C	$	i2c_c34_L_5:
$010C	$1607			BSF	TRISC, 4
$010D	$	i2c_c34_L_6:
;i2c_c34.ppas,12 :: 		
$010D	$	i2c_c34_L_7:
$010D	$1587			BSF	TRISC, 3
$010E	$	i2c_c34_L_8:
;i2c_c34.ppas,13 :: 		
$010E	$3038			MOVLW	56
$010F	$1283			BCF	STATUS, RP0
$0110	$0094			MOVWF	SSPCON
$0111	$	i2c_c34_L_0:
;i2c_c34.ppas,15 :: 		
$0111	$0008			RETURN
$0112	$	_delayonems:
;ugeneral.ppas,3 :: 		procedure DelayOneMS;
;ugeneral.ppas,5 :: 		Delay_ms(1);
$0112	$3005			MOVLW	5
$0113	$1303			BCF	STATUS, RP1
$0114	$1283			BCF	STATUS, RP0
$0115	$00FB			MOVWF	STACK_11
$0116	$30FF			MOVLW	255
$0117	$00FA			MOVWF	STACK_10
$0118	$0BFB			DECFSZ	STACK_11, F
$0119	$291B			GOTO	$+2
$011A	$291E			GOTO	$+4
$011B	$0BFA			DECFSZ	STACK_10, F
$011C	$291B			GOTO	$-1
$011D	$2918			GOTO	$-5
$011E	$30C5			MOVLW	197
$011F	$00FA			MOVWF	STACK_10
$0120	$0BFA			DECFSZ	STACK_10, F
$0121	$2920			GOTO	$-1
$0122	$0000			NOP
$0123	$0000			NOP
$0124	$	ugeneral_L_0:
;ugeneral.ppas,6 :: 		end;
$0124	$0008			RETURN
$0125	$	_i2c_is_idle:
;i2c_c34.ppas,21 :: 		
;i2c_c34.ppas,23 :: 		
$0125	$1303			BCF	STATUS, RP1
$0126	$1683			BSF	STATUS, RP0
$0127	$01A5			CLRF	_i2c_is_idle_local_result, 1
;i2c_c34.ppas,24 :: 		
$0128	$3000			MOVLW	0
$0129	$1914			BTFSC	SSPSTAT, 2
$012A	$3001			MOVLW	1
$012B	$00F1			MOVWF	STACK_1
$012C	$0871			MOVF	STACK_1, 0
$012D	$3A00			XORLW	0
$012E	$1D03			BTFSS	STATUS, Z
$012F	$2939			GOTO	i2c_c34_L_11
$0130	$	i2c_c34_L_10:
;i2c_c34.ppas,25 :: 		
$0130	$301F			MOVLW	31
$0131	$0511			ANDWF	SSPCON2, 0
$0132	$00F1			MOVWF	STACK_1
$0133	$0871			MOVF	STACK_1, 0
$0134	$3A00			XORLW	0
$0135	$1D03			BTFSS	STATUS, Z
$0136	$2939			GOTO	i2c_c34_L_14
$0137	$	i2c_c34_L_13:
$0137	$30FF			MOVLW	255
$0138	$00A5			MOVWF	_i2c_is_idle_local_result
$0139	$	i2c_c34_L_14:
$0139	$	i2c_c34_L_15:
$0139	$	i2c_c34_L_11:
$0139	$	i2c_c34_L_12:
$0139	$	i2c_c34_L_9:
$0139	$0825			MOVF	_i2c_is_idle_local_result, 0
$013A	$00F0			MOVWF	STACK_0
;i2c_c34.ppas,26 :: 		
$013B	$0008			RETURN
$013C	$	_i2c_setmastermode:
;ui2c.ppas,46 :: 		procedure I2C_SetMasterMode;
;ui2c.ppas,48 :: 		PIE1.SSPIE:=False; // Prevent our I2C interrupt handler from operating whilst we are master.
$013C	$1303			BCF	STATUS, RP1
$013D	$1683			BSF	STATUS, RP0
$013E	$118C			BCF	PIE1, 3
$013F	$	ui2c_L_13:
;ui2c.ppas,49 :: 		PIE2.BCLIE:=False; // Prevent our I2C interrupt handler from operating whilst we are master.
$013F	$118D			BCF	PIE2, 3
$0140	$	ui2c_L_15:
;ui2c.ppas,51 :: 		SSPCON.SSPEN:=False; // Reset I2C module.
$0140	$1283			BCF	STATUS, RP0
$0141	$1294			BCF	SSPCON, 5
$0142	$	ui2c_L_17:
;ui2c.ppas,52 :: 		if I2C_UseDebugSpeed then
$0142	$0863			MOVF	_i2c_usedebugspeed, 0
$0143	$1903			BTFSC	STATUS, Z
$0144	$294A			GOTO	ui2c_L_19
$0145	$	ui2c_L_18:
;ui2c.ppas,53 :: 		I2C_Init(20000)
$0145	$30B8			MOVLW	184
$0146	$1683			BSF	STATUS, RP0
$0147	$0093			MOVWF	SSPADD
$0148	$2108			CALL	_i2c_init
$0149	$294E			GOTO	ui2c_L_20
;ui2c.ppas,54 :: 		else
$014A	$	ui2c_L_19:
;ui2c.ppas,55 :: 		I2C_Init(100000);
$014A	$3024			MOVLW	36
$014B	$1683			BSF	STATUS, RP0
$014C	$0093			MOVWF	SSPADD
$014D	$2108			CALL	_i2c_init
$014E	$	ui2c_L_20:
$014E	$	ui2c_L_11:
;ui2c.ppas,56 :: 		end;
$014E	$0008			RETURN
$014F	$	_private_i2c_master_start:
;ui2c.ppas,73 :: 		function Private_I2C_Master_Start:Boolean;
;ui2c.ppas,76 :: 		Result:=False;
$014F	$1303			BCF	STATUS, RP1
$0150	$1683			BSF	STATUS, RP0
$0151	$01A5			CLRF	_private_i2c_master_start_local_result, 1
;ui2c.ppas,78 :: 		PIR1.SSPIF:=False;
$0152	$1283			BCF	STATUS, RP0
$0153	$118C			BCF	PIR1, 3
$0154	$	ui2c_L_27:
;ui2c.ppas,79 :: 		PIR2.BCLIF:=False; // Bus collision detect.
$0154	$118D			BCF	PIR2, 3
$0155	$	ui2c_L_29:
;ui2c.ppas,80 :: 		SSPCON2.SEN:=True;
$0155	$	ui2c_L_30:
$0155	$1683			BSF	STATUS, RP0
$0156	$1411			BSF	SSPCON2, 0
$0157	$	ui2c_L_31:
;ui2c.ppas,81 :: 		while PIR1.SSPIF=False do
$0157	$	ui2c_L_33:
$0157	$3000			MOVLW	0
$0158	$1283			BCF	STATUS, RP0
$0159	$198C			BTFSC	PIR1, 3
$015A	$3001			MOVLW	1
$015B	$00F1			MOVWF	STACK_1
$015C	$0871			MOVF	STACK_1, 0
$015D	$3A00			XORLW	0
$015E	$1D03			BTFSS	STATUS, Z
$015F	$296A			GOTO	ui2c_L_34
;ui2c.ppas,83 :: 		if PIR2.BCLIF then
$0160	$3000			MOVLW	0
$0161	$198D			BTFSC	PIR2, 3
$0162	$3001			MOVLW	1
$0163	$00F1			MOVWF	STACK_1
$0164	$0871			MOVF	STACK_1, 0
$0165	$1903			BTFSC	STATUS, Z
$0166	$2969			GOTO	ui2c_L_38
$0167	$	ui2c_L_37:
;ui2c.ppas,85 :: 		PIR2.BCLIF:=False;
$0167	$118D			BCF	PIR2, 3
$0168	$	ui2c_L_41:
;ui2c.ppas,86 :: 		Exit;
$0168	$296E			GOTO	ui2c_L_25
;ui2c.ppas,87 :: 		end;
$0169	$	ui2c_L_38:
$0169	$	ui2c_L_39:
;ui2c.ppas,88 :: 		end;
$0169	$2957			GOTO	ui2c_L_33
$016A	$	ui2c_L_34:
;ui2c.ppas,90 :: 		PIR1.SSPIF:=False;
$016A	$118C			BCF	PIR1, 3
$016B	$	ui2c_L_43:
;ui2c.ppas,92 :: 		Result:=True;
$016B	$30FF			MOVLW	255
$016C	$1683			BSF	STATUS, RP0
$016D	$00A5			MOVWF	_private_i2c_master_start_local_result
$016E	$	ui2c_L_25:
$016E	$1303			BCF	STATUS, RP1
$016F	$1683			BSF	STATUS, RP0
$0170	$0825			MOVF	_private_i2c_master_start_local_result, 0
$0171	$00F0			MOVWF	STACK_0
;ui2c.ppas,93 :: 		end;
$0172	$0008			RETURN
$0173	$	_i2c_setslavemode:
;ui2c.ppas,33 :: 		procedure I2C_SetSlaveMode;
;ui2c.ppas,35 :: 		SSPCON.SSPEN:=False; // Reset I2C module.
$0173	$1303			BCF	STATUS, RP1
$0174	$1283			BCF	STATUS, RP0
$0175	$1294			BCF	SSPCON, 5
$0176	$	ui2c_L_2:
;ui2c.ppas,36 :: 		SSPADD:=I2C_SlaveAddress;
$0176	$0864			MOVF	_i2c_slaveaddress, 0
$0177	$1683			BSF	STATUS, RP0
$0178	$0093			MOVWF	SSPADD
;ui2c.ppas,37 :: 		SSPCON:=$36; // I2C slave mode.
$0179	$3036			MOVLW	54
$017A	$1283			BCF	STATUS, RP0
$017B	$0094			MOVWF	SSPCON
;ui2c.ppas,38 :: 		SSPCON2.GCEN:=True; // General call.
$017C	$	ui2c_L_3:
$017C	$1683			BSF	STATUS, RP0
$017D	$1791			BSF	SSPCON2, 7
$017E	$	ui2c_L_4:
;ui2c.ppas,40 :: 		PIR1.SSPIF:=False;
$017E	$1283			BCF	STATUS, RP0
$017F	$118C			BCF	PIR1, 3
$0180	$	ui2c_L_6:
;ui2c.ppas,41 :: 		PIE1.SSPIE:=True;
$0180	$	ui2c_L_7:
$0180	$1683			BSF	STATUS, RP0
$0181	$158C			BSF	PIE1, 3
$0182	$	ui2c_L_8:
;ui2c.ppas,43 :: 		PIE2.BCLIE:=False;
$0182	$118D			BCF	PIE2, 3
$0183	$	ui2c_L_10:
$0183	$	ui2c_L_0:
;ui2c.ppas,44 :: 		end;
$0183	$0008			RETURN
$0184	$	_delayms:
;ugeneral.ppas,11 :: 		Count:Word;
;ugeneral.ppas,13 :: 		for Count:=0 to Value-1 do
$0184	$1303			BCF	STATUS, RP1
$0185	$1683			BSF	STATUS, RP0
$0186	$01A7			CLRF	_delayms_local_count
$0187	$01A8			CLRF	_delayms_local_count+1
$0188	$3001			MOVLW	1
$0189	$0225			SUBWF	FARG_DelayMS, 0
$018A	$00A9			MOVWF	FLOC_DelayMS+2
$018B	$3000			MOVLW	0
$018C	$1C03			BTFSS	STATUS, C
$018D	$3F01			ADDLW	1
$018E	$0226			SUBWF	FARG_DelayMS+1, 0
$018F	$00AA			MOVWF	FLOC_DelayMS+3
$0190	$	ugeneral_L_2:
$0190	$0828			MOVF	_delayms_local_count+1, 0
$0191	$022A			SUBWF	FLOC_DelayMS+3, 0
$0192	$1D03			BTFSS	STATUS, Z
$0193	$2996			GOTO	L_DelayMS_0
$0194	$0827			MOVF	_delayms_local_count, 0
$0195	$0229			SUBWF	FLOC_DelayMS+2, 0
$0196	$	L_DelayMS_0:
$0196	$1C03			BTFSS	STATUS, C
$0197	$29A6			GOTO	ugeneral_L_5
;ugeneral.ppas,14 :: 		DelayOneMS;
$0198	$2112			CALL	_delayonems
$0199	$1683			BSF	STATUS, RP0
$019A	$0828			MOVF	_delayms_local_count+1, 0
$019B	$062A			XORWF	FLOC_DelayMS+3, 0
$019C	$1D03			BTFSS	STATUS, Z
$019D	$29A0			GOTO	L_DelayMS_1
$019E	$0829			MOVF	FLOC_DelayMS+2, 0
$019F	$0627			XORWF	_delayms_local_count, 0
$01A0	$	L_DelayMS_1:
$01A0	$1903			BTFSC	STATUS, Z
$01A1	$29A6			GOTO	ugeneral_L_5
$01A2	$	ugeneral_L_3:
$01A2	$0AA7			INCF	_delayms_local_count, 1
$01A3	$1903			BTFSC	STATUS, Z
$01A4	$0AA8			INCF	_delayms_local_count+1, 1
$01A5	$2990			GOTO	ugeneral_L_2
$01A6	$	ugeneral_L_5:
$01A6	$	ugeneral_L_1:
;ugeneral.ppas,15 :: 		end;
$01A6	$0008			RETURN
$01A7	$	_private_i2c_master_restart:
;ui2c.ppas,95 :: 		procedure Private_I2C_Master_Restart;
;ui2c.ppas,97 :: 		SSPCON2.RSEN:=True;
$01A7	$	ui2c_L_45:
$01A7	$1303			BCF	STATUS, RP1
$01A8	$1683			BSF	STATUS, RP0
$01A9	$1491			BSF	SSPCON2, 1
$01AA	$	ui2c_L_46:
;ui2c.ppas,98 :: 		while PIR1.SSPIF=False do begin end;
$01AA	$	ui2c_L_48:
$01AA	$3000			MOVLW	0
$01AB	$1283			BCF	STATUS, RP0
$01AC	$198C			BTFSC	PIR1, 3
$01AD	$3001			MOVLW	1
$01AE	$00F1			MOVWF	STACK_1
$01AF	$0871			MOVF	STACK_1, 0
$01B0	$3A00			XORLW	0
$01B1	$1903			BTFSC	STATUS, Z
$01B2	$29AA			GOTO	ui2c_L_48
$01B3	$	ui2c_L_49:
;ui2c.ppas,99 :: 		PIR1.SSPIF:=False;
$01B3	$118C			BCF	PIR1, 3
$01B4	$	ui2c_L_53:
$01B4	$	ui2c_L_44:
;ui2c.ppas,100 :: 		end;
$01B4	$0008			RETURN
$01B5	$	_private_i2c_master_acquirebusandstart:
;ui2c.ppas,102 :: 		procedure Private_I2C_Master_AcquireBusAndStart;
;ui2c.ppas,108 :: 		I2C_Started:=False;
$01B5	$1303			BCF	STATUS, RP1
$01B6	$1283			BCF	STATUS, RP0
$01B7	$01E5			CLRF	_i2c_started, 1
;ui2c.ppas,110 :: 		if I2C_MultiMasterMode then
$01B8	$0866			MOVF	_i2c_multimastermode, 0
$01B9	$1903			BTFSC	STATUS, Z
$01BA	$29D2			GOTO	ui2c_L_56
$01BB	$	ui2c_L_55:
;ui2c.ppas,112 :: 		while True do
$01BB	$	ui2c_L_59:
$01BB	$1303			BCF	STATUS, RP1
$01BC	$1283			BCF	STATUS, RP0
;ui2c.ppas,114 :: 		if I2C_Is_Idle then
$01BD	$2125			CALL	_i2c_is_idle
$01BE	$0870			MOVF	STACK_0, 0
$01BF	$1903			BTFSC	STATUS, Z
$01C0	$29CD			GOTO	ui2c_L_64
$01C1	$	ui2c_L_63:
;ui2c.ppas,116 :: 		I2C_SetMasterMode;
$01C1	$213C			CALL	_i2c_setmastermode
;ui2c.ppas,117 :: 		if Private_I2C_Master_Start then
$01C2	$214F			CALL	_private_i2c_master_start
$01C3	$0870			MOVF	STACK_0, 0
$01C4	$1903			BTFSC	STATUS, Z
$01C5	$29CA			GOTO	ui2c_L_67
$01C6	$	ui2c_L_66:
;ui2c.ppas,119 :: 		I2C_Started:=True;
$01C6	$30FF			MOVLW	255
$01C7	$1283			BCF	STATUS, RP0
$01C8	$00E5			MOVWF	_i2c_started
;ui2c.ppas,120 :: 		Exit; // Success.
$01C9	$29DD			GOTO	ui2c_L_54
;ui2c.ppas,121 :: 		end;
$01CA	$	ui2c_L_67:
$01CA	$	ui2c_L_68:
$01CA	$1303			BCF	STATUS, RP1
$01CB	$1283			BCF	STATUS, RP0
;ui2c.ppas,122 :: 		I2C_SetSlaveMode;
$01CC	$2173			CALL	_i2c_setslavemode
;ui2c.ppas,123 :: 		end;
$01CD	$	ui2c_L_64:
$01CD	$	ui2c_L_65:
;ui2c.ppas,125 :: 		DelayMS(10); // Arbitrary but longer than the longest time to handle an instruction. A random time would be better.
$01CD	$300A			MOVLW	10
$01CE	$00A5			MOVWF	FARG_DelayMS
$01CF	$01A6			CLRF	FARG_DelayMS+1
$01D0	$2184			CALL	_delayms
;ui2c.ppas,126 :: 		end;
$01D1	$29BB			GOTO	ui2c_L_59
;ui2c.ppas,128 :: 		else
$01D2	$	ui2c_L_56:
$01D2	$1303			BCF	STATUS, RP1
$01D3	$1683			BSF	STATUS, RP0
;ui2c.ppas,130 :: 		repeat until Private_I2C_Master_Start;
$01D4	$	ui2c_L_69:
$01D4	$	ui2c_L_70:
$01D4	$214F			CALL	_private_i2c_master_start
$01D5	$0870			MOVF	STACK_0, 0
$01D6	$1903			BTFSC	STATUS, Z
$01D7	$29D9			GOTO	ui2c_L_72
$01D8	$	ui2c_L_73:
$01D8	$29DA			GOTO	ui2c_L_71
$01D9	$	ui2c_L_72:
$01D9	$29D4			GOTO	ui2c_L_69
$01DA	$	ui2c_L_71:
;ui2c.ppas,131 :: 		I2C_Started:=True;
$01DA	$30FF			MOVLW	255
$01DB	$1283			BCF	STATUS, RP0
$01DC	$00E5			MOVWF	_i2c_started
;ui2c.ppas,132 :: 		end;
$01DD	$	ui2c_L_57:
$01DD	$	ui2c_L_54:
;ui2c.ppas,133 :: 		end;
$01DD	$0008			RETURN
$01DE	$	_i2c_master_sendbyte:
;ui2c.ppas,135 :: 		procedure I2C_Master_SendByte(Value:Byte);
;ui2c.ppas,137 :: 		SSPBUF:=Value;
$01DE	$1303			BCF	STATUS, RP1
$01DF	$1683			BSF	STATUS, RP0
$01E0	$0824			MOVF	FARG_I2C_Master_SendByte, 0
$01E1	$1283			BCF	STATUS, RP0
$01E2	$0093			MOVWF	SSPBUF
;ui2c.ppas,138 :: 		if SSPCON.WCOL then
$01E3	$3000			MOVLW	0
$01E4	$1B94			BTFSC	SSPCON, 7
$01E5	$3001			MOVLW	1
$01E6	$00F1			MOVWF	STACK_1
$01E7	$0871			MOVF	STACK_1, 0
$01E8	$1903			BTFSC	STATUS, Z
$01E9	$29ED			GOTO	ui2c_L_76
$01EA	$	ui2c_L_75:
;ui2c.ppas,140 :: 		I2C_Error:=I2C_WriteError;
$01EA	$3001			MOVLW	1
$01EB	$00E7			MOVWF	_i2c_error
;ui2c.ppas,141 :: 		SSPCON.WCOL:=False;
$01EC	$1394			BCF	SSPCON, 7
$01ED	$	ui2c_L_79:
;ui2c.ppas,142 :: 		end;
$01ED	$	ui2c_L_76:
$01ED	$	ui2c_L_77:
;ui2c.ppas,143 :: 		while PIR1.SSPIF=False do begin end;
$01ED	$	ui2c_L_81:
$01ED	$3000			MOVLW	0
$01EE	$198C			BTFSC	PIR1, 3
$01EF	$3001			MOVLW	1
$01F0	$00F1			MOVWF	STACK_1
$01F1	$0871			MOVF	STACK_1, 0
$01F2	$3A00			XORLW	0
$01F3	$1903			BTFSC	STATUS, Z
$01F4	$29ED			GOTO	ui2c_L_81
$01F5	$	ui2c_L_82:
;ui2c.ppas,144 :: 		PIR1.SSPIF:=False;
$01F5	$118C			BCF	PIR1, 3
$01F6	$	ui2c_L_86:
;ui2c.ppas,145 :: 		if SSPCON2.ACKSTAT then
$01F6	$3000			MOVLW	0
$01F7	$1683			BSF	STATUS, RP0
$01F8	$1B11			BTFSC	SSPCON2, 6
$01F9	$3001			MOVLW	1
$01FA	$00F1			MOVWF	STACK_1
$01FB	$0871			MOVF	STACK_1, 0
$01FC	$1903			BTFSC	STATUS, Z
$01FD	$2A01			GOTO	ui2c_L_88
$01FE	$	ui2c_L_87:
;ui2c.ppas,147 :: 		I2C_Error:=I2C_AckError;
$01FE	$3002			MOVLW	2
$01FF	$1283			BCF	STATUS, RP0
$0200	$00E7			MOVWF	_i2c_error
;ui2c.ppas,148 :: 		end;
$0201	$	ui2c_L_88:
$0201	$	ui2c_L_89:
$0201	$	ui2c_L_74:
$0201	$1303			BCF	STATUS, RP1
$0202	$1283			BCF	STATUS, RP0
;ui2c.ppas,149 :: 		end;
$0203	$0008			RETURN
$0204	$	_i2c_initialize:
;ui2c.ppas,58 :: 		procedure I2C_Initialize(SlaveAddress:Byte;MultiMasterMode,UseDebugSpeed:Boolean);
;ui2c.ppas,61 :: 		I2C_Started:=False;
$0204	$1303			BCF	STATUS, RP1
$0205	$1283			BCF	STATUS, RP0
$0206	$01E5			CLRF	_i2c_started, 1
;ui2c.ppas,62 :: 		I2C_Error:=0;
$0207	$01E7			CLRF	_i2c_error, 1
;ui2c.ppas,63 :: 		I2C_MultiMasterMode:=MultiMasterMode;
$0208	$1683			BSF	STATUS, RP0
$0209	$0822			MOVF	FARG_I2C_Initialize+1, 0
$020A	$1283			BCF	STATUS, RP0
$020B	$00E6			MOVWF	_i2c_multimastermode
;ui2c.ppas,64 :: 		I2C_UseDebugSpeed:=UseDebugSpeed;
$020C	$1683			BSF	STATUS, RP0
$020D	$0823			MOVF	FARG_I2C_Initialize+2, 0
$020E	$1283			BCF	STATUS, RP0
$020F	$00E3			MOVWF	_i2c_usedebugspeed
;ui2c.ppas,65 :: 		I2C_SlaveAddress:=SlaveAddress;
$0210	$1683			BSF	STATUS, RP0
$0211	$0821			MOVF	FARG_I2C_Initialize, 0
$0212	$1283			BCF	STATUS, RP0
$0213	$00E4			MOVWF	_i2c_slaveaddress
;ui2c.ppas,66 :: 		if MultiMasterMode then
$0214	$1683			BSF	STATUS, RP0
$0215	$0822			MOVF	FARG_I2C_Initialize+1, 0
$0216	$1903			BTFSC	STATUS, Z
$0217	$2A19			GOTO	ui2c_L_23
$0218	$	ui2c_L_22:
;ui2c.ppas,67 :: 		I2C_SetSlaveMode;
$0218	$2173			CALL	_i2c_setslavemode
$0219	$	ui2c_L_23:
$0219	$	ui2c_L_24:
$0219	$	ui2c_L_21:
;ui2c.ppas,68 :: 		end;
$0219	$0008			RETURN
$021A	$	_i2c_master_startwrite:
;ui2c.ppas,157 :: 		procedure I2C_Master_StartWrite(DeviceAddress:Byte);
;ui2c.ppas,159 :: 		if I2C_Started then
$021A	$1303			BCF	STATUS, RP1
$021B	$1283			BCF	STATUS, RP0
$021C	$0865			MOVF	_i2c_started, 0
$021D	$1903			BTFSC	STATUS, Z
$021E	$2A21			GOTO	ui2c_L_93
$021F	$	ui2c_L_92:
;ui2c.ppas,160 :: 		Private_I2C_Master_Restart
$021F	$21A7			CALL	_private_i2c_master_restart
$0220	$2A22			GOTO	ui2c_L_94
;ui2c.ppas,161 :: 		else
$0221	$	ui2c_L_93:
;ui2c.ppas,162 :: 		Private_I2C_Master_AcquireBusAndStart;
$0221	$21B5			CALL	_private_i2c_master_acquirebusandstart
$0222	$	ui2c_L_94:
;ui2c.ppas,164 :: 		I2C_Master_SendByte(DeviceAddress);
$0222	$1683			BSF	STATUS, RP0
$0223	$0821			MOVF	FARG_I2C_Master_StartWrite, 0
$0224	$00A4			MOVWF	FARG_I2C_Master_SendByte
$0225	$21DE			CALL	_i2c_master_sendbyte
$0226	$	ui2c_L_91:
;ui2c.ppas,165 :: 		end;
$0226	$0008			RETURN
$0227	$	_i2c_master_sendcommandwithbyteparameter:
;ui2c.ppas,189 :: 		procedure I2C_Master_SendCommandWithByteParameter(Command,Parameter:Byte);
;ui2c.ppas,191 :: 		I2C_Master_SendByte(Command);
$0227	$1303			BCF	STATUS, RP1
$0228	$1683			BSF	STATUS, RP0
$0229	$0821			MOVF	FARG_I2C_Master_SendCommandWithByteParameter, 0
$022A	$00A4			MOVWF	FARG_I2C_Master_SendByte
$022B	$21DE			CALL	_i2c_master_sendbyte
;ui2c.ppas,192 :: 		I2C_Master_SendByte(Parameter);
$022C	$1683			BSF	STATUS, RP0
$022D	$0822			MOVF	FARG_I2C_Master_SendCommandWithByteParameter+1, 0
$022E	$00A4			MOVWF	FARG_I2C_Master_SendByte
$022F	$21DE			CALL	_i2c_master_sendbyte
$0230	$	ui2c_L_112:
;ui2c.ppas,193 :: 		end;
$0230	$0008			RETURN
$0231	$	_i2c_master_stop:
;ui2c.ppas,177 :: 		procedure I2C_Master_Stop;
;ui2c.ppas,179 :: 		I2C_Started:=False;
$0231	$1303			BCF	STATUS, RP1
$0232	$1283			BCF	STATUS, RP0
$0233	$01E5			CLRF	_i2c_started, 1
;ui2c.ppas,181 :: 		SSPCON2.PEN:=True;
$0234	$	ui2c_L_100:
$0234	$1683			BSF	STATUS, RP0
$0235	$1511			BSF	SSPCON2, 2
$0236	$	ui2c_L_101:
;ui2c.ppas,182 :: 		while PIR1.SSPIF=False do begin end;
$0236	$	ui2c_L_103:
$0236	$3000			MOVLW	0
$0237	$1283			BCF	STATUS, RP0
$0238	$198C			BTFSC	PIR1, 3
$0239	$3001			MOVLW	1
$023A	$00F1			MOVWF	STACK_1
$023B	$0871			MOVF	STACK_1, 0
$023C	$3A00			XORLW	0
$023D	$1903			BTFSC	STATUS, Z
$023E	$2A36			GOTO	ui2c_L_103
$023F	$	ui2c_L_104:
;ui2c.ppas,183 :: 		PIR1.SSPIF:=False;
$023F	$118C			BCF	PIR1, 3
$0240	$	ui2c_L_108:
;ui2c.ppas,185 :: 		if I2C_MultiMasterMode then
$0240	$0866			MOVF	_i2c_multimastermode, 0
$0241	$1903			BTFSC	STATUS, Z
$0242	$2A44			GOTO	ui2c_L_110
$0243	$	ui2c_L_109:
;ui2c.ppas,186 :: 		I2C_SetSlaveMode;
$0243	$2173			CALL	_i2c_setslavemode
$0244	$	ui2c_L_110:
$0244	$	ui2c_L_111:
$0244	$	ui2c_L_99:
$0244	$1303			BCF	STATUS, RP1
$0245	$1683			BSF	STATUS, RP0
;ui2c.ppas,187 :: 		end;
$0246	$0008			RETURN
$0247	$	_i2c_master_sendcommandwithwordparameter:
;ui2c.ppas,195 :: 		procedure I2C_Master_SendCommandWithWordParameter(Command:Byte;Parameter:Word);
;ui2c.ppas,197 :: 		I2C_Master_SendByte(Command);
$0247	$1303			BCF	STATUS, RP1
$0248	$1683			BSF	STATUS, RP0
$0249	$0821			MOVF	FARG_I2C_Master_SendCommandWithWordParameter, 0
$024A	$00A4			MOVWF	FARG_I2C_Master_SendByte
$024B	$21DE			CALL	_i2c_master_sendbyte
;ui2c.ppas,198 :: 		I2C_Master_SendByte(Lo(Parameter));
$024C	$30FF			MOVLW	255
$024D	$1683			BSF	STATUS, RP0
$024E	$0522			ANDWF	FARG_I2C_Master_SendCommandWithWordParameter+1, 0
$024F	$00A4			MOVWF	FARG_I2C_Master_SendByte
$0250	$21DE			CALL	_i2c_master_sendbyte
;ui2c.ppas,199 :: 		I2C_Master_SendByte(Hi(Parameter));
$0251	$1683			BSF	STATUS, RP0
$0252	$0823			MOVF	FARG_I2C_Master_SendCommandWithWordParameter+2, 0
$0253	$00A4			MOVWF	FARG_I2C_Master_SendByte
$0254	$21DE			CALL	_i2c_master_sendbyte
$0255	$	ui2c_L_113:
;ui2c.ppas,200 :: 		end;
$0255	$0008			RETURN
$0256	$	_sendtransmitbuffer:
;I2CMonitor.ppas,128 :: 		Count:Byte;
;I2CMonitor.ppas,130 :: 		for Count:=0 to TransmitBufferSize-1 do
$0256	$1303			BCF	STATUS, RP1
$0257	$1683			BSF	STATUS, RP0
$0258	$01A1			CLRF	_sendtransmitbuffer_local_count, 1
$0259	$	I2CMonitor_L_75:
$0259	$0821			MOVF	_sendtransmitbuffer_local_count, 0
$025A	$3C3F			SUBLW	63
$025B	$1C03			BTFSS	STATUS, C
$025C	$2A82			GOTO	I2CMonitor_L_78
;I2CMonitor.ppas,132 :: 		if TransmitWriteCount=0 then break;
$025D	$1283			BCF	STATUS, RP0
$025E	$0820			MOVF	_transmitwritecount, 0
$025F	$3A00			XORLW	0
$0260	$1D03			BTFSS	STATUS, Z
$0261	$2A63			GOTO	I2CMonitor_L_80
$0262	$	I2CMonitor_L_79:
$0262	$2A82			GOTO	I2CMonitor_L_78
$0263	$	I2CMonitor_L_80:
$0263	$	I2CMonitor_L_81:
;I2CMonitor.ppas,134 :: 		repeat until PIR1.TXIF; // Wait for TX buffer empty.
$0263	$	I2CMonitor_L_82:
$0263	$	I2CMonitor_L_83:
$0263	$3000			MOVLW	0
$0264	$1A0C			BTFSC	PIR1, 4
$0265	$3001			MOVLW	1
$0266	$00F1			MOVWF	STACK_1
$0267	$0871			MOVF	STACK_1, 0
$0268	$1903			BTFSC	STATUS, Z
$0269	$2A6B			GOTO	I2CMonitor_L_85
$026A	$	I2CMonitor_L_86:
$026A	$2A6C			GOTO	I2CMonitor_L_84
$026B	$	I2CMonitor_L_85:
$026B	$2A63			GOTO	I2CMonitor_L_82
$026C	$	I2CMonitor_L_84:
;I2CMonitor.ppas,135 :: 		TXREG:=TransmitBuffer[TransmitReadIndex]; // Automatically clears PIR1.TXIF.
$026C	$3021			MOVLW	_transmitbuffer
$026D	$00F0			MOVWF	STACK_0
$026E	$0868			MOVF	_transmitreadindex, 0
$026F	$07F0			ADDWF	STACK_0, 1
$0270	$0870			MOVF	STACK_0, 0
$0271	$0084			MOVWF	FSR
$0272	$0800			MOVF	INDF, 0
$0273	$0099			MOVWF	TXREG
;I2CMonitor.ppas,137 :: 		Dec(TransmitWriteCount);
$0274	$03A0			DECF	_transmitwritecount, 1
;I2CMonitor.ppas,138 :: 		Inc(TransmitReadIndex);
$0275	$0AE8			INCF	_transmitreadindex, 1
;I2CMonitor.ppas,139 :: 		if TransmitReadIndex=TransmitBufferSize then
$0276	$0868			MOVF	_transmitreadindex, 0
$0277	$3A40			XORLW	64
$0278	$1D03			BTFSS	STATUS, Z
$0279	$2A7B			GOTO	I2CMonitor_L_88
$027A	$	I2CMonitor_L_87:
;I2CMonitor.ppas,140 :: 		TransmitReadIndex:=0;
$027A	$01E8			CLRF	_transmitreadindex, 1
$027B	$	I2CMonitor_L_88:
$027B	$	I2CMonitor_L_89:
;I2CMonitor.ppas,141 :: 		end;
$027B	$1683			BSF	STATUS, RP0
$027C	$0821			MOVF	_sendtransmitbuffer_local_count, 0
$027D	$3A3F			XORLW	63
$027E	$1903			BTFSC	STATUS, Z
$027F	$2A82			GOTO	I2CMonitor_L_78
$0280	$	I2CMonitor_L_76:
$0280	$0AA1			INCF	_sendtransmitbuffer_local_count, 1
$0281	$2A59			GOTO	I2CMonitor_L_75
$0282	$	I2CMonitor_L_78:
$0282	$	I2CMonitor_L_74:
$0282	$1303			BCF	STATUS, RP1
$0283	$1683			BSF	STATUS, RP0
;I2CMonitor.ppas,142 :: 		end;
$0284	$0008			RETURN
$0285	$	_main:
;I2CMonitor.ppas,145 :: 		OPTION_REG:=$50; // Set weak PORTB pullups (Bit 7=0).
$0285	$3050			MOVLW	80
$0286	$1303			BCF	STATUS, RP1
$0287	$1683			BSF	STATUS, RP0
$0288	$0081			MOVWF	OPTION_REG
;I2CMonitor.ppas,148 :: 		ADCON0:=$00;
$0289	$1283			BCF	STATUS, RP0
$028A	$019F			CLRF	ADCON0, 1
;I2CMonitor.ppas,149 :: 		ADCON1:=$06;
$028B	$3006			MOVLW	6
$028C	$1683			BSF	STATUS, RP0
$028D	$009F			MOVWF	ADCON1
;I2CMonitor.ppas,151 :: 		TRISA:=$FF;
$028E	$30FF			MOVLW	255
$028F	$0085			MOVWF	TRISA
;I2CMonitor.ppas,153 :: 		TRISB:=$FF;
$0290	$30FF			MOVLW	255
$0291	$0086			MOVWF	TRISB
;I2CMonitor.ppas,154 :: 		TRISB.0:=0; // Buffer overflow LED.
$0292	$1006			BCF	TRISB, 0
$0293	$	I2CMonitor_L_92:
;I2CMonitor.ppas,155 :: 		TRISB.1:=0; // Test LED.
$0293	$1086			BCF	TRISB, 1
$0294	$	I2CMonitor_L_94:
;I2CMonitor.ppas,156 :: 		TRISB.2:=0; // Test LED.
$0294	$1106			BCF	TRISB, 2
$0295	$	I2CMonitor_L_96:
;I2CMonitor.ppas,157 :: 		TRISB.6:=1; // I2C SCL.
$0295	$	I2CMonitor_L_97:
$0295	$1706			BSF	TRISB, 6
$0296	$	I2CMonitor_L_98:
;I2CMonitor.ppas,158 :: 		TRISB.7:=1; // I2C SDA.
$0296	$	I2CMonitor_L_99:
$0296	$1786			BSF	TRISB, 7
$0297	$	I2CMonitor_L_100:
;I2CMonitor.ppas,159 :: 		PORTB:=$00;
$0297	$1283			BCF	STATUS, RP0
$0298	$0186			CLRF	PORTB, 1
;I2CMonitor.ppas,161 :: 		TRISC:=$FF;
$0299	$30FF			MOVLW	255
$029A	$1683			BSF	STATUS, RP0
$029B	$0087			MOVWF	TRISC
;I2CMonitor.ppas,162 :: 		TRISC.6:=1; // RX
$029C	$	I2CMonitor_L_101:
$029C	$1707			BSF	TRISC, 6
$029D	$	I2CMonitor_L_102:
;I2CMonitor.ppas,163 :: 		TRISC.7:=1; // TX
$029D	$	I2CMonitor_L_103:
$029D	$1787			BSF	TRISC, 7
$029E	$	I2CMonitor_L_104:
;I2CMonitor.ppas,165 :: 		TransmitWriteCount:=0;
$029E	$1283			BCF	STATUS, RP0
$029F	$01A0			CLRF	_transmitwritecount, 1
;I2CMonitor.ppas,166 :: 		TransmitWriteIndex:=0;
$02A0	$01E1			CLRF	_transmitwriteindex, 1
;I2CMonitor.ppas,167 :: 		TransmitReadIndex:=0;
$02A1	$01E8			CLRF	_transmitreadindex, 1
;I2CMonitor.ppas,170 :: 		TransmitBuffer[TransmitWriteIndex]:=$40;
$02A2	$3021			MOVLW	_transmitbuffer
$02A3	$00F0			MOVWF	STACK_0
$02A4	$0870			MOVF	STACK_0, 0
$02A5	$0084			MOVWF	FSR
$02A6	$3040			MOVLW	64
$02A7	$0080			MOVWF	INDF
;I2CMonitor.ppas,171 :: 		Inc(TransmitWriteIndex);
$02A8	$0AE1			INCF	_transmitwriteindex, 1
;I2CMonitor.ppas,172 :: 		Inc(TransmitWriteCount);
$02A9	$0AA0			INCF	_transmitwritecount, 1
;I2CMonitor.ppas,174 :: 		I2C_Initialize(SlaveAddress,False,True);
$02AA	$3048			MOVLW	72
$02AB	$1683			BSF	STATUS, RP0
$02AC	$00A1			MOVWF	FARG_I2C_Initialize
$02AD	$01A2			CLRF	FARG_I2C_Initialize+1, 1
$02AE	$30FF			MOVLW	255
$02AF	$00A3			MOVWF	FARG_I2C_Initialize+2
$02B0	$2204			CALL	_i2c_initialize
;I2CMonitor.ppas,177 :: 		if PORTC.5 then
$02B1	$3000			MOVLW	0
$02B2	$1283			BCF	STATUS, RP0
$02B3	$1A87			BTFSC	PORTC, 5
$02B4	$3001			MOVLW	1
$02B5	$00F1			MOVWF	STACK_1
$02B6	$0871			MOVF	STACK_1, 0
$02B7	$1903			BTFSC	STATUS, Z
$02B8	$2AE2			GOTO	I2CMonitor_L_106
$02B9	$	I2CMonitor_L_105:
;I2CMonitor.ppas,179 :: 		I2C_SetMasterMode;
$02B9	$213C			CALL	_i2c_setmastermode
;I2CMonitor.ppas,181 :: 		DelayMS(100);
$02BA	$3064			MOVLW	100
$02BB	$1683			BSF	STATUS, RP0
$02BC	$00A5			MOVWF	FARG_DelayMS
$02BD	$01A6			CLRF	FARG_DelayMS+1
$02BE	$2184			CALL	_delayms
;I2CMonitor.ppas,184 :: 		repeat until PORTC.5=0;
$02BF	$	I2CMonitor_L_108:
$02BF	$	I2CMonitor_L_109:
$02BF	$1303			BCF	STATUS, RP1
$02C0	$1683			BSF	STATUS, RP0
$02C1	$3000			MOVLW	0
$02C2	$1283			BCF	STATUS, RP0
$02C3	$1A87			BTFSC	PORTC, 5
$02C4	$3001			MOVLW	1
$02C5	$00F1			MOVWF	STACK_1
$02C6	$0871			MOVF	STACK_1, 0
$02C7	$3A00			XORLW	0
$02C8	$1D03			BTFSS	STATUS, Z
$02C9	$2ACB			GOTO	I2CMonitor_L_111
$02CA	$	I2CMonitor_L_112:
$02CA	$2ACC			GOTO	I2CMonitor_L_110
$02CB	$	I2CMonitor_L_111:
$02CB	$2ABF			GOTO	I2CMonitor_L_108
$02CC	$	I2CMonitor_L_110:
;I2CMonitor.ppas,186 :: 		I2C_Master_StartWrite($00);
$02CC	$1683			BSF	STATUS, RP0
$02CD	$01A1			CLRF	FARG_I2C_Master_StartWrite, 1
$02CE	$221A			CALL	_i2c_master_startwrite
;I2CMonitor.ppas,187 :: 		I2C_Master_SendCommandWithByteParameter($FF,1); // Set debug I2C speed on all devices.
$02CF	$30FF			MOVLW	255
$02D0	$1683			BSF	STATUS, RP0
$02D1	$00A1			MOVWF	FARG_I2C_Master_SendCommandWithByteParameter
$02D2	$3001			MOVLW	1
$02D3	$00A2			MOVWF	FARG_I2C_Master_SendCommandWithByteParameter+1
$02D4	$2227			CALL	_i2c_master_sendcommandwithbyteparameter
;I2CMonitor.ppas,188 :: 		I2C_Master_Stop;
$02D5	$2231			CALL	_i2c_master_stop
;I2CMonitor.ppas,191 :: 		I2C_Master_StartWrite($28);
$02D6	$3028			MOVLW	40
$02D7	$00A1			MOVWF	FARG_I2C_Master_StartWrite
$02D8	$221A			CALL	_i2c_master_startwrite
;I2CMonitor.ppas,192 :: 		I2C_Master_SendCommandWithWordParameter($02,789);
$02D9	$3002			MOVLW	2
$02DA	$1683			BSF	STATUS, RP0
$02DB	$00A1			MOVWF	FARG_I2C_Master_SendCommandWithWordParameter
$02DC	$3015			MOVLW	21
$02DD	$00A2			MOVWF	FARG_I2C_Master_SendCommandWithWordParameter+1
$02DE	$3003			MOVLW	3
$02DF	$00A3			MOVWF	FARG_I2C_Master_SendCommandWithWordParameter+2
$02E0	$2247			CALL	_i2c_master_sendcommandwithwordparameter
;I2CMonitor.ppas,193 :: 		I2C_Master_Stop;
$02E1	$2231			CALL	_i2c_master_stop
;I2CMonitor.ppas,194 :: 		end;
$02E2	$	I2CMonitor_L_106:
$02E2	$	I2CMonitor_L_107:
$02E2	$1303			BCF	STATUS, RP1
$02E3	$1683			BSF	STATUS, RP0
;I2CMonitor.ppas,197 :: 		if PORTC.0=0 then
$02E4	$3001			MOVLW	1
$02E5	$1283			BCF	STATUS, RP0
$02E6	$0507			ANDWF	PORTC, 0
$02E7	$00F1			MOVWF	STACK_1
$02E8	$0871			MOVF	STACK_1, 0
$02E9	$3A00			XORLW	0
$02EA	$1D03			BTFSS	STATUS, Z
$02EB	$2AED			GOTO	I2CMonitor_L_114
$02EC	$	I2CMonitor_L_113:
;I2CMonitor.ppas,198 :: 		I2C_SetSlaveMode;
$02EC	$2173			CALL	_i2c_setslavemode
$02ED	$	I2CMonitor_L_114:
$02ED	$	I2CMonitor_L_115:
$02ED	$1303			BCF	STATUS, RP1
$02EE	$1683			BSF	STATUS, RP0
;I2CMonitor.ppas,201 :: 		SPBRG:=7; // Baud rate=14745600/(16(X+1). Speeds greater than 115200 require a pulldown resistor on TX to a negative supply.
$02EF	$3007			MOVLW	7
$02F0	$0099			MOVWF	SPBRG
;I2CMonitor.ppas,202 :: 		TXSTA:=%00000110;
$02F1	$3006			MOVLW	6
$02F2	$0098			MOVWF	TXSTA
;I2CMonitor.ppas,203 :: 		RCSTA:=%10000000;
$02F3	$3080			MOVLW	128
$02F4	$1283			BCF	STATUS, RP0
$02F5	$0098			MOVWF	RCSTA
;I2CMonitor.ppas,204 :: 		PIE1.TXIE:=0;
$02F6	$1683			BSF	STATUS, RP0
$02F7	$120C			BCF	PIE1, 4
$02F8	$	I2CMonitor_L_117:
;I2CMonitor.ppas,205 :: 		TXSTA.TXEN:=1;
$02F8	$	I2CMonitor_L_118:
$02F8	$1698			BSF	TXSTA, 5
$02F9	$	I2CMonitor_L_119:
;I2CMonitor.ppas,207 :: 		if PORTC.0=1 then
$02F9	$3001			MOVLW	1
$02FA	$1283			BCF	STATUS, RP0
$02FB	$0507			ANDWF	PORTC, 0
$02FC	$00F1			MOVWF	STACK_1
$02FD	$0871			MOVF	STACK_1, 0
$02FE	$3A01			XORLW	1
$02FF	$1D03			BTFSS	STATUS, Z
$0300	$2B02			GOTO	I2CMonitor_L_121
$0301	$	I2CMonitor_L_120:
;I2CMonitor.ppas,208 :: 		INTCON.3:=1; // Interrupt on PORTB bits 4 to 7 changed.
$0301	$	I2CMonitor_L_123:
$0301	$158B			BSF	INTCON, 3
$0302	$	I2CMonitor_L_124:
$0302	$	I2CMonitor_L_121:
$0302	$	I2CMonitor_L_122:
;I2CMonitor.ppas,210 :: 		INTCON.PEIE:=1;
$0302	$	I2CMonitor_L_125:
$0302	$170B			BSF	INTCON, 6
$0303	$	I2CMonitor_L_126:
;I2CMonitor.ppas,211 :: 		INTCON.GIE:=1;
$0303	$	I2CMonitor_L_127:
$0303	$178B			BSF	INTCON, 7
$0304	$	I2CMonitor_L_128:
;I2CMonitor.ppas,213 :: 		repeat
$0304	$	I2CMonitor_L_129:
;I2CMonitor.ppas,214 :: 		repeat until TransmitWriteCount<>0;
$0304	$	I2CMonitor_L_134:
$0304	$	I2CMonitor_L_135:
$0304	$0820			MOVF	_transmitwritecount, 0
$0305	$3A00			XORLW	0
$0306	$1903			BTFSC	STATUS, Z
$0307	$2B09			GOTO	I2CMonitor_L_137
$0308	$	I2CMonitor_L_138:
$0308	$2B0A			GOTO	I2CMonitor_L_136
$0309	$	I2CMonitor_L_137:
$0309	$2B04			GOTO	I2CMonitor_L_134
$030A	$	I2CMonitor_L_136:
;I2CMonitor.ppas,217 :: 		SendTransmitBuffer;
$030A	$2256			CALL	_sendtransmitbuffer
;I2CMonitor.ppas,218 :: 		Delay_MS(10); // Allow PC to receive and process block of data without flow control being required.
$030B	$3030			MOVLW	48
$030C	$00FB			MOVWF	STACK_11
$030D	$30FF			MOVLW	255
$030E	$00FA			MOVWF	STACK_10
$030F	$0BFB			DECFSZ	STACK_11, F
$0310	$2B12			GOTO	$+2
$0311	$2B15			GOTO	$+4
$0312	$0BFA			DECFSZ	STACK_10, F
$0313	$2B12			GOTO	$-1
$0314	$2B0F			GOTO	$-5
$0315	$30BF			MOVLW	191
$0316	$00FA			MOVWF	STACK_10
$0317	$0BFA			DECFSZ	STACK_10, F
$0318	$2B17			GOTO	$-1
$0319	$0000			NOP
;I2CMonitor.ppas,220 :: 		if PORTB.1=0 then PORTB.1:=1 else PORTB.1:=0;
$031A	$3000			MOVLW	0
$031B	$1283			BCF	STATUS, RP0
$031C	$1886			BTFSC	PORTB, 1
$031D	$3001			MOVLW	1
$031E	$00F1			MOVWF	STACK_1
$031F	$0871			MOVF	STACK_1, 0
$0320	$3A00			XORLW	0
$0321	$1D03			BTFSS	STATUS, Z
$0322	$2B25			GOTO	I2CMonitor_L_140
$0323	$	I2CMonitor_L_139:
$0323	$	I2CMonitor_L_142:
$0323	$1486			BSF	PORTB, 1
$0324	$	I2CMonitor_L_143:
$0324	$2B26			GOTO	I2CMonitor_L_141
$0325	$	I2CMonitor_L_140:
$0325	$1086			BCF	PORTB, 1
$0326	$	I2CMonitor_L_145:
$0326	$	I2CMonitor_L_141:
;I2CMonitor.ppas,221 :: 		until False;
$0326	$	I2CMonitor_L_130:
$0326	$	I2CMonitor_L_132:
$0326	$2B04			GOTO	I2CMonitor_L_129
;I2CMonitor.ppas,222 :: 		end.
$0327	$2B27			GOTO	$
