;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 05/03/2008 19:47:32
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2AC2			GOTO	_main
$0031	$	_i2c_slave_receivebyte:
;ui2c.ppas,224 :: 		function I2C_Slave_ReceiveByte:Byte;
;ui2c.ppas,226 :: 		PIR1.SSPIF:=False;
$0031	$1303			BCF	STATUS, RP1
$0032	$1283			BCF	STATUS, RP0
$0033	$118C			BCF	PIR1, 3
$0034	$	ui2c_L_140:
;ui2c.ppas,227 :: 		while (PIR1.SSPIF=0) or (SSPSTAT.BF=0) do begin end;
$0034	$	ui2c_L_142:
$0034	$3000			MOVLW	0
$0035	$198C			BTFSC	PIR1, 3
$0036	$3001			MOVLW	1
$0037	$00F1			MOVWF	STACK_1
$0038	$0871			MOVF	STACK_1, 0
$0039	$3A00			XORLW	0
$003A	$30FF			MOVLW	255
$003B	$1D03			BTFSS	STATUS, Z
$003C	$3000			MOVLW	0
$003D	$00F2			MOVWF	STACK_2
$003E	$3001			MOVLW	1
$003F	$1683			BSF	STATUS, RP0
$0040	$0514			ANDWF	SSPSTAT, 0
$0041	$1283			BCF	STATUS, RP0
$0042	$00F1			MOVWF	STACK_1
$0043	$0871			MOVF	STACK_1, 0
$0044	$3A00			XORLW	0
$0045	$30FF			MOVLW	255
$0046	$1D03			BTFSS	STATUS, Z
$0047	$3000			MOVLW	0
$0048	$00F0			MOVWF	STACK_0
$0049	$0872			MOVF	STACK_2, 0
$004A	$04F0			IORWF	STACK_0, 1
$004B	$0870			MOVF	STACK_0, 0
$004C	$1D03			BTFSS	STATUS, Z
$004D	$2834			GOTO	ui2c_L_142
$004E	$	ui2c_L_143:
;ui2c.ppas,228 :: 		Result:=SSPBUF;
$004E	$0813			MOVF	SSPBUF, 0
$004F	$00BA			MOVWF	_i2c_slave_receivebyte_local_result
;ui2c.ppas,229 :: 		SSPSTAT.SSPOV:=False;
$0050	$1683			BSF	STATUS, RP0
$0051	$1314			BCF	SSPSTAT, 6
$0052	$	ui2c_L_147:
;ui2c.ppas,230 :: 		PIR1.SSPIF:=False;
$0052	$1283			BCF	STATUS, RP0
$0053	$118C			BCF	PIR1, 3
$0054	$	ui2c_L_149:
$0054	$	ui2c_L_138:
$0054	$083A			MOVF	_i2c_slave_receivebyte_local_result, 0
$0055	$00F0			MOVWF	STACK_0
;ui2c.ppas,231 :: 		end;
$0056	$0008			RETURN
$0057	$	_div_8x8_u:
$0057	$1303			BCF	STATUS, RP1
$0058	$1283			BCF	STATUS, RP0
;math.ppas,87 :: 		
;math.ppas,90 :: 		
$0059	$01F8			CLRF	STACK_8, F
;math.ppas,91 :: 		
$005A	$3008			MOVLW	8
;math.ppas,92 :: 		
$005B	$00FC			MOVWF	STACK_12
;math.ppas,93 :: 		
$005C	$0D70			RLF	STACK_0, W
;math.ppas,94 :: 		
$005D	$0DF8			RLF	STACK_8, F
;math.ppas,95 :: 		
$005E	$0874			MOVF	STACK_4, W
;math.ppas,96 :: 		
$005F	$02F8			SUBWF	STACK_8, F
;math.ppas,97 :: 		
$0060	$1803			BTFSC	STATUS, C
;math.ppas,98 :: 		
$0061	$2864			GOTO	$+3
;math.ppas,99 :: 		
$0062	$07F8			ADDWF	STACK_8, F
;math.ppas,100 :: 		
$0063	$1003			BCF	STATUS, C
;math.ppas,101 :: 		
$0064	$0DF0			RLF	STACK_0, F
;math.ppas,102 :: 		
$0065	$0BFC			DECFSZ	STACK_12, F
;math.ppas,103 :: 		
$0066	$285C			GOTO	$-10
;math.ppas,104 :: 		
$0067	$	math_L_2:
;math.ppas,105 :: 		
$0067	$0008			RETURN
$0068	$	_i2cinterrupt:
;SecondBoardController.ppas,32 :: 		DiceValue:Byte;
;SecondBoardController.ppas,36 :: 		if PIE1.SSPIE=False then Exit;
$0068	$3000			MOVLW	0
$0069	$1303			BCF	STATUS, RP1
$006A	$1683			BSF	STATUS, RP0
$006B	$198C			BTFSC	PIE1, 3
$006C	$3001			MOVLW	1
$006D	$1283			BCF	STATUS, RP0
$006E	$00F2			MOVWF	STACK_2
$006F	$0872			MOVF	STACK_2, 0
$0070	$3A00			XORLW	0
$0071	$1D03			BTFSS	STATUS, Z
$0072	$2874			GOTO	SecondBoardController_L_2
$0073	$	SecondBoardController_L_1:
$0073	$2906			GOTO	SecondBoardController_L_0
$0074	$	SecondBoardController_L_2:
$0074	$	SecondBoardController_L_3:
;SecondBoardController.ppas,38 :: 		if PIR1.SSPIF then
$0074	$3000			MOVLW	0
$0075	$198C			BTFSC	PIR1, 3
$0076	$3001			MOVLW	1
$0077	$00F2			MOVWF	STACK_2
$0078	$0872			MOVF	STACK_2, 0
$0079	$1903			BTFSC	STATUS, Z
$007A	$2906			GOTO	SecondBoardController_L_5
$007B	$	SecondBoardController_L_4:
;SecondBoardController.ppas,40 :: 		if (SSPSTAT.D_A=0) then // Command.
$007B	$3000			MOVLW	0
$007C	$1683			BSF	STATUS, RP0
$007D	$1A94			BTFSC	SSPSTAT, 5
$007E	$3001			MOVLW	1
$007F	$1283			BCF	STATUS, RP0
$0080	$00F2			MOVWF	STACK_2
$0081	$0872			MOVF	STACK_2, 0
$0082	$3A00			XORLW	0
$0083	$1D03			BTFSS	STATUS, Z
$0084	$2905			GOTO	SecondBoardController_L_8
$0085	$	SecondBoardController_L_7:
;SecondBoardController.ppas,42 :: 		if SSPSTAT.R_W then
$0085	$3000			MOVLW	0
$0086	$1683			BSF	STATUS, RP0
$0087	$1914			BTFSC	SSPSTAT, 2
$0088	$3001			MOVLW	1
$0089	$1283			BCF	STATUS, RP0
$008A	$00F2			MOVWF	STACK_2
$008B	$0872			MOVF	STACK_2, 0
$008C	$1903			BTFSC	STATUS, Z
$008D	$288F			GOTO	SecondBoardController_L_11
$008E	$	SecondBoardController_L_10:
;SecondBoardController.ppas,48 :: 		end
$008E	$2905			GOTO	SecondBoardController_L_12
;SecondBoardController.ppas,49 :: 		else
$008F	$	SecondBoardController_L_11:
;SecondBoardController.ppas,51 :: 		if SSPSTAT.BF then
$008F	$3001			MOVLW	1
$0090	$1683			BSF	STATUS, RP0
$0091	$0514			ANDWF	SSPSTAT, 0
$0092	$1283			BCF	STATUS, RP0
$0093	$00F2			MOVWF	STACK_2
$0094	$0872			MOVF	STACK_2, 0
$0095	$1903			BTFSC	STATUS, Z
$0096	$2905			GOTO	SecondBoardController_L_14
$0097	$	SecondBoardController_L_13:
;SecondBoardController.ppas,53 :: 		MandatoryByte:=SSPBUF; // Make sure this is not optimized out!
$0097	$0813			MOVF	SSPBUF, 0
$0098	$00A0			MOVWF	_mandatorybyte
;SecondBoardController.ppas,54 :: 		SSPSTAT.SSPOV:=False;
$0099	$1683			BSF	STATUS, RP0
$009A	$1314			BCF	SSPSTAT, 6
$009B	$	SecondBoardController_L_17:
;SecondBoardController.ppas,56 :: 		I2CCommand:=I2C_Slave_ReceiveByte;
$009B	$2031			CALL	_i2c_slave_receivebyte
$009C	$0870			MOVF	STACK_0, 0
$009D	$00A1			MOVWF	_i2ccommand
;SecondBoardController.ppas,59 :: 		0:
$009E	$	SecondBoardController_L_20:
$009E	$0821			MOVF	_i2ccommand, 0
$009F	$3A00			XORLW	0
$00A0	$1D03			BTFSS	STATUS, Z
$00A1	$28A8			GOTO	SecondBoardController_L_21
$00A2	$	SecondBoardController_L_19:
;SecondBoardController.ppas,61 :: 		DigitMask:=I2C_Slave_ReceiveByte;
$00A2	$2031			CALL	_i2c_slave_receivebyte
$00A3	$0870			MOVF	STACK_0, 0
$00A4	$00A2			MOVWF	_digitmask
;SecondBoardController.ppas,62 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$00A5	$30FF			MOVLW	255
$00A6	$00A3			MOVWF	_interrupt_saveoptionstoeeprom
;SecondBoardController.ppas,63 :: 		end;
$00A7	$2905			GOTO	SecondBoardController_L_18
$00A8	$	SecondBoardController_L_21:
;SecondBoardController.ppas,65 :: 		1:
$00A8	$	SecondBoardController_L_23:
$00A8	$0821			MOVF	_i2ccommand, 0
$00A9	$3A01			XORLW	1
$00AA	$1D03			BTFSS	STATUS, Z
$00AB	$28BE			GOTO	SecondBoardController_L_24
$00AC	$	SecondBoardController_L_22:
;SecondBoardController.ppas,67 :: 		DisplayDots[0]:=I2C_Slave_ReceiveByte;
$00AC	$2031			CALL	_i2c_slave_receivebyte
$00AD	$0870			MOVF	STACK_0, 0
$00AE	$00A4			MOVWF	_displaydots+0
;SecondBoardController.ppas,68 :: 		DisplayDots[1]:=I2C_Slave_ReceiveByte;
$00AF	$2031			CALL	_i2c_slave_receivebyte
$00B0	$0870			MOVF	STACK_0, 0
$00B1	$00A5			MOVWF	_displaydots+1
;SecondBoardController.ppas,69 :: 		DisplayDots[2]:=I2C_Slave_ReceiveByte;
$00B2	$2031			CALL	_i2c_slave_receivebyte
$00B3	$0870			MOVF	STACK_0, 0
$00B4	$00A6			MOVWF	_displaydots+2
;SecondBoardController.ppas,70 :: 		DisplayDots[3]:=I2C_Slave_ReceiveByte;
$00B5	$2031			CALL	_i2c_slave_receivebyte
$00B6	$0870			MOVF	STACK_0, 0
$00B7	$00A7			MOVWF	_displaydots+3
;SecondBoardController.ppas,71 :: 		DisplayDots[4]:=I2C_Slave_ReceiveByte;
$00B8	$2031			CALL	_i2c_slave_receivebyte
$00B9	$0870			MOVF	STACK_0, 0
$00BA	$00A8			MOVWF	_displaydots+4
;SecondBoardController.ppas,72 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$00BB	$30FF			MOVLW	255
$00BC	$00A3			MOVWF	_interrupt_saveoptionstoeeprom
;SecondBoardController.ppas,73 :: 		end;
$00BD	$2905			GOTO	SecondBoardController_L_18
$00BE	$	SecondBoardController_L_24:
;SecondBoardController.ppas,75 :: 		2:
$00BE	$	SecondBoardController_L_26:
$00BE	$0821			MOVF	_i2ccommand, 0
$00BF	$3A02			XORLW	2
$00C0	$1D03			BTFSS	STATUS, Z
$00C1	$28DC			GOTO	SecondBoardController_L_27
$00C2	$	SecondBoardController_L_25:
;SecondBoardController.ppas,77 :: 		DiceValue:=I2C_Slave_ReceiveByte;
$00C2	$2031			CALL	_i2c_slave_receivebyte
$00C3	$0870			MOVF	STACK_0, 0
$00C4	$00B9			MOVWF	_i2cinterrupt_local_dicevalue
;SecondBoardController.ppas,78 :: 		if (DiceValue>=1) and (DiceValue<=6) then
$00C5	$3001			MOVLW	1
$00C6	$0270			SUBWF	STACK_0, 0
$00C7	$30FF			MOVLW	255
$00C8	$1C03			BTFSS	STATUS, C
$00C9	$3000			MOVLW	0
$00CA	$00F3			MOVWF	STACK_3
$00CB	$0870			MOVF	STACK_0, 0
$00CC	$3C06			SUBLW	6
$00CD	$30FF			MOVLW	255
$00CE	$1C03			BTFSS	STATUS, C
$00CF	$3000			MOVLW	0
$00D0	$00F2			MOVWF	STACK_2
$00D1	$0872			MOVF	STACK_2, 0
$00D2	$0573			ANDWF	STACK_3, 0
$00D3	$00F0			MOVWF	STACK_0
$00D4	$0870			MOVF	STACK_0, 0
$00D5	$1903			BTFSC	STATUS, Z
$00D6	$28DB			GOTO	SecondBoardController_L_29
$00D7	$	SecondBoardController_L_28:
;SecondBoardController.ppas,80 :: 		Interrupt_SetDiceValue:=DiceValue;
$00D7	$0839			MOVF	_i2cinterrupt_local_dicevalue, 0
$00D8	$00A9			MOVWF	_interrupt_setdicevalue
;SecondBoardController.ppas,81 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$00D9	$30FF			MOVLW	255
$00DA	$00A3			MOVWF	_interrupt_saveoptionstoeeprom
;SecondBoardController.ppas,82 :: 		end;
$00DB	$	SecondBoardController_L_29:
$00DB	$	SecondBoardController_L_30:
;SecondBoardController.ppas,83 :: 		end;
$00DB	$2905			GOTO	SecondBoardController_L_18
$00DC	$	SecondBoardController_L_27:
;SecondBoardController.ppas,85 :: 		3:
$00DC	$	SecondBoardController_L_32:
$00DC	$0821			MOVF	_i2ccommand, 0
$00DD	$3A03			XORLW	3
$00DE	$1D03			BTFSS	STATUS, Z
$00DF	$28EA			GOTO	SecondBoardController_L_33
$00E0	$	SecondBoardController_L_31:
;SecondBoardController.ppas,87 :: 		Interrupt_SetDiceValue:=1+(InterruptCount mod 6);
$00E0	$3006			MOVLW	6
$00E1	$00F4			MOVWF	STACK_4
$00E2	$082A			MOVF	_interruptcount, 0
$00E3	$00F0			MOVWF	STACK_0
$00E4	$2057			CALL	_div_8x8_u
$00E5	$0878			MOVF	STACK_8, 0
$00E6	$00F0			MOVWF	STACK_0
$00E7	$0A70			INCF	STACK_0, 0
$00E8	$00A9			MOVWF	_interrupt_setdicevalue
;SecondBoardController.ppas,88 :: 		end;
$00E9	$2905			GOTO	SecondBoardController_L_18
$00EA	$	SecondBoardController_L_33:
;SecondBoardController.ppas,90 :: 		4:
$00EA	$	SecondBoardController_L_35:
$00EA	$0821			MOVF	_i2ccommand, 0
$00EB	$3A04			XORLW	4
$00EC	$1D03			BTFSS	STATUS, Z
$00ED	$28F3			GOTO	SecondBoardController_L_36
$00EE	$	SecondBoardController_L_34:
;SecondBoardController.ppas,92 :: 		Interrupt_ToggleRelay:=True;
$00EE	$30FF			MOVLW	255
$00EF	$00AB			MOVWF	_interrupt_togglerelay
;SecondBoardController.ppas,93 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$00F0	$30FF			MOVLW	255
$00F1	$00A3			MOVWF	_interrupt_saveoptionstoeeprom
;SecondBoardController.ppas,94 :: 		end;
$00F2	$2905			GOTO	SecondBoardController_L_18
$00F3	$	SecondBoardController_L_36:
;SecondBoardController.ppas,96 :: 		5:
$00F3	$	SecondBoardController_L_38:
$00F3	$0821			MOVF	_i2ccommand, 0
$00F4	$3A05			XORLW	5
$00F5	$1D03			BTFSS	STATUS, Z
$00F6	$28FC			GOTO	SecondBoardController_L_39
$00F7	$	SecondBoardController_L_37:
;SecondBoardController.ppas,98 :: 		Interrupt_ToggleDots:=True;
$00F7	$30FF			MOVLW	255
$00F8	$00AC			MOVWF	_interrupt_toggledots
;SecondBoardController.ppas,99 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$00F9	$30FF			MOVLW	255
$00FA	$00A3			MOVWF	_interrupt_saveoptionstoeeprom
;SecondBoardController.ppas,100 :: 		end;
$00FB	$2905			GOTO	SecondBoardController_L_18
$00FC	$	SecondBoardController_L_39:
;SecondBoardController.ppas,102 :: 		999:
$00FC	$	SecondBoardController_L_41:
$00FC	$0821			MOVF	_i2ccommand, 0
$00FD	$3AE7			XORLW	231
$00FE	$1D03			BTFSS	STATUS, Z
$00FF	$2905			GOTO	SecondBoardController_L_42
$0100	$	SecondBoardController_L_40:
;SecondBoardController.ppas,104 :: 		Interrupt_SetDefaultOptions:=True;
$0100	$30FF			MOVLW	255
$0101	$00AD			MOVWF	_interrupt_setdefaultoptions
;SecondBoardController.ppas,105 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$0102	$30FF			MOVLW	255
$0103	$00A3			MOVWF	_interrupt_saveoptionstoeeprom
;SecondBoardController.ppas,106 :: 		end;
$0104	$2905			GOTO	SecondBoardController_L_18
$0105	$	SecondBoardController_L_42:
$0105	$	SecondBoardController_L_18:
;SecondBoardController.ppas,108 :: 		end;
$0105	$	SecondBoardController_L_14:
$0105	$	SecondBoardController_L_15:
;SecondBoardController.ppas,109 :: 		end;
$0105	$	SecondBoardController_L_12:
;SecondBoardController.ppas,110 :: 		end;
$0105	$	SecondBoardController_L_8:
$0105	$	SecondBoardController_L_9:
;SecondBoardController.ppas,112 :: 		PIR1.SSPIF:=False;
$0105	$118C			BCF	PIR1, 3
$0106	$	SecondBoardController_L_44:
;SecondBoardController.ppas,113 :: 		end;
$0106	$	SecondBoardController_L_5:
$0106	$	SecondBoardController_L_6:
$0106	$	SecondBoardController_L_0:
;SecondBoardController.ppas,114 :: 		end;
$0106	$0008			RETURN
$0107	$	_sevensegmentinterrupt:
;SecondBoardController.ppas,116 :: 		procedure SevenSegmentInterrupt;
;SecondBoardController.ppas,118 :: 		if INTCON.T0IE=False then Exit;
$0107	$3000			MOVLW	0
$0108	$1A8B			BTFSC	INTCON, 5
$0109	$3001			MOVLW	1
$010A	$1303			BCF	STATUS, RP1
$010B	$1283			BCF	STATUS, RP0
$010C	$00F2			MOVWF	STACK_2
$010D	$0872			MOVF	STACK_2, 0
$010E	$3A00			XORLW	0
$010F	$1D03			BTFSS	STATUS, Z
$0110	$2912			GOTO	SecondBoardController_L_47
$0111	$	SecondBoardController_L_46:
$0111	$2951			GOTO	SecondBoardController_L_45
$0112	$	SecondBoardController_L_47:
$0112	$	SecondBoardController_L_48:
;SecondBoardController.ppas,120 :: 		if INTCON.T0IF then
$0112	$3000			MOVLW	0
$0113	$190B			BTFSC	INTCON, 2
$0114	$3001			MOVLW	1
$0115	$00F2			MOVWF	STACK_2
$0116	$0872			MOVF	STACK_2, 0
$0117	$1903			BTFSC	STATUS, Z
$0118	$2951			GOTO	SecondBoardController_L_50
$0119	$	SecondBoardController_L_49:
;SecondBoardController.ppas,125 :: 		0:
$0119	$	SecondBoardController_L_54:
$0119	$082E			MOVF	_displaycolumnindex, 0
$011A	$3A00			XORLW	0
$011B	$1D03			BTFSS	STATUS, Z
$011C	$2922			GOTO	SecondBoardController_L_55
$011D	$	SecondBoardController_L_53:
;SecondBoardController.ppas,127 :: 		PORTC:=$01;
$011D	$3001			MOVLW	1
$011E	$0087			MOVWF	PORTC
;SecondBoardController.ppas,128 :: 		PORTB:=not DisplayDots[0];
$011F	$0924			COMF	_displaydots+0, W
$0120	$0086			MOVWF	PORTB
;SecondBoardController.ppas,129 :: 		end;
$0121	$294A			GOTO	SecondBoardController_L_52
$0122	$	SecondBoardController_L_55:
;SecondBoardController.ppas,131 :: 		1:
$0122	$	SecondBoardController_L_57:
$0122	$082E			MOVF	_displaycolumnindex, 0
$0123	$3A01			XORLW	1
$0124	$1D03			BTFSS	STATUS, Z
$0125	$292B			GOTO	SecondBoardController_L_58
$0126	$	SecondBoardController_L_56:
;SecondBoardController.ppas,133 :: 		PORTC:=$02;
$0126	$3002			MOVLW	2
$0127	$0087			MOVWF	PORTC
;SecondBoardController.ppas,134 :: 		PORTB:=not DisplayDots[1];
$0128	$0925			COMF	_displaydots+1, W
$0129	$0086			MOVWF	PORTB
;SecondBoardController.ppas,135 :: 		end;
$012A	$294A			GOTO	SecondBoardController_L_52
$012B	$	SecondBoardController_L_58:
;SecondBoardController.ppas,137 :: 		2:
$012B	$	SecondBoardController_L_60:
$012B	$082E			MOVF	_displaycolumnindex, 0
$012C	$3A02			XORLW	2
$012D	$1D03			BTFSS	STATUS, Z
$012E	$2934			GOTO	SecondBoardController_L_61
$012F	$	SecondBoardController_L_59:
;SecondBoardController.ppas,139 :: 		PORTC:=$04;
$012F	$3004			MOVLW	4
$0130	$0087			MOVWF	PORTC
;SecondBoardController.ppas,140 :: 		PORTB:=not DisplayDots[2];
$0131	$0926			COMF	_displaydots+2, W
$0132	$0086			MOVWF	PORTB
;SecondBoardController.ppas,141 :: 		end;
$0133	$294A			GOTO	SecondBoardController_L_52
$0134	$	SecondBoardController_L_61:
;SecondBoardController.ppas,143 :: 		3:
$0134	$	SecondBoardController_L_63:
$0134	$082E			MOVF	_displaycolumnindex, 0
$0135	$3A03			XORLW	3
$0136	$1D03			BTFSS	STATUS, Z
$0137	$293D			GOTO	SecondBoardController_L_64
$0138	$	SecondBoardController_L_62:
;SecondBoardController.ppas,145 :: 		PORTC:=$20;
$0138	$3020			MOVLW	32
$0139	$0087			MOVWF	PORTC
;SecondBoardController.ppas,146 :: 		PORTB:=not DisplayDots[3];
$013A	$0927			COMF	_displaydots+3, W
$013B	$0086			MOVWF	PORTB
;SecondBoardController.ppas,147 :: 		end;
$013C	$294A			GOTO	SecondBoardController_L_52
$013D	$	SecondBoardController_L_64:
;SecondBoardController.ppas,149 :: 		4:
$013D	$	SecondBoardController_L_66:
$013D	$082E			MOVF	_displaycolumnindex, 0
$013E	$3A04			XORLW	4
$013F	$1D03			BTFSS	STATUS, Z
$0140	$2946			GOTO	SecondBoardController_L_67
$0141	$	SecondBoardController_L_65:
;SecondBoardController.ppas,151 :: 		PORTC:=$40;
$0141	$3040			MOVLW	64
$0142	$0087			MOVWF	PORTC
;SecondBoardController.ppas,152 :: 		PORTB:=not DisplayDots[4];
$0143	$0928			COMF	_displaydots+4, W
$0144	$0086			MOVWF	PORTB
;SecondBoardController.ppas,155 :: 		else
$0145	$294A			GOTO	SecondBoardController_L_52
$0146	$	SecondBoardController_L_67:
;SecondBoardController.ppas,157 :: 		PORTC:=$80;
$0146	$3080			MOVLW	128
$0147	$0087			MOVWF	PORTC
;SecondBoardController.ppas,158 :: 		PORTB:=not DigitMask;
$0148	$0922			COMF	_digitmask, W
$0149	$0086			MOVWF	PORTB
;SecondBoardController.ppas,159 :: 		end;
$014A	$	SecondBoardController_L_52:
;SecondBoardController.ppas,162 :: 		Inc(DisplayColumnIndex);
$014A	$0AAE			INCF	_displaycolumnindex, 1
;SecondBoardController.ppas,163 :: 		if DisplayColumnIndex=8 then
$014B	$082E			MOVF	_displaycolumnindex, 0
$014C	$3A08			XORLW	8
$014D	$1D03			BTFSS	STATUS, Z
$014E	$2950			GOTO	SecondBoardController_L_69
$014F	$	SecondBoardController_L_68:
;SecondBoardController.ppas,164 :: 		DisplayColumnIndex:=0;
$014F	$01AE			CLRF	_displaycolumnindex, 1
$0150	$	SecondBoardController_L_69:
$0150	$	SecondBoardController_L_70:
;SecondBoardController.ppas,166 :: 		INTCON.T0IF:=False;
$0150	$110B			BCF	INTCON, 2
$0151	$	SecondBoardController_L_72:
;SecondBoardController.ppas,167 :: 		end;
$0151	$	SecondBoardController_L_50:
$0151	$	SecondBoardController_L_51:
$0151	$	SecondBoardController_L_45:
;SecondBoardController.ppas,168 :: 		end;
$0151	$0008			RETURN
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00B7			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00B6			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00B8			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0878			MOVF	STACK_8, 0
$000E	$00D1			MOVWF	STSAVED_8
$000F	$0874			MOVF	STACK_4, 0
$0010	$00D0			MOVWF	STSAVED_4
$0011	$0873			MOVF	STACK_3, 0
$0012	$00CF			MOVWF	STSAVED_3
$0013	$0872			MOVF	STACK_2, 0
$0014	$00CE			MOVWF	STSAVED_2
$0015	$0871			MOVF	STACK_1, 0
$0016	$00CD			MOVWF	STSAVED_1
$0017	$0870			MOVF	STACK_0, 0
$0018	$00CC			MOVWF	STSAVED_0
;SecondBoardController.ppas,170 :: 		procedure interrupt;
;SecondBoardController.ppas,172 :: 		I2CInterrupt;
$0019	$2068			CALL	_i2cinterrupt
;SecondBoardController.ppas,173 :: 		SevenSegmentInterrupt;
$001A	$2107			CALL	_sevensegmentinterrupt
;SecondBoardController.ppas,174 :: 		Inc(InterruptCount);
$001B	$0AAA			INCF	_interruptcount, 1
$001C	$	SecondBoardController_L_73:
;SecondBoardController.ppas,175 :: 		end;
$001C	$	L_Interrupt_end:
$001C	$0851			MOVF	STSAVED_8, 0
$001D	$00F8			MOVWF	STACK_8
$001E	$0850			MOVF	STSAVED_4, 0
$001F	$00F4			MOVWF	STACK_4
$0020	$084F			MOVF	STSAVED_3, 0
$0021	$00F3			MOVWF	STACK_3
$0022	$084E			MOVF	STSAVED_2, 0
$0023	$00F2			MOVWF	STACK_2
$0024	$084D			MOVF	STSAVED_1, 0
$0025	$00F1			MOVWF	STACK_1
$0026	$084C			MOVF	STSAVED_0, 0
$0027	$00F0			MOVWF	STACK_0
$0028	$0838			MOVF	?savePCLATH, 0
$0029	$008A			MOVWF	PCLATH
$002A	$0836			MOVF	?saveFSR, 0
$002B	$0084			MOVWF	FSR
$002C	$0E37			SWAPF	?saveSTATUS, 0
$002D	$0083			MOVWF	STATUS
$002E	$0EFF			SWAPF	STACK_15, 1
$002F	$0E7F			SWAPF	STACK_15, 0
$0030	$0009			RETFIE
$0152	$	_delayonems:
;ugeneral.ppas,3 :: 		procedure DelayOneMS;
;ugeneral.ppas,5 :: 		Delay_ms(1);
$0152	$3007			MOVLW	7
$0153	$1303			BCF	STATUS, RP1
$0154	$1283			BCF	STATUS, RP0
$0155	$00FB			MOVWF	STACK_11
$0156	$30FF			MOVLW	255
$0157	$00FA			MOVWF	STACK_10
$0158	$0BFB			DECFSZ	STACK_11, F
$0159	$295B			GOTO	$+2
$015A	$295E			GOTO	$+4
$015B	$0BFA			DECFSZ	STACK_10, F
$015C	$295B			GOTO	$-1
$015D	$2958			GOTO	$-5
$015E	$3079			MOVLW	121
$015F	$00FA			MOVWF	STACK_10
$0160	$0BFA			DECFSZ	STACK_10, F
$0161	$2960			GOTO	$-1
$0162	$0000			NOP
$0163	$	ugeneral_L_0:
;ugeneral.ppas,6 :: 		end;
$0163	$0008			RETURN
$0164	$	_eeprom_read:
;eepromlib_e_a.ppas,6 :: 		
;eepromlib_e_a.ppas,8 :: 		
$0164	$1303			BCF	STATUS, RP1
$0165	$1283			BCF	STATUS, RP0
$0166	$0846			MOVF	FARG_EEprom_read, 0
$0167	$1703			BSF	STATUS, RP1
$0168	$008D			MOVWF	EEADR
;eepromlib_e_a.ppas,9 :: 		
$0169	$1683			BSF	STATUS, RP0
$016A	$138C			BCF	EECON1, 7
;eepromlib_e_a.ppas,12 :: 		
$016B	$138C			BCF	EECON1, EEPGD
;eepromlib_e_a.ppas,13 :: 		
$016C	$140C			BSF	EECON1, RD
;eepromlib_e_a.ppas,14 :: 		
$016D	$0000			NOP
;eepromlib_e_a.ppas,15 :: 		
$016E	$0000			NOP
;eepromlib_e_a.ppas,17 :: 		
$016F	$1283			BCF	STATUS, RP0
$0170	$080C			MOVF	EEDATA, 0
$0171	$00C7			MOVWF	_eeprom_read_local_result
$0172	$	eepromlib_e_a_L_0:
$0172	$0847			MOVF	_eeprom_read_local_result, 0
$0173	$00F0			MOVWF	STACK_0
;eepromlib_e_a.ppas,18 :: 		
$0174	$0008			RETURN
$0175	$	_delayms:
;ugeneral.ppas,11 :: 		Count:Word;
;ugeneral.ppas,13 :: 		for Count:=0 to Value-1 do
$0175	$1303			BCF	STATUS, RP1
$0176	$1283			BCF	STATUS, RP0
$0177	$01C8			CLRF	_delayms_local_count
$0178	$01C9			CLRF	_delayms_local_count+1
$0179	$3001			MOVLW	1
$017A	$0246			SUBWF	FARG_DelayMS, 0
$017B	$00CA			MOVWF	FLOC_DelayMS+2
$017C	$3000			MOVLW	0
$017D	$1C03			BTFSS	STATUS, C
$017E	$3F01			ADDLW	1
$017F	$0247			SUBWF	FARG_DelayMS+1, 0
$0180	$00CB			MOVWF	FLOC_DelayMS+3
$0181	$	ugeneral_L_2:
$0181	$0849			MOVF	_delayms_local_count+1, 0
$0182	$024B			SUBWF	FLOC_DelayMS+3, 0
$0183	$1D03			BTFSS	STATUS, Z
$0184	$2987			GOTO	L_DelayMS_0
$0185	$0848			MOVF	_delayms_local_count, 0
$0186	$024A			SUBWF	FLOC_DelayMS+2, 0
$0187	$	L_DelayMS_0:
$0187	$1C03			BTFSS	STATUS, C
$0188	$2996			GOTO	ugeneral_L_5
;ugeneral.ppas,14 :: 		DelayOneMS;
$0189	$2152			CALL	_delayonems
$018A	$0849			MOVF	_delayms_local_count+1, 0
$018B	$064B			XORWF	FLOC_DelayMS+3, 0
$018C	$1D03			BTFSS	STATUS, Z
$018D	$2990			GOTO	L_DelayMS_1
$018E	$084A			MOVF	FLOC_DelayMS+2, 0
$018F	$0648			XORWF	_delayms_local_count, 0
$0190	$	L_DelayMS_1:
$0190	$1903			BTFSC	STATUS, Z
$0191	$2996			GOTO	ugeneral_L_5
$0192	$	ugeneral_L_3:
$0192	$0AC8			INCF	_delayms_local_count, 1
$0193	$1903			BTFSC	STATUS, Z
$0194	$0AC9			INCF	_delayms_local_count+1, 1
$0195	$2981			GOTO	ugeneral_L_2
$0196	$	ugeneral_L_5:
$0196	$	ugeneral_L_1:
;ugeneral.ppas,15 :: 		end;
$0196	$0008			RETURN
$0197	$	_eeprom_write:
;eepromlib_e_a.ppas,20 :: 		
;eepromlib_e_a.ppas,22 :: 		
$0197	$0000			NOP
;eepromlib_e_a.ppas,23 :: 		
$0198	$	eepromlib_e_a_L_3:
$0198	$1703			BSF	STATUS, RP1
$0199	$1683			BSF	STATUS, RP0
$019A	$3000			MOVLW	0
$019B	$1703			BSF	STATUS, RP1
$019C	$1683			BSF	STATUS, RP0
$019D	$188C			BTFSC	EECON1, 1
$019E	$3001			MOVLW	1
$019F	$1303			BCF	STATUS, RP1
$01A0	$1283			BCF	STATUS, RP0
$01A1	$00F1			MOVWF	STACK_1
$01A2	$0871			MOVF	STACK_1, 0
$01A3	$3A01			XORLW	1
$01A4	$1D03			BTFSS	STATUS, Z
$01A5	$29A8			GOTO	eepromlib_e_a_L_4
;eepromlib_e_a.ppas,24 :: 		
$01A6	$0000			NOP
$01A7	$2998			GOTO	eepromlib_e_a_L_3
$01A8	$	eepromlib_e_a_L_4:
;eepromlib_e_a.ppas,25 :: 		
$01A8	$0846			MOVF	FARG_EEprom_write, 0
$01A9	$1703			BSF	STATUS, RP1
$01AA	$008D			MOVWF	EEADR
;eepromlib_e_a.ppas,26 :: 		
$01AB	$0847			MOVF	FARG_EEprom_write+1, 0
$01AC	$008C			MOVWF	EEDATA
;eepromlib_e_a.ppas,27 :: 		
$01AD	$307F			MOVLW	127
$01AE	$1683			BSF	STATUS, RP0
$01AF	$050C			ANDWF	EECON1, 0
$01B0	$1303			BCF	STATUS, RP1
$01B1	$1283			BCF	STATUS, RP0
$01B2	$00F0			MOVWF	STACK_0
$01B3	$0870			MOVF	STACK_0, 0
$01B4	$1703			BSF	STATUS, RP1
$01B5	$1683			BSF	STATUS, RP0
$01B6	$008C			MOVWF	EECON1
;eepromlib_e_a.ppas,28 :: 		
$01B7	$3004			MOVLW	4
$01B8	$1303			BCF	STATUS, RP1
$01B9	$1283			BCF	STATUS, RP0
$01BA	$0470			IORWF	STACK_0, 0
$01BB	$1703			BSF	STATUS, RP1
$01BC	$1683			BSF	STATUS, RP0
$01BD	$008C			MOVWF	EECON1
;eepromlib_e_a.ppas,30 :: 		
$01BE	$138B			BCF	INTCON, 7
;eepromlib_e_a.ppas,31 :: 		
$01BF	$3055			MOVLW	85
$01C0	$008D			MOVWF	EECON2
;eepromlib_e_a.ppas,32 :: 		
$01C1	$30AA			MOVLW	170
$01C2	$008D			MOVWF	EECON2
;eepromlib_e_a.ppas,35 :: 		
$01C3	$148C			BSF	EECON1, WR
;eepromlib_e_a.ppas,37 :: 		
$01C4	$178B			BSF	INTCON, 7
;eepromlib_e_a.ppas,39 :: 		
$01C5	$110C			BCF	EECON1, 2
$01C6	$	eepromlib_e_a_L_1:
;eepromlib_e_a.ppas,40 :: 		
$01C6	$0008			RETURN
$01C7	$	_eeprom_readbyte:
;ugeneral.ppas,30 :: 		function EEPROM_ReadByte(Address:Byte):Byte;
;ugeneral.ppas,32 :: 		Result:=EEPROM_Read(Address);
$01C7	$1303			BCF	STATUS, RP1
$01C8	$1283			BCF	STATUS, RP0
$01C9	$0844			MOVF	FARG_EEPROM_ReadByte, 0
$01CA	$00C6			MOVWF	FARG_EEprom_read
$01CB	$2164			CALL	_eeprom_read
$01CC	$0870			MOVF	STACK_0, 0
$01CD	$00C5			MOVWF	_eeprom_readbyte_local_result
;ugeneral.ppas,33 :: 		DelayMS(20);
$01CE	$3014			MOVLW	20
$01CF	$00C6			MOVWF	FARG_DelayMS
$01D0	$01C7			CLRF	FARG_DelayMS+1
$01D1	$2175			CALL	_delayms
$01D2	$	ugeneral_L_15:
$01D2	$0845			MOVF	_eeprom_readbyte_local_result, 0
$01D3	$00F0			MOVWF	STACK_0
;ugeneral.ppas,34 :: 		end;
$01D4	$0008			RETURN
$01D5	$	_i2c_setslavemode:
;ui2c.ppas,32 :: 		procedure I2C_SetSlaveMode;
;ui2c.ppas,34 :: 		SSPCON.SSPEN:=False; // Reset I2C module.
$01D5	$1303			BCF	STATUS, RP1
$01D6	$1283			BCF	STATUS, RP0
$01D7	$1294			BCF	SSPCON, 5
$01D8	$	ui2c_L_2:
;ui2c.ppas,35 :: 		SSPADD:=I2C_SlaveAddress;
$01D8	$082F			MOVF	_i2c_slaveaddress, 0
$01D9	$1683			BSF	STATUS, RP0
$01DA	$0093			MOVWF	SSPADD
;ui2c.ppas,36 :: 		SSPCON:=$36; // I2C slave mode.
$01DB	$3036			MOVLW	54
$01DC	$1283			BCF	STATUS, RP0
$01DD	$0094			MOVWF	SSPCON
;ui2c.ppas,37 :: 		SSPCON2.GCEN:=True; // General call.
$01DE	$	ui2c_L_3:
$01DE	$1683			BSF	STATUS, RP0
$01DF	$1791			BSF	SSPCON2, 7
$01E0	$	ui2c_L_4:
;ui2c.ppas,39 :: 		PIR1.SSPIF:=False;
$01E0	$1283			BCF	STATUS, RP0
$01E1	$118C			BCF	PIR1, 3
$01E2	$	ui2c_L_6:
;ui2c.ppas,40 :: 		PIE1.SSPIE:=True;
$01E2	$	ui2c_L_7:
$01E2	$1683			BSF	STATUS, RP0
$01E3	$158C			BSF	PIE1, 3
$01E4	$	ui2c_L_8:
;ui2c.ppas,42 :: 		PIE2.BCLIE:=False;
$01E4	$118D			BCF	PIE2, 3
$01E5	$	ui2c_L_10:
$01E5	$	ui2c_L_0:
;ui2c.ppas,43 :: 		end;
$01E5	$0008			RETURN
$01E6	$	_eeprom_writebyte:
;ugeneral.ppas,36 :: 		procedure EEPROM_WriteByte(Address:Byte;Value:Byte);
;ugeneral.ppas,38 :: 		EEPROM_Write(Address,Value);
$01E6	$1303			BCF	STATUS, RP1
$01E7	$1283			BCF	STATUS, RP0
$01E8	$0844			MOVF	FARG_EEPROM_WriteByte, 0
$01E9	$00C6			MOVWF	FARG_EEprom_write
$01EA	$0845			MOVF	FARG_EEPROM_WriteByte+1, 0
$01EB	$00C7			MOVWF	FARG_EEprom_write+1
$01EC	$2197			CALL	_eeprom_write
;ugeneral.ppas,39 :: 		DelayMS(20);
$01ED	$3014			MOVLW	20
$01EE	$1303			BCF	STATUS, RP1
$01EF	$1283			BCF	STATUS, RP0
$01F0	$00C6			MOVWF	FARG_DelayMS
$01F1	$01C7			CLRF	FARG_DelayMS+1
$01F2	$2175			CALL	_delayms
$01F3	$	ugeneral_L_16:
;ugeneral.ppas,40 :: 		end;
$01F3	$0008			RETURN
$01F4	$	_setdefaultoptions:
;SecondBoardController.ppas,177 :: 		procedure SetDefaultOptions;
;SecondBoardController.ppas,179 :: 		PORTA:=$00;
$01F4	$1303			BCF	STATUS, RP1
$01F5	$1283			BCF	STATUS, RP0
$01F6	$0185			CLRF	PORTA, 1
;SecondBoardController.ppas,181 :: 		DisplayDots[0]:=$00;
$01F7	$01A4			CLRF	_displaydots+0, 1
;SecondBoardController.ppas,182 :: 		DisplayDots[1]:=$00;
$01F8	$01A5			CLRF	_displaydots+1, 1
;SecondBoardController.ppas,183 :: 		DisplayDots[2]:=$00;
$01F9	$01A6			CLRF	_displaydots+2, 1
;SecondBoardController.ppas,184 :: 		DisplayDots[3]:=$00;
$01FA	$01A7			CLRF	_displaydots+3, 1
;SecondBoardController.ppas,185 :: 		DisplayDots[4]:=$00;
$01FB	$01A8			CLRF	_displaydots+4, 1
;SecondBoardController.ppas,186 :: 		DigitMask:=$00;
$01FC	$01A2			CLRF	_digitmask, 1
$01FD	$	SecondBoardController_L_74:
;SecondBoardController.ppas,187 :: 		end;
$01FD	$0008			RETURN
$01FE	$	_loadoptionsfromeeprom:
;SecondBoardController.ppas,189 :: 		procedure LoadOptionsFromEEPROM;
;SecondBoardController.ppas,191 :: 		if EEPROM_ReadByte($00)=$FF then Exit; // Check options are valid.
$01FE	$1303			BCF	STATUS, RP1
$01FF	$1283			BCF	STATUS, RP0
$0200	$01C4			CLRF	FARG_EEPROM_ReadByte, 1
$0201	$21C7			CALL	_eeprom_readbyte
$0202	$0870			MOVF	STACK_0, 0
$0203	$3AFF			XORLW	255
$0204	$1D03			BTFSS	STATUS, Z
$0205	$2A07			GOTO	SecondBoardController_L_77
$0206	$	SecondBoardController_L_76:
$0206	$2A2A			GOTO	SecondBoardController_L_75
$0207	$	SecondBoardController_L_77:
$0207	$	SecondBoardController_L_78:
;SecondBoardController.ppas,193 :: 		PORTA:=EEPROM_ReadByte($01);
$0207	$3001			MOVLW	1
$0208	$00C4			MOVWF	FARG_EEPROM_ReadByte
$0209	$21C7			CALL	_eeprom_readbyte
$020A	$0870			MOVF	STACK_0, 0
$020B	$0085			MOVWF	PORTA
;SecondBoardController.ppas,194 :: 		DigitMask:=EEPROM_ReadByte($02);
$020C	$3002			MOVLW	2
$020D	$00C4			MOVWF	FARG_EEPROM_ReadByte
$020E	$21C7			CALL	_eeprom_readbyte
$020F	$0870			MOVF	STACK_0, 0
$0210	$00A2			MOVWF	_digitmask
;SecondBoardController.ppas,195 :: 		DisplayDots[0]:=EEPROM_ReadByte($03);
$0211	$3003			MOVLW	3
$0212	$00C4			MOVWF	FARG_EEPROM_ReadByte
$0213	$21C7			CALL	_eeprom_readbyte
$0214	$0870			MOVF	STACK_0, 0
$0215	$00A4			MOVWF	_displaydots+0
;SecondBoardController.ppas,196 :: 		DisplayDots[1]:=EEPROM_ReadByte($04);
$0216	$3004			MOVLW	4
$0217	$00C4			MOVWF	FARG_EEPROM_ReadByte
$0218	$21C7			CALL	_eeprom_readbyte
$0219	$0870			MOVF	STACK_0, 0
$021A	$00A5			MOVWF	_displaydots+1
;SecondBoardController.ppas,197 :: 		DisplayDots[2]:=EEPROM_ReadByte($05);
$021B	$3005			MOVLW	5
$021C	$00C4			MOVWF	FARG_EEPROM_ReadByte
$021D	$21C7			CALL	_eeprom_readbyte
$021E	$0870			MOVF	STACK_0, 0
$021F	$00A6			MOVWF	_displaydots+2
;SecondBoardController.ppas,198 :: 		DisplayDots[3]:=EEPROM_ReadByte($06);
$0220	$3006			MOVLW	6
$0221	$00C4			MOVWF	FARG_EEPROM_ReadByte
$0222	$21C7			CALL	_eeprom_readbyte
$0223	$0870			MOVF	STACK_0, 0
$0224	$00A7			MOVWF	_displaydots+3
;SecondBoardController.ppas,199 :: 		DisplayDots[4]:=EEPROM_ReadByte($07);
$0225	$3007			MOVLW	7
$0226	$00C4			MOVWF	FARG_EEPROM_ReadByte
$0227	$21C7			CALL	_eeprom_readbyte
$0228	$0870			MOVF	STACK_0, 0
$0229	$00A8			MOVWF	_displaydots+4
$022A	$	SecondBoardController_L_75:
;SecondBoardController.ppas,200 :: 		end;
$022A	$0008			RETURN
$022B	$	_i2c_initialize:
;ui2c.ppas,54 :: 		procedure I2C_Initialize(SlaveAddress:Byte;MultiMasterMode:Boolean);
;ui2c.ppas,57 :: 		I2C_Started:=False;
$022B	$1303			BCF	STATUS, RP1
$022C	$1283			BCF	STATUS, RP0
$022D	$01B0			CLRF	_i2c_started, 1
;ui2c.ppas,58 :: 		I2C_Error:=0;
$022E	$01B1			CLRF	_i2c_error, 1
;ui2c.ppas,59 :: 		I2C_MultiMasterMode:=MultiMasterMode;
$022F	$0843			MOVF	FARG_I2C_Initialize+1, 0
$0230	$00B2			MOVWF	_i2c_multimastermode
;ui2c.ppas,60 :: 		I2C_SlaveAddress:=SlaveAddress;
$0231	$0842			MOVF	FARG_I2C_Initialize, 0
$0232	$00AF			MOVWF	_i2c_slaveaddress
;ui2c.ppas,61 :: 		if MultiMasterMode then
$0233	$0843			MOVF	FARG_I2C_Initialize+1, 0
$0234	$1903			BTFSC	STATUS, Z
$0235	$2A37			GOTO	ui2c_L_20
$0236	$	ui2c_L_19:
;ui2c.ppas,62 :: 		I2C_SetSlaveMode;
$0236	$21D5			CALL	_i2c_setslavemode
$0237	$	ui2c_L_20:
$0237	$	ui2c_L_21:
$0237	$	ui2c_L_18:
$0237	$1303			BCF	STATUS, RP1
$0238	$1683			BSF	STATUS, RP0
;ui2c.ppas,63 :: 		end;
$0239	$0008			RETURN
$023A	$	_globaldisableinterrupts:
;ugeneral.ppas,22 :: 		procedure GlobalDisableInterrupts;
;ugeneral.ppas,25 :: 		repeat
$023A	$	ugeneral_L_8:
;ugeneral.ppas,26 :: 		INTCON.GIE:=False;
$023A	$138B			BCF	INTCON, 7
$023B	$	ugeneral_L_14:
;ugeneral.ppas,27 :: 		until INTCON.GIE=False;
$023B	$	ugeneral_L_9:
$023B	$3000			MOVLW	0
$023C	$1B8B			BTFSC	INTCON, 7
$023D	$3001			MOVLW	1
$023E	$1303			BCF	STATUS, RP1
$023F	$1283			BCF	STATUS, RP0
$0240	$00F1			MOVWF	STACK_1
$0241	$0871			MOVF	STACK_1, 0
$0242	$3A00			XORLW	0
$0243	$1D03			BTFSS	STATUS, Z
$0244	$2A46			GOTO	ugeneral_L_11
$0245	$	ugeneral_L_12:
$0245	$2A47			GOTO	ugeneral_L_10
$0246	$	ugeneral_L_11:
$0246	$2A3A			GOTO	ugeneral_L_8
$0247	$	ugeneral_L_10:
$0247	$	ugeneral_L_7:
;ugeneral.ppas,28 :: 		end;
$0247	$0008			RETURN
$0248	$	_saveoptionstoeeprom:
;SecondBoardController.ppas,202 :: 		procedure SaveOptionsToEEPROM;
;SecondBoardController.ppas,204 :: 		EEPROM_WriteByte($00,$00); // $00=Options valid.
$0248	$1303			BCF	STATUS, RP1
$0249	$1283			BCF	STATUS, RP0
$024A	$01C4			CLRF	FARG_EEPROM_WriteByte, 1
$024B	$01C5			CLRF	FARG_EEPROM_WriteByte+1, 1
$024C	$21E6			CALL	_eeprom_writebyte
;SecondBoardController.ppas,206 :: 		EEPROM_WriteByte($01,PORTA);
$024D	$3001			MOVLW	1
$024E	$00C4			MOVWF	FARG_EEPROM_WriteByte
$024F	$0805			MOVF	PORTA, 0
$0250	$00C5			MOVWF	FARG_EEPROM_WriteByte+1
$0251	$21E6			CALL	_eeprom_writebyte
;SecondBoardController.ppas,207 :: 		EEPROM_WriteByte($02,DigitMask);
$0252	$3002			MOVLW	2
$0253	$00C4			MOVWF	FARG_EEPROM_WriteByte
$0254	$0822			MOVF	_digitmask, 0
$0255	$00C5			MOVWF	FARG_EEPROM_WriteByte+1
$0256	$21E6			CALL	_eeprom_writebyte
;SecondBoardController.ppas,208 :: 		EEPROM_WriteByte($03,DisplayDots[0]);
$0257	$3003			MOVLW	3
$0258	$00C4			MOVWF	FARG_EEPROM_WriteByte
$0259	$0824			MOVF	_displaydots+0, 0
$025A	$00C5			MOVWF	FARG_EEPROM_WriteByte+1
$025B	$21E6			CALL	_eeprom_writebyte
;SecondBoardController.ppas,209 :: 		EEPROM_WriteByte($04,DisplayDots[1]);
$025C	$3004			MOVLW	4
$025D	$00C4			MOVWF	FARG_EEPROM_WriteByte
$025E	$0825			MOVF	_displaydots+1, 0
$025F	$00C5			MOVWF	FARG_EEPROM_WriteByte+1
$0260	$21E6			CALL	_eeprom_writebyte
;SecondBoardController.ppas,210 :: 		EEPROM_WriteByte($05,DisplayDots[2]);
$0261	$3005			MOVLW	5
$0262	$00C4			MOVWF	FARG_EEPROM_WriteByte
$0263	$0826			MOVF	_displaydots+2, 0
$0264	$00C5			MOVWF	FARG_EEPROM_WriteByte+1
$0265	$21E6			CALL	_eeprom_writebyte
;SecondBoardController.ppas,211 :: 		EEPROM_WriteByte($06,DisplayDots[3]);
$0266	$3006			MOVLW	6
$0267	$00C4			MOVWF	FARG_EEPROM_WriteByte
$0268	$0827			MOVF	_displaydots+3, 0
$0269	$00C5			MOVWF	FARG_EEPROM_WriteByte+1
$026A	$21E6			CALL	_eeprom_writebyte
;SecondBoardController.ppas,212 :: 		EEPROM_WriteByte($07,DisplayDots[4]);
$026B	$3007			MOVLW	7
$026C	$00C4			MOVWF	FARG_EEPROM_WriteByte
$026D	$0828			MOVF	_displaydots+4, 0
$026E	$00C5			MOVWF	FARG_EEPROM_WriteByte+1
$026F	$21E6			CALL	_eeprom_writebyte
$0270	$	SecondBoardController_L_79:
;SecondBoardController.ppas,213 :: 		end;
$0270	$0008			RETURN
$0271	$	table__DiceDots:
;SecondBoardController.ppas,18 :: 		);
$0271	$3400			RETLW	0
$0272	$3400			RETLW	0
$0273	$3408			RETLW	8
$0274	$3400			RETLW	0
$0275	$3400			RETLW	0
$0276	$3402			RETLW	2
$0277	$3400			RETLW	0
$0278	$3400			RETLW	0
$0279	$3400			RETLW	0
$027A	$3420			RETLW	32
$027B	$3402			RETLW	2
$027C	$3400			RETLW	0
$027D	$3408			RETLW	8
$027E	$3400			RETLW	0
$027F	$3420			RETLW	32
$0280	$3422			RETLW	34
$0281	$3400			RETLW	0
$0282	$3400			RETLW	0
$0283	$3400			RETLW	0
$0284	$3422			RETLW	34
$0285	$3422			RETLW	34
$0286	$3400			RETLW	0
$0287	$3408			RETLW	8
$0288	$3400			RETLW	0
$0289	$3422			RETLW	34
$028A	$342A			RETLW	42
$028B	$3400			RETLW	0
$028C	$3400			RETLW	0
$028D	$3400			RETLW	0
$028E	$342A			RETLW	42
$028F	$0008			RETURN
$0290	$	_mul_16x16_u:
$0290	$1303			BCF	STATUS, RP1
$0291	$1283			BCF	STATUS, RP0
;math.ppas,41 :: 		
;math.ppas,44 :: 		
$0292	$01FB			CLRF	STACK_11
;math.ppas,45 :: 		
$0293	$01FA			CLRF	STACK_10
;math.ppas,46 :: 		
$0294	$01F9			CLRF	STACK_9
;math.ppas,47 :: 		
$0295	$3080			MOVLW	128
;math.ppas,48 :: 		
$0296	$00F8			MOVWF	STACK_8
;math.ppas,49 :: 		
$0297	$0CF1			RRF	STACK_1, F
;math.ppas,50 :: 		
$0298	$0CF0			RRF	STACK_0, F
;math.ppas,51 :: 		
$0299	$1C03			BTFSS	STATUS, C
;math.ppas,52 :: 		
$029A	$2AA4			GOTO	$+10
;math.ppas,53 :: 		
$029B	$0874			MOVF	STACK_4, W
;math.ppas,54 :: 		
$029C	$07F9			ADDWF	STACK_9, F
;math.ppas,55 :: 		
$029D	$0875			MOVF	STACK_5, W
;math.ppas,56 :: 		
$029E	$1803			BTFSC	STATUS, C
;math.ppas,57 :: 		
$029F	$0F75			INCFSZ	STACK_5, W
;math.ppas,58 :: 		
$02A0	$07FA			ADDWF	STACK_10, F
;math.ppas,59 :: 		
$02A1	$1803			BTFSC	STATUS, C
;math.ppas,60 :: 		
$02A2	$0AFB			INCF	STACK_11, F
;math.ppas,61 :: 		
$02A3	$1003			BCF	STATUS, C
;math.ppas,62 :: 		
$02A4	$1FF0			BTFSS	STACK_0, 7
;math.ppas,63 :: 		
$02A5	$2AAC			GOTO	$+7
;math.ppas,64 :: 		
$02A6	$0874			MOVF	STACK_4, W
;math.ppas,65 :: 		
$02A7	$07FA			ADDWF	STACK_10, F
;math.ppas,66 :: 		
$02A8	$0875			MOVF	STACK_5, W
;math.ppas,67 :: 		
$02A9	$1803			BTFSC	STATUS, C
;math.ppas,68 :: 		
$02AA	$0F75			INCFSZ	STACK_5, W
;math.ppas,69 :: 		
$02AB	$07FB			ADDWF	STACK_11, F
;math.ppas,70 :: 		
$02AC	$0CFB			RRF	STACK_11, F
;math.ppas,71 :: 		
$02AD	$0CFA			RRF	STACK_10, F
;math.ppas,72 :: 		
$02AE	$0CF9			RRF	STACK_9, F
;math.ppas,73 :: 		
$02AF	$0CF8			RRF	STACK_8, F
;math.ppas,74 :: 		
$02B0	$1C03			BTFSS	STATUS, C
;math.ppas,75 :: 		
$02B1	$2A97			GOTO	$-26
;math.ppas,76 :: 		
$02B2	$087B			MOVF	STACK_11, W
;math.ppas,77 :: 		
$02B3	$00F3			MOVWF	STACK_3
;math.ppas,78 :: 		
$02B4	$087A			MOVF	STACK_10, W
;math.ppas,79 :: 		
$02B5	$00F2			MOVWF	STACK_2
;math.ppas,80 :: 		
$02B6	$0879			MOVF	STACK_9, W
;math.ppas,81 :: 		
$02B7	$00F1			MOVWF	STACK_1
;math.ppas,82 :: 		
$02B8	$0878			MOVF	STACK_8, W
;math.ppas,83 :: 		
$02B9	$00F0			MOVWF	STACK_0
;math.ppas,84 :: 		
$02BA	$	math_L_1:
;math.ppas,85 :: 		
$02BA	$0008			RETURN
$02BB	$	_____doicp:
;system.ppas,19 :: 		
;system.ppas,20 :: 		
$02BB	$	_____DoICP:
;system.ppas,23 :: 		
$02BB	$1303			BCF	STATUS, RP1
$02BC	$1283			BCF	STATUS, RP0
$02BD	$0835			MOVF	____DoICPHiAddr, 0
$02BE	$008A			MOVWF	PCLATH
;system.ppas,24 :: 		
$02BF	$0833			MOVF	____DoICPLoAddr, 0
$02C0	$0082			MOVWF	PCL
$02C1	$	system_L_0:
;system.ppas,26 :: 		
$02C1	$0008			RETURN
$02C2	$	_main:
;SecondBoardController.ppas,218 :: 		MainThread_SetDefaultOptions,MainThread_SaveOptionsToEEPROM:Boolean;
;SecondBoardController.ppas,220 :: 		OPTION_REG:=$D3; // Timer 0 prescaler.
$02C2	$30D3			MOVLW	211
$02C3	$1303			BCF	STATUS, RP1
$02C4	$1683			BSF	STATUS, RP0
$02C5	$0081			MOVWF	OPTION_REG
;SecondBoardController.ppas,223 :: 		ADCON0:=$00;
$02C6	$1283			BCF	STATUS, RP0
$02C7	$019F			CLRF	ADCON0, 1
;SecondBoardController.ppas,224 :: 		ADCON1:=$06;
$02C8	$3006			MOVLW	6
$02C9	$1683			BSF	STATUS, RP0
$02CA	$009F			MOVWF	ADCON1
;SecondBoardController.ppas,226 :: 		I2CCommand:=-1;
$02CB	$30FF			MOVLW	255
$02CC	$1283			BCF	STATUS, RP0
$02CD	$00A1			MOVWF	_i2ccommand
;SecondBoardController.ppas,227 :: 		InterruptCount:=0;
$02CE	$01AA			CLRF	_interruptcount, 1
;SecondBoardController.ppas,228 :: 		Interrupt_SetDiceValue:=0;
$02CF	$01A9			CLRF	_interrupt_setdicevalue, 1
;SecondBoardController.ppas,229 :: 		Interrupt_ToggleRelay:=False;
$02D0	$01AB			CLRF	_interrupt_togglerelay, 1
;SecondBoardController.ppas,230 :: 		Interrupt_ToggleDots:=False;
$02D1	$01AC			CLRF	_interrupt_toggledots, 1
;SecondBoardController.ppas,231 :: 		Interrupt_SetDefaultOptions:=False;
$02D2	$01AD			CLRF	_interrupt_setdefaultoptions, 1
;SecondBoardController.ppas,232 :: 		Interrupt_SaveOptionsToEEPROM:=False;
$02D3	$01A3			CLRF	_interrupt_saveoptionstoeeprom, 1
;SecondBoardController.ppas,233 :: 		DisplayColumnIndex:=0;
$02D4	$01AE			CLRF	_displaycolumnindex, 1
;SecondBoardController.ppas,235 :: 		SetDefaultOptions;
$02D5	$21F4			CALL	_setdefaultoptions
;SecondBoardController.ppas,236 :: 		LoadOptionsFromEEPROM;
$02D6	$21FE			CALL	_loadoptionsfromeeprom
;SecondBoardController.ppas,239 :: 		TRISA:=$DF;
$02D7	$30DF			MOVLW	223
$02D8	$1683			BSF	STATUS, RP0
$02D9	$0085			MOVWF	TRISA
;SecondBoardController.ppas,240 :: 		TRISB:=$00;
$02DA	$0186			CLRF	TRISB, 1
;SecondBoardController.ppas,241 :: 		TRISC:=$18;
$02DB	$3018			MOVLW	24
$02DC	$0087			MOVWF	TRISC
;SecondBoardController.ppas,243 :: 		I2C_Initialize(SlaveAddress,True);
$02DD	$3014			MOVLW	20
$02DE	$1283			BCF	STATUS, RP0
$02DF	$00C2			MOVWF	FARG_I2C_Initialize
$02E0	$30FF			MOVLW	255
$02E1	$00C3			MOVWF	FARG_I2C_Initialize+1
$02E2	$222B			CALL	_i2c_initialize
;SecondBoardController.ppas,245 :: 		INTCON:=$E0;
$02E3	$30E0			MOVLW	224
$02E4	$008B			MOVWF	INTCON
;SecondBoardController.ppas,247 :: 		repeat
$02E5	$	SecondBoardController_L_81:
$02E5	$1303			BCF	STATUS, RP1
$02E6	$1683			BSF	STATUS, RP0
;SecondBoardController.ppas,249 :: 		GlobalDisableInterrupts;
$02E7	$223A			CALL	_globaldisableinterrupts
;SecondBoardController.ppas,250 :: 		MainThread_SetDiceValue:=Interrupt_SetDiceValue;
$02E8	$0829			MOVF	_interrupt_setdicevalue, 0
$02E9	$00BB			MOVWF	_main_local_mainthread_setdicevalue
;SecondBoardController.ppas,251 :: 		Interrupt_SetDiceValue:=0;
$02EA	$01A9			CLRF	_interrupt_setdicevalue, 1
;SecondBoardController.ppas,252 :: 		MainThread_ToggleRelay:=Interrupt_ToggleRelay;
$02EB	$082B			MOVF	_interrupt_togglerelay, 0
$02EC	$00BC			MOVWF	_main_local_mainthread_togglerelay
;SecondBoardController.ppas,253 :: 		Interrupt_ToggleRelay:=False;
$02ED	$01AB			CLRF	_interrupt_togglerelay, 1
;SecondBoardController.ppas,254 :: 		MainThread_ToggleDots:=Interrupt_ToggleDots;
$02EE	$082C			MOVF	_interrupt_toggledots, 0
$02EF	$00BD			MOVWF	_main_local_mainthread_toggledots
;SecondBoardController.ppas,255 :: 		Interrupt_ToggleDots:=False;
$02F0	$01AC			CLRF	_interrupt_toggledots, 1
;SecondBoardController.ppas,256 :: 		MainThread_SetDefaultOptions:=Interrupt_SetDefaultOptions;
$02F1	$082D			MOVF	_interrupt_setdefaultoptions, 0
$02F2	$00BE			MOVWF	_main_local_mainthread_setdefaultoptions
;SecondBoardController.ppas,257 :: 		Interrupt_SetDefaultOptions:=False;
$02F3	$01AD			CLRF	_interrupt_setdefaultoptions, 1
;SecondBoardController.ppas,258 :: 		MainThread_SaveOptionsToEEPROM:=Interrupt_SaveOptionsToEEPROM;
$02F4	$0823			MOVF	_interrupt_saveoptionstoeeprom, 0
$02F5	$00BF			MOVWF	_main_local_mainthread_saveoptionstoeeprom
;SecondBoardController.ppas,259 :: 		Interrupt_SaveOptionsToEEPROM:=False;
$02F6	$01A3			CLRF	_interrupt_saveoptionstoeeprom, 1
;SecondBoardController.ppas,260 :: 		INTCON.GIE:=True;
$02F7	$	SecondBoardController_L_86:
$02F7	$178B			BSF	INTCON, 7
$02F8	$	SecondBoardController_L_87:
;SecondBoardController.ppas,262 :: 		if MainThread_SetDefaultOptions then
$02F8	$083E			MOVF	_main_local_mainthread_setdefaultoptions, 0
$02F9	$1903			BTFSC	STATUS, Z
$02FA	$2AFC			GOTO	SecondBoardController_L_89
$02FB	$	SecondBoardController_L_88:
;SecondBoardController.ppas,263 :: 		SetDefaultOptions;
$02FB	$21F4			CALL	_setdefaultoptions
$02FC	$	SecondBoardController_L_89:
$02FC	$	SecondBoardController_L_90:
;SecondBoardController.ppas,265 :: 		if MainThread_SetDiceValue<>0 then
$02FC	$083B			MOVF	_main_local_mainthread_setdicevalue, 0
$02FD	$3A00			XORLW	0
$02FE	$1903			BTFSC	STATUS, Z
$02FF	$2B85			GOTO	SecondBoardController_L_92
$0300	$	SecondBoardController_L_91:
;SecondBoardController.ppas,268 :: 		DisplayDots[0]:=DiceDots[MainThread_SetDiceValue][0];
$0300	$3071			MOVLW	#dicedots
$0301	$00C0			MOVWF	FLOC_main+5
$0302	$3002			MOVLW	@#dicedots
$0303	$00C1			MOVWF	FLOC_main+6
$0304	$033B			DECF	_main_local_mainthread_setdicevalue, 0
$0305	$00F0			MOVWF	STACK_0
$0306	$3000			MOVLW	0
$0307	$00F1			MOVWF	STACK_0+1
$0308	$3005			MOVLW	5
$0309	$00F4			MOVWF	STACK_4
$030A	$3000			MOVLW	0
$030B	$00F5			MOVWF	STACK_4+1
$030C	$2290			CALL	_mul_16x16_u
$030D	$0870			MOVF	STACK_0, 0
$030E	$0740			ADDWF	FLOC_main+5, 0
$030F	$00F2			MOVWF	STACK_2
$0310	$0841			MOVF	FLOC_main+6, 0
$0311	$1803			BTFSC	STATUS, C
$0312	$3F01			ADDLW	1
$0313	$0771			ADDWF	STACK_0+1, 0
$0314	$00F3			MOVWF	STACK_2+1
$0315	$0872			MOVF	STACK_2, 0
$0316	$00B3			MOVWF	____DoICPLoAddr
$0317	$0873			MOVF	STACK_2+1, 0
$0318	$00B5			MOVWF	____DoICPHiAddr
$0319	$080A			MOVF	PCLATH, 0
$031A	$00B4			MOVWF	____DoICPSavePCLATH
$031B	$22BB			CALL	_____DoICP
$031C	$00F2			MOVWF	STACK_2
$031D	$0834			MOVF	____DoICPSavePCLATH, 0
$031E	$008A			MOVWF	PCLATH
$031F	$0872			MOVF	STACK_2, 0
$0320	$00A4			MOVWF	_displaydots+0
;SecondBoardController.ppas,269 :: 		DisplayDots[1]:=DiceDots[MainThread_SetDiceValue][1];
$0321	$0870			MOVF	STACK_0, 0
$0322	$3F01			ADDLW	1
$0323	$00F2			MOVWF	STACK_2
$0324	$3000			MOVLW	0
$0325	$1803			BTFSC	STATUS, C
$0326	$3F01			ADDLW	1
$0327	$0771			ADDWF	STACK_0+1, 0
$0328	$00F3			MOVWF	STACK_2+1
$0329	$0840			MOVF	FLOC_main+5, 0
$032A	$07F2			ADDWF	STACK_2, 1
$032B	$0841			MOVF	FLOC_main+6, 0
$032C	$1803			BTFSC	STATUS, C
$032D	$3F01			ADDLW	1
$032E	$07F3			ADDWF	STACK_2+1, 1
$032F	$0872			MOVF	STACK_2, 0
$0330	$00B3			MOVWF	____DoICPLoAddr
$0331	$0873			MOVF	STACK_2+1, 0
$0332	$00B5			MOVWF	____DoICPHiAddr
$0333	$080A			MOVF	PCLATH, 0
$0334	$00B4			MOVWF	____DoICPSavePCLATH
$0335	$22BB			CALL	_____DoICP
$0336	$00F2			MOVWF	STACK_2
$0337	$0834			MOVF	____DoICPSavePCLATH, 0
$0338	$008A			MOVWF	PCLATH
$0339	$0872			MOVF	STACK_2, 0
$033A	$00A5			MOVWF	_displaydots+1
;SecondBoardController.ppas,270 :: 		DisplayDots[2]:=DiceDots[MainThread_SetDiceValue][2];
$033B	$0870			MOVF	STACK_0, 0
$033C	$3F02			ADDLW	2
$033D	$00F2			MOVWF	STACK_2
$033E	$3000			MOVLW	0
$033F	$1803			BTFSC	STATUS, C
$0340	$3F01			ADDLW	1
$0341	$0771			ADDWF	STACK_0+1, 0
$0342	$00F3			MOVWF	STACK_2+1
$0343	$0840			MOVF	FLOC_main+5, 0
$0344	$07F2			ADDWF	STACK_2, 1
$0345	$0841			MOVF	FLOC_main+6, 0
$0346	$1803			BTFSC	STATUS, C
$0347	$3F01			ADDLW	1
$0348	$07F3			ADDWF	STACK_2+1, 1
$0349	$0872			MOVF	STACK_2, 0
$034A	$00B3			MOVWF	____DoICPLoAddr
$034B	$0873			MOVF	STACK_2+1, 0
$034C	$00B5			MOVWF	____DoICPHiAddr
$034D	$080A			MOVF	PCLATH, 0
$034E	$00B4			MOVWF	____DoICPSavePCLATH
$034F	$22BB			CALL	_____DoICP
$0350	$00F2			MOVWF	STACK_2
$0351	$0834			MOVF	____DoICPSavePCLATH, 0
$0352	$008A			MOVWF	PCLATH
$0353	$0872			MOVF	STACK_2, 0
$0354	$00A6			MOVWF	_displaydots+2
;SecondBoardController.ppas,271 :: 		DisplayDots[3]:=DiceDots[MainThread_SetDiceValue][3];
$0355	$0870			MOVF	STACK_0, 0
$0356	$3F03			ADDLW	3
$0357	$00F2			MOVWF	STACK_2
$0358	$3000			MOVLW	0
$0359	$1803			BTFSC	STATUS, C
$035A	$3F01			ADDLW	1
$035B	$0771			ADDWF	STACK_0+1, 0
$035C	$00F3			MOVWF	STACK_2+1
$035D	$0840			MOVF	FLOC_main+5, 0
$035E	$07F2			ADDWF	STACK_2, 1
$035F	$0841			MOVF	FLOC_main+6, 0
$0360	$1803			BTFSC	STATUS, C
$0361	$3F01			ADDLW	1
$0362	$07F3			ADDWF	STACK_2+1, 1
$0363	$0872			MOVF	STACK_2, 0
$0364	$00B3			MOVWF	____DoICPLoAddr
$0365	$0873			MOVF	STACK_2+1, 0
$0366	$00B5			MOVWF	____DoICPHiAddr
$0367	$080A			MOVF	PCLATH, 0
$0368	$00B4			MOVWF	____DoICPSavePCLATH
$0369	$22BB			CALL	_____DoICP
$036A	$00F2			MOVWF	STACK_2
$036B	$0834			MOVF	____DoICPSavePCLATH, 0
$036C	$008A			MOVWF	PCLATH
$036D	$0872			MOVF	STACK_2, 0
$036E	$00A7			MOVWF	_displaydots+3
;SecondBoardController.ppas,272 :: 		DisplayDots[4]:=DiceDots[MainThread_SetDiceValue][4];
$036F	$3004			MOVLW	4
$0370	$07F0			ADDWF	STACK_0, 1
$0371	$1803			BTFSC	STATUS, C
$0372	$0AF1			INCF	STACK_0+1, 1
$0373	$0840			MOVF	FLOC_main+5, 0
$0374	$07F0			ADDWF	STACK_0, 1
$0375	$0841			MOVF	FLOC_main+6, 0
$0376	$1803			BTFSC	STATUS, C
$0377	$3F01			ADDLW	1
$0378	$07F1			ADDWF	STACK_0+1, 1
$0379	$0870			MOVF	STACK_0, 0
$037A	$00B3			MOVWF	____DoICPLoAddr
$037B	$0871			MOVF	STACK_0+1, 0
$037C	$00B5			MOVWF	____DoICPHiAddr
$037D	$080A			MOVF	PCLATH, 0
$037E	$00B4			MOVWF	____DoICPSavePCLATH
$037F	$22BB			CALL	_____DoICP
$0380	$00F0			MOVWF	STACK_0
$0381	$0834			MOVF	____DoICPSavePCLATH, 0
$0382	$008A			MOVWF	PCLATH
$0383	$0870			MOVF	STACK_0, 0
$0384	$00A8			MOVWF	_displaydots+4
;SecondBoardController.ppas,273 :: 		end;
$0385	$	SecondBoardController_L_92:
$0385	$	SecondBoardController_L_93:
;SecondBoardController.ppas,275 :: 		if MainThread_ToggleRelay then
$0385	$083C			MOVF	_main_local_mainthread_togglerelay, 0
$0386	$1903			BTFSC	STATUS, Z
$0387	$2B92			GOTO	SecondBoardController_L_95
$0388	$	SecondBoardController_L_94:
;SecondBoardController.ppas,277 :: 		if PORTA.5 then
$0388	$3000			MOVLW	0
$0389	$1A85			BTFSC	PORTA, 5
$038A	$3001			MOVLW	1
$038B	$00F2			MOVWF	STACK_2
$038C	$0872			MOVF	STACK_2, 0
$038D	$1903			BTFSC	STATUS, Z
$038E	$2B91			GOTO	SecondBoardController_L_98
$038F	$	SecondBoardController_L_97:
;SecondBoardController.ppas,278 :: 		PORTA.5:=0
$038F	$1285			BCF	PORTA, 5
$0390	$	SecondBoardController_L_101:
$0390	$2B92			GOTO	SecondBoardController_L_99
;SecondBoardController.ppas,279 :: 		else
$0391	$	SecondBoardController_L_98:
;SecondBoardController.ppas,280 :: 		PORTA.5:=1;
$0391	$	SecondBoardController_L_102:
$0391	$1685			BSF	PORTA, 5
$0392	$	SecondBoardController_L_103:
$0392	$	SecondBoardController_L_99:
;SecondBoardController.ppas,281 :: 		end;
$0392	$	SecondBoardController_L_95:
$0392	$	SecondBoardController_L_96:
;SecondBoardController.ppas,283 :: 		if MainThread_ToggleDots then
$0392	$083D			MOVF	_main_local_mainthread_toggledots, 0
$0393	$1903			BTFSC	STATUS, Z
$0394	$2B9A			GOTO	SecondBoardController_L_105
$0395	$	SecondBoardController_L_104:
;SecondBoardController.ppas,285 :: 		DisplayDots[0]:=not DisplayDots[0];
$0395	$09A4			COMF	_displaydots+0, F
;SecondBoardController.ppas,286 :: 		DisplayDots[1]:=not DisplayDots[1];
$0396	$09A5			COMF	_displaydots+1, F
;SecondBoardController.ppas,287 :: 		DisplayDots[2]:=not DisplayDots[2];
$0397	$09A6			COMF	_displaydots+2, F
;SecondBoardController.ppas,288 :: 		DisplayDots[3]:=not DisplayDots[3];
$0398	$09A7			COMF	_displaydots+3, F
;SecondBoardController.ppas,289 :: 		DisplayDots[4]:=not DisplayDots[4];
$0399	$09A8			COMF	_displaydots+4, F
;SecondBoardController.ppas,290 :: 		end;
$039A	$	SecondBoardController_L_105:
$039A	$	SecondBoardController_L_106:
;SecondBoardController.ppas,292 :: 		if MainThread_SaveOptionsToEEPROM then
$039A	$083F			MOVF	_main_local_mainthread_saveoptionstoeeprom, 0
$039B	$1903			BTFSC	STATUS, Z
$039C	$2B9E			GOTO	SecondBoardController_L_108
$039D	$	SecondBoardController_L_107:
;SecondBoardController.ppas,293 :: 		SaveOptionsToEEPROM;
$039D	$2248			CALL	_saveoptionstoeeprom
$039E	$	SecondBoardController_L_108:
$039E	$	SecondBoardController_L_109:
;SecondBoardController.ppas,294 :: 		until False;
$039E	$	SecondBoardController_L_82:
$039E	$	SecondBoardController_L_84:
$039E	$2AE5			GOTO	SecondBoardController_L_81
;SecondBoardController.ppas,295 :: 		end.
$039F	$2B9F			GOTO	$
