;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 09/01/2009 23:29:35
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2827			GOTO	_main
$0494	$	_i2c_slave_sendbyte:
;UI2C.ppas,279 :: 		begin
;UI2C.ppas,280 :: 		while (PIR1.SSPIF=0) do begin end;
$0494	$	UI2C_L_156:
$0494	$1303			BCF	STATUS, RP1
$0495	$1283			BCF	STATUS, RP0
$0496	$080C			MOVF	PIR1, 0
$0497	$00F1			MOVWF	STACK_1
$0498	$3000			MOVLW	0
$0499	$19F1			BTFSC	STACK_1, 3
$049A	$3001			MOVLW	1
$049B	$00F1			MOVWF	STACK_1
$049C	$0871			MOVF	STACK_1, 0
$049D	$3A00			XORLW	0
$049E	$1903			BTFSC	STATUS, Z
$049F	$2C94			GOTO	UI2C_L_156
$04A0	$	UI2C_L_157:
;UI2C.ppas,281 :: 		SSPBUF:=Value;
$04A0	$083C			MOVF	FARG_I2C_Slave_SendByte, 0
$04A1	$0093			MOVWF	SSPBUF
;UI2C.ppas,282 :: 		SSPCON1.CKP:=True;
$04A2	$	UI2C_L_160:
$04A2	$1614			BSF	SSPCON1, 4
$04A3	$	UI2C_L_161:
;UI2C.ppas,283 :: 		PIR1.SSPIF:=False;
$04A3	$118C			BCF	PIR1, 3
$04A4	$	UI2C_L_163:
$04A4	$	UI2C_L_154:
;UI2C.ppas,284 :: 		end;
$04A4	$0008			RETURN
$031D	$	_i2c_slave_receivebyte:
;UI2C.ppas,261 :: 		begin
;UI2C.ppas,262 :: 		PIR1.SSPIF:=False;
$031D	$1303			BCF	STATUS, RP1
$031E	$1283			BCF	STATUS, RP0
$031F	$118C			BCF	PIR1, 3
$0320	$	UI2C_L_143:
;UI2C.ppas,263 :: 		while (PIR1.SSPIF=0) or (SSPSTAT.BF=0) do begin end;
$0320	$	UI2C_L_145:
$0320	$080C			MOVF	PIR1, 0
$0321	$00F1			MOVWF	STACK_1
$0322	$3000			MOVLW	0
$0323	$19F1			BTFSC	STACK_1, 3
$0324	$3001			MOVLW	1
$0325	$00F1			MOVWF	STACK_1
$0326	$0871			MOVF	STACK_1, 0
$0327	$3A00			XORLW	0
$0328	$30FF			MOVLW	255
$0329	$1D03			BTFSS	STATUS, Z
$032A	$3000			MOVLW	0
$032B	$00F2			MOVWF	STACK_2
$032C	$1683			BSF	STATUS, RP0
$032D	$0814			MOVF	SSPSTAT, 0
$032E	$1283			BCF	STATUS, RP0
$032F	$00F1			MOVWF	STACK_1
$0330	$3001			MOVLW	1
$0331	$05F1			ANDWF	STACK_1, 1
$0332	$0871			MOVF	STACK_1, 0
$0333	$3A00			XORLW	0
$0334	$30FF			MOVLW	255
$0335	$1D03			BTFSS	STATUS, Z
$0336	$3000			MOVLW	0
$0337	$00F0			MOVWF	STACK_0
$0338	$0872			MOVF	STACK_2, 0
$0339	$04F0			IORWF	STACK_0, 1
$033A	$1D03			BTFSS	STATUS, Z
$033B	$2B20			GOTO	UI2C_L_145
$033C	$	UI2C_L_146:
;UI2C.ppas,264 :: 		Result:=SSPBUF;
$033C	$0813			MOVF	SSPBUF, 0
$033D	$00BC			MOVWF	_i2c_slave_receivebyte_local_result
;UI2C.ppas,265 :: 		SSPSTAT.SSPOV:=False;
$033E	$1683			BSF	STATUS, RP0
$033F	$1314			BCF	SSPSTAT, 6
$0340	$	UI2C_L_150:
;UI2C.ppas,266 :: 		PIR1.SSPIF:=False;
$0340	$1283			BCF	STATUS, RP0
$0341	$118C			BCF	PIR1, 3
$0342	$	UI2C_L_152:
$0342	$	UI2C_L_141:
;UI2C.ppas,267 :: 		end;
$0342	$083C			MOVF	_i2c_slave_receivebyte_local_result, 0
$0343	$00F0			MOVWF	STACK_0
$0344	$0008			RETURN
$0532	$	_i2c_slave_sendword:
;UI2C.ppas,287 :: 		begin
;UI2C.ppas,288 :: 		I2C_Slave_SendByte(Lo(Value));
$0532	$30FF			MOVLW	255
$0533	$1303			BCF	STATUS, RP1
$0534	$1283			BCF	STATUS, RP0
$0535	$0539			ANDWF	FARG_I2C_Slave_SendWord, 0
$0536	$00BC			MOVWF	FARG_I2C_Slave_SendByte
$0537	$2494			CALL	_i2c_slave_sendbyte
;UI2C.ppas,289 :: 		I2C_Slave_SendByte(Hi(Value));
$0538	$083A			MOVF	FARG_I2C_Slave_SendWord+1, 0
$0539	$00BC			MOVWF	FARG_I2C_Slave_SendByte
$053A	$2494			CALL	_i2c_slave_sendbyte
$053B	$	UI2C_L_164:
;UI2C.ppas,290 :: 		end;
$053B	$0008			RETURN
$0440	$	_i2c_slave_receiveword:
;UI2C.ppas,272 :: 		begin
;UI2C.ppas,273 :: 		LowByte:=I2C_Slave_ReceiveByte;
$0440	$231D			CALL	_i2c_slave_receivebyte
$0441	$0870			MOVF	STACK_0, 0
$0442	$00BB			MOVWF	_i2c_slave_receiveword_local_lowbyte
;UI2C.ppas,274 :: 		HighByte:=I2C_Slave_ReceiveByte;
$0443	$231D			CALL	_i2c_slave_receivebyte
;UI2C.ppas,275 :: 		Result:=LowByte+(HighByte shl 8);
$0444	$0870			MOVF	STACK_0, 0
$0445	$00F2			MOVWF	STACK_2
$0446	$01F3			CLRF	STACK_2+1
$0447	$0872			MOVF	STACK_2, 0
$0448	$00F3			MOVWF	STACK_2+1
$0449	$01F2			CLRF	STACK_2
$044A	$083B			MOVF	_i2c_slave_receiveword_local_lowbyte, 0
$044B	$00B9			MOVWF	_i2c_slave_receiveword_local_result
$044C	$01BA			CLRF	_i2c_slave_receiveword_local_result+1
$044D	$0872			MOVF	STACK_2, 0
$044E	$07B9			ADDWF	_i2c_slave_receiveword_local_result, 1
$044F	$0873			MOVF	STACK_2+1, 0
$0450	$1803			BTFSC	STATUS, C
$0451	$3F01			ADDLW	1
$0452	$07BA			ADDWF	_i2c_slave_receiveword_local_result+1, 1
$0453	$	UI2C_L_153:
;UI2C.ppas,276 :: 		end;
$0453	$0839			MOVF	_i2c_slave_receiveword_local_result, 0
$0454	$00F0			MOVWF	STACK_0
$0455	$083A			MOVF	_i2c_slave_receiveword_local_result+1, 0
$0456	$00F1			MOVWF	STACK_0+1
$0457	$0008			RETURN
$017F	$	_i2cinterrupt:
;I2C.ppas,22 :: 		begin
;I2C.ppas,25 :: 		if PIE1.SSPIE=False then Exit;
$017F	$1303			BCF	STATUS, RP1
$0180	$1683			BSF	STATUS, RP0
$0181	$080C			MOVF	PIE1, 0
$0182	$1283			BCF	STATUS, RP0
$0183	$00F2			MOVWF	STACK_2
$0184	$3000			MOVLW	0
$0185	$19F2			BTFSC	STACK_2, 3
$0186	$3001			MOVLW	1
$0187	$00F2			MOVWF	STACK_2
$0188	$0872			MOVF	STACK_2, 0
$0189	$3A00			XORLW	0
$018A	$1D03			BTFSS	STATUS, Z
$018B	$298D			GOTO	I2C_L_2
$018C	$	I2C_L_1:
$018C	$2A64			GOTO	I2C_L_0
$018D	$	I2C_L_2:
$018D	$	I2C_L_3:
;I2C.ppas,27 :: 		if PIR1.SSPIF then
$018D	$080C			MOVF	PIR1, 0
$018E	$00F2			MOVWF	STACK_2
$018F	$3000			MOVLW	0
$0190	$19F2			BTFSC	STACK_2, 3
$0191	$3001			MOVLW	1
$0192	$00F2			MOVWF	STACK_2
$0193	$0872			MOVF	STACK_2, 0
$0194	$1903			BTFSC	STATUS, Z
$0195	$2A64			GOTO	I2C_L_5
$0196	$	I2C_L_4:
;I2C.ppas,29 :: 		if (SSPSTAT.D_A=0) then // Command.
$0196	$1683			BSF	STATUS, RP0
$0197	$0814			MOVF	SSPSTAT, 0
$0198	$1283			BCF	STATUS, RP0
$0199	$00F2			MOVWF	STACK_2
$019A	$3000			MOVLW	0
$019B	$1AF2			BTFSC	STACK_2, 5
$019C	$3001			MOVLW	1
$019D	$00F2			MOVWF	STACK_2
$019E	$0872			MOVF	STACK_2, 0
$019F	$3A00			XORLW	0
$01A0	$1D03			BTFSS	STATUS, Z
$01A1	$2A61			GOTO	I2C_L_8
$01A2	$	I2C_L_7:
;I2C.ppas,31 :: 		if SSPSTAT.R_W then
$01A2	$1683			BSF	STATUS, RP0
$01A3	$0814			MOVF	SSPSTAT, 0
$01A4	$1283			BCF	STATUS, RP0
$01A5	$00F2			MOVWF	STACK_2
$01A6	$3000			MOVLW	0
$01A7	$1972			BTFSC	STACK_2, 2
$01A8	$3001			MOVLW	1
$01A9	$00F2			MOVWF	STACK_2
$01AA	$0872			MOVF	STACK_2, 0
$01AB	$1903			BTFSC	STATUS, Z
$01AC	$29C0			GOTO	I2C_L_11
$01AD	$	I2C_L_10:
;I2C.ppas,34 :: 		$05: I2C_Slave_SendByte(PORTA);
$01AD	$	I2C_L_15:
$01AD	$0820			MOVF	_i2ccommand, 0
$01AE	$3A05			XORLW	5
$01AF	$1D03			BTFSS	STATUS, Z
$01B0	$29B5			GOTO	I2C_L_16
$01B1	$	I2C_L_14:
$01B1	$0805			MOVF	PORTA, 0
$01B2	$00BC			MOVWF	FARG_I2C_Slave_SendByte
$01B3	$2494			CALL	_i2c_slave_sendbyte
$01B4	$29BF			GOTO	I2C_L_13
$01B5	$	I2C_L_16:
;I2C.ppas,35 :: 		$06: I2C_Slave_SendWord(DelayTimeMS);
$01B5	$	I2C_L_18:
$01B5	$0820			MOVF	_i2ccommand, 0
$01B6	$3A06			XORLW	6
$01B7	$1D03			BTFSS	STATUS, Z
$01B8	$29BF			GOTO	I2C_L_19
$01B9	$	I2C_L_17:
$01B9	$0821			MOVF	_delaytimems, 0
$01BA	$00B9			MOVWF	FARG_I2C_Slave_SendWord
$01BB	$0822			MOVF	_delaytimems+1, 0
$01BC	$00BA			MOVWF	FARG_I2C_Slave_SendWord+1
$01BD	$2532			CALL	_i2c_slave_sendword
$01BE	$29BF			GOTO	I2C_L_13
$01BF	$	I2C_L_19:
$01BF	$	I2C_L_13:
;I2C.ppas,37 :: 		end
$01BF	$2A61			GOTO	I2C_L_12
;I2C.ppas,38 :: 		else
$01C0	$	I2C_L_11:
;I2C.ppas,40 :: 		if SSPSTAT.BF then
$01C0	$1683			BSF	STATUS, RP0
$01C1	$0814			MOVF	SSPSTAT, 0
$01C2	$1283			BCF	STATUS, RP0
$01C3	$00F2			MOVWF	STACK_2
$01C4	$3001			MOVLW	1
$01C5	$05F2			ANDWF	STACK_2, 1
$01C6	$0872			MOVF	STACK_2, 0
$01C7	$1903			BTFSC	STATUS, Z
$01C8	$2A61			GOTO	I2C_L_21
$01C9	$	I2C_L_20:
;I2C.ppas,42 :: 		MandatoryByte:=SSPBUF; // Make sure this is not optimized out!
$01C9	$0813			MOVF	SSPBUF, 0
$01CA	$00A3			MOVWF	_mandatorybyte
;I2C.ppas,43 :: 		SSPSTAT.SSPOV:=False;
$01CB	$1683			BSF	STATUS, RP0
$01CC	$1314			BCF	SSPSTAT, 6
$01CD	$	I2C_L_24:
;I2C.ppas,45 :: 		I2CCommand:=I2C_Slave_ReceiveByte;
$01CD	$231D			CALL	_i2c_slave_receivebyte
$01CE	$0870			MOVF	STACK_0, 0
$01CF	$00A0			MOVWF	_i2ccommand
;I2C.ppas,48 :: 		0:
$01D0	$	I2C_L_27:
$01D0	$0820			MOVF	_i2ccommand, 0
$01D1	$3A00			XORLW	0
$01D2	$1D03			BTFSS	STATUS, Z
$01D3	$29DB			GOTO	I2C_L_28
$01D4	$	I2C_L_26:
;I2C.ppas,50 :: 		PORTA:=I2C_Slave_ReceiveByte xor PORTA_BitPolarity;
$01D4	$231D			CALL	_i2c_slave_receivebyte
$01D5	$0824			MOVF	_porta_bitpolarity, 0
$01D6	$0670			XORWF	STACK_0, 0
$01D7	$0085			MOVWF	PORTA
;I2C.ppas,51 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$01D8	$30FF			MOVLW	255
$01D9	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,52 :: 		end;
$01DA	$2A61			GOTO	I2C_L_25
$01DB	$	I2C_L_28:
;I2C.ppas,54 :: 		1:
$01DB	$	I2C_L_30:
$01DB	$0820			MOVF	_i2ccommand, 0
$01DC	$3A01			XORLW	1
$01DD	$1D03			BTFSS	STATUS, Z
$01DE	$29E6			GOTO	I2C_L_31
$01DF	$	I2C_L_29:
;I2C.ppas,56 :: 		PORTB:=I2C_Slave_ReceiveByte xor PORTB_BitPolarity;
$01DF	$231D			CALL	_i2c_slave_receivebyte
$01E0	$0826			MOVF	_portb_bitpolarity, 0
$01E1	$0670			XORWF	STACK_0, 0
$01E2	$0086			MOVWF	PORTB
;I2C.ppas,57 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$01E3	$30FF			MOVLW	255
$01E4	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,58 :: 		end;
$01E5	$2A61			GOTO	I2C_L_25
$01E6	$	I2C_L_31:
;I2C.ppas,60 :: 		2:
$01E6	$	I2C_L_33:
$01E6	$0820			MOVF	_i2ccommand, 0
$01E7	$3A02			XORLW	2
$01E8	$1D03			BTFSS	STATUS, Z
$01E9	$29F1			GOTO	I2C_L_34
$01EA	$	I2C_L_32:
;I2C.ppas,62 :: 		PORTC:=I2C_Slave_ReceiveByte xor PORTC_BitPolarity;
$01EA	$231D			CALL	_i2c_slave_receivebyte
$01EB	$0827			MOVF	_portc_bitpolarity, 0
$01EC	$0670			XORWF	STACK_0, 0
$01ED	$0087			MOVWF	PORTC
;I2C.ppas,63 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$01EE	$30FF			MOVLW	255
$01EF	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,64 :: 		end;
$01F0	$2A61			GOTO	I2C_L_25
$01F1	$	I2C_L_34:
;I2C.ppas,66 :: 		3:
$01F1	$	I2C_L_36:
$01F1	$0820			MOVF	_i2ccommand, 0
$01F2	$3A03			XORLW	3
$01F3	$1D03			BTFSS	STATUS, Z
$01F4	$2A1A			GOTO	I2C_L_37
$01F5	$	I2C_L_35:
;I2C.ppas,68 :: 		WordParameter:=I2C_Slave_ReceiveWord;
$01F5	$2440			CALL	_i2c_slave_receiveword
$01F6	$0870			MOVF	STACK_0, 0
$01F7	$00B7			MOVWF	_i2cinterrupt_local_wordparameter
$01F8	$0871			MOVF	STACK_0+1, 0
$01F9	$00B8			MOVWF	_i2cinterrupt_local_wordparameter+1
;I2C.ppas,69 :: 		if (WordParameter<>0) and (WordParameter<=5000) then
$01FA	$3000			MOVLW	0
$01FB	$0671			XORWF	STACK_0+1, 0
$01FC	$1D03			BTFSS	STATUS, Z
$01FD	$2A00			GOTO	L_I2CInterrupt_0
$01FE	$3000			MOVLW	0
$01FF	$0670			XORWF	STACK_0, 0
$0200	$	L_I2CInterrupt_0:
$0200	$30FF			MOVLW	255
$0201	$1903			BTFSC	STATUS, Z
$0202	$3000			MOVLW	0
$0203	$00F3			MOVWF	STACK_3
$0204	$0871			MOVF	STACK_0+1, 0
$0205	$3C13			SUBLW	19
$0206	$1D03			BTFSS	STATUS, Z
$0207	$2A0A			GOTO	L_I2CInterrupt_1
$0208	$0870			MOVF	STACK_0, 0
$0209	$3C88			SUBLW	136
$020A	$	L_I2CInterrupt_1:
$020A	$30FF			MOVLW	255
$020B	$1C03			BTFSS	STATUS, C
$020C	$3000			MOVLW	0
$020D	$00F2			MOVWF	STACK_2
$020E	$0872			MOVF	STACK_2, 0
$020F	$0573			ANDWF	STACK_3, 0
$0210	$00F0			MOVWF	STACK_0
$0211	$1903			BTFSC	STATUS, Z
$0212	$2A19			GOTO	I2C_L_39
$0213	$	I2C_L_38:
;I2C.ppas,71 :: 		DelayTimeMS:=WordParameter;
$0213	$0837			MOVF	_i2cinterrupt_local_wordparameter, 0
$0214	$00A1			MOVWF	_delaytimems
$0215	$0838			MOVF	_i2cinterrupt_local_wordparameter+1, 0
$0216	$00A2			MOVWF	_delaytimems+1
;I2C.ppas,72 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$0217	$30FF			MOVLW	255
$0218	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,73 :: 		end;
$0219	$	I2C_L_39:
$0219	$	I2C_L_40:
;I2C.ppas,74 :: 		end;
$0219	$2A61			GOTO	I2C_L_25
$021A	$	I2C_L_37:
;I2C.ppas,76 :: 		4:
$021A	$	I2C_L_42:
$021A	$0820			MOVF	_i2ccommand, 0
$021B	$3A04			XORLW	4
$021C	$1D03			BTFSS	STATUS, Z
$021D	$2A23			GOTO	I2C_L_43
$021E	$	I2C_L_41:
;I2C.ppas,78 :: 		ByteParameter:=I2C_Slave_ReceiveByte;
$021E	$231D			CALL	_i2c_slave_receivebyte
;I2C.ppas,79 :: 		TRISA:=ByteParameter;
$021F	$0870			MOVF	STACK_0, 0
$0220	$1683			BSF	STATUS, RP0
$0221	$0085			MOVWF	TRISA
;I2C.ppas,80 :: 		end;
$0222	$2A61			GOTO	I2C_L_25
$0223	$	I2C_L_43:
;I2C.ppas,82 :: 		5: begin end; // Read PORTA.
$0223	$	I2C_L_45:
$0223	$1303			BCF	STATUS, RP1
$0224	$1683			BSF	STATUS, RP0
$0225	$1283			BCF	STATUS, RP0
$0226	$0820			MOVF	_i2ccommand, 0
$0227	$3A05			XORLW	5
$0228	$1D03			BTFSS	STATUS, Z
$0229	$2A2B			GOTO	I2C_L_46
$022A	$	I2C_L_44:
$022A	$2A61			GOTO	I2C_L_25
$022B	$	I2C_L_46:
;I2C.ppas,84 :: 		6: begin end; // 16 bit read.
$022B	$	I2C_L_48:
$022B	$0820			MOVF	_i2ccommand, 0
$022C	$3A06			XORLW	6
$022D	$1D03			BTFSS	STATUS, Z
$022E	$2A30			GOTO	I2C_L_49
$022F	$	I2C_L_47:
$022F	$2A61			GOTO	I2C_L_25
$0230	$	I2C_L_49:
;I2C.ppas,86 :: 		7: // Set mode.
$0230	$	I2C_L_51:
$0230	$0820			MOVF	_i2ccommand, 0
$0231	$3A07			XORLW	7
$0232	$1D03			BTFSS	STATUS, Z
$0233	$2A3A			GOTO	I2C_L_52
$0234	$	I2C_L_50:
;I2C.ppas,88 :: 		Interrupt_Mode:=I2C_Slave_ReceiveByte;
$0234	$231D			CALL	_i2c_slave_receivebyte
$0235	$0870			MOVF	STACK_0, 0
$0236	$00A8			MOVWF	_interrupt_mode
;I2C.ppas,89 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$0237	$30FF			MOVLW	255
$0238	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,90 :: 		end;
$0239	$2A61			GOTO	I2C_L_25
$023A	$	I2C_L_52:
;I2C.ppas,92 :: 		8:
$023A	$	I2C_L_54:
$023A	$0820			MOVF	_i2ccommand, 0
$023B	$3A08			XORLW	8
$023C	$1D03			BTFSS	STATUS, Z
$023D	$2A44			GOTO	I2C_L_55
$023E	$	I2C_L_53:
;I2C.ppas,94 :: 		PORTA_BitPolarity:=I2C_Slave_ReceiveByte;
$023E	$231D			CALL	_i2c_slave_receivebyte
$023F	$0870			MOVF	STACK_0, 0
$0240	$00A4			MOVWF	_porta_bitpolarity
;I2C.ppas,95 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$0241	$30FF			MOVLW	255
$0242	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,96 :: 		end;
$0243	$2A61			GOTO	I2C_L_25
$0244	$	I2C_L_55:
;I2C.ppas,98 :: 		9:
$0244	$	I2C_L_57:
$0244	$0820			MOVF	_i2ccommand, 0
$0245	$3A09			XORLW	9
$0246	$1D03			BTFSS	STATUS, Z
$0247	$2A4E			GOTO	I2C_L_58
$0248	$	I2C_L_56:
;I2C.ppas,100 :: 		PORTB_BitPolarity:=I2C_Slave_ReceiveByte;
$0248	$231D			CALL	_i2c_slave_receivebyte
$0249	$0870			MOVF	STACK_0, 0
$024A	$00A6			MOVWF	_portb_bitpolarity
;I2C.ppas,101 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$024B	$30FF			MOVLW	255
$024C	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,102 :: 		end;
$024D	$2A61			GOTO	I2C_L_25
$024E	$	I2C_L_58:
;I2C.ppas,104 :: 		10:
$024E	$	I2C_L_60:
$024E	$0820			MOVF	_i2ccommand, 0
$024F	$3A0A			XORLW	10
$0250	$1D03			BTFSS	STATUS, Z
$0251	$2A58			GOTO	I2C_L_61
$0252	$	I2C_L_59:
;I2C.ppas,106 :: 		PORTC_BitPolarity:=I2C_Slave_ReceiveByte;
$0252	$231D			CALL	_i2c_slave_receivebyte
$0253	$0870			MOVF	STACK_0, 0
$0254	$00A7			MOVWF	_portc_bitpolarity
;I2C.ppas,107 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$0255	$30FF			MOVLW	255
$0256	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,108 :: 		end;
$0257	$2A61			GOTO	I2C_L_25
$0258	$	I2C_L_61:
;I2C.ppas,110 :: 		999:
$0258	$	I2C_L_63:
$0258	$0820			MOVF	_i2ccommand, 0
$0259	$3AE7			XORLW	231
$025A	$1D03			BTFSS	STATUS, Z
$025B	$2A61			GOTO	I2C_L_64
$025C	$	I2C_L_62:
;I2C.ppas,112 :: 		Interrupt_SetDefaultOptions:=True;
$025C	$30FF			MOVLW	255
$025D	$00A9			MOVWF	_interrupt_setdefaultoptions
;I2C.ppas,113 :: 		Interrupt_SaveOptionsToEEPROM:=True;
$025E	$30FF			MOVLW	255
$025F	$00A5			MOVWF	_interrupt_saveoptionstoeeprom
;I2C.ppas,114 :: 		end;
$0260	$2A61			GOTO	I2C_L_25
$0261	$	I2C_L_64:
$0261	$	I2C_L_25:
;I2C.ppas,116 :: 		end;
$0261	$	I2C_L_21:
$0261	$	I2C_L_22:
;I2C.ppas,117 :: 		end;
$0261	$	I2C_L_12:
;I2C.ppas,118 :: 		end;
$0261	$	I2C_L_8:
$0261	$	I2C_L_9:
;I2C.ppas,120 :: 		PIR1.SSPIF:=False;
$0261	$1303			BCF	STATUS, RP1
$0262	$1283			BCF	STATUS, RP0
$0263	$118C			BCF	PIR1, 3
$0264	$	I2C_L_66:
;I2C.ppas,121 :: 		end;
$0264	$	I2C_L_5:
$0264	$	I2C_L_6:
$0264	$	I2C_L_0:
;I2C.ppas,122 :: 		end;
$0264	$0008			RETURN
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00B5			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00B4			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00B6			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0873			MOVF	STACK_3, 0
$000E	$00D2			MOVWF	STSAVED_3
$000F	$0872			MOVF	STACK_2, 0
$0010	$00D1			MOVWF	STSAVED_2
$0011	$0871			MOVF	STACK_1, 0
$0012	$00D0			MOVWF	STSAVED_1
$0013	$0870			MOVF	STACK_0, 0
$0014	$00CF			MOVWF	STSAVED_0
;I2C.ppas,125 :: 		begin
;I2C.ppas,126 :: 		I2CInterrupt;
$0015	$217F			CALL	_i2cinterrupt
$0016	$	I2C_L_67:
;I2C.ppas,127 :: 		end;
$0016	$	L_Interrupt_end:
$0016	$0852			MOVF	STSAVED_3, 0
$0017	$00F3			MOVWF	STACK_3
$0018	$0851			MOVF	STSAVED_2, 0
$0019	$00F2			MOVWF	STACK_2
$001A	$0850			MOVF	STSAVED_1, 0
$001B	$00F1			MOVWF	STACK_1
$001C	$084F			MOVF	STSAVED_0, 0
$001D	$00F0			MOVWF	STACK_0
$001E	$0836			MOVF	?savePCLATH, 0
$001F	$008A			MOVWF	PCLATH
$0020	$0834			MOVF	?saveFSR, 0
$0021	$0084			MOVWF	FSR
$0022	$0E35			SWAPF	?saveSTATUS, 0
$0023	$0083			MOVWF	STATUS
$0024	$0EFF			SWAPF	STACK_15, 1
$0025	$0E7F			SWAPF	STACK_15, 0
$0026	$0009			RETFIE
$0528	$	_i2c_init:
;I2C_c34.ppas,8 :: 		
;I2C_c34.ppas,9 :: 		
$0528	$1303			BCF	STATUS, RP1
$0529	$1683			BSF	STATUS, RP0
$052A	$1314			BCF	SSPSTAT, 6
$052B	$	I2C_c34_L_2:
;I2C_c34.ppas,10 :: 		
$052B	$1394			BCF	SSPSTAT, 7
$052C	$	I2C_c34_L_4:
;I2C_c34.ppas,11 :: 		
$052C	$	I2C_c34_L_5:
$052C	$1607			BSF	TRISC, 4
$052D	$	I2C_c34_L_6:
;I2C_c34.ppas,12 :: 		
$052D	$	I2C_c34_L_7:
$052D	$1587			BSF	TRISC, 3
$052E	$	I2C_c34_L_8:
;I2C_c34.ppas,13 :: 		
$052E	$3038			MOVLW	56
$052F	$1283			BCF	STATUS, RP0
$0530	$0094			MOVWF	SSPCON
$0531	$	I2C_c34_L_0:
;I2C_c34.ppas,15 :: 		
$0531	$0008			RETURN
$0481	$	_delayonems:
;UGeneral.ppas,4 :: 		begin
;UGeneral.ppas,5 :: 		Delay_ms(1);
$0481	$3007			MOVLW	7
$0482	$1303			BCF	STATUS, RP1
$0483	$1283			BCF	STATUS, RP0
$0484	$00FB			MOVWF	STACK_11
$0485	$30FF			MOVLW	255
$0486	$00FA			MOVWF	STACK_10
$0487	$0BFB			DECFSZ	STACK_11, F
$0488	$2C8A			GOTO	$+2
$0489	$2C8D			GOTO	$+4
$048A	$0BFA			DECFSZ	STACK_10, F
$048B	$2C8A			GOTO	$-1
$048C	$2C87			GOTO	$-5
$048D	$3078			MOVLW	120
$048E	$00FA			MOVWF	STACK_10
$048F	$0BFA			DECFSZ	STACK_10, F
$0490	$2C8F			GOTO	$-1
$0491	$0000			NOP
$0492	$0000			NOP
$0493	$	UGeneral_L_0:
;UGeneral.ppas,6 :: 		end;
$0493	$0008			RETURN
$03D6	$	_i2c_is_idle:
;I2C_c34.ppas,22 :: 		
;I2C_c34.ppas,23 :: 		
$03D6	$1303			BCF	STATUS, RP1
$03D7	$1283			BCF	STATUS, RP0
$03D8	$01C7			CLRF	_i2c_is_idle_local_result, 1
;I2C_c34.ppas,24 :: 		
$03D9	$1683			BSF	STATUS, RP0
$03DA	$0814			MOVF	SSPSTAT, 0
$03DB	$1283			BCF	STATUS, RP0
$03DC	$00F1			MOVWF	STACK_1
$03DD	$3000			MOVLW	0
$03DE	$1971			BTFSC	STACK_1, 2
$03DF	$3001			MOVLW	1
$03E0	$00F1			MOVWF	STACK_1
$03E1	$0871			MOVF	STACK_1, 0
$03E2	$3A00			XORLW	0
$03E3	$1D03			BTFSS	STATUS, Z
$03E4	$2BF0			GOTO	I2C_c34_L_11
$03E5	$	I2C_c34_L_10:
;I2C_c34.ppas,25 :: 		
$03E5	$301F			MOVLW	31
$03E6	$1683			BSF	STATUS, RP0
$03E7	$0511			ANDWF	SSPCON2, 0
$03E8	$1283			BCF	STATUS, RP0
$03E9	$00F1			MOVWF	STACK_1
$03EA	$0871			MOVF	STACK_1, 0
$03EB	$3A00			XORLW	0
$03EC	$1D03			BTFSS	STATUS, Z
$03ED	$2BF0			GOTO	I2C_c34_L_14
$03EE	$	I2C_c34_L_13:
$03EE	$30FF			MOVLW	255
$03EF	$00C7			MOVWF	_i2c_is_idle_local_result
$03F0	$	I2C_c34_L_14:
$03F0	$	I2C_c34_L_15:
$03F0	$	I2C_c34_L_11:
$03F0	$	I2C_c34_L_12:
$03F0	$	I2C_c34_L_9:
;I2C_c34.ppas,26 :: 		
$03F0	$0847			MOVF	_i2c_is_idle_local_result, 0
$03F1	$00F0			MOVWF	STACK_0
$03F2	$0008			RETURN
$03F3	$	_i2c_setmastermode:
;UI2C.ppas,66 :: 		begin
;UI2C.ppas,67 :: 		PIE1.SSPIE:=False; // Prevent our I2C interrupt handler from operating whilst we are master.
$03F3	$1303			BCF	STATUS, RP1
$03F4	$1683			BSF	STATUS, RP0
$03F5	$118C			BCF	PIE1, 3
$03F6	$	UI2C_L_13:
;UI2C.ppas,68 :: 		PIE2.BCLIE:=False; // Prevent our I2C interrupt handler from operating whilst we are master.
$03F6	$118D			BCF	PIE2, 3
$03F7	$	UI2C_L_15:
;UI2C.ppas,70 :: 		SSPCON1.SSPEN:=False; // Reset I2C module.
$03F7	$1283			BCF	STATUS, RP0
$03F8	$1294			BCF	SSPCON1, 5
$03F9	$	UI2C_L_17:
;UI2C.ppas,72 :: 		if not I2C_Initialized then
$03F9	$092A			COMF	_i2c_initialized, W
$03FA	$1903			BTFSC	STATUS, Z
$03FB	$2C07			GOTO	UI2C_L_19
$03FC	$	UI2C_L_18:
;UI2C.ppas,74 :: 		I2C_Init(100000); // Sets SSPCON1 according to specified speed and currently selected clock speed. HOWEVER it also pulls SCL and SDA low momenterally which causes problems with the ISD5116 speech chip if used in MultiMaster mode.
$03FC	$3032			MOVLW	50
$03FD	$1683			BSF	STATUS, RP0
$03FE	$0093			MOVWF	SSPADD
$03FF	$2528			CALL	_i2c_init
;UI2C.ppas,75 :: 		I2C_MasterMode_SSPADD:=SSPADD;
$0400	$1683			BSF	STATUS, RP0
$0401	$0813			MOVF	SSPADD, 0
$0402	$1283			BCF	STATUS, RP0
$0403	$00AB			MOVWF	_i2c_mastermode_sspadd
;UI2C.ppas,76 :: 		I2C_MasterMode_SSPCON1:=SSPCON1;
$0404	$0814			MOVF	SSPCON1, 0
$0405	$00AC			MOVWF	_i2c_mastermode_sspcon1
;UI2C.ppas,77 :: 		end
$0406	$2C0D			GOTO	UI2C_L_20
;UI2C.ppas,78 :: 		else
$0407	$	UI2C_L_19:
;UI2C.ppas,82 :: 		SSPADD:=I2C_MasterMode_SSPADD;
$0407	$082B			MOVF	_i2c_mastermode_sspadd, 0
$0408	$1683			BSF	STATUS, RP0
$0409	$0093			MOVWF	SSPADD
;UI2C.ppas,83 :: 		SSPCON1:=I2C_MasterMode_SSPCON1;
$040A	$1283			BCF	STATUS, RP0
$040B	$082C			MOVF	_i2c_mastermode_sspcon1, 0
$040C	$0094			MOVWF	SSPCON1
;UI2C.ppas,84 :: 		end;
$040D	$	UI2C_L_20:
$040D	$	UI2C_L_11:
;UI2C.ppas,85 :: 		end;
$040D	$0008			RETURN
$036C	$	_private_i2c_master_start:
;UI2C.ppas,106 :: 		begin
;UI2C.ppas,107 :: 		Result:=False;
$036C	$1303			BCF	STATUS, RP1
$036D	$1283			BCF	STATUS, RP0
$036E	$01C7			CLRF	_private_i2c_master_start_local_result, 1
;UI2C.ppas,109 :: 		PIR1.SSPIF:=False;
$036F	$118C			BCF	PIR1, 3
$0370	$	UI2C_L_27:
;UI2C.ppas,110 :: 		PIR2.BCLIF:=False; // Bus collision detect.
$0370	$118D			BCF	PIR2, 3
$0371	$	UI2C_L_29:
;UI2C.ppas,111 :: 		SSPCON2.SEN:=True;
$0371	$	UI2C_L_30:
$0371	$1683			BSF	STATUS, RP0
$0372	$1411			BSF	SSPCON2, 0
$0373	$	UI2C_L_31:
;UI2C.ppas,112 :: 		while PIR1.SSPIF=False do
$0373	$	UI2C_L_33:
$0373	$1283			BCF	STATUS, RP0
$0374	$080C			MOVF	PIR1, 0
$0375	$00F1			MOVWF	STACK_1
$0376	$3000			MOVLW	0
$0377	$19F1			BTFSC	STACK_1, 3
$0378	$3001			MOVLW	1
$0379	$00F1			MOVWF	STACK_1
$037A	$0871			MOVF	STACK_1, 0
$037B	$3A00			XORLW	0
$037C	$1D03			BTFSS	STATUS, Z
$037D	$2B8A			GOTO	UI2C_L_34
;UI2C.ppas,114 :: 		if PIR2.BCLIF then
$037E	$080D			MOVF	PIR2, 0
$037F	$00F1			MOVWF	STACK_1
$0380	$3000			MOVLW	0
$0381	$19F1			BTFSC	STACK_1, 3
$0382	$3001			MOVLW	1
$0383	$00F1			MOVWF	STACK_1
$0384	$0871			MOVF	STACK_1, 0
$0385	$1903			BTFSC	STATUS, Z
$0386	$2B89			GOTO	UI2C_L_38
$0387	$	UI2C_L_37:
;UI2C.ppas,116 :: 		PIR2.BCLIF:=False;
$0387	$118D			BCF	PIR2, 3
$0388	$	UI2C_L_41:
;UI2C.ppas,117 :: 		Exit;
$0388	$2B8D			GOTO	UI2C_L_25
;UI2C.ppas,118 :: 		end;
$0389	$	UI2C_L_38:
$0389	$	UI2C_L_39:
;UI2C.ppas,119 :: 		end;
$0389	$2B73			GOTO	UI2C_L_33
$038A	$	UI2C_L_34:
;UI2C.ppas,121 :: 		PIR1.SSPIF:=False;
$038A	$118C			BCF	PIR1, 3
$038B	$	UI2C_L_43:
;UI2C.ppas,123 :: 		Result:=True;
$038B	$30FF			MOVLW	255
$038C	$00C7			MOVWF	_private_i2c_master_start_local_result
$038D	$	UI2C_L_25:
;UI2C.ppas,124 :: 		end;
$038D	$0847			MOVF	_private_i2c_master_start_local_result, 0
$038E	$00F0			MOVWF	STACK_0
$038F	$0008			RETURN
$04A5	$	_i2c_setslavemode:
;UI2C.ppas,53 :: 		begin
;UI2C.ppas,54 :: 		SSPCON1.SSPEN:=False; // Reset I2C module.
$04A5	$1303			BCF	STATUS, RP1
$04A6	$1283			BCF	STATUS, RP0
$04A7	$1294			BCF	SSPCON1, 5
$04A8	$	UI2C_L_2:
;UI2C.ppas,55 :: 		SSPADD:=I2C_SlaveAddress;
$04A8	$082D			MOVF	_i2c_slaveaddress, 0
$04A9	$1683			BSF	STATUS, RP0
$04AA	$0093			MOVWF	SSPADD
;UI2C.ppas,56 :: 		SSPCON1:=$36; // I2C slave mode.
$04AB	$3036			MOVLW	54
$04AC	$1283			BCF	STATUS, RP0
$04AD	$0094			MOVWF	SSPCON1
;UI2C.ppas,57 :: 		SSPCON2.GCEN:=True; // General call.
$04AE	$	UI2C_L_3:
$04AE	$1683			BSF	STATUS, RP0
$04AF	$1791			BSF	SSPCON2, 7
$04B0	$	UI2C_L_4:
;UI2C.ppas,59 :: 		PIR1.SSPIF:=False;
$04B0	$1283			BCF	STATUS, RP0
$04B1	$118C			BCF	PIR1, 3
$04B2	$	UI2C_L_6:
;UI2C.ppas,60 :: 		PIE1.SSPIE:=True;
$04B2	$	UI2C_L_7:
$04B2	$1683			BSF	STATUS, RP0
$04B3	$158C			BSF	PIE1, 3
$04B4	$	UI2C_L_8:
;UI2C.ppas,62 :: 		PIE2.BCLIE:=False;
$04B4	$118D			BCF	PIE2, 3
$04B5	$	UI2C_L_10:
$04B5	$	UI2C_L_0:
;UI2C.ppas,63 :: 		end;
$04B5	$0008			RETURN
$03B4	$	_delayms:
;UGeneral.ppas,12 :: 		begin
;UGeneral.ppas,13 :: 		for Count:=0 to Value-1 do
$03B4	$1303			BCF	STATUS, RP1
$03B5	$1283			BCF	STATUS, RP0
$03B6	$01C9			CLRF	_delayms_local_count
$03B7	$01CA			CLRF	_delayms_local_count+1
$03B8	$	UGeneral_L_2:
$03B8	$3001			MOVLW	1
$03B9	$0247			SUBWF	FARG_DelayMS, 0
$03BA	$00CB			MOVWF	FLOC_DelayMS+2
$03BB	$3000			MOVLW	0
$03BC	$1C03			BTFSS	STATUS, C
$03BD	$3F01			ADDLW	1
$03BE	$0248			SUBWF	FARG_DelayMS+1, 0
$03BF	$00CC			MOVWF	FLOC_DelayMS+3
$03C0	$084A			MOVF	_delayms_local_count+1, 0
$03C1	$024C			SUBWF	FLOC_DelayMS+3, 0
$03C2	$1D03			BTFSS	STATUS, Z
$03C3	$2BC6			GOTO	L_DelayMS_0
$03C4	$0849			MOVF	_delayms_local_count, 0
$03C5	$024B			SUBWF	FLOC_DelayMS+2, 0
$03C6	$	L_DelayMS_0:
$03C6	$1C03			BTFSS	STATUS, C
$03C7	$2BD5			GOTO	UGeneral_L_5
;UGeneral.ppas,14 :: 		DelayOneMS;
$03C8	$2481			CALL	_delayonems
$03C9	$084A			MOVF	_delayms_local_count+1, 0
$03CA	$064C			XORWF	FLOC_DelayMS+3, 0
$03CB	$1D03			BTFSS	STATUS, Z
$03CC	$2BCF			GOTO	L_DelayMS_1
$03CD	$084B			MOVF	FLOC_DelayMS+2, 0
$03CE	$0649			XORWF	_delayms_local_count, 0
$03CF	$	L_DelayMS_1:
$03CF	$1903			BTFSC	STATUS, Z
$03D0	$2BD5			GOTO	UGeneral_L_5
$03D1	$	UGeneral_L_3:
$03D1	$0AC9			INCF	_delayms_local_count, 1
$03D2	$1903			BTFSC	STATUS, Z
$03D3	$0ACA			INCF	_delayms_local_count+1, 1
$03D4	$2BB8			GOTO	UGeneral_L_2
$03D5	$	UGeneral_L_5:
$03D5	$	UGeneral_L_1:
;UGeneral.ppas,15 :: 		end;
$03D5	$0008			RETURN
$0501	$	_eeprom_read:
;EEPROMlib_E_A.ppas,10 :: 		
;EEPROMlib_E_A.ppas,11 :: 		
$0501	$1303			BCF	STATUS, RP1
$0502	$1283			BCF	STATUS, RP0
$0503	$0844			MOVF	FARG_EEprom_read, 0
$0504	$1703			BSF	STATUS, RP1
$0505	$008D			MOVWF	EEADR
;EEPROMlib_E_A.ppas,12 :: 		
$0506	$1683			BSF	STATUS, RP0
$0507	$138C			BCF	EECON1, 7
$0508	$	EEPROMlib_E_A_L_2:
;EEPROMlib_E_A.ppas,13 :: 		
$0508	$	EEPROMlib_E_A_L_3:
$0508	$140C			BSF	EECON1, 0
$0509	$	EEPROMlib_E_A_L_4:
;EEPROMlib_E_A.ppas,14 :: 		
$0509	$1283			BCF	STATUS, RP0
$050A	$080C			MOVF	EEDATA, 0
$050B	$00C5			MOVWF	_eeprom_read_local_result
$050C	$	EEPROMlib_E_A_L_0:
;EEPROMlib_E_A.ppas,15 :: 		
$050C	$0845			MOVF	_eeprom_read_local_result, 0
$050D	$00F0			MOVWF	STACK_0
$050E	$0008			RETURN
$02C9	$	_eeprom_write:
;EEPROMlib_E_A.ppas,19 :: 		
;EEPROMlib_E_A.ppas,20 :: 		
$02C9	$	EEPROMlib_E_A_L_7:
$02C9	$1703			BSF	STATUS, RP1
$02CA	$1683			BSF	STATUS, RP0
$02CB	$3000			MOVLW	0
$02CC	$1703			BSF	STATUS, RP1
$02CD	$1683			BSF	STATUS, RP0
$02CE	$188C			BTFSC	EECON1, 1
$02CF	$3001			MOVLW	1
$02D0	$1303			BCF	STATUS, RP1
$02D1	$1283			BCF	STATUS, RP0
$02D2	$00F1			MOVWF	STACK_1
$02D3	$0871			MOVF	STACK_1, 0
$02D4	$3A01			XORLW	1
$02D5	$1D03			BTFSS	STATUS, Z
$02D6	$2AD9			GOTO	EEPROMlib_E_A_L_8
;EEPROMlib_E_A.ppas,21 :: 		
$02D7	$0000			NOP
$02D8	$2AC9			GOTO	EEPROMlib_E_A_L_7
$02D9	$	EEPROMlib_E_A_L_8:
;EEPROMlib_E_A.ppas,23 :: 		
$02D9	$0844			MOVF	FARG_EEprom_write, 0
$02DA	$1703			BSF	STATUS, RP1
$02DB	$008D			MOVWF	EEADR
;EEPROMlib_E_A.ppas,24 :: 		
$02DC	$0845			MOVF	FARG_EEprom_write+1, 0
$02DD	$008C			MOVWF	EEDATA
;EEPROMlib_E_A.ppas,25 :: 		
$02DE	$1683			BSF	STATUS, RP0
$02DF	$138C			BCF	EECON1, 7
$02E0	$	EEPROMlib_E_A_L_12:
;EEPROMlib_E_A.ppas,26 :: 		
$02E0	$	EEPROMlib_E_A_L_13:
$02E0	$150C			BSF	EECON1, 2
$02E1	$	EEPROMlib_E_A_L_14:
;EEPROMlib_E_A.ppas,28 :: 		
$02E1	$080B			MOVF	INTCON, 0
$02E2	$1303			BCF	STATUS, RP1
$02E3	$1283			BCF	STATUS, RP0
$02E4	$00C6			MOVWF	_eeprom_write_local_saveintcon
;EEPROMlib_E_A.ppas,31 :: 		
$02E5	$138B			BCF	INTCON, 7
$02E6	$	EEPROMlib_E_A_L_16:
;EEPROMlib_E_A.ppas,32 :: 		
$02E6	$3055			MOVLW	85
$02E7	$1703			BSF	STATUS, RP1
$02E8	$1683			BSF	STATUS, RP0
$02E9	$008D			MOVWF	EECON2
;EEPROMlib_E_A.ppas,33 :: 		
$02EA	$30AA			MOVLW	170
$02EB	$008D			MOVWF	EECON2
;EEPROMlib_E_A.ppas,34 :: 		
$02EC	$	EEPROMlib_E_A_L_17:
$02EC	$148C			BSF	EECON1, 1
$02ED	$	EEPROMlib_E_A_L_18:
;EEPROMlib_E_A.ppas,38 :: 		
$02ED	$1303			BCF	STATUS, RP1
$02EE	$1283			BCF	STATUS, RP0
$02EF	$0846			MOVF	_eeprom_write_local_saveintcon, 0
$02F0	$008B			MOVWF	INTCON
;EEPROMlib_E_A.ppas,39 :: 		
$02F1	$1703			BSF	STATUS, RP1
$02F2	$1683			BSF	STATUS, RP0
$02F3	$110C			BCF	EECON1, 2
$02F4	$	EEPROMlib_E_A_L_20:
$02F4	$	EEPROMlib_E_A_L_5:
;EEPROMlib_E_A.ppas,40 :: 		
$02F4	$0008			RETURN
$04B6	$	_private_i2c_master_restart:
;UI2C.ppas,127 :: 		begin
;UI2C.ppas,128 :: 		SSPCON2.RSEN:=True;
$04B6	$	UI2C_L_45:
$04B6	$1303			BCF	STATUS, RP1
$04B7	$1683			BSF	STATUS, RP0
$04B8	$1491			BSF	SSPCON2, 1
$04B9	$	UI2C_L_46:
;UI2C.ppas,129 :: 		while PIR1.SSPIF=False do begin end;
$04B9	$	UI2C_L_48:
$04B9	$1283			BCF	STATUS, RP0
$04BA	$080C			MOVF	PIR1, 0
$04BB	$00F1			MOVWF	STACK_1
$04BC	$3000			MOVLW	0
$04BD	$19F1			BTFSC	STACK_1, 3
$04BE	$3001			MOVLW	1
$04BF	$00F1			MOVWF	STACK_1
$04C0	$0871			MOVF	STACK_1, 0
$04C1	$3A00			XORLW	0
$04C2	$1903			BTFSC	STATUS, Z
$04C3	$2CB9			GOTO	UI2C_L_48
$04C4	$	UI2C_L_49:
;UI2C.ppas,130 :: 		PIR1.SSPIF:=False;
$04C4	$118C			BCF	PIR1, 3
$04C5	$	UI2C_L_53:
$04C5	$	UI2C_L_44:
;UI2C.ppas,131 :: 		end;
$04C5	$0008			RETURN
$0390	$	_private_i2c_master_acquirebusandstart:
;UI2C.ppas,138 :: 		begin
;UI2C.ppas,139 :: 		I2C_Started:=False;
$0390	$1303			BCF	STATUS, RP1
$0391	$1283			BCF	STATUS, RP0
$0392	$01AE			CLRF	_i2c_started, 1
;UI2C.ppas,141 :: 		if I2C_MultiMasterMode then
$0393	$082F			MOVF	_i2c_multimastermode, 0
$0394	$1903			BTFSC	STATUS, Z
$0395	$2BAB			GOTO	UI2C_L_56
$0396	$	UI2C_L_55:
;UI2C.ppas,143 :: 		while True do
$0396	$	UI2C_L_59:
;UI2C.ppas,145 :: 		if I2C_Is_Idle then
$0396	$23D6			CALL	_i2c_is_idle
$0397	$0870			MOVF	STACK_0, 0
$0398	$1903			BTFSC	STATUS, Z
$0399	$2BA3			GOTO	UI2C_L_64
$039A	$	UI2C_L_63:
;UI2C.ppas,147 :: 		I2C_SetMasterMode;
$039A	$23F3			CALL	_i2c_setmastermode
;UI2C.ppas,148 :: 		if Private_I2C_Master_Start then
$039B	$236C			CALL	_private_i2c_master_start
$039C	$0870			MOVF	STACK_0, 0
$039D	$1903			BTFSC	STATUS, Z
$039E	$2BA2			GOTO	UI2C_L_67
$039F	$	UI2C_L_66:
;UI2C.ppas,150 :: 		I2C_Started:=True;
$039F	$30FF			MOVLW	255
$03A0	$00AE			MOVWF	_i2c_started
;UI2C.ppas,151 :: 		Exit; // Success.
$03A1	$2BB3			GOTO	UI2C_L_54
;UI2C.ppas,152 :: 		end;
$03A2	$	UI2C_L_67:
$03A2	$	UI2C_L_68:
;UI2C.ppas,153 :: 		I2C_SetSlaveMode;
$03A2	$24A5			CALL	_i2c_setslavemode
;UI2C.ppas,154 :: 		end;
$03A3	$	UI2C_L_64:
$03A3	$	UI2C_L_65:
;UI2C.ppas,156 :: 		DelayMS(10); // Arbitrary but longer than the longest time to handle an instruction. A random time would be better.
$03A3	$1303			BCF	STATUS, RP1
$03A4	$1683			BSF	STATUS, RP0
$03A5	$300A			MOVLW	10
$03A6	$1283			BCF	STATUS, RP0
$03A7	$00C7			MOVWF	FARG_DelayMS
$03A8	$01C8			CLRF	FARG_DelayMS+1
$03A9	$23B4			CALL	_delayms
;UI2C.ppas,157 :: 		end;
$03AA	$2B96			GOTO	UI2C_L_59
;UI2C.ppas,159 :: 		else
$03AB	$	UI2C_L_56:
;UI2C.ppas,161 :: 		repeat until Private_I2C_Master_Start;
$03AB	$	UI2C_L_69:
$03AB	$	UI2C_L_70:
$03AB	$236C			CALL	_private_i2c_master_start
$03AC	$0870			MOVF	STACK_0, 0
$03AD	$1903			BTFSC	STATUS, Z
$03AE	$2BB0			GOTO	UI2C_L_72
$03AF	$	UI2C_L_73:
$03AF	$2BB1			GOTO	UI2C_L_71
$03B0	$	UI2C_L_72:
$03B0	$2BAB			GOTO	UI2C_L_69
$03B1	$	UI2C_L_71:
;UI2C.ppas,162 :: 		I2C_Started:=True;
$03B1	$30FF			MOVLW	255
$03B2	$00AE			MOVWF	_i2c_started
;UI2C.ppas,163 :: 		end;
$03B3	$	UI2C_L_57:
$03B3	$	UI2C_L_54:
;UI2C.ppas,164 :: 		end;
$03B3	$0008			RETURN
$0345	$	_i2c_master_sendbyte:
;UI2C.ppas,167 :: 		begin
;UI2C.ppas,168 :: 		SSPBUF:=Value;
$0345	$1303			BCF	STATUS, RP1
$0346	$1283			BCF	STATUS, RP0
$0347	$0844			MOVF	FARG_I2C_Master_SendByte, 0
$0348	$0093			MOVWF	SSPBUF
;UI2C.ppas,169 :: 		if SSPCON1.WCOL then
$0349	$3000			MOVLW	0
$034A	$1B94			BTFSC	SSPCON1, 7
$034B	$3001			MOVLW	1
$034C	$00F1			MOVWF	STACK_1
$034D	$0871			MOVF	STACK_1, 0
$034E	$1903			BTFSC	STATUS, Z
$034F	$2B53			GOTO	UI2C_L_76
$0350	$	UI2C_L_75:
;UI2C.ppas,171 :: 		I2C_Error:=I2C_WriteError;
$0350	$3001			MOVLW	1
$0351	$00B0			MOVWF	_i2c_error
;UI2C.ppas,172 :: 		SSPCON1.WCOL:=False;
$0352	$1394			BCF	SSPCON1, 7
$0353	$	UI2C_L_79:
;UI2C.ppas,173 :: 		end;
$0353	$	UI2C_L_76:
$0353	$	UI2C_L_77:
;UI2C.ppas,174 :: 		while PIR1.SSPIF=False do begin end;
$0353	$	UI2C_L_81:
$0353	$080C			MOVF	PIR1, 0
$0354	$00F1			MOVWF	STACK_1
$0355	$3000			MOVLW	0
$0356	$19F1			BTFSC	STACK_1, 3
$0357	$3001			MOVLW	1
$0358	$00F1			MOVWF	STACK_1
$0359	$0871			MOVF	STACK_1, 0
$035A	$3A00			XORLW	0
$035B	$1903			BTFSC	STATUS, Z
$035C	$2B53			GOTO	UI2C_L_81
$035D	$	UI2C_L_82:
;UI2C.ppas,175 :: 		PIR1.SSPIF:=False;
$035D	$118C			BCF	PIR1, 3
$035E	$	UI2C_L_86:
;UI2C.ppas,176 :: 		if SSPCON2.ACKSTAT then
$035E	$1683			BSF	STATUS, RP0
$035F	$0811			MOVF	SSPCON2, 0
$0360	$1283			BCF	STATUS, RP0
$0361	$00F1			MOVWF	STACK_1
$0362	$3000			MOVLW	0
$0363	$1B71			BTFSC	STACK_1, 6
$0364	$3001			MOVLW	1
$0365	$00F1			MOVWF	STACK_1
$0366	$0871			MOVF	STACK_1, 0
$0367	$1903			BTFSC	STATUS, Z
$0368	$2B6B			GOTO	UI2C_L_88
$0369	$	UI2C_L_87:
;UI2C.ppas,178 :: 		I2C_Error:=I2C_AckError;
$0369	$3002			MOVLW	2
$036A	$00B0			MOVWF	_i2c_error
;UI2C.ppas,179 :: 		end;
$036B	$	UI2C_L_88:
$036B	$	UI2C_L_89:
$036B	$	UI2C_L_74:
;UI2C.ppas,180 :: 		end;
$036B	$0008			RETURN
$04E5	$	_eeprom_readbyte:
;UGeneral.ppas,31 :: 		begin
;UGeneral.ppas,32 :: 		Result:=EEPROM_Read(Address);
$04E5	$1303			BCF	STATUS, RP1
$04E6	$1283			BCF	STATUS, RP0
$04E7	$083F			MOVF	FARG_EEPROM_ReadByte, 0
$04E8	$00C4			MOVWF	FARG_EEprom_read
$04E9	$2501			CALL	_eeprom_read
$04EA	$0870			MOVF	STACK_0, 0
$04EB	$00C0			MOVWF	_eeprom_readbyte_local_result
;UGeneral.ppas,33 :: 		DelayMS(20);
$04EC	$3014			MOVLW	20
$04ED	$00C7			MOVWF	FARG_DelayMS
$04EE	$01C8			CLRF	FARG_DelayMS+1
$04EF	$23B4			CALL	_delayms
$04F0	$	UGeneral_L_15:
;UGeneral.ppas,34 :: 		end;
$04F0	$0840			MOVF	_eeprom_readbyte_local_result, 0
$04F1	$00F0			MOVWF	STACK_0
$04F2	$0008			RETURN
$02F5	$	_eeprom_readword:
;UGeneral.ppas,45 :: 		begin
;UGeneral.ppas,46 :: 		LowByte:=EEPROM_Read(Address);
$02F5	$1303			BCF	STATUS, RP1
$02F6	$1283			BCF	STATUS, RP0
$02F7	$083F			MOVF	FARG_EEPROM_ReadWord, 0
$02F8	$00C4			MOVWF	FARG_EEprom_read
$02F9	$2501			CALL	_eeprom_read
$02FA	$0870			MOVF	STACK_0, 0
$02FB	$00C2			MOVWF	_eeprom_readword_local_lowbyte
;UGeneral.ppas,47 :: 		DelayMS(20);
$02FC	$3014			MOVLW	20
$02FD	$00C7			MOVWF	FARG_DelayMS
$02FE	$01C8			CLRF	FARG_DelayMS+1
$02FF	$23B4			CALL	_delayms
;UGeneral.ppas,48 :: 		HighByte:=EEPROM_Read(Address+1);
$0300	$0A3F			INCF	FARG_EEPROM_ReadWord, 0
$0301	$00C4			MOVWF	FARG_EEprom_read
$0302	$2501			CALL	_eeprom_read
$0303	$0870			MOVF	STACK_0, 0
$0304	$00C3			MOVWF	_eeprom_readword_local_highbyte
;UGeneral.ppas,49 :: 		DelayMS(20);
$0305	$3014			MOVLW	20
$0306	$00C7			MOVWF	FARG_DelayMS
$0307	$01C8			CLRF	FARG_DelayMS+1
$0308	$23B4			CALL	_delayms
;UGeneral.ppas,51 :: 		Result:=LowByte+(HighByte shl 8);
$0309	$0843			MOVF	_eeprom_readword_local_highbyte, 0
$030A	$00F2			MOVWF	STACK_2
$030B	$01F3			CLRF	STACK_2+1
$030C	$0872			MOVF	STACK_2, 0
$030D	$00F3			MOVWF	STACK_2+1
$030E	$01F2			CLRF	STACK_2
$030F	$0842			MOVF	_eeprom_readword_local_lowbyte, 0
$0310	$00C0			MOVWF	_eeprom_readword_local_result
$0311	$01C1			CLRF	_eeprom_readword_local_result+1
$0312	$0872			MOVF	STACK_2, 0
$0313	$07C0			ADDWF	_eeprom_readword_local_result, 1
$0314	$0873			MOVF	STACK_2+1, 0
$0315	$1803			BTFSC	STATUS, C
$0316	$3F01			ADDLW	1
$0317	$07C1			ADDWF	_eeprom_readword_local_result+1, 1
$0318	$	UGeneral_L_17:
;UGeneral.ppas,52 :: 		end;
$0318	$0840			MOVF	_eeprom_readword_local_result, 0
$0319	$00F0			MOVWF	STACK_0
$031A	$0841			MOVF	_eeprom_readword_local_result+1, 0
$031B	$00F1			MOVWF	STACK_0+1
$031C	$0008			RETURN
$04F3	$	_eeprom_writebyte:
;UGeneral.ppas,37 :: 		begin
;UGeneral.ppas,38 :: 		EEPROM_Write(Address,Value);
$04F3	$1303			BCF	STATUS, RP1
$04F4	$1283			BCF	STATUS, RP0
$04F5	$083F			MOVF	FARG_EEPROM_WriteByte, 0
$04F6	$00C4			MOVWF	FARG_EEprom_write
$04F7	$0840			MOVF	FARG_EEPROM_WriteByte+1, 0
$04F8	$00C5			MOVWF	FARG_EEprom_write+1
$04F9	$22C9			CALL	_eeprom_write
;UGeneral.ppas,39 :: 		DelayMS(20);
$04FA	$3014			MOVLW	20
$04FB	$1303			BCF	STATUS, RP1
$04FC	$1283			BCF	STATUS, RP0
$04FD	$00C7			MOVWF	FARG_DelayMS
$04FE	$01C8			CLRF	FARG_DelayMS+1
$04FF	$23B4			CALL	_delayms
$0500	$	UGeneral_L_16:
;UGeneral.ppas,40 :: 		end;
$0500	$0008			RETURN
$040E	$	_eeprom_writeword:
;UGeneral.ppas,55 :: 		begin
;UGeneral.ppas,56 :: 		EEPROM_Write(Address,Lo(Value));
$040E	$1303			BCF	STATUS, RP1
$040F	$1283			BCF	STATUS, RP0
$0410	$083F			MOVF	FARG_EEPROM_WriteWord, 0
$0411	$00C4			MOVWF	FARG_EEprom_write
$0412	$30FF			MOVLW	255
$0413	$0540			ANDWF	FARG_EEPROM_WriteWord+1, 0
$0414	$00C5			MOVWF	FARG_EEprom_write+1
$0415	$22C9			CALL	_eeprom_write
;UGeneral.ppas,57 :: 		DelayMS(20);
$0416	$3014			MOVLW	20
$0417	$1303			BCF	STATUS, RP1
$0418	$1283			BCF	STATUS, RP0
$0419	$00C7			MOVWF	FARG_DelayMS
$041A	$01C8			CLRF	FARG_DelayMS+1
$041B	$23B4			CALL	_delayms
;UGeneral.ppas,58 :: 		EEPROM_Write(Address+1,Hi(Value));
$041C	$0A3F			INCF	FARG_EEPROM_WriteWord, 0
$041D	$00C4			MOVWF	FARG_EEprom_write
$041E	$0841			MOVF	FARG_EEPROM_WriteWord+2, 0
$041F	$00C5			MOVWF	FARG_EEprom_write+1
$0420	$22C9			CALL	_eeprom_write
;UGeneral.ppas,59 :: 		DelayMS(20);
$0421	$3014			MOVLW	20
$0422	$1303			BCF	STATUS, RP1
$0423	$1283			BCF	STATUS, RP0
$0424	$00C7			MOVWF	FARG_DelayMS
$0425	$01C8			CLRF	FARG_DelayMS+1
$0426	$23B4			CALL	_delayms
$0427	$	UGeneral_L_18:
;UGeneral.ppas,60 :: 		end;
$0427	$0008			RETURN
$051C	$	_i2c_master_startwrite:
;UI2C.ppas,189 :: 		begin
;UI2C.ppas,190 :: 		if I2C_Started then
$051C	$1303			BCF	STATUS, RP1
$051D	$1283			BCF	STATUS, RP0
$051E	$082E			MOVF	_i2c_started, 0
$051F	$1903			BTFSC	STATUS, Z
$0520	$2D23			GOTO	UI2C_L_93
$0521	$	UI2C_L_92:
;UI2C.ppas,191 :: 		Private_I2C_Master_Restart
$0521	$24B6			CALL	_private_i2c_master_restart
$0522	$2D24			GOTO	UI2C_L_94
;UI2C.ppas,192 :: 		else
$0523	$	UI2C_L_93:
;UI2C.ppas,193 :: 		Private_I2C_Master_AcquireBusAndStart;
$0523	$2390			CALL	_private_i2c_master_acquirebusandstart
$0524	$	UI2C_L_94:
;UI2C.ppas,195 :: 		I2C_Master_SendByte(DeviceAddress);
$0524	$083F			MOVF	FARG_I2C_Master_StartWrite, 0
$0525	$00C4			MOVWF	FARG_I2C_Master_SendByte
$0526	$2345			CALL	_i2c_master_sendbyte
$0527	$	UI2C_L_91:
;UI2C.ppas,196 :: 		end;
$0527	$0008			RETURN
$050F	$	_i2c_master_sendcommandwithwordparameter:
;UI2C.ppas,227 :: 		begin
;UI2C.ppas,228 :: 		I2C_Master_SendByte(Command);
$050F	$1303			BCF	STATUS, RP1
$0510	$1283			BCF	STATUS, RP0
$0511	$083F			MOVF	FARG_I2C_Master_SendCommandWithWordParameter, 0
$0512	$00C4			MOVWF	FARG_I2C_Master_SendByte
$0513	$2345			CALL	_i2c_master_sendbyte
;UI2C.ppas,229 :: 		I2C_Master_SendByte(Lo(Parameter));
$0514	$30FF			MOVLW	255
$0515	$0540			ANDWF	FARG_I2C_Master_SendCommandWithWordParameter+1, 0
$0516	$00C4			MOVWF	FARG_I2C_Master_SendByte
$0517	$2345			CALL	_i2c_master_sendbyte
;UI2C.ppas,230 :: 		I2C_Master_SendByte(Hi(Parameter));
$0518	$0841			MOVF	FARG_I2C_Master_SendCommandWithWordParameter+2, 0
$0519	$00C4			MOVWF	FARG_I2C_Master_SendByte
$051A	$2345			CALL	_i2c_master_sendbyte
$051B	$	UI2C_L_113:
;UI2C.ppas,231 :: 		end;
$051B	$0008			RETURN
$0428	$	_i2c_master_stop:
;UI2C.ppas,209 :: 		begin
;UI2C.ppas,210 :: 		I2C_Started:=False;
$0428	$1303			BCF	STATUS, RP1
$0429	$1283			BCF	STATUS, RP0
$042A	$01AE			CLRF	_i2c_started, 1
;UI2C.ppas,212 :: 		SSPCON2.PEN:=True;
$042B	$	UI2C_L_100:
$042B	$1683			BSF	STATUS, RP0
$042C	$1511			BSF	SSPCON2, 2
$042D	$	UI2C_L_101:
;UI2C.ppas,213 :: 		while PIR1.SSPIF=False do begin end;
$042D	$	UI2C_L_103:
$042D	$1283			BCF	STATUS, RP0
$042E	$080C			MOVF	PIR1, 0
$042F	$00F1			MOVWF	STACK_1
$0430	$3000			MOVLW	0
$0431	$19F1			BTFSC	STACK_1, 3
$0432	$3001			MOVLW	1
$0433	$00F1			MOVWF	STACK_1
$0434	$0871			MOVF	STACK_1, 0
$0435	$3A00			XORLW	0
$0436	$1903			BTFSC	STATUS, Z
$0437	$2C2D			GOTO	UI2C_L_103
$0438	$	UI2C_L_104:
;UI2C.ppas,214 :: 		PIR1.SSPIF:=False;
$0438	$118C			BCF	PIR1, 3
$0439	$	UI2C_L_108:
;UI2C.ppas,216 :: 		if I2C_MultiMasterMode then
$0439	$082F			MOVF	_i2c_multimastermode, 0
$043A	$1903			BTFSC	STATUS, Z
$043B	$2C3D			GOTO	UI2C_L_110
$043C	$	UI2C_L_109:
;UI2C.ppas,217 :: 		I2C_SetSlaveMode;
$043C	$24A5			CALL	_i2c_setslavemode
$043D	$	UI2C_L_110:
$043D	$	UI2C_L_111:
$043D	$	UI2C_L_99:
;UI2C.ppas,218 :: 		end;
$043D	$1303			BCF	STATUS, RP1
$043E	$1683			BSF	STATUS, RP0
$043F	$0008			RETURN
$04D6	$	_setdefaultoptions:
;I2C.ppas,141 :: 		begin
;I2C.ppas,142 :: 		PORTA_BitPolarity:=$00;
$04D6	$1303			BCF	STATUS, RP1
$04D7	$1283			BCF	STATUS, RP0
$04D8	$01A4			CLRF	_porta_bitpolarity, 1
;I2C.ppas,143 :: 		PORTB_BitPolarity:=$00;
$04D9	$01A6			CLRF	_portb_bitpolarity, 1
;I2C.ppas,144 :: 		PORTC_BitPolarity:=$00;
$04DA	$01A7			CLRF	_portc_bitpolarity, 1
;I2C.ppas,145 :: 		PORTA:=$00;
$04DB	$0185			CLRF	PORTA, 1
;I2C.ppas,146 :: 		PORTB:=$00;
$04DC	$0186			CLRF	PORTB, 1
;I2C.ppas,147 :: 		PORTC:=$00;
$04DD	$0187			CLRF	PORTC, 1
;I2C.ppas,148 :: 		Mode:=-1;
$04DE	$30FF			MOVLW	255
$04DF	$00B1			MOVWF	_mode
;I2C.ppas,149 :: 		DelayTimeMS:=500;
$04E0	$30F4			MOVLW	244
$04E1	$00A1			MOVWF	_delaytimems
$04E2	$3001			MOVLW	1
$04E3	$00A2			MOVWF	_delaytimems+1
$04E4	$	I2C_L_69:
;I2C.ppas,150 :: 		end;
$04E4	$0008			RETURN
$0265	$	_loadoptionsfromeeprom:
;I2C.ppas,153 :: 		begin
;I2C.ppas,154 :: 		if EEPROM_ReadByte($00)=$FF then Exit; // Check options are valid.
$0265	$1303			BCF	STATUS, RP1
$0266	$1283			BCF	STATUS, RP0
$0267	$01BF			CLRF	FARG_EEPROM_ReadByte, 1
$0268	$24E5			CALL	_eeprom_readbyte
$0269	$0870			MOVF	STACK_0, 0
$026A	$3AFF			XORLW	255
$026B	$1D03			BTFSS	STATUS, Z
$026C	$2A6E			GOTO	I2C_L_72
$026D	$	I2C_L_71:
$026D	$2A98			GOTO	I2C_L_70
$026E	$	I2C_L_72:
$026E	$	I2C_L_73:
;I2C.ppas,156 :: 		PORTA_BitPolarity:=EEPROM_ReadByte($01);
$026E	$3001			MOVLW	1
$026F	$00BF			MOVWF	FARG_EEPROM_ReadByte
$0270	$24E5			CALL	_eeprom_readbyte
$0271	$0870			MOVF	STACK_0, 0
$0272	$00A4			MOVWF	_porta_bitpolarity
;I2C.ppas,157 :: 		PORTB_BitPolarity:=EEPROM_ReadByte($02);
$0273	$3002			MOVLW	2
$0274	$00BF			MOVWF	FARG_EEPROM_ReadByte
$0275	$24E5			CALL	_eeprom_readbyte
$0276	$0870			MOVF	STACK_0, 0
$0277	$00A6			MOVWF	_portb_bitpolarity
;I2C.ppas,158 :: 		PORTC_BitPolarity:=EEPROM_ReadByte($03);
$0278	$3003			MOVLW	3
$0279	$00BF			MOVWF	FARG_EEPROM_ReadByte
$027A	$24E5			CALL	_eeprom_readbyte
$027B	$0870			MOVF	STACK_0, 0
$027C	$00A7			MOVWF	_portc_bitpolarity
;I2C.ppas,159 :: 		PORTA:=EEPROM_ReadByte($04);
$027D	$3004			MOVLW	4
$027E	$00BF			MOVWF	FARG_EEPROM_ReadByte
$027F	$24E5			CALL	_eeprom_readbyte
$0280	$0870			MOVF	STACK_0, 0
$0281	$0085			MOVWF	PORTA
;I2C.ppas,160 :: 		PORTB:=EEPROM_ReadByte($05);
$0282	$3005			MOVLW	5
$0283	$00BF			MOVWF	FARG_EEPROM_ReadByte
$0284	$24E5			CALL	_eeprom_readbyte
$0285	$0870			MOVF	STACK_0, 0
$0286	$0086			MOVWF	PORTB
;I2C.ppas,161 :: 		PORTC:=EEPROM_ReadByte($06);
$0287	$3006			MOVLW	6
$0288	$00BF			MOVWF	FARG_EEPROM_ReadByte
$0289	$24E5			CALL	_eeprom_readbyte
$028A	$0870			MOVF	STACK_0, 0
$028B	$0087			MOVWF	PORTC
;I2C.ppas,162 :: 		Mode:=EEPROM_ReadByte($07);
$028C	$3007			MOVLW	7
$028D	$00BF			MOVWF	FARG_EEPROM_ReadByte
$028E	$24E5			CALL	_eeprom_readbyte
$028F	$0870			MOVF	STACK_0, 0
$0290	$00B1			MOVWF	_mode
;I2C.ppas,163 :: 		DelayTimeMS:=EEPROM_ReadWord($08);
$0291	$3008			MOVLW	8
$0292	$00BF			MOVWF	FARG_EEPROM_ReadWord
$0293	$22F5			CALL	_eeprom_readword
$0294	$0870			MOVF	STACK_0, 0
$0295	$00A1			MOVWF	_delaytimems
$0296	$0871			MOVF	STACK_0+1, 0
$0297	$00A2			MOVWF	_delaytimems+1
$0298	$	I2C_L_70:
;I2C.ppas,164 :: 		end;
$0298	$0008			RETURN
$046D	$	_i2c_initialize:
;UI2C.ppas,89 :: 		begin
;UI2C.ppas,90 :: 		I2C_Initialized:=False;
$046D	$1303			BCF	STATUS, RP1
$046E	$1283			BCF	STATUS, RP0
$046F	$01AA			CLRF	_i2c_initialized, 1
;UI2C.ppas,91 :: 		I2C_Started:=False;
$0470	$01AE			CLRF	_i2c_started, 1
;UI2C.ppas,92 :: 		I2C_Error:=0;
$0471	$01B0			CLRF	_i2c_error, 1
;UI2C.ppas,93 :: 		I2C_MultiMasterMode:=MultiMasterMode;
$0472	$083E			MOVF	FARG_I2C_Initialize+1, 0
$0473	$00AF			MOVWF	_i2c_multimastermode
;UI2C.ppas,94 :: 		I2C_SlaveAddress:=SlaveAddress;
$0474	$083D			MOVF	FARG_I2C_Initialize, 0
$0475	$00AD			MOVWF	_i2c_slaveaddress
;UI2C.ppas,95 :: 		I2C_SetMasterMode; // Call even in MultiMasterMode to setup the port pins.
$0476	$23F3			CALL	_i2c_setmastermode
;UI2C.ppas,96 :: 		if MultiMasterMode then
$0477	$083E			MOVF	FARG_I2C_Initialize+1, 0
$0478	$1903			BTFSC	STATUS, Z
$0479	$2C7B			GOTO	UI2C_L_23
$047A	$	UI2C_L_22:
;UI2C.ppas,97 :: 		I2C_SetSlaveMode;
$047A	$24A5			CALL	_i2c_setslavemode
$047B	$	UI2C_L_23:
$047B	$	UI2C_L_24:
;UI2C.ppas,98 :: 		I2C_Initialized:=True;
$047B	$1303			BCF	STATUS, RP1
$047C	$1683			BSF	STATUS, RP0
$047D	$30FF			MOVLW	255
$047E	$1283			BCF	STATUS, RP0
$047F	$00AA			MOVWF	_i2c_initialized
$0480	$	UI2C_L_21:
;UI2C.ppas,99 :: 		end;
$0480	$0008			RETURN
$04C6	$	_globaldisableinterrupts:
;UGeneral.ppas,24 :: 		begin
;UGeneral.ppas,25 :: 		repeat
$04C6	$	UGeneral_L_8:
;UGeneral.ppas,26 :: 		INTCON.GIE:=False;
$04C6	$138B			BCF	INTCON, 7
$04C7	$	UGeneral_L_14:
;UGeneral.ppas,27 :: 		until INTCON.GIE=False;
$04C7	$	UGeneral_L_9:
$04C7	$080B			MOVF	INTCON, 0
$04C8	$1303			BCF	STATUS, RP1
$04C9	$1283			BCF	STATUS, RP0
$04CA	$00F1			MOVWF	STACK_1
$04CB	$3000			MOVLW	0
$04CC	$1BF1			BTFSC	STACK_1, 7
$04CD	$3001			MOVLW	1
$04CE	$00F1			MOVWF	STACK_1
$04CF	$0871			MOVF	STACK_1, 0
$04D0	$3A00			XORLW	0
$04D1	$1D03			BTFSS	STATUS, Z
$04D2	$2CD4			GOTO	UGeneral_L_11
$04D3	$	UGeneral_L_12:
$04D3	$2CD5			GOTO	UGeneral_L_10
$04D4	$	UGeneral_L_11:
$04D4	$2CC6			GOTO	UGeneral_L_8
$04D5	$	UGeneral_L_10:
$04D5	$	UGeneral_L_7:
;UGeneral.ppas,28 :: 		end;
$04D5	$0008			RETURN
$0299	$	_saveoptionstoeeprom:
;I2C.ppas,167 :: 		begin
;I2C.ppas,168 :: 		EEPROM_WriteByte($00,$00); // $00=Options valid.
$0299	$1303			BCF	STATUS, RP1
$029A	$1283			BCF	STATUS, RP0
$029B	$01BF			CLRF	FARG_EEPROM_WriteByte, 1
$029C	$01C0			CLRF	FARG_EEPROM_WriteByte+1, 1
$029D	$24F3			CALL	_eeprom_writebyte
;I2C.ppas,169 :: 		EEPROM_WriteByte($01,PORTA_BitPolarity);
$029E	$3001			MOVLW	1
$029F	$00BF			MOVWF	FARG_EEPROM_WriteByte
$02A0	$0824			MOVF	_porta_bitpolarity, 0
$02A1	$00C0			MOVWF	FARG_EEPROM_WriteByte+1
$02A2	$24F3			CALL	_eeprom_writebyte
;I2C.ppas,170 :: 		EEPROM_WriteByte($02,PORTB_BitPolarity);
$02A3	$3002			MOVLW	2
$02A4	$00BF			MOVWF	FARG_EEPROM_WriteByte
$02A5	$0826			MOVF	_portb_bitpolarity, 0
$02A6	$00C0			MOVWF	FARG_EEPROM_WriteByte+1
$02A7	$24F3			CALL	_eeprom_writebyte
;I2C.ppas,171 :: 		EEPROM_WriteByte($03,PORTC_BitPolarity);
$02A8	$3003			MOVLW	3
$02A9	$00BF			MOVWF	FARG_EEPROM_WriteByte
$02AA	$0827			MOVF	_portc_bitpolarity, 0
$02AB	$00C0			MOVWF	FARG_EEPROM_WriteByte+1
$02AC	$24F3			CALL	_eeprom_writebyte
;I2C.ppas,172 :: 		EEPROM_WriteByte($04,PORTA);
$02AD	$3004			MOVLW	4
$02AE	$00BF			MOVWF	FARG_EEPROM_WriteByte
$02AF	$0805			MOVF	PORTA, 0
$02B0	$00C0			MOVWF	FARG_EEPROM_WriteByte+1
$02B1	$24F3			CALL	_eeprom_writebyte
;I2C.ppas,173 :: 		EEPROM_WriteByte($05,PORTB);
$02B2	$3005			MOVLW	5
$02B3	$00BF			MOVWF	FARG_EEPROM_WriteByte
$02B4	$0806			MOVF	PORTB, 0
$02B5	$00C0			MOVWF	FARG_EEPROM_WriteByte+1
$02B6	$24F3			CALL	_eeprom_writebyte
;I2C.ppas,174 :: 		EEPROM_WriteByte($06,PORTC);
$02B7	$3006			MOVLW	6
$02B8	$00BF			MOVWF	FARG_EEPROM_WriteByte
$02B9	$0807			MOVF	PORTC, 0
$02BA	$00C0			MOVWF	FARG_EEPROM_WriteByte+1
$02BB	$24F3			CALL	_eeprom_writebyte
;I2C.ppas,175 :: 		EEPROM_WriteByte($07,Mode);
$02BC	$3007			MOVLW	7
$02BD	$00BF			MOVWF	FARG_EEPROM_WriteByte
$02BE	$0831			MOVF	_mode, 0
$02BF	$00C0			MOVWF	FARG_EEPROM_WriteByte+1
$02C0	$24F3			CALL	_eeprom_writebyte
;I2C.ppas,176 :: 		EEPROM_WriteWord($08,DelayTimeMS);
$02C1	$3008			MOVLW	8
$02C2	$00BF			MOVWF	FARG_EEPROM_WriteWord
$02C3	$0821			MOVF	_delaytimems, 0
$02C4	$00C0			MOVWF	FARG_EEPROM_WriteWord+1
$02C5	$0822			MOVF	_delaytimems+1, 0
$02C6	$00C1			MOVWF	FARG_EEPROM_WriteWord+2
$02C7	$240E			CALL	_eeprom_writeword
$02C8	$	I2C_L_74:
;I2C.ppas,177 :: 		end;
$02C8	$0008			RETURN
$0458	$	_sendportatodisplay:
;I2C.ppas,130 :: 		begin
;I2C.ppas,131 :: 		TRISA:=$FF;
$0458	$30FF			MOVLW	255
$0459	$1303			BCF	STATUS, RP1
$045A	$1683			BSF	STATUS, RP0
$045B	$0085			MOVWF	TRISA
;I2C.ppas,133 :: 		I2C_Master_StartWrite($28);
$045C	$3028			MOVLW	40
$045D	$1283			BCF	STATUS, RP0
$045E	$00BF			MOVWF	FARG_I2C_Master_StartWrite
$045F	$251C			CALL	_i2c_master_startwrite
;I2C.ppas,134 :: 		I2C_Master_SendCommandWithWordParameter($02,PORTA);
$0460	$3002			MOVLW	2
$0461	$00BF			MOVWF	FARG_I2C_Master_SendCommandWithWordParameter
$0462	$0805			MOVF	PORTA, 0
$0463	$00C0			MOVWF	FARG_I2C_Master_SendCommandWithWordParameter+1
$0464	$01C1			CLRF	FARG_I2C_Master_SendCommandWithWordParameter+2
$0465	$250F			CALL	_i2c_master_sendcommandwithwordparameter
;I2C.ppas,135 :: 		I2C_Master_Stop;
$0466	$2428			CALL	_i2c_master_stop
;I2C.ppas,137 :: 		DelayMS(50); // Reduce flicker.
$0467	$3032			MOVLW	50
$0468	$1283			BCF	STATUS, RP0
$0469	$00C7			MOVWF	FARG_DelayMS
$046A	$01C8			CLRF	FARG_DelayMS+1
$046B	$23B4			CALL	_delayms
$046C	$	I2C_L_68:
;I2C.ppas,138 :: 		end;
$046C	$0008			RETURN
$0027	$	_main:
;I2C.ppas,179 :: 		begin
;I2C.ppas,180 :: 		OPTION_REG:=$D7; // Includes timer 0 prescale.
$0027	$30D7			MOVLW	215
$0028	$1303			BCF	STATUS, RP1
$0029	$1683			BSF	STATUS, RP0
$002A	$0081			MOVWF	OPTION_REG
;I2C.ppas,183 :: 		ADCON0:=$00;
$002B	$1283			BCF	STATUS, RP0
$002C	$019F			CLRF	ADCON0, 1
;I2C.ppas,184 :: 		ADCON1:=$06;
$002D	$3006			MOVLW	6
$002E	$1683			BSF	STATUS, RP0
$002F	$009F			MOVWF	ADCON1
;I2C.ppas,186 :: 		I2CCommand:=-1;
$0030	$30FF			MOVLW	255
$0031	$1283			BCF	STATUS, RP0
$0032	$00A0			MOVWF	_i2ccommand
;I2C.ppas,187 :: 		Interrupt_SetDefaultOptions:=False;
$0033	$01A9			CLRF	_interrupt_setdefaultoptions, 1
;I2C.ppas,188 :: 		Interrupt_SaveOptionsToEEPROM:=False;
$0034	$01A5			CLRF	_interrupt_saveoptionstoeeprom, 1
;I2C.ppas,190 :: 		SetDefaultOptions;
$0035	$24D6			CALL	_setdefaultoptions
;I2C.ppas,191 :: 		LoadOptionsFromEEPROM;
$0036	$2265			CALL	_loadoptionsfromeeprom
;I2C.ppas,194 :: 		TRISA:=$FF;
$0037	$30FF			MOVLW	255
$0038	$1683			BSF	STATUS, RP0
$0039	$0085			MOVWF	TRISA
;I2C.ppas,195 :: 		TRISB:=$00;
$003A	$0186			CLRF	TRISB, 1
;I2C.ppas,196 :: 		TRISC:=$18;
$003B	$3018			MOVLW	24
$003C	$0087			MOVWF	TRISC
;I2C.ppas,198 :: 		I2C_Initialize(SlaveAddress,True);
$003D	$3024			MOVLW	36
$003E	$1283			BCF	STATUS, RP0
$003F	$00BD			MOVWF	FARG_I2C_Initialize
$0040	$30FF			MOVLW	255
$0041	$00BE			MOVWF	FARG_I2C_Initialize+1
$0042	$246D			CALL	_i2c_initialize
;I2C.ppas,200 :: 		INTCON:=$C0;
$0043	$30C0			MOVLW	192
$0044	$008B			MOVWF	INTCON
;I2C.ppas,203 :: 		if Mode>=16 then Mode:=0;
$0045	$3010			MOVLW	16
$0046	$0231			SUBWF	_mode, 0
$0047	$1C03			BTFSS	STATUS, C
$0048	$284A			GOTO	I2C_L_77
$0049	$	I2C_L_76:
$0049	$01B1			CLRF	_mode, 1
$004A	$	I2C_L_77:
$004A	$	I2C_L_78:
;I2C.ppas,205 :: 		Interrupt_Mode:=Mode;
$004A	$0831			MOVF	_mode, 0
$004B	$00A8			MOVWF	_interrupt_mode
;I2C.ppas,207 :: 		repeat
$004C	$	I2C_L_79:
;I2C.ppas,209 :: 		GlobalDisableInterrupts;
$004C	$24C6			CALL	_globaldisableinterrupts
;I2C.ppas,210 :: 		Mode:=Interrupt_Mode;
$004D	$0828			MOVF	_interrupt_mode, 0
$004E	$00B1			MOVWF	_mode
;I2C.ppas,211 :: 		MainThread_SetDefaultOptions:=Interrupt_SetDefaultOptions;
$004F	$0829			MOVF	_interrupt_setdefaultoptions, 0
$0050	$00B2			MOVWF	_mainthread_setdefaultoptions
;I2C.ppas,212 :: 		Interrupt_SetDefaultOptions:=False;
$0051	$01A9			CLRF	_interrupt_setdefaultoptions, 1
;I2C.ppas,213 :: 		MainThread_SaveOptionsToEEPROM:=Interrupt_SaveOptionsToEEPROM;
$0052	$0825			MOVF	_interrupt_saveoptionstoeeprom, 0
$0053	$00B3			MOVWF	_mainthread_saveoptionstoeeprom
;I2C.ppas,214 :: 		Interrupt_SaveOptionsToEEPROM:=False;
$0054	$01A5			CLRF	_interrupt_saveoptionstoeeprom, 1
;I2C.ppas,215 :: 		INTCON.GIE:=True;
$0055	$	I2C_L_84:
$0055	$178B			BSF	INTCON, 7
$0056	$	I2C_L_85:
;I2C.ppas,217 :: 		if MainThread_SetDefaultOptions then
$0056	$0832			MOVF	_mainthread_setdefaultoptions, 0
$0057	$1903			BTFSC	STATUS, Z
$0058	$285A			GOTO	I2C_L_87
$0059	$	I2C_L_86:
;I2C.ppas,218 :: 		SetDefaultOptions;
$0059	$24D6			CALL	_setdefaultoptions
$005A	$	I2C_L_87:
$005A	$	I2C_L_88:
;I2C.ppas,220 :: 		if MainThread_SaveOptionsToEEPROM then
$005A	$0833			MOVF	_mainthread_saveoptionstoeeprom, 0
$005B	$1903			BTFSC	STATUS, Z
$005C	$285E			GOTO	I2C_L_90
$005D	$	I2C_L_89:
;I2C.ppas,221 :: 		SaveOptionsToEEPROM;
$005D	$2299			CALL	_saveoptionstoeeprom
$005E	$	I2C_L_90:
$005E	$	I2C_L_91:
;I2C.ppas,224 :: 		$00:
$005E	$	I2C_L_94:
$005E	$0831			MOVF	_mode, 0
$005F	$3A00			XORLW	0
$0060	$1D03			BTFSS	STATUS, Z
$0061	$2879			GOTO	I2C_L_95
$0062	$	I2C_L_93:
;I2C.ppas,227 :: 		PORTC.0:=1;
$0062	$	I2C_L_96:
$0062	$1407			BSF	PORTC, 0
$0063	$	I2C_L_97:
;I2C.ppas,228 :: 		PORTC.1:=0;
$0063	$1087			BCF	PORTC, 1
$0064	$	I2C_L_99:
;I2C.ppas,229 :: 		PORTC.2:=1;
$0064	$	I2C_L_100:
$0064	$1507			BSF	PORTC, 2
$0065	$	I2C_L_101:
;I2C.ppas,232 :: 		PORTC.5:=1;
$0065	$	I2C_L_102:
$0065	$1687			BSF	PORTC, 5
$0066	$	I2C_L_103:
;I2C.ppas,233 :: 		PORTC.6:=0;
$0066	$1307			BCF	PORTC, 6
$0067	$	I2C_L_105:
;I2C.ppas,234 :: 		PORTC.7:=1;
$0067	$	I2C_L_106:
$0067	$1787			BSF	PORTC, 7
$0068	$	I2C_L_107:
;I2C.ppas,236 :: 		DelayMS(DelayTimeMS);
$0068	$0821			MOVF	_delaytimems, 0
$0069	$00C7			MOVWF	FARG_DelayMS
$006A	$0822			MOVF	_delaytimems+1, 0
$006B	$00C8			MOVWF	FARG_DelayMS+1
$006C	$23B4			CALL	_delayms
;I2C.ppas,239 :: 		PORTC.0:=0;
$006D	$1007			BCF	PORTC, 0
$006E	$	I2C_L_109:
;I2C.ppas,240 :: 		PORTC.1:=1;
$006E	$	I2C_L_110:
$006E	$1487			BSF	PORTC, 1
$006F	$	I2C_L_111:
;I2C.ppas,241 :: 		PORTC.2:=0;
$006F	$1107			BCF	PORTC, 2
$0070	$	I2C_L_113:
;I2C.ppas,244 :: 		PORTC.5:=0;
$0070	$1287			BCF	PORTC, 5
$0071	$	I2C_L_115:
;I2C.ppas,245 :: 		PORTC.6:=1;
$0071	$	I2C_L_116:
$0071	$1707			BSF	PORTC, 6
$0072	$	I2C_L_117:
;I2C.ppas,246 :: 		PORTC.7:=0;
$0072	$1387			BCF	PORTC, 7
$0073	$	I2C_L_119:
;I2C.ppas,248 :: 		DelayMS(DelayTimeMS);
$0073	$0821			MOVF	_delaytimems, 0
$0074	$00C7			MOVWF	FARG_DelayMS
$0075	$0822			MOVF	_delaytimems+1, 0
$0076	$00C8			MOVWF	FARG_DelayMS+1
$0077	$23B4			CALL	_delayms
;I2C.ppas,249 :: 		end;
$0078	$297D			GOTO	I2C_L_92
$0079	$	I2C_L_95:
;I2C.ppas,251 :: 		$01:
$0079	$	I2C_L_121:
$0079	$0831			MOVF	_mode, 0
$007A	$3A01			XORLW	1
$007B	$1D03			BTFSS	STATUS, Z
$007C	$2893			GOTO	I2C_L_122
$007D	$	I2C_L_120:
;I2C.ppas,253 :: 		PORTC:=%00100001;
$007D	$3021			MOVLW	33
$007E	$0087			MOVWF	PORTC
;I2C.ppas,254 :: 		DelayMS(DelayTimeMS);
$007F	$0821			MOVF	_delaytimems, 0
$0080	$00C7			MOVWF	FARG_DelayMS
$0081	$0822			MOVF	_delaytimems+1, 0
$0082	$00C8			MOVWF	FARG_DelayMS+1
$0083	$23B4			CALL	_delayms
;I2C.ppas,255 :: 		PORTC:=%01000010;
$0084	$3042			MOVLW	66
$0085	$0087			MOVWF	PORTC
;I2C.ppas,256 :: 		DelayMS(DelayTimeMS);
$0086	$0821			MOVF	_delaytimems, 0
$0087	$00C7			MOVWF	FARG_DelayMS
$0088	$0822			MOVF	_delaytimems+1, 0
$0089	$00C8			MOVWF	FARG_DelayMS+1
$008A	$23B4			CALL	_delayms
;I2C.ppas,257 :: 		PORTC:=%10000100;
$008B	$3084			MOVLW	132
$008C	$0087			MOVWF	PORTC
;I2C.ppas,258 :: 		DelayMS(DelayTimeMS);
$008D	$0821			MOVF	_delaytimems, 0
$008E	$00C7			MOVWF	FARG_DelayMS
$008F	$0822			MOVF	_delaytimems+1, 0
$0090	$00C8			MOVWF	FARG_DelayMS+1
$0091	$23B4			CALL	_delayms
;I2C.ppas,259 :: 		end;
$0092	$297D			GOTO	I2C_L_92
$0093	$	I2C_L_122:
;I2C.ppas,261 :: 		$02:
$0093	$	I2C_L_124:
$0093	$0831			MOVF	_mode, 0
$0094	$3A02			XORLW	2
$0095	$1D03			BTFSS	STATUS, Z
$0096	$28AD			GOTO	I2C_L_125
$0097	$	I2C_L_123:
;I2C.ppas,263 :: 		PORTC:=%10000100;
$0097	$3084			MOVLW	132
$0098	$0087			MOVWF	PORTC
;I2C.ppas,264 :: 		DelayMS(DelayTimeMS);
$0099	$0821			MOVF	_delaytimems, 0
$009A	$00C7			MOVWF	FARG_DelayMS
$009B	$0822			MOVF	_delaytimems+1, 0
$009C	$00C8			MOVWF	FARG_DelayMS+1
$009D	$23B4			CALL	_delayms
;I2C.ppas,265 :: 		PORTC:=%01000010;
$009E	$3042			MOVLW	66
$009F	$0087			MOVWF	PORTC
;I2C.ppas,266 :: 		DelayMS(DelayTimeMS);
$00A0	$0821			MOVF	_delaytimems, 0
$00A1	$00C7			MOVWF	FARG_DelayMS
$00A2	$0822			MOVF	_delaytimems+1, 0
$00A3	$00C8			MOVWF	FARG_DelayMS+1
$00A4	$23B4			CALL	_delayms
;I2C.ppas,267 :: 		PORTC:=%00100001;
$00A5	$3021			MOVLW	33
$00A6	$0087			MOVWF	PORTC
;I2C.ppas,268 :: 		DelayMS(DelayTimeMS);
$00A7	$0821			MOVF	_delaytimems, 0
$00A8	$00C7			MOVWF	FARG_DelayMS
$00A9	$0822			MOVF	_delaytimems+1, 0
$00AA	$00C8			MOVWF	FARG_DelayMS+1
$00AB	$23B4			CALL	_delayms
;I2C.ppas,269 :: 		end;
$00AC	$297D			GOTO	I2C_L_92
$00AD	$	I2C_L_125:
;I2C.ppas,271 :: 		$03:
$00AD	$	I2C_L_127:
$00AD	$0831			MOVF	_mode, 0
$00AE	$3A03			XORLW	3
$00AF	$1D03			BTFSS	STATUS, Z
$00B0	$28DC			GOTO	I2C_L_128
$00B1	$	I2C_L_126:
;I2C.ppas,273 :: 		PORTC:=%00000001;
$00B1	$3001			MOVLW	1
$00B2	$0087			MOVWF	PORTC
;I2C.ppas,274 :: 		DelayMS(DelayTimeMS);
$00B3	$0821			MOVF	_delaytimems, 0
$00B4	$00C7			MOVWF	FARG_DelayMS
$00B5	$0822			MOVF	_delaytimems+1, 0
$00B6	$00C8			MOVWF	FARG_DelayMS+1
$00B7	$23B4			CALL	_delayms
;I2C.ppas,275 :: 		PORTC:=%00000010;
$00B8	$3002			MOVLW	2
$00B9	$0087			MOVWF	PORTC
;I2C.ppas,276 :: 		DelayMS(DelayTimeMS);
$00BA	$0821			MOVF	_delaytimems, 0
$00BB	$00C7			MOVWF	FARG_DelayMS
$00BC	$0822			MOVF	_delaytimems+1, 0
$00BD	$00C8			MOVWF	FARG_DelayMS+1
$00BE	$23B4			CALL	_delayms
;I2C.ppas,277 :: 		PORTC:=%00000100;
$00BF	$3004			MOVLW	4
$00C0	$0087			MOVWF	PORTC
;I2C.ppas,278 :: 		DelayMS(DelayTimeMS);
$00C1	$0821			MOVF	_delaytimems, 0
$00C2	$00C7			MOVWF	FARG_DelayMS
$00C3	$0822			MOVF	_delaytimems+1, 0
$00C4	$00C8			MOVWF	FARG_DelayMS+1
$00C5	$23B4			CALL	_delayms
;I2C.ppas,279 :: 		PORTC:=%00100000;
$00C6	$3020			MOVLW	32
$00C7	$0087			MOVWF	PORTC
;I2C.ppas,280 :: 		DelayMS(DelayTimeMS);
$00C8	$0821			MOVF	_delaytimems, 0
$00C9	$00C7			MOVWF	FARG_DelayMS
$00CA	$0822			MOVF	_delaytimems+1, 0
$00CB	$00C8			MOVWF	FARG_DelayMS+1
$00CC	$23B4			CALL	_delayms
;I2C.ppas,281 :: 		PORTC:=%01000000;
$00CD	$3040			MOVLW	64
$00CE	$0087			MOVWF	PORTC
;I2C.ppas,282 :: 		DelayMS(DelayTimeMS);
$00CF	$0821			MOVF	_delaytimems, 0
$00D0	$00C7			MOVWF	FARG_DelayMS
$00D1	$0822			MOVF	_delaytimems+1, 0
$00D2	$00C8			MOVWF	FARG_DelayMS+1
$00D3	$23B4			CALL	_delayms
;I2C.ppas,283 :: 		PORTC:=%10000000;
$00D4	$3080			MOVLW	128
$00D5	$0087			MOVWF	PORTC
;I2C.ppas,284 :: 		DelayMS(DelayTimeMS);
$00D6	$0821			MOVF	_delaytimems, 0
$00D7	$00C7			MOVWF	FARG_DelayMS
$00D8	$0822			MOVF	_delaytimems+1, 0
$00D9	$00C8			MOVWF	FARG_DelayMS+1
$00DA	$23B4			CALL	_delayms
;I2C.ppas,285 :: 		end;
$00DB	$297D			GOTO	I2C_L_92
$00DC	$	I2C_L_128:
;I2C.ppas,287 :: 		$04:
$00DC	$	I2C_L_130:
$00DC	$0831			MOVF	_mode, 0
$00DD	$3A04			XORLW	4
$00DE	$1D03			BTFSS	STATUS, Z
$00DF	$290B			GOTO	I2C_L_131
$00E0	$	I2C_L_129:
;I2C.ppas,289 :: 		PORTC:=%10000000;
$00E0	$3080			MOVLW	128
$00E1	$0087			MOVWF	PORTC
;I2C.ppas,290 :: 		DelayMS(DelayTimeMS);
$00E2	$0821			MOVF	_delaytimems, 0
$00E3	$00C7			MOVWF	FARG_DelayMS
$00E4	$0822			MOVF	_delaytimems+1, 0
$00E5	$00C8			MOVWF	FARG_DelayMS+1
$00E6	$23B4			CALL	_delayms
;I2C.ppas,291 :: 		PORTC:=%01000000;
$00E7	$3040			MOVLW	64
$00E8	$0087			MOVWF	PORTC
;I2C.ppas,292 :: 		DelayMS(DelayTimeMS);
$00E9	$0821			MOVF	_delaytimems, 0
$00EA	$00C7			MOVWF	FARG_DelayMS
$00EB	$0822			MOVF	_delaytimems+1, 0
$00EC	$00C8			MOVWF	FARG_DelayMS+1
$00ED	$23B4			CALL	_delayms
;I2C.ppas,293 :: 		PORTC:=%00100000;
$00EE	$3020			MOVLW	32
$00EF	$0087			MOVWF	PORTC
;I2C.ppas,294 :: 		DelayMS(DelayTimeMS);
$00F0	$0821			MOVF	_delaytimems, 0
$00F1	$00C7			MOVWF	FARG_DelayMS
$00F2	$0822			MOVF	_delaytimems+1, 0
$00F3	$00C8			MOVWF	FARG_DelayMS+1
$00F4	$23B4			CALL	_delayms
;I2C.ppas,295 :: 		PORTC:=%00000100;
$00F5	$3004			MOVLW	4
$00F6	$0087			MOVWF	PORTC
;I2C.ppas,296 :: 		DelayMS(DelayTimeMS);
$00F7	$0821			MOVF	_delaytimems, 0
$00F8	$00C7			MOVWF	FARG_DelayMS
$00F9	$0822			MOVF	_delaytimems+1, 0
$00FA	$00C8			MOVWF	FARG_DelayMS+1
$00FB	$23B4			CALL	_delayms
;I2C.ppas,297 :: 		PORTC:=%00000010;
$00FC	$3002			MOVLW	2
$00FD	$0087			MOVWF	PORTC
;I2C.ppas,298 :: 		DelayMS(DelayTimeMS);
$00FE	$0821			MOVF	_delaytimems, 0
$00FF	$00C7			MOVWF	FARG_DelayMS
$0100	$0822			MOVF	_delaytimems+1, 0
$0101	$00C8			MOVWF	FARG_DelayMS+1
$0102	$23B4			CALL	_delayms
;I2C.ppas,299 :: 		PORTC:=%00000001;
$0103	$3001			MOVLW	1
$0104	$0087			MOVWF	PORTC
;I2C.ppas,300 :: 		DelayMS(DelayTimeMS);
$0105	$0821			MOVF	_delaytimems, 0
$0106	$00C7			MOVWF	FARG_DelayMS
$0107	$0822			MOVF	_delaytimems+1, 0
$0108	$00C8			MOVWF	FARG_DelayMS+1
$0109	$23B4			CALL	_delayms
;I2C.ppas,301 :: 		end;
$010A	$297D			GOTO	I2C_L_92
$010B	$	I2C_L_131:
;I2C.ppas,303 :: 		$05:
$010B	$	I2C_L_133:
$010B	$0831			MOVF	_mode, 0
$010C	$3A05			XORLW	5
$010D	$1D03			BTFSS	STATUS, Z
$010E	$292C			GOTO	I2C_L_134
$010F	$	I2C_L_132:
;I2C.ppas,305 :: 		PORTC:=%00100001;
$010F	$3021			MOVLW	33
$0110	$0087			MOVWF	PORTC
;I2C.ppas,306 :: 		DelayMS(DelayTimeMS);
$0111	$0821			MOVF	_delaytimems, 0
$0112	$00C7			MOVWF	FARG_DelayMS
$0113	$0822			MOVF	_delaytimems+1, 0
$0114	$00C8			MOVWF	FARG_DelayMS+1
$0115	$23B4			CALL	_delayms
;I2C.ppas,307 :: 		PORTC:=%01000010;
$0116	$3042			MOVLW	66
$0117	$0087			MOVWF	PORTC
;I2C.ppas,308 :: 		DelayMS(DelayTimeMS);
$0118	$0821			MOVF	_delaytimems, 0
$0119	$00C7			MOVWF	FARG_DelayMS
$011A	$0822			MOVF	_delaytimems+1, 0
$011B	$00C8			MOVWF	FARG_DelayMS+1
$011C	$23B4			CALL	_delayms
;I2C.ppas,309 :: 		PORTC:=%10000100;
$011D	$3084			MOVLW	132
$011E	$0087			MOVWF	PORTC
;I2C.ppas,310 :: 		DelayMS(DelayTimeMS);
$011F	$0821			MOVF	_delaytimems, 0
$0120	$00C7			MOVWF	FARG_DelayMS
$0121	$0822			MOVF	_delaytimems+1, 0
$0122	$00C8			MOVWF	FARG_DelayMS+1
$0123	$23B4			CALL	_delayms
;I2C.ppas,311 :: 		PORTC:=%01000010;
$0124	$3042			MOVLW	66
$0125	$0087			MOVWF	PORTC
;I2C.ppas,312 :: 		DelayMS(DelayTimeMS);
$0126	$0821			MOVF	_delaytimems, 0
$0127	$00C7			MOVWF	FARG_DelayMS
$0128	$0822			MOVF	_delaytimems+1, 0
$0129	$00C8			MOVWF	FARG_DelayMS+1
$012A	$23B4			CALL	_delayms
;I2C.ppas,313 :: 		end;
$012B	$297D			GOTO	I2C_L_92
$012C	$	I2C_L_134:
;I2C.ppas,315 :: 		$06:
$012C	$	I2C_L_136:
$012C	$0831			MOVF	_mode, 0
$012D	$3A06			XORLW	6
$012E	$1D03			BTFSS	STATUS, Z
$012F	$2977			GOTO	I2C_L_137
$0130	$	I2C_L_135:
;I2C.ppas,317 :: 		PORTC:=%10000000;
$0130	$3080			MOVLW	128
$0131	$0087			MOVWF	PORTC
;I2C.ppas,318 :: 		DelayMS(DelayTimeMS);
$0132	$0821			MOVF	_delaytimems, 0
$0133	$00C7			MOVWF	FARG_DelayMS
$0134	$0822			MOVF	_delaytimems+1, 0
$0135	$00C8			MOVWF	FARG_DelayMS+1
$0136	$23B4			CALL	_delayms
;I2C.ppas,319 :: 		PORTC:=%01000000;
$0137	$3040			MOVLW	64
$0138	$0087			MOVWF	PORTC
;I2C.ppas,320 :: 		DelayMS(DelayTimeMS);
$0139	$0821			MOVF	_delaytimems, 0
$013A	$00C7			MOVWF	FARG_DelayMS
$013B	$0822			MOVF	_delaytimems+1, 0
$013C	$00C8			MOVWF	FARG_DelayMS+1
$013D	$23B4			CALL	_delayms
;I2C.ppas,321 :: 		PORTC:=%00100000;
$013E	$3020			MOVLW	32
$013F	$0087			MOVWF	PORTC
;I2C.ppas,322 :: 		DelayMS(DelayTimeMS);
$0140	$0821			MOVF	_delaytimems, 0
$0141	$00C7			MOVWF	FARG_DelayMS
$0142	$0822			MOVF	_delaytimems+1, 0
$0143	$00C8			MOVWF	FARG_DelayMS+1
$0144	$23B4			CALL	_delayms
;I2C.ppas,323 :: 		PORTC:=%00000100;
$0145	$3004			MOVLW	4
$0146	$0087			MOVWF	PORTC
;I2C.ppas,324 :: 		DelayMS(DelayTimeMS);
$0147	$0821			MOVF	_delaytimems, 0
$0148	$00C7			MOVWF	FARG_DelayMS
$0149	$0822			MOVF	_delaytimems+1, 0
$014A	$00C8			MOVWF	FARG_DelayMS+1
$014B	$23B4			CALL	_delayms
;I2C.ppas,325 :: 		PORTC:=%00000010;
$014C	$3002			MOVLW	2
$014D	$0087			MOVWF	PORTC
;I2C.ppas,326 :: 		DelayMS(DelayTimeMS);
$014E	$0821			MOVF	_delaytimems, 0
$014F	$00C7			MOVWF	FARG_DelayMS
$0150	$0822			MOVF	_delaytimems+1, 0
$0151	$00C8			MOVWF	FARG_DelayMS+1
$0152	$23B4			CALL	_delayms
;I2C.ppas,327 :: 		PORTC:=%00000001;
$0153	$3001			MOVLW	1
$0154	$0087			MOVWF	PORTC
;I2C.ppas,328 :: 		DelayMS(DelayTimeMS);
$0155	$0821			MOVF	_delaytimems, 0
$0156	$00C7			MOVWF	FARG_DelayMS
$0157	$0822			MOVF	_delaytimems+1, 0
$0158	$00C8			MOVWF	FARG_DelayMS+1
$0159	$23B4			CALL	_delayms
;I2C.ppas,329 :: 		PORTC:=%00000010;
$015A	$3002			MOVLW	2
$015B	$0087			MOVWF	PORTC
;I2C.ppas,330 :: 		DelayMS(DelayTimeMS);
$015C	$0821			MOVF	_delaytimems, 0
$015D	$00C7			MOVWF	FARG_DelayMS
$015E	$0822			MOVF	_delaytimems+1, 0
$015F	$00C8			MOVWF	FARG_DelayMS+1
$0160	$23B4			CALL	_delayms
;I2C.ppas,331 :: 		PORTC:=%00000100;
$0161	$3004			MOVLW	4
$0162	$0087			MOVWF	PORTC
;I2C.ppas,332 :: 		DelayMS(DelayTimeMS);
$0163	$0821			MOVF	_delaytimems, 0
$0164	$00C7			MOVWF	FARG_DelayMS
$0165	$0822			MOVF	_delaytimems+1, 0
$0166	$00C8			MOVWF	FARG_DelayMS+1
$0167	$23B4			CALL	_delayms
;I2C.ppas,333 :: 		PORTC:=%00100000;
$0168	$3020			MOVLW	32
$0169	$0087			MOVWF	PORTC
;I2C.ppas,334 :: 		DelayMS(DelayTimeMS);
$016A	$0821			MOVF	_delaytimems, 0
$016B	$00C7			MOVWF	FARG_DelayMS
$016C	$0822			MOVF	_delaytimems+1, 0
$016D	$00C8			MOVWF	FARG_DelayMS+1
$016E	$23B4			CALL	_delayms
;I2C.ppas,335 :: 		PORTC:=%01000000;
$016F	$3040			MOVLW	64
$0170	$0087			MOVWF	PORTC
;I2C.ppas,336 :: 		DelayMS(DelayTimeMS);
$0171	$0821			MOVF	_delaytimems, 0
$0172	$00C7			MOVWF	FARG_DelayMS
$0173	$0822			MOVF	_delaytimems+1, 0
$0174	$00C8			MOVWF	FARG_DelayMS+1
$0175	$23B4			CALL	_delayms
;I2C.ppas,337 :: 		end;
$0176	$297D			GOTO	I2C_L_92
$0177	$	I2C_L_137:
;I2C.ppas,339 :: 		32: SendPortAToDisplay;
$0177	$	I2C_L_139:
$0177	$0831			MOVF	_mode, 0
$0178	$3A20			XORLW	32
$0179	$1D03			BTFSS	STATUS, Z
$017A	$297D			GOTO	I2C_L_140
$017B	$	I2C_L_138:
$017B	$2458			CALL	_sendportatodisplay
$017C	$297D			GOTO	I2C_L_92
$017D	$	I2C_L_140:
$017D	$	I2C_L_92:
;I2C.ppas,341 :: 		until False;
$017D	$	I2C_L_80:
$017D	$	I2C_L_82:
$017D	$284C			GOTO	I2C_L_79
;I2C.ppas,342 :: 		end.
$017E	$297E			GOTO	$
