;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 01/01/2009 11:29:19
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2AA6			GOTO	_main
$04D3	$	_i2c_slave_receivebyte:
;UI2C.ppas,225 :: 		begin
;UI2C.ppas,226 :: 		PIR1.SSPIF:=False;
$04D3	$1303			BCF	STATUS, RP1
$04D4	$1283			BCF	STATUS, RP0
$04D5	$118C			BCF	PIR1, 3
$04D6	$	UI2C_L_140:
;UI2C.ppas,227 :: 		while (PIR1.SSPIF=0) or (SSPSTAT.BF=0) do begin end;
$04D6	$	UI2C_L_142:
$04D6	$080C			MOVF	PIR1, 0
$04D7	$00F1			MOVWF	STACK_1
$04D8	$3000			MOVLW	0
$04D9	$19F1			BTFSC	STACK_1, 3
$04DA	$3001			MOVLW	1
$04DB	$00F1			MOVWF	STACK_1
$04DC	$0871			MOVF	STACK_1, 0
$04DD	$3A00			XORLW	0
$04DE	$30FF			MOVLW	255
$04DF	$1D03			BTFSS	STATUS, Z
$04E0	$3000			MOVLW	0
$04E1	$00F2			MOVWF	STACK_2
$04E2	$1683			BSF	STATUS, RP0
$04E3	$0814			MOVF	SSPSTAT, 0
$04E4	$1283			BCF	STATUS, RP0
$04E5	$00F1			MOVWF	STACK_1
$04E6	$3001			MOVLW	1
$04E7	$05F1			ANDWF	STACK_1, 1
$04E8	$0871			MOVF	STACK_1, 0
$04E9	$3A00			XORLW	0
$04EA	$30FF			MOVLW	255
$04EB	$1D03			BTFSS	STATUS, Z
$04EC	$3000			MOVLW	0
$04ED	$00F0			MOVWF	STACK_0
$04EE	$0872			MOVF	STACK_2, 0
$04EF	$04F0			IORWF	STACK_0, 1
$04F0	$1D03			BTFSS	STATUS, Z
$04F1	$2CD6			GOTO	UI2C_L_142
$04F2	$	UI2C_L_143:
;UI2C.ppas,228 :: 		Result:=SSPBUF;
$04F2	$0813			MOVF	SSPBUF, 0
$04F3	$00C7			MOVWF	_i2c_slave_receivebyte_local_result
;UI2C.ppas,229 :: 		SSPSTAT.SSPOV:=False;
$04F4	$1683			BSF	STATUS, RP0
$04F5	$1314			BCF	SSPSTAT, 6
$04F6	$	UI2C_L_147:
;UI2C.ppas,230 :: 		PIR1.SSPIF:=False;
$04F6	$1283			BCF	STATUS, RP0
$04F7	$118C			BCF	PIR1, 3
$04F8	$	UI2C_L_149:
$04F8	$	UI2C_L_138:
;UI2C.ppas,231 :: 		end;
$04F8	$0847			MOVF	_i2c_slave_receivebyte_local_result, 0
$04F9	$00F0			MOVWF	STACK_0
$04FA	$0008			RETURN
$0582	$	_i2c_slave_receiveword:
;UI2C.ppas,236 :: 		begin
;UI2C.ppas,237 :: 		LowByte:=I2C_Slave_ReceiveByte;
$0582	$24D3			CALL	_i2c_slave_receivebyte
$0583	$0870			MOVF	STACK_0, 0
$0584	$00C6			MOVWF	_i2c_slave_receiveword_local_lowbyte
;UI2C.ppas,238 :: 		HighByte:=I2C_Slave_ReceiveByte;
$0585	$24D3			CALL	_i2c_slave_receivebyte
;UI2C.ppas,239 :: 		Result:=LowByte+(HighByte shl 8);
$0586	$0870			MOVF	STACK_0, 0
$0587	$00F2			MOVWF	STACK_2
$0588	$01F3			CLRF	STACK_2+1
$0589	$0872			MOVF	STACK_2, 0
$058A	$00F3			MOVWF	STACK_2+1
$058B	$01F2			CLRF	STACK_2
$058C	$0846			MOVF	_i2c_slave_receiveword_local_lowbyte, 0
$058D	$00C4			MOVWF	_i2c_slave_receiveword_local_result
$058E	$01C5			CLRF	_i2c_slave_receiveword_local_result+1
$058F	$0872			MOVF	STACK_2, 0
$0590	$07C4			ADDWF	_i2c_slave_receiveword_local_result, 1
$0591	$0873			MOVF	STACK_2+1, 0
$0592	$1803			BTFSC	STATUS, C
$0593	$3F01			ADDLW	1
$0594	$07C5			ADDWF	_i2c_slave_receiveword_local_result+1, 1
$0595	$	UI2C_L_150:
;UI2C.ppas,240 :: 		end;
$0595	$0844			MOVF	_i2c_slave_receiveword_local_result, 0
$0596	$00F0			MOVWF	STACK_0
$0597	$0845			MOVF	_i2c_slave_receiveword_local_result+1, 0
$0598	$00F1			MOVWF	STACK_0+1
$0599	$0008			RETURN
$0316	$	_i2cinterrupt:
;SevenSegmentDisplays.ppas,25 :: 		begin
;SevenSegmentDisplays.ppas,28 :: 		if PIE1.SSPIE=False then Exit;
$0316	$1303			BCF	STATUS, RP1
$0317	$1683			BSF	STATUS, RP0
$0318	$080C			MOVF	PIE1, 0
$0319	$1283			BCF	STATUS, RP0
$031A	$00F2			MOVWF	STACK_2
$031B	$3000			MOVLW	0
$031C	$19F2			BTFSC	STACK_2, 3
$031D	$3001			MOVLW	1
$031E	$00F2			MOVWF	STACK_2
$031F	$0872			MOVF	STACK_2, 0
$0320	$3A00			XORLW	0
$0321	$1D03			BTFSS	STATUS, Z
$0322	$2B24			GOTO	SevenSegmentDisplays_L_2
$0323	$	SevenSegmentDisplays_L_1:
$0323	$2B82			GOTO	SevenSegmentDisplays_L_0
$0324	$	SevenSegmentDisplays_L_2:
$0324	$	SevenSegmentDisplays_L_3:
;SevenSegmentDisplays.ppas,30 :: 		if PIR1.SSPIF then
$0324	$080C			MOVF	PIR1, 0
$0325	$00F2			MOVWF	STACK_2
$0326	$3000			MOVLW	0
$0327	$19F2			BTFSC	STACK_2, 3
$0328	$3001			MOVLW	1
$0329	$00F2			MOVWF	STACK_2
$032A	$0872			MOVF	STACK_2, 0
$032B	$1903			BTFSC	STATUS, Z
$032C	$2B82			GOTO	SevenSegmentDisplays_L_5
$032D	$	SevenSegmentDisplays_L_4:
;SevenSegmentDisplays.ppas,32 :: 		if (SSPSTAT.D_A=0) then // Command.
$032D	$1683			BSF	STATUS, RP0
$032E	$0814			MOVF	SSPSTAT, 0
$032F	$1283			BCF	STATUS, RP0
$0330	$00F2			MOVWF	STACK_2
$0331	$3000			MOVLW	0
$0332	$1AF2			BTFSC	STACK_2, 5
$0333	$3001			MOVLW	1
$0334	$00F2			MOVWF	STACK_2
$0335	$0872			MOVF	STACK_2, 0
$0336	$3A00			XORLW	0
$0337	$1D03			BTFSS	STATUS, Z
$0338	$2B81			GOTO	SevenSegmentDisplays_L_8
$0339	$	SevenSegmentDisplays_L_7:
;SevenSegmentDisplays.ppas,34 :: 		if SSPSTAT.R_W then
$0339	$1683			BSF	STATUS, RP0
$033A	$0814			MOVF	SSPSTAT, 0
$033B	$1283			BCF	STATUS, RP0
$033C	$00F2			MOVWF	STACK_2
$033D	$3000			MOVLW	0
$033E	$1972			BTFSC	STACK_2, 2
$033F	$3001			MOVLW	1
$0340	$00F2			MOVWF	STACK_2
$0341	$0872			MOVF	STACK_2, 0
$0342	$1903			BTFSC	STATUS, Z
$0343	$2B45			GOTO	SevenSegmentDisplays_L_11
$0344	$	SevenSegmentDisplays_L_10:
;SevenSegmentDisplays.ppas,37 :: 		end
$0344	$2B81			GOTO	SevenSegmentDisplays_L_12
;SevenSegmentDisplays.ppas,38 :: 		else
$0345	$	SevenSegmentDisplays_L_11:
;SevenSegmentDisplays.ppas,40 :: 		MandatoryByte:=SSPBUF; // Make sure this is not optimized out!
$0345	$0813			MOVF	SSPBUF, 0
$0346	$00A0			MOVWF	_mandatorybyte
;SevenSegmentDisplays.ppas,41 :: 		SSPSTAT.SSPOV:=False;
$0347	$1683			BSF	STATUS, RP0
$0348	$1314			BCF	SSPSTAT, 6
$0349	$	SevenSegmentDisplays_L_14:
;SevenSegmentDisplays.ppas,43 :: 		Command:=I2C_Slave_ReceiveByte;
$0349	$24D3			CALL	_i2c_slave_receivebyte
$034A	$0870			MOVF	STACK_0, 0
$034B	$00C2			MOVWF	_i2cinterrupt_local_command
;SevenSegmentDisplays.ppas,46 :: 		$00: Interrupt_Mode:=-1;
$034C	$	SevenSegmentDisplays_L_17:
$034C	$0842			MOVF	_i2cinterrupt_local_command, 0
$034D	$3A00			XORLW	0
$034E	$1D03			BTFSS	STATUS, Z
$034F	$2B53			GOTO	SevenSegmentDisplays_L_18
$0350	$	SevenSegmentDisplays_L_16:
$0350	$30FF			MOVLW	255
$0351	$00A1			MOVWF	_interrupt_mode
$0352	$2B81			GOTO	SevenSegmentDisplays_L_15
$0353	$	SevenSegmentDisplays_L_18:
;SevenSegmentDisplays.ppas,48 :: 		$01:
$0353	$	SevenSegmentDisplays_L_20:
$0353	$0842			MOVF	_i2cinterrupt_local_command, 0
$0354	$3A01			XORLW	1
$0355	$1D03			BTFSS	STATUS, Z
$0356	$2B61			GOTO	SevenSegmentDisplays_L_21
$0357	$	SevenSegmentDisplays_L_19:
;SevenSegmentDisplays.ppas,50 :: 		ByteParameter:=I2C_Slave_ReceiveByte;
$0357	$24D3			CALL	_i2c_slave_receivebyte
$0358	$0870			MOVF	STACK_0, 0
$0359	$00C3			MOVWF	_i2cinterrupt_local_byteparameter
;SevenSegmentDisplays.ppas,51 :: 		if ByteParameter<=7 then
$035A	$0870			MOVF	STACK_0, 0
$035B	$3C07			SUBLW	7
$035C	$1C03			BTFSS	STATUS, C
$035D	$2B60			GOTO	SevenSegmentDisplays_L_23
$035E	$	SevenSegmentDisplays_L_22:
;SevenSegmentDisplays.ppas,52 :: 		Interrupt_Mode:=ByteParameter;
$035E	$0843			MOVF	_i2cinterrupt_local_byteparameter, 0
$035F	$00A1			MOVWF	_interrupt_mode
$0360	$	SevenSegmentDisplays_L_23:
$0360	$	SevenSegmentDisplays_L_24:
;SevenSegmentDisplays.ppas,53 :: 		end;
$0360	$2B81			GOTO	SevenSegmentDisplays_L_15
$0361	$	SevenSegmentDisplays_L_21:
;SevenSegmentDisplays.ppas,55 :: 		$02: // Display decimal word.
$0361	$	SevenSegmentDisplays_L_26:
$0361	$0842			MOVF	_i2cinterrupt_local_command, 0
$0362	$3A02			XORLW	2
$0363	$1D03			BTFSS	STATUS, Z
$0364	$2B6D			GOTO	SevenSegmentDisplays_L_27
$0365	$	SevenSegmentDisplays_L_25:
;SevenSegmentDisplays.ppas,57 :: 		CommandValue:=I2C_Slave_ReceiveWord;
$0365	$2582			CALL	_i2c_slave_receiveword
$0366	$0870			MOVF	STACK_0, 0
$0367	$00A2			MOVWF	_commandvalue
$0368	$0871			MOVF	STACK_0+1, 0
$0369	$00A3			MOVWF	_commandvalue+1
;SevenSegmentDisplays.ppas,58 :: 		Interrupt_Mode:=8;
$036A	$3008			MOVLW	8
$036B	$00A1			MOVWF	_interrupt_mode
;SevenSegmentDisplays.ppas,59 :: 		end;
$036C	$2B81			GOTO	SevenSegmentDisplays_L_15
$036D	$	SevenSegmentDisplays_L_27:
;SevenSegmentDisplays.ppas,61 :: 		$03:
$036D	$	SevenSegmentDisplays_L_29:
$036D	$0842			MOVF	_i2cinterrupt_local_command, 0
$036E	$3A03			XORLW	3
$036F	$1D03			BTFSS	STATUS, Z
$0370	$2B75			GOTO	SevenSegmentDisplays_L_30
$0371	$	SevenSegmentDisplays_L_28:
;SevenSegmentDisplays.ppas,63 :: 		DimDisplay:=I2C_Slave_ReceiveByte;
$0371	$24D3			CALL	_i2c_slave_receivebyte
$0372	$0870			MOVF	STACK_0, 0
$0373	$00A4			MOVWF	_dimdisplay
;SevenSegmentDisplays.ppas,64 :: 		end;
$0374	$2B81			GOTO	SevenSegmentDisplays_L_15
$0375	$	SevenSegmentDisplays_L_30:
;SevenSegmentDisplays.ppas,66 :: 		$04: // Display hexadecimal word.
$0375	$	SevenSegmentDisplays_L_32:
$0375	$0842			MOVF	_i2cinterrupt_local_command, 0
$0376	$3A04			XORLW	4
$0377	$1D03			BTFSS	STATUS, Z
$0378	$2B81			GOTO	SevenSegmentDisplays_L_33
$0379	$	SevenSegmentDisplays_L_31:
;SevenSegmentDisplays.ppas,68 :: 		CommandValue:=I2C_Slave_ReceiveWord;
$0379	$2582			CALL	_i2c_slave_receiveword
$037A	$0870			MOVF	STACK_0, 0
$037B	$00A2			MOVWF	_commandvalue
$037C	$0871			MOVF	STACK_0+1, 0
$037D	$00A3			MOVWF	_commandvalue+1
;SevenSegmentDisplays.ppas,69 :: 		Interrupt_Mode:=9;
$037E	$3009			MOVLW	9
$037F	$00A1			MOVWF	_interrupt_mode
;SevenSegmentDisplays.ppas,70 :: 		end;
$0380	$2B81			GOTO	SevenSegmentDisplays_L_15
$0381	$	SevenSegmentDisplays_L_33:
$0381	$	SevenSegmentDisplays_L_15:
;SevenSegmentDisplays.ppas,72 :: 		end;
$0381	$	SevenSegmentDisplays_L_12:
;SevenSegmentDisplays.ppas,73 :: 		end;
$0381	$	SevenSegmentDisplays_L_8:
$0381	$	SevenSegmentDisplays_L_9:
;SevenSegmentDisplays.ppas,75 :: 		PIR1.SSPIF:=False;
$0381	$118C			BCF	PIR1, 3
$0382	$	SevenSegmentDisplays_L_35:
;SevenSegmentDisplays.ppas,76 :: 		end;
$0382	$	SevenSegmentDisplays_L_5:
$0382	$	SevenSegmentDisplays_L_6:
$0382	$	SevenSegmentDisplays_L_0:
;SevenSegmentDisplays.ppas,77 :: 		end;
$0382	$0008			RETURN
$0028	$	_sevensegmentinterrupt:
;SevenSegmentDisplays.ppas,80 :: 		begin
;SevenSegmentDisplays.ppas,81 :: 		if INTCON.T0IE=False then Exit;
$0028	$080B			MOVF	INTCON, 0
$0029	$1303			BCF	STATUS, RP1
$002A	$1283			BCF	STATUS, RP0
$002B	$00F1			MOVWF	STACK_1
$002C	$3000			MOVLW	0
$002D	$1AF1			BTFSC	STACK_1, 5
$002E	$3001			MOVLW	1
$002F	$00F1			MOVWF	STACK_1
$0030	$0871			MOVF	STACK_1, 0
$0031	$3A00			XORLW	0
$0032	$1D03			BTFSS	STATUS, Z
$0033	$2835			GOTO	SevenSegmentDisplays_L_38
$0034	$	SevenSegmentDisplays_L_37:
$0034	$28D1			GOTO	SevenSegmentDisplays_L_36
$0035	$	SevenSegmentDisplays_L_38:
$0035	$	SevenSegmentDisplays_L_39:
;SevenSegmentDisplays.ppas,83 :: 		if INTCON.T0IF then
$0035	$080B			MOVF	INTCON, 0
$0036	$00F1			MOVWF	STACK_1
$0037	$3000			MOVLW	0
$0038	$1971			BTFSC	STACK_1, 2
$0039	$3001			MOVLW	1
$003A	$00F1			MOVWF	STACK_1
$003B	$0871			MOVF	STACK_1, 0
$003C	$1903			BTFSC	STATUS, Z
$003D	$28D1			GOTO	SevenSegmentDisplays_L_41
$003E	$	SevenSegmentDisplays_L_40:
;SevenSegmentDisplays.ppas,87 :: 		if SevenSegmentDisplayCount=0 then // Don't run seven segments too fast or adjacent segments light up.
$003E	$0825			MOVF	_sevensegmentdisplaycount, 0
$003F	$3A00			XORLW	0
$0040	$1D03			BTFSS	STATUS, Z
$0041	$2890			GOTO	SevenSegmentDisplays_L_44
$0042	$	SevenSegmentDisplays_L_43:
;SevenSegmentDisplays.ppas,89 :: 		PORTB:=not DisplayMask;
$0042	$0926			COMF	_displaymask, W
$0043	$0086			MOVWF	PORTB
;SevenSegmentDisplays.ppas,91 :: 		PORTC.0:=(DigitMasks[0] and DisplayMask)<>0;
$0044	$0826			MOVF	_displaymask, 0
$0045	$0527			ANDWF	_digitmasks+0, 0
$0046	$00F0			MOVWF	STACK_0
$0047	$0870			MOVF	STACK_0, 0
$0048	$3A00			XORLW	0
$0049	$30FF			MOVLW	255
$004A	$1903			BTFSC	STATUS, Z
$004B	$3000			MOVLW	0
$004C	$00F1			MOVWF	STACK_1
$004D	$0871			MOVF	STACK_1, 0
$004E	$3A00			XORLW	0
$004F	$1D03			BTFSS	STATUS, Z
$0050	$2853			GOTO	SevenSegmentDisplays_L_46
$0051	$1007			BCF	PORTC, 0
$0052	$2854			GOTO	SevenSegmentDisplays_L_47
$0053	$	SevenSegmentDisplays_L_46:
$0053	$1407			BSF	PORTC, 0
$0054	$	SevenSegmentDisplays_L_47:
;SevenSegmentDisplays.ppas,92 :: 		PORTC.1:=(DigitMasks[1] and DisplayMask)<>0;
$0054	$0826			MOVF	_displaymask, 0
$0055	$0528			ANDWF	_digitmasks+1, 0
$0056	$00F0			MOVWF	STACK_0
$0057	$0870			MOVF	STACK_0, 0
$0058	$3A00			XORLW	0
$0059	$30FF			MOVLW	255
$005A	$1903			BTFSC	STATUS, Z
$005B	$3000			MOVLW	0
$005C	$00F1			MOVWF	STACK_1
$005D	$0871			MOVF	STACK_1, 0
$005E	$3A00			XORLW	0
$005F	$1D03			BTFSS	STATUS, Z
$0060	$2863			GOTO	SevenSegmentDisplays_L_48
$0061	$1087			BCF	PORTC, 1
$0062	$2864			GOTO	SevenSegmentDisplays_L_49
$0063	$	SevenSegmentDisplays_L_48:
$0063	$1487			BSF	PORTC, 1
$0064	$	SevenSegmentDisplays_L_49:
;SevenSegmentDisplays.ppas,93 :: 		PORTC.2:=(DigitMasks[2] and DisplayMask)<>0;
$0064	$0826			MOVF	_displaymask, 0
$0065	$0529			ANDWF	_digitmasks+2, 0
$0066	$00F0			MOVWF	STACK_0
$0067	$0870			MOVF	STACK_0, 0
$0068	$3A00			XORLW	0
$0069	$30FF			MOVLW	255
$006A	$1903			BTFSC	STATUS, Z
$006B	$3000			MOVLW	0
$006C	$00F1			MOVWF	STACK_1
$006D	$0871			MOVF	STACK_1, 0
$006E	$3A00			XORLW	0
$006F	$1D03			BTFSS	STATUS, Z
$0070	$2873			GOTO	SevenSegmentDisplays_L_50
$0071	$1107			BCF	PORTC, 2
$0072	$2874			GOTO	SevenSegmentDisplays_L_51
$0073	$	SevenSegmentDisplays_L_50:
$0073	$1507			BSF	PORTC, 2
$0074	$	SevenSegmentDisplays_L_51:
;SevenSegmentDisplays.ppas,94 :: 		PORTA.5:=(DigitMasks[3] and DisplayMask)<>0;
$0074	$0826			MOVF	_displaymask, 0
$0075	$052A			ANDWF	_digitmasks+3, 0
$0076	$00F0			MOVWF	STACK_0
$0077	$0870			MOVF	STACK_0, 0
$0078	$3A00			XORLW	0
$0079	$30FF			MOVLW	255
$007A	$1903			BTFSC	STATUS, Z
$007B	$3000			MOVLW	0
$007C	$00F1			MOVWF	STACK_1
$007D	$0871			MOVF	STACK_1, 0
$007E	$3A00			XORLW	0
$007F	$1D03			BTFSS	STATUS, Z
$0080	$2883			GOTO	SevenSegmentDisplays_L_52
$0081	$1285			BCF	PORTA, 5
$0082	$2884			GOTO	SevenSegmentDisplays_L_53
$0083	$	SevenSegmentDisplays_L_52:
$0083	$1685			BSF	PORTA, 5
$0084	$	SevenSegmentDisplays_L_53:
;SevenSegmentDisplays.ppas,96 :: 		DisplayMask:=DisplayMask shl 1;
$0084	$0826			MOVF	_displaymask, 0
$0085	$00F1			MOVWF	STACK_1
$0086	$0DF1			RLF	STACK_1, 1
$0087	$1071			BCF	STACK_1, 0
$0088	$0871			MOVF	STACK_1, 0
$0089	$00A6			MOVWF	_displaymask
;SevenSegmentDisplays.ppas,97 :: 		if DisplayMask=$00 then
$008A	$0871			MOVF	STACK_1, 0
$008B	$3A00			XORLW	0
$008C	$1D03			BTFSS	STATUS, Z
$008D	$2890			GOTO	SevenSegmentDisplays_L_55
$008E	$	SevenSegmentDisplays_L_54:
;SevenSegmentDisplays.ppas,98 :: 		DisplayMask:=$01;
$008E	$3001			MOVLW	1
$008F	$00A6			MOVWF	_displaymask
$0090	$	SevenSegmentDisplays_L_55:
$0090	$	SevenSegmentDisplays_L_56:
;SevenSegmentDisplays.ppas,99 :: 		end;
$0090	$	SevenSegmentDisplays_L_44:
$0090	$	SevenSegmentDisplays_L_45:
;SevenSegmentDisplays.ppas,101 :: 		if DimDisplay and (SevenSegmentDisplayCount>=2) then
$0090	$3002			MOVLW	2
$0091	$0225			SUBWF	_sevensegmentdisplaycount, 0
$0092	$30FF			MOVLW	255
$0093	$1C03			BTFSS	STATUS, C
$0094	$3000			MOVLW	0
$0095	$00F0			MOVWF	STACK_0
$0096	$0824			MOVF	_dimdisplay, 0
$0097	$05F0			ANDWF	STACK_0, 1
$0098	$1903			BTFSC	STATUS, Z
$0099	$289C			GOTO	SevenSegmentDisplays_L_58
$009A	$	SevenSegmentDisplays_L_57:
;SevenSegmentDisplays.ppas,103 :: 		PORTB:=$FF;
$009A	$30FF			MOVLW	255
$009B	$0086			MOVWF	PORTB
;SevenSegmentDisplays.ppas,104 :: 		end;
$009C	$	SevenSegmentDisplays_L_58:
$009C	$	SevenSegmentDisplays_L_59:
;SevenSegmentDisplays.ppas,110 :: 		PORTC.5:=(FullColourLEDDisplayCount>=RedLEDDrive);
$009C	$082C			MOVF	_redleddrive, 0
$009D	$022B			SUBWF	_fullcolourleddisplaycount, 0
$009E	$30FF			MOVLW	255
$009F	$1C03			BTFSS	STATUS, C
$00A0	$3000			MOVLW	0
$00A1	$00F1			MOVWF	STACK_1
$00A2	$0871			MOVF	STACK_1, 0
$00A3	$3A00			XORLW	0
$00A4	$1D03			BTFSS	STATUS, Z
$00A5	$28A8			GOTO	SevenSegmentDisplays_L_60
$00A6	$1287			BCF	PORTC, 5
$00A7	$28A9			GOTO	SevenSegmentDisplays_L_61
$00A8	$	SevenSegmentDisplays_L_60:
$00A8	$1687			BSF	PORTC, 5
$00A9	$	SevenSegmentDisplays_L_61:
;SevenSegmentDisplays.ppas,111 :: 		PORTC.6:=(FullColourLEDDisplayCount>=GreenLEDDrive);
$00A9	$082D			MOVF	_greenleddrive, 0
$00AA	$022B			SUBWF	_fullcolourleddisplaycount, 0
$00AB	$30FF			MOVLW	255
$00AC	$1C03			BTFSS	STATUS, C
$00AD	$3000			MOVLW	0
$00AE	$00F1			MOVWF	STACK_1
$00AF	$0871			MOVF	STACK_1, 0
$00B0	$3A00			XORLW	0
$00B1	$1D03			BTFSS	STATUS, Z
$00B2	$28B5			GOTO	SevenSegmentDisplays_L_62
$00B3	$1307			BCF	PORTC, 6
$00B4	$28B6			GOTO	SevenSegmentDisplays_L_63
$00B5	$	SevenSegmentDisplays_L_62:
$00B5	$1707			BSF	PORTC, 6
$00B6	$	SevenSegmentDisplays_L_63:
;SevenSegmentDisplays.ppas,112 :: 		PORTC.7:=(FullColourLEDDisplayCount>=BlueLEDDrive);
$00B6	$082E			MOVF	_blueleddrive, 0
$00B7	$022B			SUBWF	_fullcolourleddisplaycount, 0
$00B8	$30FF			MOVLW	255
$00B9	$1C03			BTFSS	STATUS, C
$00BA	$3000			MOVLW	0
$00BB	$00F1			MOVWF	STACK_1
$00BC	$0871			MOVF	STACK_1, 0
$00BD	$3A00			XORLW	0
$00BE	$1D03			BTFSS	STATUS, Z
$00BF	$28C2			GOTO	SevenSegmentDisplays_L_64
$00C0	$1387			BCF	PORTC, 7
$00C1	$28C3			GOTO	SevenSegmentDisplays_L_65
$00C2	$	SevenSegmentDisplays_L_64:
$00C2	$1787			BSF	PORTC, 7
$00C3	$	SevenSegmentDisplays_L_65:
;SevenSegmentDisplays.ppas,114 :: 		Inc(SevenSegmentDisplayCount);
$00C3	$0AA5			INCF	_sevensegmentdisplaycount, 1
;SevenSegmentDisplays.ppas,115 :: 		if SevenSegmentDisplayCount=4 then
$00C4	$0825			MOVF	_sevensegmentdisplaycount, 0
$00C5	$3A04			XORLW	4
$00C6	$1D03			BTFSS	STATUS, Z
$00C7	$28C9			GOTO	SevenSegmentDisplays_L_67
$00C8	$	SevenSegmentDisplays_L_66:
;SevenSegmentDisplays.ppas,116 :: 		SevenSegmentDisplayCount:=0;
$00C8	$01A5			CLRF	_sevensegmentdisplaycount, 1
$00C9	$	SevenSegmentDisplays_L_67:
$00C9	$	SevenSegmentDisplays_L_68:
;SevenSegmentDisplays.ppas,118 :: 		if FullColourLEDDisplayCount=39 then
$00C9	$082B			MOVF	_fullcolourleddisplaycount, 0
$00CA	$3A27			XORLW	39
$00CB	$1D03			BTFSS	STATUS, Z
$00CC	$28CF			GOTO	SevenSegmentDisplays_L_70
$00CD	$	SevenSegmentDisplays_L_69:
;SevenSegmentDisplays.ppas,119 :: 		FullColourLEDDisplayCount:=0
$00CD	$01AB			CLRF	_fullcolourleddisplaycount, 1
$00CE	$28D0			GOTO	SevenSegmentDisplays_L_71
;SevenSegmentDisplays.ppas,120 :: 		else
$00CF	$	SevenSegmentDisplays_L_70:
;SevenSegmentDisplays.ppas,121 :: 		Inc(FullColourLEDDisplayCount);
$00CF	$0AAB			INCF	_fullcolourleddisplaycount, 1
$00D0	$	SevenSegmentDisplays_L_71:
;SevenSegmentDisplays.ppas,123 :: 		INTCON.T0IF:=False;
$00D0	$110B			BCF	INTCON, 2
$00D1	$	SevenSegmentDisplays_L_73:
;SevenSegmentDisplays.ppas,124 :: 		end;
$00D1	$	SevenSegmentDisplays_L_41:
$00D1	$	SevenSegmentDisplays_L_42:
$00D1	$	SevenSegmentDisplays_L_36:
;SevenSegmentDisplays.ppas,125 :: 		end;
$00D1	$0008			RETURN
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00C0			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00BF			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00C1			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0873			MOVF	STACK_3, 0
$000E	$00DF			MOVWF	STSAVED_3
$000F	$0872			MOVF	STACK_2, 0
$0010	$00DE			MOVWF	STSAVED_2
$0011	$0871			MOVF	STACK_1, 0
$0012	$00DD			MOVWF	STSAVED_1
$0013	$0870			MOVF	STACK_0, 0
$0014	$00DC			MOVWF	STSAVED_0
;SevenSegmentDisplays.ppas,128 :: 		begin
;SevenSegmentDisplays.ppas,129 :: 		I2CInterrupt;
$0015	$2316			CALL	_i2cinterrupt
;SevenSegmentDisplays.ppas,130 :: 		SevenSegmentInterrupt;
$0016	$2028			CALL	_sevensegmentinterrupt
$0017	$	SevenSegmentDisplays_L_74:
;SevenSegmentDisplays.ppas,131 :: 		end;
$0017	$	L_Interrupt_end:
$0017	$085F			MOVF	STSAVED_3, 0
$0018	$00F3			MOVWF	STACK_3
$0019	$085E			MOVF	STSAVED_2, 0
$001A	$00F2			MOVWF	STACK_2
$001B	$085D			MOVF	STSAVED_1, 0
$001C	$00F1			MOVWF	STACK_1
$001D	$085C			MOVF	STSAVED_0, 0
$001E	$00F0			MOVWF	STACK_0
$001F	$0841			MOVF	?savePCLATH, 0
$0020	$008A			MOVWF	PCLATH
$0021	$083F			MOVF	?saveFSR, 0
$0022	$0084			MOVWF	FSR
$0023	$0E40			SWAPF	?saveSTATUS, 0
$0024	$0083			MOVWF	STATUS
$0025	$0EFF			SWAPF	STACK_15, 1
$0026	$0E7F			SWAPF	STACK_15, 0
$0027	$0009			RETFIE
$0655	$	_i2c_init:
;I2C_c34.ppas,8 :: 		
;I2C_c34.ppas,9 :: 		
$0655	$1303			BCF	STATUS, RP1
$0656	$1683			BSF	STATUS, RP0
$0657	$1314			BCF	SSPSTAT, 6
$0658	$	I2C_c34_L_2:
;I2C_c34.ppas,10 :: 		
$0658	$1394			BCF	SSPSTAT, 7
$0659	$	I2C_c34_L_4:
;I2C_c34.ppas,11 :: 		
$0659	$	I2C_c34_L_5:
$0659	$1607			BSF	TRISC, 4
$065A	$	I2C_c34_L_6:
;I2C_c34.ppas,12 :: 		
$065A	$	I2C_c34_L_7:
$065A	$1587			BSF	TRISC, 3
$065B	$	I2C_c34_L_8:
;I2C_c34.ppas,13 :: 		
$065B	$3038			MOVLW	56
$065C	$1283			BCF	STATUS, RP0
$065D	$0094			MOVWF	SSPCON
$065E	$	I2C_c34_L_0:
;I2C_c34.ppas,15 :: 		
$065E	$0008			RETURN
$05B2	$	_delayonems:
;UGeneral.ppas,4 :: 		begin
;UGeneral.ppas,5 :: 		Delay_ms(1);
$05B2	$3007			MOVLW	7
$05B3	$1303			BCF	STATUS, RP1
$05B4	$1283			BCF	STATUS, RP0
$05B5	$00FB			MOVWF	STACK_11
$05B6	$30FF			MOVLW	255
$05B7	$00FA			MOVWF	STACK_10
$05B8	$0BFB			DECFSZ	STACK_11, F
$05B9	$2DBB			GOTO	$+2
$05BA	$2DBE			GOTO	$+4
$05BB	$0BFA			DECFSZ	STACK_10, F
$05BC	$2DBB			GOTO	$-1
$05BD	$2DB8			GOTO	$-5
$05BE	$3078			MOVLW	120
$05BF	$00FA			MOVWF	STACK_10
$05C0	$0BFA			DECFSZ	STACK_10, F
$05C1	$2DC0			GOTO	$-1
$05C2	$0000			NOP
$05C3	$0000			NOP
$05C4	$	UGeneral_L_0:
;UGeneral.ppas,6 :: 		end;
$05C4	$0008			RETURN
$05C5	$	table__SevenSegment:
;SevenSegmentDisplays.ppas,7 :: 		SevenSegment:Array[0..15] of Byte=(63,6,91,79,102,109,125,7,127,111,119,124,57,94,121,113);
$05C5	$343F			RETLW	63
$05C6	$3406			RETLW	6
$05C7	$345B			RETLW	91
$05C8	$344F			RETLW	79
$05C9	$3466			RETLW	102
$05CA	$346D			RETLW	109
$05CB	$347D			RETLW	125
$05CC	$3407			RETLW	7
$05CD	$347F			RETLW	127
$05CE	$346F			RETLW	111
$05CF	$3477			RETLW	119
$05D0	$347C			RETLW	124
$05D1	$3439			RETLW	57
$05D2	$345E			RETLW	94
$05D3	$3479			RETLW	121
$05D4	$3471			RETLW	113
$05D5	$0008			RETURN
$0668	$	_____doicp:
;system.ppas,20 :: 		
;system.ppas,23 :: 		
$0668	$1303			BCF	STATUS, RP1
$0669	$1283			BCF	STATUS, RP0
$066A	$0831			MOVF	___DoICPHiAddr, 0
$066B	$008A			MOVWF	PCLATH
;system.ppas,24 :: 		
$066C	$082F			MOVF	___DoICPLoAddr, 0
$066D	$0082			MOVWF	PCL
$066E	$	system_L_0:
;system.ppas,26 :: 		
$066E	$0008			RETURN
$0565	$	_i2c_is_idle:
;I2C_c34.ppas,22 :: 		
;I2C_c34.ppas,23 :: 		
$0565	$1303			BCF	STATUS, RP1
$0566	$1283			BCF	STATUS, RP0
$0567	$01D4			CLRF	_i2c_is_idle_local_result, 1
;I2C_c34.ppas,24 :: 		
$0568	$1683			BSF	STATUS, RP0
$0569	$0814			MOVF	SSPSTAT, 0
$056A	$1283			BCF	STATUS, RP0
$056B	$00F1			MOVWF	STACK_1
$056C	$3000			MOVLW	0
$056D	$1971			BTFSC	STACK_1, 2
$056E	$3001			MOVLW	1
$056F	$00F1			MOVWF	STACK_1
$0570	$0871			MOVF	STACK_1, 0
$0571	$3A00			XORLW	0
$0572	$1D03			BTFSS	STATUS, Z
$0573	$2D7F			GOTO	I2C_c34_L_11
$0574	$	I2C_c34_L_10:
;I2C_c34.ppas,25 :: 		
$0574	$301F			MOVLW	31
$0575	$1683			BSF	STATUS, RP0
$0576	$0511			ANDWF	SSPCON2, 0
$0577	$1283			BCF	STATUS, RP0
$0578	$00F1			MOVWF	STACK_1
$0579	$0871			MOVF	STACK_1, 0
$057A	$3A00			XORLW	0
$057B	$1D03			BTFSS	STATUS, Z
$057C	$2D7F			GOTO	I2C_c34_L_14
$057D	$	I2C_c34_L_13:
$057D	$30FF			MOVLW	255
$057E	$00D4			MOVWF	_i2c_is_idle_local_result
$057F	$	I2C_c34_L_14:
$057F	$	I2C_c34_L_15:
$057F	$	I2C_c34_L_11:
$057F	$	I2C_c34_L_12:
$057F	$	I2C_c34_L_9:
;I2C_c34.ppas,26 :: 		
$057F	$0854			MOVF	_i2c_is_idle_local_result, 0
$0580	$00F0			MOVWF	STACK_0
$0581	$0008			RETURN
$0640	$	_i2c_setmastermode:
;UI2C.ppas,46 :: 		begin
;UI2C.ppas,47 :: 		PIE1.SSPIE:=False; // Prevent our I2C interrupt handler from operating whilst we are master.
$0640	$1303			BCF	STATUS, RP1
$0641	$1683			BSF	STATUS, RP0
$0642	$118C			BCF	PIE1, 3
$0643	$	UI2C_L_13:
;UI2C.ppas,48 :: 		PIE2.BCLIE:=False; // Prevent our I2C interrupt handler from operating whilst we are master.
$0643	$118D			BCF	PIE2, 3
$0644	$	UI2C_L_15:
;UI2C.ppas,50 :: 		SSPCON.SSPEN:=False; // Reset I2C module.
$0644	$1283			BCF	STATUS, RP0
$0645	$1294			BCF	SSPCON, 5
$0646	$	UI2C_L_17:
;UI2C.ppas,51 :: 		I2C_Init(100000);
$0646	$3032			MOVLW	50
$0647	$1683			BSF	STATUS, RP0
$0648	$0093			MOVWF	SSPADD
$0649	$2655			CALL	_i2c_init
$064A	$	UI2C_L_11:
;UI2C.ppas,52 :: 		end;
$064A	$0008			RETURN
$051F	$	_private_i2c_master_start:
;UI2C.ppas,70 :: 		begin
;UI2C.ppas,71 :: 		Result:=False;
$051F	$1303			BCF	STATUS, RP1
$0520	$1283			BCF	STATUS, RP0
$0521	$01D4			CLRF	_private_i2c_master_start_local_result, 1
;UI2C.ppas,73 :: 		PIR1.SSPIF:=False;
$0522	$118C			BCF	PIR1, 3
$0523	$	UI2C_L_24:
;UI2C.ppas,74 :: 		PIR2.BCLIF:=False; // Bus collision detect.
$0523	$118D			BCF	PIR2, 3
$0524	$	UI2C_L_26:
;UI2C.ppas,75 :: 		SSPCON2.SEN:=True;
$0524	$	UI2C_L_27:
$0524	$1683			BSF	STATUS, RP0
$0525	$1411			BSF	SSPCON2, 0
$0526	$	UI2C_L_28:
;UI2C.ppas,76 :: 		while PIR1.SSPIF=False do
$0526	$	UI2C_L_30:
$0526	$1283			BCF	STATUS, RP0
$0527	$080C			MOVF	PIR1, 0
$0528	$00F1			MOVWF	STACK_1
$0529	$3000			MOVLW	0
$052A	$19F1			BTFSC	STACK_1, 3
$052B	$3001			MOVLW	1
$052C	$00F1			MOVWF	STACK_1
$052D	$0871			MOVF	STACK_1, 0
$052E	$3A00			XORLW	0
$052F	$1D03			BTFSS	STATUS, Z
$0530	$2D3D			GOTO	UI2C_L_31
;UI2C.ppas,78 :: 		if PIR2.BCLIF then
$0531	$080D			MOVF	PIR2, 0
$0532	$00F1			MOVWF	STACK_1
$0533	$3000			MOVLW	0
$0534	$19F1			BTFSC	STACK_1, 3
$0535	$3001			MOVLW	1
$0536	$00F1			MOVWF	STACK_1
$0537	$0871			MOVF	STACK_1, 0
$0538	$1903			BTFSC	STATUS, Z
$0539	$2D3C			GOTO	UI2C_L_35
$053A	$	UI2C_L_34:
;UI2C.ppas,80 :: 		PIR2.BCLIF:=False;
$053A	$118D			BCF	PIR2, 3
$053B	$	UI2C_L_38:
;UI2C.ppas,81 :: 		Exit;
$053B	$2D40			GOTO	UI2C_L_22
;UI2C.ppas,82 :: 		end;
$053C	$	UI2C_L_35:
$053C	$	UI2C_L_36:
;UI2C.ppas,83 :: 		end;
$053C	$2D26			GOTO	UI2C_L_30
$053D	$	UI2C_L_31:
;UI2C.ppas,85 :: 		PIR1.SSPIF:=False;
$053D	$118C			BCF	PIR1, 3
$053E	$	UI2C_L_40:
;UI2C.ppas,87 :: 		Result:=True;
$053E	$30FF			MOVLW	255
$053F	$00D4			MOVWF	_private_i2c_master_start_local_result
$0540	$	UI2C_L_22:
;UI2C.ppas,88 :: 		end;
$0540	$0854			MOVF	_private_i2c_master_start_local_result, 0
$0541	$00F0			MOVWF	STACK_0
$0542	$0008			RETURN
$05E7	$	_i2c_setslavemode:
;UI2C.ppas,33 :: 		begin
;UI2C.ppas,34 :: 		SSPCON.SSPEN:=False; // Reset I2C module.
$05E7	$1303			BCF	STATUS, RP1
$05E8	$1283			BCF	STATUS, RP0
$05E9	$1294			BCF	SSPCON, 5
$05EA	$	UI2C_L_2:
;UI2C.ppas,35 :: 		SSPADD:=I2C_SlaveAddress;
$05EA	$0832			MOVF	_i2c_slaveaddress, 0
$05EB	$1683			BSF	STATUS, RP0
$05EC	$0093			MOVWF	SSPADD
;UI2C.ppas,36 :: 		SSPCON:=$36; // I2C slave mode.
$05ED	$3036			MOVLW	54
$05EE	$1283			BCF	STATUS, RP0
$05EF	$0094			MOVWF	SSPCON
;UI2C.ppas,37 :: 		SSPCON2.GCEN:=True; // General call.
$05F0	$	UI2C_L_3:
$05F0	$1683			BSF	STATUS, RP0
$05F1	$1791			BSF	SSPCON2, 7
$05F2	$	UI2C_L_4:
;UI2C.ppas,39 :: 		PIR1.SSPIF:=False;
$05F2	$1283			BCF	STATUS, RP0
$05F3	$118C			BCF	PIR1, 3
$05F4	$	UI2C_L_6:
;UI2C.ppas,40 :: 		PIE1.SSPIE:=True;
$05F4	$	UI2C_L_7:
$05F4	$1683			BSF	STATUS, RP0
$05F5	$158C			BSF	PIE1, 3
$05F6	$	UI2C_L_8:
;UI2C.ppas,42 :: 		PIE2.BCLIE:=False;
$05F6	$118D			BCF	PIE2, 3
$05F7	$	UI2C_L_10:
$05F7	$	UI2C_L_0:
;UI2C.ppas,43 :: 		end;
$05F7	$0008			RETURN
$0543	$	_delayms:
;UGeneral.ppas,12 :: 		begin
;UGeneral.ppas,13 :: 		for Count:=0 to Value-1 do
$0543	$1303			BCF	STATUS, RP1
$0544	$1283			BCF	STATUS, RP0
$0545	$01D6			CLRF	_delayms_local_count
$0546	$01D7			CLRF	_delayms_local_count+1
$0547	$	UGeneral_L_2:
$0547	$3001			MOVLW	1
$0548	$0254			SUBWF	FARG_DelayMS, 0
$0549	$00D8			MOVWF	FLOC_DelayMS+2
$054A	$3000			MOVLW	0
$054B	$1C03			BTFSS	STATUS, C
$054C	$3F01			ADDLW	1
$054D	$0255			SUBWF	FARG_DelayMS+1, 0
$054E	$00D9			MOVWF	FLOC_DelayMS+3
$054F	$0857			MOVF	_delayms_local_count+1, 0
$0550	$0259			SUBWF	FLOC_DelayMS+3, 0
$0551	$1D03			BTFSS	STATUS, Z
$0552	$2D55			GOTO	L_DelayMS_0
$0553	$0856			MOVF	_delayms_local_count, 0
$0554	$0258			SUBWF	FLOC_DelayMS+2, 0
$0555	$	L_DelayMS_0:
$0555	$1C03			BTFSS	STATUS, C
$0556	$2D64			GOTO	UGeneral_L_5
;UGeneral.ppas,14 :: 		DelayOneMS;
$0557	$25B2			CALL	_delayonems
$0558	$0857			MOVF	_delayms_local_count+1, 0
$0559	$0659			XORWF	FLOC_DelayMS+3, 0
$055A	$1D03			BTFSS	STATUS, Z
$055B	$2D5E			GOTO	L_DelayMS_1
$055C	$0858			MOVF	FLOC_DelayMS+2, 0
$055D	$0656			XORWF	_delayms_local_count, 0
$055E	$	L_DelayMS_1:
$055E	$1903			BTFSC	STATUS, Z
$055F	$2D64			GOTO	UGeneral_L_5
$0560	$	UGeneral_L_3:
$0560	$0AD6			INCF	_delayms_local_count, 1
$0561	$1903			BTFSC	STATUS, Z
$0562	$0AD7			INCF	_delayms_local_count+1, 1
$0563	$2D47			GOTO	UGeneral_L_2
$0564	$	UGeneral_L_5:
$0564	$	UGeneral_L_1:
;UGeneral.ppas,15 :: 		end;
$0564	$0008			RETURN
$041D	$	_calculatedigitmask:
;SevenSegmentDisplays.ppas,134 :: 		begin
;SevenSegmentDisplays.ppas,135 :: 		if (not IsHexadecimal) and (Digit>9) then
$041D	$1303			BCF	STATUS, RP1
$041E	$1283			BCF	STATUS, RP0
$041F	$0955			COMF	FARG_CalculateDigitMask+1, W
$0420	$00F2			MOVWF	STACK_2
$0421	$0854			MOVF	FARG_CalculateDigitMask, 0
$0422	$3C09			SUBLW	9
$0423	$30FF			MOVLW	255
$0424	$1803			BTFSC	STATUS, C
$0425	$3000			MOVLW	0
$0426	$00F0			MOVWF	STACK_0
$0427	$0872			MOVF	STACK_2, 0
$0428	$05F0			ANDWF	STACK_0, 1
$0429	$1903			BTFSC	STATUS, Z
$042A	$2C2E			GOTO	SevenSegmentDisplays_L_77
$042B	$	SevenSegmentDisplays_L_76:
;SevenSegmentDisplays.ppas,136 :: 		Result:=$79 // 'E' for error.
$042B	$3079			MOVLW	121
$042C	$00D6			MOVWF	_calculatedigitmask_local_result
$042D	$2C54			GOTO	SevenSegmentDisplays_L_78
;SevenSegmentDisplays.ppas,137 :: 		else if IsHexadecimal and (Digit>15) then
$042E	$	SevenSegmentDisplays_L_77:
$042E	$0854			MOVF	FARG_CalculateDigitMask, 0
$042F	$3C0F			SUBLW	15
$0430	$30FF			MOVLW	255
$0431	$1803			BTFSC	STATUS, C
$0432	$3000			MOVLW	0
$0433	$00F0			MOVWF	STACK_0
$0434	$0855			MOVF	FARG_CalculateDigitMask+1, 0
$0435	$05F0			ANDWF	STACK_0, 1
$0436	$1903			BTFSC	STATUS, Z
$0437	$2C3B			GOTO	SevenSegmentDisplays_L_80
$0438	$	SevenSegmentDisplays_L_79:
;SevenSegmentDisplays.ppas,138 :: 		Result:=$79 // 'E' for error.
$0438	$3079			MOVLW	121
$0439	$00D6			MOVWF	_calculatedigitmask_local_result
$043A	$2C54			GOTO	SevenSegmentDisplays_L_81
;SevenSegmentDisplays.ppas,139 :: 		else
$043B	$	SevenSegmentDisplays_L_80:
;SevenSegmentDisplays.ppas,140 :: 		Result:=SevenSegment[Digit];
$043B	$30C5			MOVLW	#sevensegment
$043C	$00F2			MOVWF	STACK_2
$043D	$3005			MOVLW	@#sevensegment
$043E	$00F3			MOVWF	STACK_2+1
$043F	$0854			MOVF	FARG_CalculateDigitMask, 0
$0440	$00F0			MOVWF	STACK_0
$0441	$01F1			CLRF	STACK_0+1
$0442	$0872			MOVF	STACK_2, 0
$0443	$07F0			ADDWF	STACK_0, 1
$0444	$0873			MOVF	STACK_2+1, 0
$0445	$1803			BTFSC	STATUS, C
$0446	$3F01			ADDLW	1
$0447	$07F1			ADDWF	STACK_0+1, 1
$0448	$0870			MOVF	STACK_0, 0
$0449	$00AF			MOVWF	___DoICPLoAddr
$044A	$0871			MOVF	STACK_0+1, 0
$044B	$00B1			MOVWF	___DoICPHiAddr
$044C	$080A			MOVF	PCLATH, 0
$044D	$00B0			MOVWF	___DoICPSavePCLATH
$044E	$2668			CALL	_____DoICP
$044F	$00F0			MOVWF	STACK_0
$0450	$0830			MOVF	___DoICPSavePCLATH, 0
$0451	$008A			MOVWF	PCLATH
$0452	$0870			MOVF	STACK_0, 0
$0453	$00D6			MOVWF	_calculatedigitmask_local_result
$0454	$	SevenSegmentDisplays_L_81:
$0454	$	SevenSegmentDisplays_L_78:
$0454	$	SevenSegmentDisplays_L_75:
;SevenSegmentDisplays.ppas,141 :: 		end;
$0454	$0856			MOVF	_calculatedigitmask_local_result, 0
$0455	$00F0			MOVWF	STACK_0
$0456	$0008			RETURN
$05F8	$	_private_i2c_master_restart:
;UI2C.ppas,91 :: 		begin
;UI2C.ppas,92 :: 		SSPCON2.RSEN:=True;
$05F8	$	UI2C_L_42:
$05F8	$1303			BCF	STATUS, RP1
$05F9	$1683			BSF	STATUS, RP0
$05FA	$1491			BSF	SSPCON2, 1
$05FB	$	UI2C_L_43:
;UI2C.ppas,93 :: 		while PIR1.SSPIF=False do begin end;
$05FB	$	UI2C_L_45:
$05FB	$1283			BCF	STATUS, RP0
$05FC	$080C			MOVF	PIR1, 0
$05FD	$00F1			MOVWF	STACK_1
$05FE	$3000			MOVLW	0
$05FF	$19F1			BTFSC	STACK_1, 3
$0600	$3001			MOVLW	1
$0601	$00F1			MOVWF	STACK_1
$0602	$0871			MOVF	STACK_1, 0
$0603	$3A00			XORLW	0
$0604	$1903			BTFSC	STATUS, Z
$0605	$2DFB			GOTO	UI2C_L_45
$0606	$	UI2C_L_46:
;UI2C.ppas,94 :: 		PIR1.SSPIF:=False;
$0606	$118C			BCF	PIR1, 3
$0607	$	UI2C_L_50:
$0607	$	UI2C_L_41:
;UI2C.ppas,95 :: 		end;
$0607	$0008			RETURN
$04FB	$	_private_i2c_master_acquirebusandstart:
;UI2C.ppas,102 :: 		begin
;UI2C.ppas,103 :: 		I2C_Started:=False;
$04FB	$1303			BCF	STATUS, RP1
$04FC	$1283			BCF	STATUS, RP0
$04FD	$01B3			CLRF	_i2c_started, 1
;UI2C.ppas,105 :: 		if I2C_MultiMasterMode then
$04FE	$0834			MOVF	_i2c_multimastermode, 0
$04FF	$1903			BTFSC	STATUS, Z
$0500	$2D16			GOTO	UI2C_L_53
$0501	$	UI2C_L_52:
;UI2C.ppas,107 :: 		while True do
$0501	$	UI2C_L_56:
;UI2C.ppas,109 :: 		if I2C_Is_Idle then
$0501	$2565			CALL	_i2c_is_idle
$0502	$0870			MOVF	STACK_0, 0
$0503	$1903			BTFSC	STATUS, Z
$0504	$2D0E			GOTO	UI2C_L_61
$0505	$	UI2C_L_60:
;UI2C.ppas,111 :: 		I2C_SetMasterMode;
$0505	$2640			CALL	_i2c_setmastermode
;UI2C.ppas,112 :: 		if Private_I2C_Master_Start then
$0506	$251F			CALL	_private_i2c_master_start
$0507	$0870			MOVF	STACK_0, 0
$0508	$1903			BTFSC	STATUS, Z
$0509	$2D0D			GOTO	UI2C_L_64
$050A	$	UI2C_L_63:
;UI2C.ppas,114 :: 		I2C_Started:=True;
$050A	$30FF			MOVLW	255
$050B	$00B3			MOVWF	_i2c_started
;UI2C.ppas,115 :: 		Exit; // Success.
$050C	$2D1E			GOTO	UI2C_L_51
;UI2C.ppas,116 :: 		end;
$050D	$	UI2C_L_64:
$050D	$	UI2C_L_65:
;UI2C.ppas,117 :: 		I2C_SetSlaveMode;
$050D	$25E7			CALL	_i2c_setslavemode
;UI2C.ppas,118 :: 		end;
$050E	$	UI2C_L_61:
$050E	$	UI2C_L_62:
;UI2C.ppas,120 :: 		DelayMS(10); // Arbitrary but longer than the longest time to handle an instruction. A random time would be better.
$050E	$1303			BCF	STATUS, RP1
$050F	$1683			BSF	STATUS, RP0
$0510	$300A			MOVLW	10
$0511	$1283			BCF	STATUS, RP0
$0512	$00D4			MOVWF	FARG_DelayMS
$0513	$01D5			CLRF	FARG_DelayMS+1
$0514	$2543			CALL	_delayms
;UI2C.ppas,121 :: 		end;
$0515	$2D01			GOTO	UI2C_L_56
;UI2C.ppas,123 :: 		else
$0516	$	UI2C_L_53:
;UI2C.ppas,125 :: 		repeat until Private_I2C_Master_Start;
$0516	$	UI2C_L_66:
$0516	$	UI2C_L_67:
$0516	$251F			CALL	_private_i2c_master_start
$0517	$0870			MOVF	STACK_0, 0
$0518	$1903			BTFSC	STATUS, Z
$0519	$2D1B			GOTO	UI2C_L_69
$051A	$	UI2C_L_70:
$051A	$2D1C			GOTO	UI2C_L_68
$051B	$	UI2C_L_69:
$051B	$2D16			GOTO	UI2C_L_66
$051C	$	UI2C_L_68:
;UI2C.ppas,126 :: 		I2C_Started:=True;
$051C	$30FF			MOVLW	255
$051D	$00B3			MOVWF	_i2c_started
;UI2C.ppas,127 :: 		end;
$051E	$	UI2C_L_54:
$051E	$	UI2C_L_51:
;UI2C.ppas,128 :: 		end;
$051E	$0008			RETURN
$0481	$	_i2c_master_sendbyte:
;UI2C.ppas,131 :: 		begin
;UI2C.ppas,132 :: 		SSPBUF:=Value;
$0481	$1303			BCF	STATUS, RP1
$0482	$1283			BCF	STATUS, RP0
$0483	$084F			MOVF	FARG_I2C_Master_SendByte, 0
$0484	$0093			MOVWF	SSPBUF
;UI2C.ppas,133 :: 		if SSPCON.WCOL then
$0485	$0814			MOVF	SSPCON, 0
$0486	$00F1			MOVWF	STACK_1
$0487	$3000			MOVLW	0
$0488	$1BF1			BTFSC	STACK_1, 7
$0489	$3001			MOVLW	1
$048A	$00F1			MOVWF	STACK_1
$048B	$0871			MOVF	STACK_1, 0
$048C	$1903			BTFSC	STATUS, Z
$048D	$2C91			GOTO	UI2C_L_73
$048E	$	UI2C_L_72:
;UI2C.ppas,135 :: 		I2C_Error:=I2C_WriteError;
$048E	$3001			MOVLW	1
$048F	$00B5			MOVWF	_i2c_error
;UI2C.ppas,136 :: 		SSPCON.WCOL:=False;
$0490	$1394			BCF	SSPCON, 7
$0491	$	UI2C_L_76:
;UI2C.ppas,137 :: 		end;
$0491	$	UI2C_L_73:
$0491	$	UI2C_L_74:
;UI2C.ppas,138 :: 		while PIR1.SSPIF=False do begin end;
$0491	$	UI2C_L_78:
$0491	$080C			MOVF	PIR1, 0
$0492	$00F1			MOVWF	STACK_1
$0493	$3000			MOVLW	0
$0494	$19F1			BTFSC	STACK_1, 3
$0495	$3001			MOVLW	1
$0496	$00F1			MOVWF	STACK_1
$0497	$0871			MOVF	STACK_1, 0
$0498	$3A00			XORLW	0
$0499	$1903			BTFSC	STATUS, Z
$049A	$2C91			GOTO	UI2C_L_78
$049B	$	UI2C_L_79:
;UI2C.ppas,139 :: 		PIR1.SSPIF:=False;
$049B	$118C			BCF	PIR1, 3
$049C	$	UI2C_L_83:
;UI2C.ppas,140 :: 		if SSPCON2.ACKSTAT then
$049C	$1683			BSF	STATUS, RP0
$049D	$0811			MOVF	SSPCON2, 0
$049E	$1283			BCF	STATUS, RP0
$049F	$00F1			MOVWF	STACK_1
$04A0	$3000			MOVLW	0
$04A1	$1B71			BTFSC	STACK_1, 6
$04A2	$3001			MOVLW	1
$04A3	$00F1			MOVWF	STACK_1
$04A4	$0871			MOVF	STACK_1, 0
$04A5	$1903			BTFSC	STATUS, Z
$04A6	$2CA9			GOTO	UI2C_L_85
$04A7	$	UI2C_L_84:
;UI2C.ppas,142 :: 		I2C_Error:=I2C_AckError;
$04A7	$3002			MOVLW	2
$04A8	$00B5			MOVWF	_i2c_error
;UI2C.ppas,143 :: 		end;
$04A9	$	UI2C_L_85:
$04A9	$	UI2C_L_86:
$04A9	$	UI2C_L_71:
;UI2C.ppas,144 :: 		end;
$04A9	$0008			RETURN
$014A	$	_calculatedecimaldigits:
;SevenSegmentDisplays.ppas,165 :: 		begin
;SevenSegmentDisplays.ppas,166 :: 		Digits[0]:=0;
$014A	$1303			BCF	STATUS, RP1
$014B	$1283			BCF	STATUS, RP0
$014C	$0851			MOVF	FARG_CalculateDecimalDigits+2, 0
$014D	$0084			MOVWF	FSR
$014E	$0851			MOVF	FARG_CalculateDecimalDigits+2, 0
$014F	$0084			MOVWF	FSR
$0150	$0180			CLRF	INDF, 1
;SevenSegmentDisplays.ppas,167 :: 		Digits[1]:=0;
$0151	$0A51			INCF	FARG_CalculateDecimalDigits+2, 0
$0152	$00F0			MOVWF	STACK_0
$0153	$0870			MOVF	STACK_0, 0
$0154	$0084			MOVWF	FSR
$0155	$0870			MOVF	STACK_0, 0
$0156	$0084			MOVWF	FSR
$0157	$0180			CLRF	INDF, 1
;SevenSegmentDisplays.ppas,168 :: 		Digits[2]:=0;
$0158	$3002			MOVLW	2
$0159	$0751			ADDWF	FARG_CalculateDecimalDigits+2, 0
$015A	$00F0			MOVWF	STACK_0
$015B	$0870			MOVF	STACK_0, 0
$015C	$0084			MOVWF	FSR
$015D	$0870			MOVF	STACK_0, 0
$015E	$0084			MOVWF	FSR
$015F	$0180			CLRF	INDF, 1
;SevenSegmentDisplays.ppas,169 :: 		Digits[3]:=0;
$0160	$3003			MOVLW	3
$0161	$0751			ADDWF	FARG_CalculateDecimalDigits+2, 0
$0162	$00F0			MOVWF	STACK_0
$0163	$0870			MOVF	STACK_0, 0
$0164	$0084			MOVWF	FSR
$0165	$0870			MOVF	STACK_0, 0
$0166	$0084			MOVWF	FSR
$0167	$0180			CLRF	INDF, 1
;SevenSegmentDisplays.ppas,171 :: 		while Value>=1000 do
$0168	$	SevenSegmentDisplays_L_95:
$0168	$3003			MOVLW	3
$0169	$0250			SUBWF	FARG_CalculateDecimalDigits+1, 0
$016A	$1D03			BTFSS	STATUS, Z
$016B	$296E			GOTO	L_CalculateDecimalDigits_0
$016C	$30E8			MOVLW	232
$016D	$024F			SUBWF	FARG_CalculateDecimalDigits, 0
$016E	$	L_CalculateDecimalDigits_0:
$016E	$1C03			BTFSS	STATUS, C
$016F	$2985			GOTO	SevenSegmentDisplays_L_96
;SevenSegmentDisplays.ppas,173 :: 		Value:=Value-1000;
$0170	$30E8			MOVLW	232
$0171	$02CF			SUBWF	FARG_CalculateDecimalDigits, 1
$0172	$1C03			BTFSS	STATUS, C
$0173	$03D0			DECF	FARG_CalculateDecimalDigits+1, 1
$0174	$3003			MOVLW	3
$0175	$02D0			SUBWF	FARG_CalculateDecimalDigits+1, 1
;SevenSegmentDisplays.ppas,174 :: 		Inc(Digits[3]);
$0176	$3003			MOVLW	3
$0177	$0751			ADDWF	FARG_CalculateDecimalDigits+2, 0
$0178	$00F1			MOVWF	STACK_1
$0179	$0871			MOVF	STACK_1, 0
$017A	$0084			MOVWF	FSR
$017B	$0800			MOVF	INDF, 0
$017C	$00F0			MOVWF	STACK_0
$017D	$0AF0			INCF	STACK_0, 1
$017E	$0871			MOVF	STACK_1, 0
$017F	$0084			MOVWF	FSR
$0180	$0871			MOVF	STACK_1, 0
$0181	$0084			MOVWF	FSR
$0182	$0870			MOVF	STACK_0, 0
$0183	$0080			MOVWF	INDF
;SevenSegmentDisplays.ppas,175 :: 		end;
$0184	$2968			GOTO	SevenSegmentDisplays_L_95
$0185	$	SevenSegmentDisplays_L_96:
;SevenSegmentDisplays.ppas,177 :: 		while Value>=100 do
$0185	$	SevenSegmentDisplays_L_100:
$0185	$3000			MOVLW	0
$0186	$0250			SUBWF	FARG_CalculateDecimalDigits+1, 0
$0187	$1D03			BTFSS	STATUS, Z
$0188	$298B			GOTO	L_CalculateDecimalDigits_1
$0189	$3064			MOVLW	100
$018A	$024F			SUBWF	FARG_CalculateDecimalDigits, 0
$018B	$	L_CalculateDecimalDigits_1:
$018B	$1C03			BTFSS	STATUS, C
$018C	$29A0			GOTO	SevenSegmentDisplays_L_101
;SevenSegmentDisplays.ppas,179 :: 		Value:=Value-100;
$018D	$3064			MOVLW	100
$018E	$02CF			SUBWF	FARG_CalculateDecimalDigits, 1
$018F	$1C03			BTFSS	STATUS, C
$0190	$03D0			DECF	FARG_CalculateDecimalDigits+1, 1
;SevenSegmentDisplays.ppas,180 :: 		Inc(Digits[2]);
$0191	$3002			MOVLW	2
$0192	$0751			ADDWF	FARG_CalculateDecimalDigits+2, 0
$0193	$00F1			MOVWF	STACK_1
$0194	$0871			MOVF	STACK_1, 0
$0195	$0084			MOVWF	FSR
$0196	$0800			MOVF	INDF, 0
$0197	$00F0			MOVWF	STACK_0
$0198	$0AF0			INCF	STACK_0, 1
$0199	$0871			MOVF	STACK_1, 0
$019A	$0084			MOVWF	FSR
$019B	$0871			MOVF	STACK_1, 0
$019C	$0084			MOVWF	FSR
$019D	$0870			MOVF	STACK_0, 0
$019E	$0080			MOVWF	INDF
;SevenSegmentDisplays.ppas,181 :: 		end;
$019F	$2985			GOTO	SevenSegmentDisplays_L_100
$01A0	$	SevenSegmentDisplays_L_101:
;SevenSegmentDisplays.ppas,183 :: 		while Value>=10 do
$01A0	$	SevenSegmentDisplays_L_105:
$01A0	$3000			MOVLW	0
$01A1	$0250			SUBWF	FARG_CalculateDecimalDigits+1, 0
$01A2	$1D03			BTFSS	STATUS, Z
$01A3	$29A6			GOTO	L_CalculateDecimalDigits_2
$01A4	$300A			MOVLW	10
$01A5	$024F			SUBWF	FARG_CalculateDecimalDigits, 0
$01A6	$	L_CalculateDecimalDigits_2:
$01A6	$1C03			BTFSS	STATUS, C
$01A7	$29BA			GOTO	SevenSegmentDisplays_L_106
;SevenSegmentDisplays.ppas,185 :: 		Value:=Value-10;
$01A8	$300A			MOVLW	10
$01A9	$02CF			SUBWF	FARG_CalculateDecimalDigits, 1
$01AA	$1C03			BTFSS	STATUS, C
$01AB	$03D0			DECF	FARG_CalculateDecimalDigits+1, 1
;SevenSegmentDisplays.ppas,186 :: 		Inc(Digits[1]);
$01AC	$0A51			INCF	FARG_CalculateDecimalDigits+2, 0
$01AD	$00F1			MOVWF	STACK_1
$01AE	$0871			MOVF	STACK_1, 0
$01AF	$0084			MOVWF	FSR
$01B0	$0800			MOVF	INDF, 0
$01B1	$00F0			MOVWF	STACK_0
$01B2	$0AF0			INCF	STACK_0, 1
$01B3	$0871			MOVF	STACK_1, 0
$01B4	$0084			MOVWF	FSR
$01B5	$0871			MOVF	STACK_1, 0
$01B6	$0084			MOVWF	FSR
$01B7	$0870			MOVF	STACK_0, 0
$01B8	$0080			MOVWF	INDF
;SevenSegmentDisplays.ppas,187 :: 		end;
$01B9	$29A0			GOTO	SevenSegmentDisplays_L_105
$01BA	$	SevenSegmentDisplays_L_106:
;SevenSegmentDisplays.ppas,189 :: 		Digits[0]:=Value;
$01BA	$0851			MOVF	FARG_CalculateDecimalDigits+2, 0
$01BB	$0084			MOVWF	FSR
$01BC	$0851			MOVF	FARG_CalculateDecimalDigits+2, 0
$01BD	$0084			MOVWF	FSR
$01BE	$084F			MOVF	FARG_CalculateDecimalDigits, 0
$01BF	$0080			MOVWF	INDF
$01C0	$	SevenSegmentDisplays_L_93:
;SevenSegmentDisplays.ppas,190 :: 		end;
$01C0	$0008			RETURN
$0383	$	_displaydigits:
;SevenSegmentDisplays.ppas,146 :: 		begin
;SevenSegmentDisplays.ppas,147 :: 		for DigitIndex:=0 to 3 do
$0383	$1303			BCF	STATUS, RP1
$0384	$1283			BCF	STATUS, RP0
$0385	$01D2			CLRF	_displaydigits_local_digitindex, 1
$0386	$	SevenSegmentDisplays_L_83:
$0386	$0852			MOVF	_displaydigits_local_digitindex, 0
$0387	$3C03			SUBLW	3
$0388	$1C03			BTFSS	STATUS, C
$0389	$2BC7			GOTO	SevenSegmentDisplays_L_86
;SevenSegmentDisplays.ppas,149 :: 		if NumDigits>DigitIndex then
$038A	$0850			MOVF	FARG_DisplayDigits+1, 0
$038B	$0252			SUBWF	_displaydigits_local_digitindex, 0
$038C	$1803			BTFSC	STATUS, C
$038D	$2BB8			GOTO	SevenSegmentDisplays_L_88
$038E	$	SevenSegmentDisplays_L_87:
;SevenSegmentDisplays.ppas,151 :: 		DigitMasks[DigitIndex]:=CalculateDigitMask(Digits[DigitIndex],IsHexadecimal);
$038E	$3027			MOVLW	_digitmasks
$038F	$00F0			MOVWF	STACK_0
$0390	$0852			MOVF	_displaydigits_local_digitindex, 0
$0391	$0770			ADDWF	STACK_0, 0
$0392	$00D3			MOVWF	FLOC_DisplayDigits+1
$0393	$3036			MOVLW	_digits
$0394	$00F0			MOVWF	STACK_0
$0395	$0852			MOVF	_displaydigits_local_digitindex, 0
$0396	$0770			ADDWF	STACK_0, 0
$0397	$0084			MOVWF	FSR
$0398	$0800			MOVF	INDF, 0
$0399	$00D4			MOVWF	FARG_CalculateDigitMask
$039A	$0851			MOVF	FARG_DisplayDigits+2, 0
$039B	$00D5			MOVWF	FARG_CalculateDigitMask+1
$039C	$241D			CALL	_calculatedigitmask
$039D	$0853			MOVF	FLOC_DisplayDigits+1, 0
$039E	$0084			MOVWF	FSR
$039F	$0853			MOVF	FLOC_DisplayDigits+1, 0
$03A0	$0084			MOVWF	FSR
$03A1	$0870			MOVF	STACK_0, 0
$03A2	$0080			MOVWF	INDF
;SevenSegmentDisplays.ppas,152 :: 		if DecimalPoint=DigitIndex then
$03A3	$084F			MOVF	FARG_DisplayDigits, 0
$03A4	$0652			XORWF	_displaydigits_local_digitindex, 0
$03A5	$1D03			BTFSS	STATUS, Z
$03A6	$2BB7			GOTO	SevenSegmentDisplays_L_91
$03A7	$	SevenSegmentDisplays_L_90:
;SevenSegmentDisplays.ppas,153 :: 		DigitMasks[DigitIndex]:=DigitMasks[DigitIndex] or $80;
$03A7	$3027			MOVLW	_digitmasks
$03A8	$00F0			MOVWF	STACK_0
$03A9	$0852			MOVF	_displaydigits_local_digitindex, 0
$03AA	$0770			ADDWF	STACK_0, 0
$03AB	$00F1			MOVWF	STACK_1
$03AC	$0871			MOVF	STACK_1, 0
$03AD	$0084			MOVWF	FSR
$03AE	$0800			MOVF	INDF, 0
$03AF	$00F0			MOVWF	STACK_0
$03B0	$17F0			BSF	STACK_0, 7
$03B1	$0871			MOVF	STACK_1, 0
$03B2	$0084			MOVWF	FSR
$03B3	$0871			MOVF	STACK_1, 0
$03B4	$0084			MOVWF	FSR
$03B5	$0870			MOVF	STACK_0, 0
$03B6	$0080			MOVWF	INDF
$03B7	$	SevenSegmentDisplays_L_91:
$03B7	$	SevenSegmentDisplays_L_92:
;SevenSegmentDisplays.ppas,154 :: 		end
$03B7	$2BC1			GOTO	SevenSegmentDisplays_L_89
;SevenSegmentDisplays.ppas,155 :: 		else
$03B8	$	SevenSegmentDisplays_L_88:
;SevenSegmentDisplays.ppas,156 :: 		DigitMasks[DigitIndex]:=0;
$03B8	$3027			MOVLW	_digitmasks
$03B9	$00F0			MOVWF	STACK_0
$03BA	$0852			MOVF	_displaydigits_local_digitindex, 0
$03BB	$07F0			ADDWF	STACK_0, 1
$03BC	$0870			MOVF	STACK_0, 0
$03BD	$0084			MOVWF	FSR
$03BE	$0870			MOVF	STACK_0, 0
$03BF	$0084			MOVWF	FSR
$03C0	$0180			CLRF	INDF, 1
$03C1	$	SevenSegmentDisplays_L_89:
;SevenSegmentDisplays.ppas,157 :: 		end;
$03C1	$0852			MOVF	_displaydigits_local_digitindex, 0
$03C2	$3A03			XORLW	3
$03C3	$1903			BTFSC	STATUS, Z
$03C4	$2BC7			GOTO	SevenSegmentDisplays_L_86
$03C5	$	SevenSegmentDisplays_L_84:
$03C5	$0AD2			INCF	_displaydigits_local_digitindex, 1
$03C6	$2B86			GOTO	SevenSegmentDisplays_L_83
$03C7	$	SevenSegmentDisplays_L_86:
;SevenSegmentDisplays.ppas,159 :: 		RedLEDDrive:=Digits[0] shl 2;
$03C7	$0836			MOVF	_digits+0, 0
$03C8	$00AC			MOVWF	_redleddrive
$03C9	$0DAC			RLF	_redleddrive, 1
$03CA	$102C			BCF	_redleddrive, 0
$03CB	$0DAC			RLF	_redleddrive, 1
$03CC	$102C			BCF	_redleddrive, 0
;SevenSegmentDisplays.ppas,160 :: 		GreenLEDDrive:=Digits[1] shl 2;
$03CD	$0837			MOVF	_digits+1, 0
$03CE	$00AD			MOVWF	_greenleddrive
$03CF	$0DAD			RLF	_greenleddrive, 1
$03D0	$102D			BCF	_greenleddrive, 0
$03D1	$0DAD			RLF	_greenleddrive, 1
$03D2	$102D			BCF	_greenleddrive, 0
;SevenSegmentDisplays.ppas,161 :: 		BlueLEDDrive:=Digits[2] shl 2;
$03D3	$0838			MOVF	_digits+2, 0
$03D4	$00AE			MOVWF	_blueleddrive
$03D5	$0DAE			RLF	_blueleddrive, 1
$03D6	$102E			BCF	_blueleddrive, 0
$03D7	$0DAE			RLF	_blueleddrive, 1
$03D8	$102E			BCF	_blueleddrive, 0
$03D9	$	SevenSegmentDisplays_L_82:
;SevenSegmentDisplays.ppas,162 :: 		end;
$03D9	$0008			RETURN
$0618	$	_i2c_initialize:
;UI2C.ppas,56 :: 		begin
;UI2C.ppas,57 :: 		I2C_Started:=False;
$0618	$1303			BCF	STATUS, RP1
$0619	$1283			BCF	STATUS, RP0
$061A	$01B3			CLRF	_i2c_started, 1
;UI2C.ppas,58 :: 		I2C_Error:=0;
$061B	$01B5			CLRF	_i2c_error, 1
;UI2C.ppas,59 :: 		I2C_MultiMasterMode:=MultiMasterMode;
$061C	$084C			MOVF	FARG_I2C_Initialize+1, 0
$061D	$00B4			MOVWF	_i2c_multimastermode
;UI2C.ppas,60 :: 		I2C_SlaveAddress:=SlaveAddress;
$061E	$084B			MOVF	FARG_I2C_Initialize, 0
$061F	$00B2			MOVWF	_i2c_slaveaddress
;UI2C.ppas,61 :: 		if MultiMasterMode then
$0620	$084C			MOVF	FARG_I2C_Initialize+1, 0
$0621	$1903			BTFSC	STATUS, Z
$0622	$2E24			GOTO	UI2C_L_20
$0623	$	UI2C_L_19:
;UI2C.ppas,62 :: 		I2C_SetSlaveMode;
$0623	$25E7			CALL	_i2c_setslavemode
$0624	$	UI2C_L_20:
$0624	$	UI2C_L_21:
$0624	$	UI2C_L_18:
;UI2C.ppas,63 :: 		end;
$0624	$1303			BCF	STATUS, RP1
$0625	$1683			BSF	STATUS, RP0
$0626	$0008			RETURN
$0634	$	_i2c_master_startwrite:
;UI2C.ppas,153 :: 		begin
;UI2C.ppas,154 :: 		if I2C_Started then
$0634	$1303			BCF	STATUS, RP1
$0635	$1283			BCF	STATUS, RP0
$0636	$0833			MOVF	_i2c_started, 0
$0637	$1903			BTFSC	STATUS, Z
$0638	$2E3B			GOTO	UI2C_L_90
$0639	$	UI2C_L_89:
;UI2C.ppas,155 :: 		Private_I2C_Master_Restart
$0639	$25F8			CALL	_private_i2c_master_restart
$063A	$2E3C			GOTO	UI2C_L_91
;UI2C.ppas,156 :: 		else
$063B	$	UI2C_L_90:
;UI2C.ppas,157 :: 		Private_I2C_Master_AcquireBusAndStart;
$063B	$24FB			CALL	_private_i2c_master_acquirebusandstart
$063C	$	UI2C_L_91:
;UI2C.ppas,159 :: 		I2C_Master_SendByte(DeviceAddress);
$063C	$084B			MOVF	FARG_I2C_Master_StartWrite, 0
$063D	$00CF			MOVWF	FARG_I2C_Master_SendByte
$063E	$2481			CALL	_i2c_master_sendbyte
$063F	$	UI2C_L_88:
;UI2C.ppas,160 :: 		end;
$063F	$0008			RETURN
$065F	$	_i2c_master_sendcommandwithbyteparameter:
;UI2C.ppas,185 :: 		begin
;UI2C.ppas,186 :: 		I2C_Master_SendByte(Command);
$065F	$1303			BCF	STATUS, RP1
$0660	$1283			BCF	STATUS, RP0
$0661	$084B			MOVF	FARG_I2C_Master_SendCommandWithByteParameter, 0
$0662	$00CF			MOVWF	FARG_I2C_Master_SendByte
$0663	$2481			CALL	_i2c_master_sendbyte
;UI2C.ppas,187 :: 		I2C_Master_SendByte(Parameter);
$0664	$084C			MOVF	FARG_I2C_Master_SendCommandWithByteParameter+1, 0
$0665	$00CF			MOVWF	FARG_I2C_Master_SendByte
$0666	$2481			CALL	_i2c_master_sendbyte
$0667	$	UI2C_L_109:
;UI2C.ppas,188 :: 		end;
$0667	$0008			RETURN
$059A	$	_i2c_master_stop:
;UI2C.ppas,173 :: 		begin
;UI2C.ppas,174 :: 		I2C_Started:=False;
$059A	$1303			BCF	STATUS, RP1
$059B	$1283			BCF	STATUS, RP0
$059C	$01B3			CLRF	_i2c_started, 1
;UI2C.ppas,176 :: 		SSPCON2.PEN:=True;
$059D	$	UI2C_L_97:
$059D	$1683			BSF	STATUS, RP0
$059E	$1511			BSF	SSPCON2, 2
$059F	$	UI2C_L_98:
;UI2C.ppas,177 :: 		while PIR1.SSPIF=False do begin end;
$059F	$	UI2C_L_100:
$059F	$1283			BCF	STATUS, RP0
$05A0	$080C			MOVF	PIR1, 0
$05A1	$00F1			MOVWF	STACK_1
$05A2	$3000			MOVLW	0
$05A3	$19F1			BTFSC	STACK_1, 3
$05A4	$3001			MOVLW	1
$05A5	$00F1			MOVWF	STACK_1
$05A6	$0871			MOVF	STACK_1, 0
$05A7	$3A00			XORLW	0
$05A8	$1903			BTFSC	STATUS, Z
$05A9	$2D9F			GOTO	UI2C_L_100
$05AA	$	UI2C_L_101:
;UI2C.ppas,178 :: 		PIR1.SSPIF:=False;
$05AA	$118C			BCF	PIR1, 3
$05AB	$	UI2C_L_105:
;UI2C.ppas,180 :: 		if I2C_MultiMasterMode then
$05AB	$0834			MOVF	_i2c_multimastermode, 0
$05AC	$1903			BTFSC	STATUS, Z
$05AD	$2DAF			GOTO	UI2C_L_107
$05AE	$	UI2C_L_106:
;UI2C.ppas,181 :: 		I2C_SetSlaveMode;
$05AE	$25E7			CALL	_i2c_setslavemode
$05AF	$	UI2C_L_107:
$05AF	$	UI2C_L_108:
$05AF	$	UI2C_L_96:
;UI2C.ppas,182 :: 		end;
$05AF	$1303			BCF	STATUS, RP1
$05B0	$1683			BSF	STATUS, RP0
$05B1	$0008			RETURN
$0627	$	_i2c_master_startread:
;UI2C.ppas,163 :: 		begin
;UI2C.ppas,164 :: 		if I2C_Started then
$0627	$1303			BCF	STATUS, RP1
$0628	$1283			BCF	STATUS, RP0
$0629	$0833			MOVF	_i2c_started, 0
$062A	$1903			BTFSC	STATUS, Z
$062B	$2E2E			GOTO	UI2C_L_94
$062C	$	UI2C_L_93:
;UI2C.ppas,165 :: 		Private_I2C_Master_Restart
$062C	$25F8			CALL	_private_i2c_master_restart
$062D	$2E2F			GOTO	UI2C_L_95
;UI2C.ppas,166 :: 		else
$062E	$	UI2C_L_94:
;UI2C.ppas,167 :: 		Private_I2C_Master_AcquireBusAndStart;
$062E	$24FB			CALL	_private_i2c_master_acquirebusandstart
$062F	$	UI2C_L_95:
;UI2C.ppas,169 :: 		I2C_Master_SendByte(DeviceAddress or 1);
$062F	$3001			MOVLW	1
$0630	$044B			IORWF	FARG_I2C_Master_StartRead, 0
$0631	$00CF			MOVWF	FARG_I2C_Master_SendByte
$0632	$2481			CALL	_i2c_master_sendbyte
$0633	$	UI2C_L_92:
;UI2C.ppas,170 :: 		end;
$0633	$0008			RETURN
$0457	$	_i2c_master_receivebyte:
;UI2C.ppas,198 :: 		begin
;UI2C.ppas,199 :: 		SSPCON2.RCEN:=True;
$0457	$	UI2C_L_112:
$0457	$1303			BCF	STATUS, RP1
$0458	$1683			BSF	STATUS, RP0
$0459	$1591			BSF	SSPCON2, 3
$045A	$	UI2C_L_113:
;UI2C.ppas,200 :: 		while PIR1.SSPIF=False do begin end;
$045A	$	UI2C_L_115:
$045A	$1283			BCF	STATUS, RP0
$045B	$080C			MOVF	PIR1, 0
$045C	$00F1			MOVWF	STACK_1
$045D	$3000			MOVLW	0
$045E	$19F1			BTFSC	STACK_1, 3
$045F	$3001			MOVLW	1
$0460	$00F1			MOVWF	STACK_1
$0461	$0871			MOVF	STACK_1, 0
$0462	$3A00			XORLW	0
$0463	$1903			BTFSC	STATUS, Z
$0464	$2C5A			GOTO	UI2C_L_115
$0465	$	UI2C_L_116:
;UI2C.ppas,201 :: 		PIR1.SSPIF:=False;
$0465	$118C			BCF	PIR1, 3
$0466	$	UI2C_L_120:
;UI2C.ppas,202 :: 		Result:=SSPBUF;
$0466	$0813			MOVF	SSPBUF, 0
$0467	$00CC			MOVWF	_i2c_master_receivebyte_local_result
;UI2C.ppas,203 :: 		if LastRead then
$0468	$084B			MOVF	FARG_I2C_Master_ReceiveByte, 0
$0469	$1903			BTFSC	STATUS, Z
$046A	$2C6E			GOTO	UI2C_L_122
$046B	$	UI2C_L_121:
;UI2C.ppas,204 :: 		SSPCON2.ACKDT:=1 // Not acknowledge.
$046B	$	UI2C_L_124:
$046B	$1683			BSF	STATUS, RP0
$046C	$1691			BSF	SSPCON2, 5
$046D	$	UI2C_L_125:
$046D	$2C71			GOTO	UI2C_L_123
;UI2C.ppas,205 :: 		else
$046E	$	UI2C_L_122:
;UI2C.ppas,206 :: 		SSPCON2.ACKDT:=0; // Acknowledge.
$046E	$1303			BCF	STATUS, RP1
$046F	$1683			BSF	STATUS, RP0
$0470	$1291			BCF	SSPCON2, 5
$0471	$	UI2C_L_127:
$0471	$	UI2C_L_123:
;UI2C.ppas,207 :: 		SSPCON2.ACKEN:=True;
$0471	$	UI2C_L_128:
$0471	$1611			BSF	SSPCON2, 4
$0472	$	UI2C_L_129:
;UI2C.ppas,208 :: 		while PIR1.SSPIF=False do begin end;
$0472	$	UI2C_L_131:
$0472	$1283			BCF	STATUS, RP0
$0473	$080C			MOVF	PIR1, 0
$0474	$00F1			MOVWF	STACK_1
$0475	$3000			MOVLW	0
$0476	$19F1			BTFSC	STACK_1, 3
$0477	$3001			MOVLW	1
$0478	$00F1			MOVWF	STACK_1
$0479	$0871			MOVF	STACK_1, 0
$047A	$3A00			XORLW	0
$047B	$1903			BTFSC	STATUS, Z
$047C	$2C72			GOTO	UI2C_L_131
$047D	$	UI2C_L_132:
;UI2C.ppas,209 :: 		PIR1.SSPIF:=False;
$047D	$118C			BCF	PIR1, 3
$047E	$	UI2C_L_136:
$047E	$	UI2C_L_111:
;UI2C.ppas,210 :: 		end;
$047E	$084C			MOVF	_i2c_master_receivebyte_local_result, 0
$047F	$00F0			MOVWF	STACK_0
$0480	$0008			RETURN
$0608	$	_displaydecimalword:
;SevenSegmentDisplays.ppas,193 :: 		begin
;SevenSegmentDisplays.ppas,194 :: 		CalculateDecimalDigits(Value,Digits);
$0608	$1303			BCF	STATUS, RP1
$0609	$1283			BCF	STATUS, RP0
$060A	$084B			MOVF	FARG_DisplayDecimalWord, 0
$060B	$00CF			MOVWF	FARG_CalculateDecimalDigits
$060C	$084C			MOVF	FARG_DisplayDecimalWord+1, 0
$060D	$00D0			MOVWF	FARG_CalculateDecimalDigits+1
$060E	$3036			MOVLW	_digits
$060F	$00D1			MOVWF	FARG_CalculateDecimalDigits+2
$0610	$214A			CALL	_calculatedecimaldigits
;SevenSegmentDisplays.ppas,195 :: 		DisplayDigits(DecimalPoint,NumDigits,False);
$0611	$084D			MOVF	FARG_DisplayDecimalWord+2, 0
$0612	$00CF			MOVWF	FARG_DisplayDigits
$0613	$084E			MOVF	FARG_DisplayDecimalWord+3, 0
$0614	$00D0			MOVWF	FARG_DisplayDigits+1
$0615	$01D1			CLRF	FARG_DisplayDigits+2, 1
$0616	$2383			CALL	_displaydigits
$0617	$	SevenSegmentDisplays_L_109:
;SevenSegmentDisplays.ppas,196 :: 		end;
$0617	$0008			RETURN
$0234	$	_calculatehexadecimaldigits:
;SevenSegmentDisplays.ppas,199 :: 		begin
;SevenSegmentDisplays.ppas,200 :: 		Digits[0]:=Value and $F;
$0234	$300F			MOVLW	15
$0235	$1303			BCF	STATUS, RP1
$0236	$1283			BCF	STATUS, RP0
$0237	$054B			ANDWF	FARG_CalculateHexadecimalDigits, 0
$0238	$00F0			MOVWF	STACK_0
$0239	$084C			MOVF	FARG_CalculateHexadecimalDigits+1, 0
$023A	$00F1			MOVWF	STACK_0+1
$023B	$3000			MOVLW	0
$023C	$05F1			ANDWF	STACK_0+1, 1
$023D	$084D			MOVF	FARG_CalculateHexadecimalDigits+2, 0
$023E	$0084			MOVWF	FSR
$023F	$084D			MOVF	FARG_CalculateHexadecimalDigits+2, 0
$0240	$0084			MOVWF	FSR
$0241	$0870			MOVF	STACK_0, 0
$0242	$0080			MOVWF	INDF
;SevenSegmentDisplays.ppas,201 :: 		Value:=Value shr 4;
$0243	$084B			MOVF	FARG_CalculateHexadecimalDigits, 0
$0244	$00F0			MOVWF	STACK_0
$0245	$084C			MOVF	FARG_CalculateHexadecimalDigits+1, 0
$0246	$00F1			MOVWF	STACK_0+1
$0247	$0CF1			RRF	STACK_0+1, 1
$0248	$0CF0			RRF	STACK_0, 1
$0249	$13F1			BCF	STACK_0+1, 7
$024A	$0CF1			RRF	STACK_0+1, 1
$024B	$0CF0			RRF	STACK_0, 1
$024C	$13F1			BCF	STACK_0+1, 7
$024D	$0CF1			RRF	STACK_0+1, 1
$024E	$0CF0			RRF	STACK_0, 1
$024F	$13F1			BCF	STACK_0+1, 7
$0250	$0CF1			RRF	STACK_0+1, 1
$0251	$0CF0			RRF	STACK_0, 1
$0252	$13F1			BCF	STACK_0+1, 7
$0253	$0870			MOVF	STACK_0, 0
$0254	$00CB			MOVWF	FARG_CalculateHexadecimalDigits
$0255	$0871			MOVF	STACK_0+1, 0
$0256	$00CC			MOVWF	FARG_CalculateHexadecimalDigits+1
;SevenSegmentDisplays.ppas,202 :: 		Digits[1]:=Value and $F;
$0257	$0A4D			INCF	FARG_CalculateHexadecimalDigits+2, 0
$0258	$00F2			MOVWF	STACK_2
$0259	$300F			MOVLW	15
$025A	$05F0			ANDWF	STACK_0, 1
$025B	$3000			MOVLW	0
$025C	$05F1			ANDWF	STACK_0+1, 1
$025D	$0872			MOVF	STACK_2, 0
$025E	$0084			MOVWF	FSR
$025F	$0872			MOVF	STACK_2, 0
$0260	$0084			MOVWF	FSR
$0261	$0870			MOVF	STACK_0, 0
$0262	$0080			MOVWF	INDF
;SevenSegmentDisplays.ppas,203 :: 		Value:=Value shr 4;
$0263	$084B			MOVF	FARG_CalculateHexadecimalDigits, 0
$0264	$00F0			MOVWF	STACK_0
$0265	$084C			MOVF	FARG_CalculateHexadecimalDigits+1, 0
$0266	$00F1			MOVWF	STACK_0+1
$0267	$0CF1			RRF	STACK_0+1, 1
$0268	$0CF0			RRF	STACK_0, 1
$0269	$13F1			BCF	STACK_0+1, 7
$026A	$0CF1			RRF	STACK_0+1, 1
$026B	$0CF0			RRF	STACK_0, 1
$026C	$13F1			BCF	STACK_0+1, 7
$026D	$0CF1			RRF	STACK_0+1, 1
$026E	$0CF0			RRF	STACK_0, 1
$026F	$13F1			BCF	STACK_0+1, 7
$0270	$0CF1			RRF	STACK_0+1, 1
$0271	$0CF0			RRF	STACK_0, 1
$0272	$13F1			BCF	STACK_0+1, 7
$0273	$0870			MOVF	STACK_0, 0
$0274	$00CB			MOVWF	FARG_CalculateHexadecimalDigits
$0275	$0871			MOVF	STACK_0+1, 0
$0276	$00CC			MOVWF	FARG_CalculateHexadecimalDigits+1
;SevenSegmentDisplays.ppas,204 :: 		Digits[2]:=Value and $F;
$0277	$3002			MOVLW	2
$0278	$074D			ADDWF	FARG_CalculateHexadecimalDigits+2, 0
$0279	$00F2			MOVWF	STACK_2
$027A	$300F			MOVLW	15
$027B	$05F0			ANDWF	STACK_0, 1
$027C	$3000			MOVLW	0
$027D	$05F1			ANDWF	STACK_0+1, 1
$027E	$0872			MOVF	STACK_2, 0
$027F	$0084			MOVWF	FSR
$0280	$0872			MOVF	STACK_2, 0
$0281	$0084			MOVWF	FSR
$0282	$0870			MOVF	STACK_0, 0
$0283	$0080			MOVWF	INDF
;SevenSegmentDisplays.ppas,205 :: 		Value:=Value shr 4;
$0284	$084B			MOVF	FARG_CalculateHexadecimalDigits, 0
$0285	$00F0			MOVWF	STACK_0
$0286	$084C			MOVF	FARG_CalculateHexadecimalDigits+1, 0
$0287	$00F1			MOVWF	STACK_0+1
$0288	$0CF1			RRF	STACK_0+1, 1
$0289	$0CF0			RRF	STACK_0, 1
$028A	$13F1			BCF	STACK_0+1, 7
$028B	$0CF1			RRF	STACK_0+1, 1
$028C	$0CF0			RRF	STACK_0, 1
$028D	$13F1			BCF	STACK_0+1, 7
$028E	$0CF1			RRF	STACK_0+1, 1
$028F	$0CF0			RRF	STACK_0, 1
$0290	$13F1			BCF	STACK_0+1, 7
$0291	$0CF1			RRF	STACK_0+1, 1
$0292	$0CF0			RRF	STACK_0, 1
$0293	$13F1			BCF	STACK_0+1, 7
$0294	$0870			MOVF	STACK_0, 0
$0295	$00CB			MOVWF	FARG_CalculateHexadecimalDigits
$0296	$0871			MOVF	STACK_0+1, 0
$0297	$00CC			MOVWF	FARG_CalculateHexadecimalDigits+1
;SevenSegmentDisplays.ppas,206 :: 		Digits[3]:=Value and $F;
$0298	$3003			MOVLW	3
$0299	$074D			ADDWF	FARG_CalculateHexadecimalDigits+2, 0
$029A	$00F2			MOVWF	STACK_2
$029B	$300F			MOVLW	15
$029C	$05F0			ANDWF	STACK_0, 1
$029D	$3000			MOVLW	0
$029E	$05F1			ANDWF	STACK_0+1, 1
$029F	$0872			MOVF	STACK_2, 0
$02A0	$0084			MOVWF	FSR
$02A1	$0872			MOVF	STACK_2, 0
$02A2	$0084			MOVWF	FSR
$02A3	$0870			MOVF	STACK_0, 0
$02A4	$0080			MOVWF	INDF
$02A5	$	SevenSegmentDisplays_L_110:
;SevenSegmentDisplays.ppas,207 :: 		end;
$02A5	$0008			RETURN
$04AA	$	_initialize:
;SevenSegmentDisplays.ppas,370 :: 		begin
;SevenSegmentDisplays.ppas,371 :: 		OPTION_REG:=$D2; // Timer 0 prescaler.
$04AA	$30D2			MOVLW	210
$04AB	$1303			BCF	STATUS, RP1
$04AC	$1683			BSF	STATUS, RP0
$04AD	$0081			MOVWF	OPTION_REG
;SevenSegmentDisplays.ppas,374 :: 		ADCON0:=$C1;
$04AE	$30C1			MOVLW	193
$04AF	$1283			BCF	STATUS, RP0
$04B0	$009F			MOVWF	ADCON0
;SevenSegmentDisplays.ppas,375 :: 		ADCON1:=$8E;
$04B1	$308E			MOVLW	142
$04B2	$1683			BSF	STATUS, RP0
$04B3	$009F			MOVWF	ADCON1
;SevenSegmentDisplays.ppas,377 :: 		TRISA:=%11011111; // Bit 5 is for fourth digit of display.
$04B4	$30DF			MOVLW	223
$04B5	$0085			MOVWF	TRISA
;SevenSegmentDisplays.ppas,379 :: 		TRISB:=$00;
$04B6	$0186			CLRF	TRISB, 1
;SevenSegmentDisplays.ppas,380 :: 		PORTB:=$00;
$04B7	$1283			BCF	STATUS, RP0
$04B8	$0186			CLRF	PORTB, 1
;SevenSegmentDisplays.ppas,382 :: 		TRISC:=$18;
$04B9	$3018			MOVLW	24
$04BA	$1683			BSF	STATUS, RP0
$04BB	$0087			MOVWF	TRISC
;SevenSegmentDisplays.ppas,383 :: 		PORTC:=$E0; // Start with full colour LEDs off (outputs high).
$04BC	$30E0			MOVLW	224
$04BD	$1283			BCF	STATUS, RP0
$04BE	$0087			MOVWF	PORTC
;SevenSegmentDisplays.ppas,385 :: 		DimDisplay:=False;
$04BF	$01A4			CLRF	_dimdisplay, 1
;SevenSegmentDisplays.ppas,387 :: 		DisplayMask:=$01;
$04C0	$3001			MOVLW	1
$04C1	$00A6			MOVWF	_displaymask
;SevenSegmentDisplays.ppas,389 :: 		DigitMasks[0]:=0;
$04C2	$01A7			CLRF	_digitmasks+0, 1
;SevenSegmentDisplays.ppas,390 :: 		DigitMasks[1]:=0;
$04C3	$01A8			CLRF	_digitmasks+1, 1
;SevenSegmentDisplays.ppas,391 :: 		DigitMasks[2]:=0;
$04C4	$01A9			CLRF	_digitmasks+2, 1
;SevenSegmentDisplays.ppas,392 :: 		DigitMasks[3]:=0;
$04C5	$01AA			CLRF	_digitmasks+3, 1
;SevenSegmentDisplays.ppas,394 :: 		SevenSegmentDisplayCount:=0;
$04C6	$01A5			CLRF	_sevensegmentdisplaycount, 1
;SevenSegmentDisplays.ppas,395 :: 		FullColourLEDDisplayCount:=0;
$04C7	$01AB			CLRF	_fullcolourleddisplaycount, 1
;SevenSegmentDisplays.ppas,397 :: 		RedLEDDrive:=$00;
$04C8	$01AC			CLRF	_redleddrive, 1
;SevenSegmentDisplays.ppas,398 :: 		GreenLEDDrive:=$00;
$04C9	$01AD			CLRF	_greenleddrive, 1
;SevenSegmentDisplays.ppas,399 :: 		BlueLEDDrive:=$00;
$04CA	$01AE			CLRF	_blueleddrive, 1
;SevenSegmentDisplays.ppas,401 :: 		I2C_Initialize($28,True);
$04CB	$3028			MOVLW	40
$04CC	$00CB			MOVWF	FARG_I2C_Initialize
$04CD	$30FF			MOVLW	255
$04CE	$00CC			MOVWF	FARG_I2C_Initialize+1
$04CF	$2618			CALL	_i2c_initialize
;SevenSegmentDisplays.ppas,403 :: 		INTCON:=$E0;
$04D0	$30E0			MOVLW	224
$04D1	$008B			MOVWF	INTCON
$04D2	$	SevenSegmentDisplays_L_170:
;SevenSegmentDisplays.ppas,404 :: 		end;
$04D2	$0008			RETURN
$064B	$	_showhappyface:
;SevenSegmentDisplays.ppas,216 :: 		begin
;SevenSegmentDisplays.ppas,217 :: 		DigitMasks[0]:=$63;
$064B	$3063			MOVLW	99
$064C	$1303			BCF	STATUS, RP1
$064D	$1283			BCF	STATUS, RP0
$064E	$00A7			MOVWF	_digitmasks+0
;SevenSegmentDisplays.ppas,218 :: 		DigitMasks[1]:=$1C;
$064F	$301C			MOVLW	28
$0650	$00A8			MOVWF	_digitmasks+1
;SevenSegmentDisplays.ppas,219 :: 		DigitMasks[2]:=$63;
$0651	$3063			MOVLW	99
$0652	$00A9			MOVWF	_digitmasks+2
;SevenSegmentDisplays.ppas,220 :: 		DigitMasks[3]:=$00;
$0653	$01AA			CLRF	_digitmasks+3, 1
$0654	$	SevenSegmentDisplays_L_112:
;SevenSegmentDisplays.ppas,221 :: 		end;
$0654	$0008			RETURN
$00D2	$	_dovoltmeter:
;SevenSegmentDisplays.ppas,227 :: 		begin
;SevenSegmentDisplays.ppas,229 :: 		SetBit(ADCON0,Go);
$00D2	$1303			BCF	STATUS, RP1
$00D3	$1283			BCF	STATUS, RP0
$00D4	$151F			BSF	ADCON0, 2
;SevenSegmentDisplays.ppas,232 :: 		while ADCON0.Go do begin end;
$00D5	$	SevenSegmentDisplays_L_115:
$00D5	$081F			MOVF	ADCON0, 0
$00D6	$00F2			MOVWF	STACK_2
$00D7	$3000			MOVLW	0
$00D8	$1972			BTFSC	STACK_2, 2
$00D9	$3001			MOVLW	1
$00DA	$00F2			MOVWF	STACK_2
$00DB	$0872			MOVF	STACK_2, 0
$00DC	$1D03			BTFSS	STATUS, Z
$00DD	$28D5			GOTO	SevenSegmentDisplays_L_115
$00DE	$	SevenSegmentDisplays_L_116:
;SevenSegmentDisplays.ppas,235 :: 		ADCResult:=ADRESL+(ADRESH shl 8);
$00DE	$081E			MOVF	ADRESH, 0
$00DF	$00F2			MOVWF	STACK_2
$00E0	$01F3			CLRF	STACK_2+1
$00E1	$0872			MOVF	STACK_2, 0
$00E2	$00F3			MOVWF	STACK_2+1
$00E3	$01F2			CLRF	STACK_2
$00E4	$1683			BSF	STATUS, RP0
$00E5	$081E			MOVF	ADRESL, 0
$00E6	$1283			BCF	STATUS, RP0
$00E7	$00F0			MOVWF	STACK_0
$00E8	$01F1			CLRF	STACK_0+1
$00E9	$0870			MOVF	STACK_0, 0
$00EA	$07F2			ADDWF	STACK_2, 1
$00EB	$0871			MOVF	STACK_0+1, 0
$00EC	$1803			BTFSC	STATUS, C
$00ED	$3F01			ADDLW	1
$00EE	$07F3			ADDWF	STACK_2+1, 1
$00EF	$0872			MOVF	STACK_2, 0
$00F0	$00C8			MOVWF	_dovoltmeter_local_adcresult
$00F1	$0873			MOVF	STACK_2+1, 0
$00F2	$00C9			MOVWF	_dovoltmeter_local_adcresult+1
;SevenSegmentDisplays.ppas,238 :: 		if ADCResult=1023 then
$00F3	$0873			MOVF	STACK_2+1, 0
$00F4	$3A03			XORLW	3
$00F5	$1D03			BTFSS	STATUS, Z
$00F6	$28F9			GOTO	L_DoVoltMeter_3
$00F7	$30FF			MOVLW	255
$00F8	$0672			XORWF	STACK_2, 0
$00F9	$	L_DoVoltMeter_3:
$00F9	$1D03			BTFSS	STATUS, Z
$00FA	$2931			GOTO	SevenSegmentDisplays_L_120
$00FB	$	SevenSegmentDisplays_L_119:
;SevenSegmentDisplays.ppas,241 :: 		DigitMasks[3]:=$00;
$00FB	$01AA			CLRF	_digitmasks+3, 1
;SevenSegmentDisplays.ppas,242 :: 		DigitMasks[2]:=$3F; // 'O'
$00FC	$303F			MOVLW	63
$00FD	$00A9			MOVWF	_digitmasks+2
;SevenSegmentDisplays.ppas,243 :: 		DigitMasks[1]:=$3E; // 'V'
$00FE	$303E			MOVLW	62
$00FF	$00A8			MOVWF	_digitmasks+1
;SevenSegmentDisplays.ppas,244 :: 		DigitMasks[0]:=$38; // 'L'
$0100	$3038			MOVLW	56
$0101	$00A7			MOVWF	_digitmasks+0
;SevenSegmentDisplays.ppas,246 :: 		RedLEDDrive:=39;
$0102	$3027			MOVLW	39
$0103	$00AC			MOVWF	_redleddrive
;SevenSegmentDisplays.ppas,247 :: 		GreenLEDDrive:=39;
$0104	$3027			MOVLW	39
$0105	$00AD			MOVWF	_greenleddrive
;SevenSegmentDisplays.ppas,248 :: 		BlueLEDDrive:=39;
$0106	$3027			MOVLW	39
$0107	$00AE			MOVWF	_blueleddrive
;SevenSegmentDisplays.ppas,250 :: 		I2C_Master_StartWrite($20);
$0108	$3020			MOVLW	32
$0109	$00CB			MOVWF	FARG_I2C_Master_StartWrite
$010A	$2634			CALL	_i2c_master_startwrite
;SevenSegmentDisplays.ppas,251 :: 		I2C_Master_SendCommandWithByteParameter($00,15);
$010B	$01CB			CLRF	FARG_I2C_Master_SendCommandWithByteParameter, 1
$010C	$300F			MOVLW	15
$010D	$00CC			MOVWF	FARG_I2C_Master_SendCommandWithByteParameter+1
$010E	$265F			CALL	_i2c_master_sendcommandwithbyteparameter
;SevenSegmentDisplays.ppas,252 :: 		I2C_Master_Stop;
$010F	$259A			CALL	_i2c_master_stop
;SevenSegmentDisplays.ppas,254 :: 		DelayMS(3); // Wait for slow interrupt handler in keypad controller.
$0110	$3003			MOVLW	3
$0111	$1283			BCF	STATUS, RP0
$0112	$00D4			MOVWF	FARG_DelayMS
$0113	$01D5			CLRF	FARG_DelayMS+1
$0114	$2543			CALL	_delayms
;SevenSegmentDisplays.ppas,257 :: 		repeat
$0115	$	SevenSegmentDisplays_L_122:
;SevenSegmentDisplays.ppas,258 :: 		I2C_Master_StartWrite($20);
$0115	$3020			MOVLW	32
$0116	$00CB			MOVWF	FARG_I2C_Master_StartWrite
$0117	$2634			CALL	_i2c_master_startwrite
;SevenSegmentDisplays.ppas,259 :: 		I2C_Master_SendByte($01);
$0118	$3001			MOVLW	1
$0119	$00CF			MOVWF	FARG_I2C_Master_SendByte
$011A	$2481			CALL	_i2c_master_sendbyte
;SevenSegmentDisplays.ppas,260 :: 		I2C_Master_StartRead($20);
$011B	$3020			MOVLW	32
$011C	$00CB			MOVWF	FARG_I2C_Master_StartRead
$011D	$2627			CALL	_i2c_master_startread
;SevenSegmentDisplays.ppas,261 :: 		SpeechBusy:=I2C_Master_ReceiveByte(True);
$011E	$30FF			MOVLW	255
$011F	$00CB			MOVWF	FARG_I2C_Master_ReceiveByte
$0120	$2457			CALL	_i2c_master_receivebyte
$0121	$0870			MOVF	STACK_0, 0
$0122	$00CA			MOVWF	_dovoltmeter_local_speechbusy
;SevenSegmentDisplays.ppas,262 :: 		I2C_Master_Stop;
$0123	$259A			CALL	_i2c_master_stop
;SevenSegmentDisplays.ppas,263 :: 		until (SpeechBusy=False);
$0124	$	SevenSegmentDisplays_L_123:
$0124	$1283			BCF	STATUS, RP0
$0125	$084A			MOVF	_dovoltmeter_local_speechbusy, 0
$0126	$3A00			XORLW	0
$0127	$1D03			BTFSS	STATUS, Z
$0128	$292A			GOTO	SevenSegmentDisplays_L_125
$0129	$	SevenSegmentDisplays_L_126:
$0129	$292B			GOTO	SevenSegmentDisplays_L_124
$012A	$	SevenSegmentDisplays_L_125:
$012A	$2915			GOTO	SevenSegmentDisplays_L_122
$012B	$	SevenSegmentDisplays_L_124:
;SevenSegmentDisplays.ppas,265 :: 		DelayMS(500); // Gap between repeated messages.
$012B	$30F4			MOVLW	244
$012C	$00D4			MOVWF	FARG_DelayMS
$012D	$3001			MOVLW	1
$012E	$00D5			MOVWF	FARG_DelayMS+1
$012F	$2543			CALL	_delayms
;SevenSegmentDisplays.ppas,266 :: 		end
$0130	$2949			GOTO	SevenSegmentDisplays_L_121
;SevenSegmentDisplays.ppas,267 :: 		else
$0131	$	SevenSegmentDisplays_L_120:
;SevenSegmentDisplays.ppas,270 :: 		ADCResult:=ADCResult shr 1;
$0131	$0848			MOVF	_dovoltmeter_local_adcresult, 0
$0132	$00F0			MOVWF	STACK_0
$0133	$0849			MOVF	_dovoltmeter_local_adcresult+1, 0
$0134	$00F1			MOVWF	STACK_0+1
$0135	$0CF1			RRF	STACK_0+1, 1
$0136	$0CF0			RRF	STACK_0, 1
$0137	$13F1			BCF	STACK_0+1, 7
$0138	$0870			MOVF	STACK_0, 0
$0139	$00C8			MOVWF	_dovoltmeter_local_adcresult
$013A	$0871			MOVF	STACK_0+1, 0
$013B	$00C9			MOVWF	_dovoltmeter_local_adcresult+1
;SevenSegmentDisplays.ppas,272 :: 		DisplayDecimalWord(ADCResult,2,4);
$013C	$0870			MOVF	STACK_0, 0
$013D	$00CB			MOVWF	FARG_DisplayDecimalWord
$013E	$0871			MOVF	STACK_0+1, 0
$013F	$00CC			MOVWF	FARG_DisplayDecimalWord+1
$0140	$3002			MOVLW	2
$0141	$00CD			MOVWF	FARG_DisplayDecimalWord+2
$0142	$3004			MOVLW	4
$0143	$00CE			MOVWF	FARG_DisplayDecimalWord+3
$0144	$2608			CALL	_displaydecimalword
;SevenSegmentDisplays.ppas,274 :: 		DelayMS(100); // Reduce flickering.
$0145	$3064			MOVLW	100
$0146	$00D4			MOVWF	FARG_DelayMS
$0147	$01D5			CLRF	FARG_DelayMS+1
$0148	$2543			CALL	_delayms
;SevenSegmentDisplays.ppas,275 :: 		end;
$0149	$	SevenSegmentDisplays_L_121:
$0149	$	SevenSegmentDisplays_L_113:
;SevenSegmentDisplays.ppas,276 :: 		end;
$0149	$0008			RETURN
$03DA	$	_docounter:
;SevenSegmentDisplays.ppas,343 :: 		begin
;SevenSegmentDisplays.ppas,344 :: 		DisplayDecimalWord(CounterValue,-1,3);
$03DA	$1303			BCF	STATUS, RP1
$03DB	$1283			BCF	STATUS, RP0
$03DC	$083A			MOVF	_countervalue, 0
$03DD	$00CB			MOVWF	FARG_DisplayDecimalWord
$03DE	$083B			MOVF	_countervalue+1, 0
$03DF	$00CC			MOVWF	FARG_DisplayDecimalWord+1
$03E0	$30FF			MOVLW	255
$03E1	$00CD			MOVWF	FARG_DisplayDecimalWord+2
$03E2	$3003			MOVLW	3
$03E3	$00CE			MOVWF	FARG_DisplayDecimalWord+3
$03E4	$2608			CALL	_displaydecimalword
;SevenSegmentDisplays.ppas,347 :: 		if Mode.2 then
$03E5	$3000			MOVLW	0
$03E6	$193C			BTFSC	_mode, 2
$03E7	$3001			MOVLW	1
$03E8	$00F1			MOVWF	STACK_1
$03E9	$0871			MOVF	STACK_1, 0
$03EA	$1903			BTFSC	STATUS, Z
$03EB	$2BF1			GOTO	SevenSegmentDisplays_L_159
$03EC	$	SevenSegmentDisplays_L_158:
;SevenSegmentDisplays.ppas,348 :: 		DelayMS(10)
$03EC	$300A			MOVLW	10
$03ED	$00D4			MOVWF	FARG_DelayMS
$03EE	$01D5			CLRF	FARG_DelayMS+1
$03EF	$2543			CALL	_delayms
$03F0	$2BF5			GOTO	SevenSegmentDisplays_L_160
;SevenSegmentDisplays.ppas,349 :: 		else
$03F1	$	SevenSegmentDisplays_L_159:
;SevenSegmentDisplays.ppas,350 :: 		DelayMS(200);
$03F1	$30C8			MOVLW	200
$03F2	$00D4			MOVWF	FARG_DelayMS
$03F3	$01D5			CLRF	FARG_DelayMS+1
$03F4	$2543			CALL	_delayms
$03F5	$	SevenSegmentDisplays_L_160:
;SevenSegmentDisplays.ppas,353 :: 		if Mode.1 then
$03F5	$3000			MOVLW	0
$03F6	$18BC			BTFSC	_mode, 1
$03F7	$3001			MOVLW	1
$03F8	$00F1			MOVWF	STACK_1
$03F9	$0871			MOVF	STACK_1, 0
$03FA	$1903			BTFSC	STATUS, Z
$03FB	$2C0B			GOTO	SevenSegmentDisplays_L_162
$03FC	$	SevenSegmentDisplays_L_161:
;SevenSegmentDisplays.ppas,355 :: 		if CounterValue=999 then
$03FC	$083B			MOVF	_countervalue+1, 0
$03FD	$3A03			XORLW	3
$03FE	$1D03			BTFSS	STATUS, Z
$03FF	$2C02			GOTO	L_DoCounter_4
$0400	$30E7			MOVLW	231
$0401	$063A			XORWF	_countervalue, 0
$0402	$	L_DoCounter_4:
$0402	$1D03			BTFSS	STATUS, Z
$0403	$2C07			GOTO	SevenSegmentDisplays_L_165
$0404	$	SevenSegmentDisplays_L_164:
;SevenSegmentDisplays.ppas,356 :: 		CounterValue:=0
$0404	$01BA			CLRF	_countervalue
$0405	$01BB			CLRF	_countervalue+1
$0406	$2C0A			GOTO	SevenSegmentDisplays_L_166
;SevenSegmentDisplays.ppas,357 :: 		else
$0407	$	SevenSegmentDisplays_L_165:
;SevenSegmentDisplays.ppas,358 :: 		Inc(CounterValue);
$0407	$0ABA			INCF	_countervalue, 1
$0408	$1903			BTFSC	STATUS, Z
$0409	$0ABB			INCF	_countervalue+1, 1
$040A	$	SevenSegmentDisplays_L_166:
;SevenSegmentDisplays.ppas,359 :: 		end
$040A	$2C1C			GOTO	SevenSegmentDisplays_L_163
;SevenSegmentDisplays.ppas,360 :: 		else
$040B	$	SevenSegmentDisplays_L_162:
;SevenSegmentDisplays.ppas,362 :: 		if CounterValue=0 then
$040B	$3000			MOVLW	0
$040C	$063B			XORWF	_countervalue+1, 0
$040D	$1D03			BTFSS	STATUS, Z
$040E	$2C11			GOTO	L_DoCounter_5
$040F	$3000			MOVLW	0
$0410	$063A			XORWF	_countervalue, 0
$0411	$	L_DoCounter_5:
$0411	$1D03			BTFSS	STATUS, Z
$0412	$2C18			GOTO	SevenSegmentDisplays_L_168
$0413	$	SevenSegmentDisplays_L_167:
;SevenSegmentDisplays.ppas,363 :: 		CounterValue:=999
$0413	$30E7			MOVLW	231
$0414	$00BA			MOVWF	_countervalue
$0415	$3003			MOVLW	3
$0416	$00BB			MOVWF	_countervalue+1
$0417	$2C1C			GOTO	SevenSegmentDisplays_L_169
;SevenSegmentDisplays.ppas,364 :: 		else
$0418	$	SevenSegmentDisplays_L_168:
;SevenSegmentDisplays.ppas,365 :: 		Dec(CounterValue);
$0418	$3001			MOVLW	1
$0419	$02BA			SUBWF	_countervalue, 1
$041A	$1C03			BTFSS	STATUS, C
$041B	$03BB			DECF	_countervalue+1, 1
$041C	$	SevenSegmentDisplays_L_169:
;SevenSegmentDisplays.ppas,366 :: 		end;
$041C	$	SevenSegmentDisplays_L_163:
$041C	$	SevenSegmentDisplays_L_157:
;SevenSegmentDisplays.ppas,367 :: 		end;
$041C	$0008			RETURN
$01C1	$	_dolightball:
;SevenSegmentDisplays.ppas,279 :: 		begin
;SevenSegmentDisplays.ppas,281 :: 		0:
$01C1	$	SevenSegmentDisplays_L_130:
$01C1	$1303			BCF	STATUS, RP1
$01C2	$1283			BCF	STATUS, RP0
$01C3	$083D			MOVF	_lightballphase, 0
$01C4	$3A00			XORLW	0
$01C5	$1D03			BTFSS	STATUS, Z
$01C6	$29CA			GOTO	SevenSegmentDisplays_L_131
$01C7	$	SevenSegmentDisplays_L_129:
;SevenSegmentDisplays.ppas,283 :: 		Dec(RedLEDDrive);
$01C7	$03AC			DECF	_redleddrive, 1
;SevenSegmentDisplays.ppas,284 :: 		Inc(BlueLEDDrive);
$01C8	$0AAE			INCF	_blueleddrive, 1
;SevenSegmentDisplays.ppas,285 :: 		end;
$01C9	$29D8			GOTO	SevenSegmentDisplays_L_128
$01CA	$	SevenSegmentDisplays_L_131:
;SevenSegmentDisplays.ppas,287 :: 		1:
$01CA	$	SevenSegmentDisplays_L_133:
$01CA	$083D			MOVF	_lightballphase, 0
$01CB	$3A01			XORLW	1
$01CC	$1D03			BTFSS	STATUS, Z
$01CD	$29D1			GOTO	SevenSegmentDisplays_L_134
$01CE	$	SevenSegmentDisplays_L_132:
;SevenSegmentDisplays.ppas,289 :: 		Dec(BlueLEDDrive);
$01CE	$03AE			DECF	_blueleddrive, 1
;SevenSegmentDisplays.ppas,290 :: 		Inc(GreenLEDDrive);
$01CF	$0AAD			INCF	_greenleddrive, 1
;SevenSegmentDisplays.ppas,291 :: 		end;
$01D0	$29D8			GOTO	SevenSegmentDisplays_L_128
$01D1	$	SevenSegmentDisplays_L_134:
;SevenSegmentDisplays.ppas,293 :: 		2:
$01D1	$	SevenSegmentDisplays_L_136:
$01D1	$083D			MOVF	_lightballphase, 0
$01D2	$3A02			XORLW	2
$01D3	$1D03			BTFSS	STATUS, Z
$01D4	$29D8			GOTO	SevenSegmentDisplays_L_137
$01D5	$	SevenSegmentDisplays_L_135:
;SevenSegmentDisplays.ppas,295 :: 		Dec(GreenLEDDrive);
$01D5	$03AD			DECF	_greenleddrive, 1
;SevenSegmentDisplays.ppas,296 :: 		Inc(RedLEDDrive);
$01D6	$0AAC			INCF	_redleddrive, 1
;SevenSegmentDisplays.ppas,297 :: 		end;
$01D7	$29D8			GOTO	SevenSegmentDisplays_L_128
$01D8	$	SevenSegmentDisplays_L_137:
$01D8	$	SevenSegmentDisplays_L_128:
;SevenSegmentDisplays.ppas,300 :: 		Digits[0]:=RedLEDDrive shr 2;
$01D8	$082C			MOVF	_redleddrive, 0
$01D9	$00F2			MOVWF	STACK_2
$01DA	$0CF2			RRF	STACK_2, 1
$01DB	$13F2			BCF	STACK_2, 7
$01DC	$0CF2			RRF	STACK_2, 1
$01DD	$13F2			BCF	STACK_2, 7
$01DE	$0872			MOVF	STACK_2, 0
$01DF	$00B6			MOVWF	_digits+0
;SevenSegmentDisplays.ppas,301 :: 		Digits[1]:=GreenLEDDrive shr 2;
$01E0	$082D			MOVF	_greenleddrive, 0
$01E1	$00B7			MOVWF	_digits+1
$01E2	$0CB7			RRF	_digits+1, 1
$01E3	$13B7			BCF	_digits+1, 7
$01E4	$0CB7			RRF	_digits+1, 1
$01E5	$13B7			BCF	_digits+1, 7
;SevenSegmentDisplays.ppas,302 :: 		Digits[2]:=BlueLEDDrive shr 2;
$01E6	$082E			MOVF	_blueleddrive, 0
$01E7	$00B8			MOVWF	_digits+2
$01E8	$0CB8			RRF	_digits+2, 1
$01E9	$13B8			BCF	_digits+2, 7
$01EA	$0CB8			RRF	_digits+2, 1
$01EB	$13B8			BCF	_digits+2, 7
;SevenSegmentDisplays.ppas,303 :: 		Digits[3]:=0;
$01EC	$01B9			CLRF	_digits+3, 1
;SevenSegmentDisplays.ppas,305 :: 		DigitMasks[0]:=CalculateDigitMask(Digits[0],False);
$01ED	$0872			MOVF	STACK_2, 0
$01EE	$00D4			MOVWF	FARG_CalculateDigitMask
$01EF	$01D5			CLRF	FARG_CalculateDigitMask+1, 1
$01F0	$241D			CALL	_calculatedigitmask
$01F1	$0870			MOVF	STACK_0, 0
$01F2	$00A7			MOVWF	_digitmasks+0
;SevenSegmentDisplays.ppas,306 :: 		DigitMasks[1]:=CalculateDigitMask(Digits[1],False);
$01F3	$0837			MOVF	_digits+1, 0
$01F4	$00D4			MOVWF	FARG_CalculateDigitMask
$01F5	$01D5			CLRF	FARG_CalculateDigitMask+1, 1
$01F6	$241D			CALL	_calculatedigitmask
$01F7	$0870			MOVF	STACK_0, 0
$01F8	$00A8			MOVWF	_digitmasks+1
;SevenSegmentDisplays.ppas,307 :: 		DigitMasks[2]:=CalculateDigitMask(Digits[2],False);
$01F9	$0838			MOVF	_digits+2, 0
$01FA	$00D4			MOVWF	FARG_CalculateDigitMask
$01FB	$01D5			CLRF	FARG_CalculateDigitMask+1, 1
$01FC	$241D			CALL	_calculatedigitmask
$01FD	$0870			MOVF	STACK_0, 0
$01FE	$00A9			MOVWF	_digitmasks+2
;SevenSegmentDisplays.ppas,308 :: 		DigitMasks[3]:=$00;
$01FF	$01AA			CLRF	_digitmasks+3, 1
;SevenSegmentDisplays.ppas,310 :: 		DelayMS(200);
$0200	$30C8			MOVLW	200
$0201	$00D4			MOVWF	FARG_DelayMS
$0202	$01D5			CLRF	FARG_DelayMS+1
$0203	$2543			CALL	_delayms
;SevenSegmentDisplays.ppas,313 :: 		0:
$0204	$	SevenSegmentDisplays_L_140:
$0204	$083D			MOVF	_lightballphase, 0
$0205	$3A00			XORLW	0
$0206	$1D03			BTFSS	STATUS, Z
$0207	$2A14			GOTO	SevenSegmentDisplays_L_141
$0208	$	SevenSegmentDisplays_L_139:
;SevenSegmentDisplays.ppas,315 :: 		if BlueLEDDrive=39 then
$0208	$082E			MOVF	_blueleddrive, 0
$0209	$3A27			XORLW	39
$020A	$1D03			BTFSS	STATUS, Z
$020B	$2A13			GOTO	SevenSegmentDisplays_L_143
$020C	$	SevenSegmentDisplays_L_142:
;SevenSegmentDisplays.ppas,317 :: 		LightBallPhase:=1;
$020C	$3001			MOVLW	1
$020D	$00BD			MOVWF	_lightballphase
;SevenSegmentDisplays.ppas,318 :: 		DelayMS(1000);
$020E	$30E8			MOVLW	232
$020F	$00D4			MOVWF	FARG_DelayMS
$0210	$3003			MOVLW	3
$0211	$00D5			MOVWF	FARG_DelayMS+1
$0212	$2543			CALL	_delayms
;SevenSegmentDisplays.ppas,319 :: 		end;
$0213	$	SevenSegmentDisplays_L_143:
$0213	$	SevenSegmentDisplays_L_144:
;SevenSegmentDisplays.ppas,320 :: 		end;
$0213	$2A33			GOTO	SevenSegmentDisplays_L_138
$0214	$	SevenSegmentDisplays_L_141:
;SevenSegmentDisplays.ppas,322 :: 		1:
$0214	$	SevenSegmentDisplays_L_146:
$0214	$083D			MOVF	_lightballphase, 0
$0215	$3A01			XORLW	1
$0216	$1D03			BTFSS	STATUS, Z
$0217	$2A24			GOTO	SevenSegmentDisplays_L_147
$0218	$	SevenSegmentDisplays_L_145:
;SevenSegmentDisplays.ppas,324 :: 		if GreenLEDDrive=39 then
$0218	$082D			MOVF	_greenleddrive, 0
$0219	$3A27			XORLW	39
$021A	$1D03			BTFSS	STATUS, Z
$021B	$2A23			GOTO	SevenSegmentDisplays_L_149
$021C	$	SevenSegmentDisplays_L_148:
;SevenSegmentDisplays.ppas,326 :: 		LightBallPhase:=2;
$021C	$3002			MOVLW	2
$021D	$00BD			MOVWF	_lightballphase
;SevenSegmentDisplays.ppas,327 :: 		DelayMS(1000);
$021E	$30E8			MOVLW	232
$021F	$00D4			MOVWF	FARG_DelayMS
$0220	$3003			MOVLW	3
$0221	$00D5			MOVWF	FARG_DelayMS+1
$0222	$2543			CALL	_delayms
;SevenSegmentDisplays.ppas,328 :: 		end;
$0223	$	SevenSegmentDisplays_L_149:
$0223	$	SevenSegmentDisplays_L_150:
;SevenSegmentDisplays.ppas,329 :: 		end;
$0223	$2A33			GOTO	SevenSegmentDisplays_L_138
$0224	$	SevenSegmentDisplays_L_147:
;SevenSegmentDisplays.ppas,331 :: 		2:
$0224	$	SevenSegmentDisplays_L_152:
$0224	$083D			MOVF	_lightballphase, 0
$0225	$3A02			XORLW	2
$0226	$1D03			BTFSS	STATUS, Z
$0227	$2A33			GOTO	SevenSegmentDisplays_L_153
$0228	$	SevenSegmentDisplays_L_151:
;SevenSegmentDisplays.ppas,333 :: 		if RedLEDDrive=39 then
$0228	$082C			MOVF	_redleddrive, 0
$0229	$3A27			XORLW	39
$022A	$1D03			BTFSS	STATUS, Z
$022B	$2A32			GOTO	SevenSegmentDisplays_L_155
$022C	$	SevenSegmentDisplays_L_154:
;SevenSegmentDisplays.ppas,335 :: 		LightBallPhase:=0;
$022C	$01BD			CLRF	_lightballphase, 1
;SevenSegmentDisplays.ppas,336 :: 		DelayMS(1000);
$022D	$30E8			MOVLW	232
$022E	$00D4			MOVWF	FARG_DelayMS
$022F	$3003			MOVLW	3
$0230	$00D5			MOVWF	FARG_DelayMS+1
$0231	$2543			CALL	_delayms
;SevenSegmentDisplays.ppas,337 :: 		end;
$0232	$	SevenSegmentDisplays_L_155:
$0232	$	SevenSegmentDisplays_L_156:
;SevenSegmentDisplays.ppas,338 :: 		end;
$0232	$2A33			GOTO	SevenSegmentDisplays_L_138
$0233	$	SevenSegmentDisplays_L_153:
$0233	$	SevenSegmentDisplays_L_138:
;SevenSegmentDisplays.ppas,339 :: 		end;
$0233	$	SevenSegmentDisplays_L_127:
;SevenSegmentDisplays.ppas,340 :: 		end;
$0233	$0008			RETURN
$05D6	$	_displayhexadecimalword:
;SevenSegmentDisplays.ppas,210 :: 		begin
;SevenSegmentDisplays.ppas,211 :: 		CalculateHexadecimalDigits(Value,Digits);
$05D6	$1303			BCF	STATUS, RP1
$05D7	$1283			BCF	STATUS, RP0
$05D8	$0848			MOVF	FARG_DisplayHexadecimalWord, 0
$05D9	$00CB			MOVWF	FARG_CalculateHexadecimalDigits
$05DA	$0849			MOVF	FARG_DisplayHexadecimalWord+1, 0
$05DB	$00CC			MOVWF	FARG_CalculateHexadecimalDigits+1
$05DC	$3036			MOVLW	_digits
$05DD	$00CD			MOVWF	FARG_CalculateHexadecimalDigits+2
$05DE	$2234			CALL	_calculatehexadecimaldigits
;SevenSegmentDisplays.ppas,212 :: 		DisplayDigits(-1,4,True);
$05DF	$30FF			MOVLW	255
$05E0	$00CF			MOVWF	FARG_DisplayDigits
$05E1	$3004			MOVLW	4
$05E2	$00D0			MOVWF	FARG_DisplayDigits+1
$05E3	$30FF			MOVLW	255
$05E4	$00D1			MOVWF	FARG_DisplayDigits+2
$05E5	$2383			CALL	_displaydigits
$05E6	$	SevenSegmentDisplays_L_111:
;SevenSegmentDisplays.ppas,213 :: 		end;
$05E6	$0008			RETURN
$02A6	$	_main:
;SevenSegmentDisplays.ppas,408 :: 		begin
;SevenSegmentDisplays.ppas,409 :: 		Initialize;
$02A6	$24AA			CALL	_initialize
;SevenSegmentDisplays.ppas,411 :: 		CounterValue:=$00;
$02A7	$1283			BCF	STATUS, RP0
$02A8	$01BA			CLRF	_countervalue
$02A9	$01BB			CLRF	_countervalue+1
;SevenSegmentDisplays.ppas,413 :: 		LightBallPhase:=0;
$02AA	$01BD			CLRF	_lightballphase, 1
;SevenSegmentDisplays.ppas,415 :: 		Interrupt_Mode:=-1;
$02AB	$30FF			MOVLW	255
$02AC	$00A1			MOVWF	_interrupt_mode
;SevenSegmentDisplays.ppas,416 :: 		PreviousMode:=Interrupt_Mode;
$02AD	$30FF			MOVLW	255
$02AE	$00BE			MOVWF	_previousmode
;SevenSegmentDisplays.ppas,418 :: 		while True do
$02AF	$	SevenSegmentDisplays_L_173:
;SevenSegmentDisplays.ppas,420 :: 		if I2C_Error<>0 then
$02AF	$0835			MOVF	_i2c_error, 0
$02B0	$3A00			XORLW	0
$02B1	$1903			BTFSC	STATUS, Z
$02B2	$2AC0			GOTO	SevenSegmentDisplays_L_178
$02B3	$	SevenSegmentDisplays_L_177:
;SevenSegmentDisplays.ppas,422 :: 		DigitMasks[0]:=$00;
$02B3	$01A7			CLRF	_digitmasks+0, 1
;SevenSegmentDisplays.ppas,423 :: 		DigitMasks[1]:=$00;
$02B4	$01A8			CLRF	_digitmasks+1, 1
;SevenSegmentDisplays.ppas,424 :: 		DigitMasks[2]:=$00;
$02B5	$01A9			CLRF	_digitmasks+2, 1
;SevenSegmentDisplays.ppas,425 :: 		DigitMasks[3]:=$00;
$02B6	$01AA			CLRF	_digitmasks+3, 1
;SevenSegmentDisplays.ppas,427 :: 		DigitMasks[0]:=I2C_Error;
$02B7	$0835			MOVF	_i2c_error, 0
$02B8	$00A7			MOVWF	_digitmasks+0
;SevenSegmentDisplays.ppas,428 :: 		I2C_Error:=0;
$02B9	$01B5			CLRF	_i2c_error, 1
;SevenSegmentDisplays.ppas,429 :: 		DelayMS(10000);
$02BA	$3010			MOVLW	16
$02BB	$00D4			MOVWF	FARG_DelayMS
$02BC	$3027			MOVLW	39
$02BD	$00D5			MOVWF	FARG_DelayMS+1
$02BE	$2543			CALL	_delayms
;SevenSegmentDisplays.ppas,431 :: 		continue;
$02BF	$2AAF			GOTO	SevenSegmentDisplays_L_173
;SevenSegmentDisplays.ppas,432 :: 		end;
$02C0	$	SevenSegmentDisplays_L_178:
$02C0	$	SevenSegmentDisplays_L_179:
;SevenSegmentDisplays.ppas,435 :: 		Mode:=Interrupt_Mode;
$02C0	$0821			MOVF	_interrupt_mode, 0
$02C1	$00BC			MOVWF	_mode
;SevenSegmentDisplays.ppas,438 :: 		-1:
$02C2	$	SevenSegmentDisplays_L_182:
$02C2	$083C			MOVF	_mode, 0
$02C3	$3AFF			XORLW	255
$02C4	$1D03			BTFSS	STATUS, Z
$02C5	$2ACB			GOTO	SevenSegmentDisplays_L_183
$02C6	$	SevenSegmentDisplays_L_181:
;SevenSegmentDisplays.ppas,440 :: 		RedLEDDrive:=0;
$02C6	$01AC			CLRF	_redleddrive, 1
;SevenSegmentDisplays.ppas,441 :: 		GreenLEDDrive:=0;
$02C7	$01AD			CLRF	_greenleddrive, 1
;SevenSegmentDisplays.ppas,442 :: 		BlueLEDDrive:=0;
$02C8	$01AE			CLRF	_blueleddrive, 1
;SevenSegmentDisplays.ppas,443 :: 		ShowHappyFace;
$02C9	$264B			CALL	_showhappyface
;SevenSegmentDisplays.ppas,444 :: 		end;
$02CA	$2B12			GOTO	SevenSegmentDisplays_L_180
$02CB	$	SevenSegmentDisplays_L_183:
;SevenSegmentDisplays.ppas,446 :: 		1,5:
$02CB	$	SevenSegmentDisplays_L_185:
$02CB	$083C			MOVF	_mode, 0
$02CC	$3A01			XORLW	1
$02CD	$1903			BTFSC	STATUS, Z
$02CE	$2AD3			GOTO	SevenSegmentDisplays_L_184
$02CF	$	SevenSegmentDisplays_L_186:
$02CF	$083C			MOVF	_mode, 0
$02D0	$3A05			XORLW	5
$02D1	$1D03			BTFSS	STATUS, Z
$02D2	$2AD5			GOTO	SevenSegmentDisplays_L_187
$02D3	$	SevenSegmentDisplays_L_184:
;SevenSegmentDisplays.ppas,448 :: 		DoVoltMeter;
$02D3	$20D2			CALL	_dovoltmeter
;SevenSegmentDisplays.ppas,449 :: 		end;
$02D4	$2B12			GOTO	SevenSegmentDisplays_L_180
$02D5	$	SevenSegmentDisplays_L_187:
;SevenSegmentDisplays.ppas,451 :: 		0,2,4,6:
$02D5	$	SevenSegmentDisplays_L_189:
$02D5	$083C			MOVF	_mode, 0
$02D6	$3A00			XORLW	0
$02D7	$1903			BTFSC	STATUS, Z
$02D8	$2AE5			GOTO	SevenSegmentDisplays_L_188
$02D9	$	SevenSegmentDisplays_L_190:
$02D9	$083C			MOVF	_mode, 0
$02DA	$3A02			XORLW	2
$02DB	$1903			BTFSC	STATUS, Z
$02DC	$2AE5			GOTO	SevenSegmentDisplays_L_188
$02DD	$	SevenSegmentDisplays_L_191:
$02DD	$083C			MOVF	_mode, 0
$02DE	$3A04			XORLW	4
$02DF	$1903			BTFSC	STATUS, Z
$02E0	$2AE5			GOTO	SevenSegmentDisplays_L_188
$02E1	$	SevenSegmentDisplays_L_192:
$02E1	$083C			MOVF	_mode, 0
$02E2	$3A06			XORLW	6
$02E3	$1D03			BTFSS	STATUS, Z
$02E4	$2AE7			GOTO	SevenSegmentDisplays_L_193
$02E5	$	SevenSegmentDisplays_L_188:
;SevenSegmentDisplays.ppas,453 :: 		DoCounter;
$02E5	$23DA			CALL	_docounter
;SevenSegmentDisplays.ppas,454 :: 		end;
$02E6	$2B12			GOTO	SevenSegmentDisplays_L_180
$02E7	$	SevenSegmentDisplays_L_193:
;SevenSegmentDisplays.ppas,456 :: 		3,7:
$02E7	$	SevenSegmentDisplays_L_195:
$02E7	$083C			MOVF	_mode, 0
$02E8	$3A03			XORLW	3
$02E9	$1903			BTFSC	STATUS, Z
$02EA	$2AEF			GOTO	SevenSegmentDisplays_L_194
$02EB	$	SevenSegmentDisplays_L_196:
$02EB	$083C			MOVF	_mode, 0
$02EC	$3A07			XORLW	7
$02ED	$1D03			BTFSS	STATUS, Z
$02EE	$2AFA			GOTO	SevenSegmentDisplays_L_197
$02EF	$	SevenSegmentDisplays_L_194:
;SevenSegmentDisplays.ppas,458 :: 		if Mode<>PreviousMode then
$02EF	$083C			MOVF	_mode, 0
$02F0	$063E			XORWF	_previousmode, 0
$02F1	$1903			BTFSC	STATUS, Z
$02F2	$2AF8			GOTO	SevenSegmentDisplays_L_199
$02F3	$	SevenSegmentDisplays_L_198:
;SevenSegmentDisplays.ppas,460 :: 		LightBallPhase:=0;
$02F3	$01BD			CLRF	_lightballphase, 1
;SevenSegmentDisplays.ppas,461 :: 		RedLEDDrive:=39;
$02F4	$3027			MOVLW	39
$02F5	$00AC			MOVWF	_redleddrive
;SevenSegmentDisplays.ppas,462 :: 		GreenLEDDrive:=0;
$02F6	$01AD			CLRF	_greenleddrive, 1
;SevenSegmentDisplays.ppas,463 :: 		BlueLEDDrive:=0;
$02F7	$01AE			CLRF	_blueleddrive, 1
;SevenSegmentDisplays.ppas,464 :: 		end;
$02F8	$	SevenSegmentDisplays_L_199:
$02F8	$	SevenSegmentDisplays_L_200:
;SevenSegmentDisplays.ppas,466 :: 		DoLightBall;
$02F8	$21C1			CALL	_dolightball
;SevenSegmentDisplays.ppas,467 :: 		end;
$02F9	$2B12			GOTO	SevenSegmentDisplays_L_180
$02FA	$	SevenSegmentDisplays_L_197:
;SevenSegmentDisplays.ppas,469 :: 		8:
$02FA	$	SevenSegmentDisplays_L_202:
$02FA	$083C			MOVF	_mode, 0
$02FB	$3A08			XORLW	8
$02FC	$1D03			BTFSS	STATUS, Z
$02FD	$2B08			GOTO	SevenSegmentDisplays_L_203
$02FE	$	SevenSegmentDisplays_L_201:
;SevenSegmentDisplays.ppas,471 :: 		DisplayDecimalWord(CommandValue,-1,4);
$02FE	$0822			MOVF	_commandvalue, 0
$02FF	$00CB			MOVWF	FARG_DisplayDecimalWord
$0300	$0823			MOVF	_commandvalue+1, 0
$0301	$00CC			MOVWF	FARG_DisplayDecimalWord+1
$0302	$30FF			MOVLW	255
$0303	$00CD			MOVWF	FARG_DisplayDecimalWord+2
$0304	$3004			MOVLW	4
$0305	$00CE			MOVWF	FARG_DisplayDecimalWord+3
$0306	$2608			CALL	_displaydecimalword
;SevenSegmentDisplays.ppas,472 :: 		end;
$0307	$2B12			GOTO	SevenSegmentDisplays_L_180
$0308	$	SevenSegmentDisplays_L_203:
;SevenSegmentDisplays.ppas,474 :: 		9:
$0308	$	SevenSegmentDisplays_L_205:
$0308	$083C			MOVF	_mode, 0
$0309	$3A09			XORLW	9
$030A	$1D03			BTFSS	STATUS, Z
$030B	$2B12			GOTO	SevenSegmentDisplays_L_206
$030C	$	SevenSegmentDisplays_L_204:
;SevenSegmentDisplays.ppas,476 :: 		DisplayHexadecimalWord(CommandValue);
$030C	$0822			MOVF	_commandvalue, 0
$030D	$00C8			MOVWF	FARG_DisplayHexadecimalWord
$030E	$0823			MOVF	_commandvalue+1, 0
$030F	$00C9			MOVWF	FARG_DisplayHexadecimalWord+1
$0310	$25D6			CALL	_displayhexadecimalword
;SevenSegmentDisplays.ppas,477 :: 		end;
$0311	$2B12			GOTO	SevenSegmentDisplays_L_180
$0312	$	SevenSegmentDisplays_L_206:
$0312	$	SevenSegmentDisplays_L_180:
;SevenSegmentDisplays.ppas,480 :: 		PreviousMode:=Mode;
$0312	$083C			MOVF	_mode, 0
$0313	$00BE			MOVWF	_previousmode
;SevenSegmentDisplays.ppas,481 :: 		end;
$0314	$2AAF			GOTO	SevenSegmentDisplays_L_173
;SevenSegmentDisplays.ppas,482 :: 		end.
$0315	$2B15			GOTO	$
