;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 11/04/2007 14:40:49
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$28AE			GOTO	_main
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00A2			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00A1			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00A3			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0871			MOVF	STACK_1, 0
$000E	$00AC			MOVWF	STSAVED_1
$000F	$0870			MOVF	STACK_0, 0
$0010	$00AB			MOVWF	STSAVED_0
;SpeechController.ppas,14 :: 		procedure interrupt;
;SpeechController.ppas,16 :: 		if INTCON.T0IF then
$0011	$3000			MOVLW	0
$0012	$190B			BTFSC	INTCON, 2
$0013	$3001			MOVLW	1
$0014	$00F1			MOVWF	STACK_1
$0015	$0871			MOVF	STACK_1, 0
$0016	$1903			BTFSC	STATUS, Z
$0017	$281B			GOTO	SpeechController_L_2
$0018	$	SpeechController_L_1:
;SpeechController.ppas,18 :: 		EOF:=1;
$0018	$3001			MOVLW	1
$0019	$00A0			MOVWF	_eof
;SpeechController.ppas,19 :: 		INTCON.T0IF:=0;
$001A	$110B			BCF	INTCON, 2
$001B	$	SpeechController_L_5:
;SpeechController.ppas,20 :: 		end;
$001B	$	SpeechController_L_2:
$001B	$	SpeechController_L_3:
$001B	$	SpeechController_L_0:
;SpeechController.ppas,21 :: 		end;
$001B	$	L_Interrupt_end:
$001B	$082C			MOVF	STSAVED_1, 0
$001C	$00F1			MOVWF	STACK_1
$001D	$082B			MOVF	STSAVED_0, 0
$001E	$00F0			MOVWF	STACK_0
$001F	$0823			MOVF	?savePCLATH, 0
$0020	$008A			MOVWF	PCLATH
$0021	$0821			MOVF	?saveFSR, 0
$0022	$0084			MOVWF	FSR
$0023	$0E22			SWAPF	?saveSTATUS, 0
$0024	$0083			MOVWF	STATUS
$0025	$0EFF			SWAPF	STACK_15, 1
$0026	$0E7F			SWAPF	STACK_15, 0
$0027	$0009			RETFIE
$0028	$	_delayonems:
;ugeneral.ppas,3 :: 		procedure DelayOneMS;
;ugeneral.ppas,5 :: 		Delay_ms(1);
$0028	$3002			MOVLW	2
$0029	$1303			BCF	STATUS, RP1
$002A	$1283			BCF	STATUS, RP0
$002B	$00FB			MOVWF	STACK_11
$002C	$30FF			MOVLW	255
$002D	$00FA			MOVWF	STACK_10
$002E	$0BFB			DECFSZ	STACK_11, F
$002F	$2831			GOTO	$+2
$0030	$2834			GOTO	$+4
$0031	$0BFA			DECFSZ	STACK_10, F
$0032	$2831			GOTO	$-1
$0033	$282E			GOTO	$-5
$0034	$304A			MOVLW	74
$0035	$00FA			MOVWF	STACK_10
$0036	$0BFA			DECFSZ	STACK_10, F
$0037	$2836			GOTO	$-1
$0038	$	ugeneral_L_0:
;ugeneral.ppas,6 :: 		end;
$0038	$0008			RETURN
$0039	$	_delayms:
;ugeneral.ppas,11 :: 		Count:Word;
;ugeneral.ppas,13 :: 		for Count:=0 to Value-1 do
$0039	$1303			BCF	STATUS, RP1
$003A	$1283			BCF	STATUS, RP0
$003B	$01A7			CLRF	_delayms_local_count
$003C	$01A8			CLRF	_delayms_local_count+1
$003D	$3001			MOVLW	1
$003E	$0225			SUBWF	FARG_DelayMS, 0
$003F	$00A9			MOVWF	FLOC_DelayMS+2
$0040	$3000			MOVLW	0
$0041	$1C03			BTFSS	STATUS, C
$0042	$3F01			ADDLW	1
$0043	$0226			SUBWF	FARG_DelayMS+1, 0
$0044	$00AA			MOVWF	FLOC_DelayMS+3
$0045	$	ugeneral_L_2:
$0045	$0828			MOVF	_delayms_local_count+1, 0
$0046	$022A			SUBWF	FLOC_DelayMS+3, 0
$0047	$1D03			BTFSS	STATUS, Z
$0048	$284B			GOTO	L_DelayMS_0
$0049	$0827			MOVF	_delayms_local_count, 0
$004A	$0229			SUBWF	FLOC_DelayMS+2, 0
$004B	$	L_DelayMS_0:
$004B	$1C03			BTFSS	STATUS, C
$004C	$285A			GOTO	ugeneral_L_5
;ugeneral.ppas,14 :: 		DelayOneMS;
$004D	$2028			CALL	_delayonems
$004E	$0828			MOVF	_delayms_local_count+1, 0
$004F	$062A			XORWF	FLOC_DelayMS+3, 0
$0050	$1D03			BTFSS	STATUS, Z
$0051	$2854			GOTO	L_DelayMS_1
$0052	$0829			MOVF	FLOC_DelayMS+2, 0
$0053	$0627			XORWF	_delayms_local_count, 0
$0054	$	L_DelayMS_1:
$0054	$1903			BTFSC	STATUS, Z
$0055	$285A			GOTO	ugeneral_L_5
$0056	$	ugeneral_L_3:
$0056	$0AA7			INCF	_delayms_local_count, 1
$0057	$1903			BTFSC	STATUS, Z
$0058	$0AA8			INCF	_delayms_local_count+1, 1
$0059	$2845			GOTO	ugeneral_L_2
$005A	$	ugeneral_L_5:
$005A	$	ugeneral_L_1:
;ugeneral.ppas,15 :: 		end;
$005A	$0008			RETURN
$005B	$	_waitforendofplayingmessage:
;SpeechController.ppas,23 :: 		procedure WaitForEndOfPlayingMessage;
;SpeechController.ppas,26 :: 		while (PORTA.6=1) and (EOF=0) do
$005B	$	SpeechController_L_8:
$005B	$3000			MOVLW	0
$005C	$1303			BCF	STATUS, RP1
$005D	$1283			BCF	STATUS, RP0
$005E	$1B05			BTFSC	PORTA, 6
$005F	$3001			MOVLW	1
$0060	$00F2			MOVWF	STACK_2
$0061	$0872			MOVF	STACK_2, 0
$0062	$3A01			XORLW	1
$0063	$30FF			MOVLW	255
$0064	$1D03			BTFSS	STATUS, Z
$0065	$3000			MOVLW	0
$0066	$00F1			MOVWF	STACK_1
$0067	$0820			MOVF	_eof, 0
$0068	$3A00			XORLW	0
$0069	$30FF			MOVLW	255
$006A	$1D03			BTFSS	STATUS, Z
$006B	$3000			MOVLW	0
$006C	$00F0			MOVWF	STACK_0
$006D	$0871			MOVF	STACK_1, 0
$006E	$05F0			ANDWF	STACK_0, 1
$006F	$0870			MOVF	STACK_0, 0
$0070	$1D03			BTFSS	STATUS, Z
$0071	$285B			GOTO	SpeechController_L_8
;SpeechController.ppas,28 :: 		end;
$0072	$	SpeechController_L_9:
;SpeechController.ppas,30 :: 		if EOF=1 then Exit;
$0072	$0820			MOVF	_eof, 0
$0073	$3A01			XORLW	1
$0074	$1D03			BTFSS	STATUS, Z
$0075	$2877			GOTO	SpeechController_L_13
$0076	$	SpeechController_L_12:
$0076	$287F			GOTO	SpeechController_L_6
$0077	$	SpeechController_L_13:
$0077	$	SpeechController_L_14:
;SpeechController.ppas,34 :: 		while (PORTA.6=0) do
$0077	$	SpeechController_L_16:
$0077	$3000			MOVLW	0
$0078	$1B05			BTFSC	PORTA, 6
$0079	$3001			MOVLW	1
$007A	$00F1			MOVWF	STACK_1
$007B	$0871			MOVF	STACK_1, 0
$007C	$3A00			XORLW	0
$007D	$1903			BTFSC	STATUS, Z
$007E	$2877			GOTO	SpeechController_L_16
;SpeechController.ppas,36 :: 		end;
$007F	$	SpeechController_L_17:
$007F	$	SpeechController_L_6:
;SpeechController.ppas,37 :: 		end;
$007F	$0008			RETURN
$0080	$	_recordmessage:
;SpeechController.ppas,39 :: 		procedure RecordMessage;
;SpeechController.ppas,41 :: 		PORTB.2:=0; // PD.
$0080	$1303			BCF	STATUS, RP1
$0081	$1283			BCF	STATUS, RP0
$0082	$1106			BCF	PORTB, 2
$0083	$	SpeechController_L_22:
;SpeechController.ppas,42 :: 		DelayMS(50);
$0083	$3032			MOVLW	50
$0084	$00A5			MOVWF	FARG_DelayMS
$0085	$01A6			CLRF	FARG_DelayMS+1
$0086	$2039			CALL	_delayms
;SpeechController.ppas,44 :: 		PORTB.1:=0; // Record.
$0087	$1086			BCF	PORTB, 1
$0088	$	SpeechController_L_24:
;SpeechController.ppas,45 :: 		PORTB.0:=0; // Chip enabled.
$0088	$1006			BCF	PORTB, 0
$0089	$	SpeechController_L_26:
;SpeechController.ppas,46 :: 		while PORTA.7=1 do
$0089	$	SpeechController_L_28:
$0089	$3000			MOVLW	0
$008A	$1B85			BTFSC	PORTA, 7
$008B	$3001			MOVLW	1
$008C	$00F1			MOVWF	STACK_1
$008D	$0871			MOVF	STACK_1, 0
$008E	$3A01			XORLW	1
$008F	$1903			BTFSC	STATUS, Z
$0090	$2889			GOTO	SpeechController_L_28
;SpeechController.ppas,48 :: 		end;
$0091	$	SpeechController_L_29:
;SpeechController.ppas,49 :: 		PORTB.0:=1; // Chip not enabled.
$0091	$	SpeechController_L_32:
$0091	$1406			BSF	PORTB, 0
$0092	$	SpeechController_L_33:
;SpeechController.ppas,50 :: 		PORTB.1:=1; // Play.
$0092	$	SpeechController_L_34:
$0092	$1486			BSF	PORTB, 1
$0093	$	SpeechController_L_35:
;SpeechController.ppas,52 :: 		DelayMS(50);
$0093	$3032			MOVLW	50
$0094	$00A5			MOVWF	FARG_DelayMS
$0095	$01A6			CLRF	FARG_DelayMS+1
$0096	$2039			CALL	_delayms
;SpeechController.ppas,53 :: 		PORTB.2:=1; // PD.
$0097	$	SpeechController_L_36:
$0097	$1506			BSF	PORTB, 2
$0098	$	SpeechController_L_37:
$0098	$	SpeechController_L_20:
;SpeechController.ppas,54 :: 		end;
$0098	$0008			RETURN
$0099	$	_playmessage:
;SpeechController.ppas,56 :: 		procedure PlayMessage;
;SpeechController.ppas,58 :: 		EOF:=0;
$0099	$1303			BCF	STATUS, RP1
$009A	$1283			BCF	STATUS, RP0
$009B	$01A0			CLRF	_eof, 1
;SpeechController.ppas,59 :: 		TMR0:=255;
$009C	$30FF			MOVLW	255
$009D	$0081			MOVWF	TMR0
;SpeechController.ppas,61 :: 		PORTB.2:=0; // PD.
$009E	$1106			BCF	PORTB, 2
$009F	$	SpeechController_L_40:
;SpeechController.ppas,62 :: 		DelayMS(50);
$009F	$3032			MOVLW	50
$00A0	$00A5			MOVWF	FARG_DelayMS
$00A1	$01A6			CLRF	FARG_DelayMS+1
$00A2	$2039			CALL	_delayms
;SpeechController.ppas,64 :: 		PORTB.1:=1; // Play.
$00A3	$	SpeechController_L_41:
$00A3	$1486			BSF	PORTB, 1
$00A4	$	SpeechController_L_42:
;SpeechController.ppas,65 :: 		PORTB.0:=0; // Chip enabled.
$00A4	$1006			BCF	PORTB, 0
$00A5	$	SpeechController_L_44:
;SpeechController.ppas,66 :: 		Delay_us(1);
$00A5	$0000			NOP
;SpeechController.ppas,67 :: 		PORTB.0:=1; // Chip not enabled.
$00A6	$	SpeechController_L_45:
$00A6	$1406			BSF	PORTB, 0
$00A7	$	SpeechController_L_46:
;SpeechController.ppas,69 :: 		WaitForEndOfPlayingMessage;
$00A7	$205B			CALL	_waitforendofplayingmessage
;SpeechController.ppas,71 :: 		DelayMS(50);
$00A8	$3032			MOVLW	50
$00A9	$00A5			MOVWF	FARG_DelayMS
$00AA	$01A6			CLRF	FARG_DelayMS+1
$00AB	$2039			CALL	_delayms
;SpeechController.ppas,72 :: 		PORTB.2:=1; // PD.
$00AC	$	SpeechController_L_47:
$00AC	$1506			BSF	PORTB, 2
$00AD	$	SpeechController_L_48:
$00AD	$	SpeechController_L_38:
;SpeechController.ppas,73 :: 		end;
$00AD	$0008			RETURN
$00AE	$	_main:
;SpeechController.ppas,76 :: 		PrevPortA5:Boolean;
;SpeechController.ppas,78 :: 		CMCON:=$07; // Without this, reading PORTA fails (returns 0).
$00AE	$3007			MOVLW	7
$00AF	$1303			BCF	STATUS, RP1
$00B0	$1283			BCF	STATUS, RP0
$00B1	$009F			MOVWF	CMCON
;SpeechController.ppas,79 :: 		OPTION_REG:=$E8;
$00B2	$30E8			MOVLW	232
$00B3	$1683			BSF	STATUS, RP0
$00B4	$0081			MOVWF	OPTION_REG
;SpeechController.ppas,80 :: 		INTCON:=$A0;
$00B5	$30A0			MOVLW	160
$00B6	$008B			MOVWF	INTCON
;SpeechController.ppas,82 :: 		TRISA:=$FF;
$00B7	$30FF			MOVLW	255
$00B8	$0085			MOVWF	TRISA
;SpeechController.ppas,84 :: 		TRISB:=$F0;
$00B9	$30F0			MOVLW	240
$00BA	$0086			MOVWF	TRISB
;SpeechController.ppas,85 :: 		PORTB:=$07;
$00BB	$3007			MOVLW	7
$00BC	$1283			BCF	STATUS, RP0
$00BD	$0086			MOVWF	PORTB
;SpeechController.ppas,87 :: 		PrevPortA5:=PORTA.5;
$00BE	$3000			MOVLW	0
$00BF	$1A85			BTFSC	PORTA, 5
$00C0	$3001			MOVLW	1
$00C1	$00F1			MOVWF	STACK_1
$00C2	$0871			MOVF	STACK_1, 0
$00C3	$00A4			MOVWF	_main_local_prevporta5
;SpeechController.ppas,89 :: 		while True do
$00C4	$	SpeechController_L_51:
;SpeechController.ppas,92 :: 		if (PORTA.7=1) and (PORTA.5=0) then
$00C4	$3000			MOVLW	0
$00C5	$1B85			BTFSC	PORTA, 7
$00C6	$3001			MOVLW	1
$00C7	$00F1			MOVWF	STACK_1
$00C8	$0871			MOVF	STACK_1, 0
$00C9	$3A01			XORLW	1
$00CA	$30FF			MOVLW	255
$00CB	$1D03			BTFSS	STATUS, Z
$00CC	$3000			MOVLW	0
$00CD	$00F2			MOVWF	STACK_2
$00CE	$3000			MOVLW	0
$00CF	$1A85			BTFSC	PORTA, 5
$00D0	$3001			MOVLW	1
$00D1	$00F1			MOVWF	STACK_1
$00D2	$0871			MOVF	STACK_1, 0
$00D3	$3A00			XORLW	0
$00D4	$30FF			MOVLW	255
$00D5	$1D03			BTFSS	STATUS, Z
$00D6	$3000			MOVLW	0
$00D7	$00F0			MOVWF	STACK_0
$00D8	$0872			MOVF	STACK_2, 0
$00D9	$05F0			ANDWF	STACK_0, 1
$00DA	$0870			MOVF	STACK_0, 0
$00DB	$1903			BTFSC	STATUS, Z
$00DC	$28E0			GOTO	SpeechController_L_56
$00DD	$	SpeechController_L_55:
;SpeechController.ppas,94 :: 		PORTB.3:=1; // Busy.
$00DD	$	SpeechController_L_58:
$00DD	$1586			BSF	PORTB, 3
$00DE	$	SpeechController_L_59:
;SpeechController.ppas,95 :: 		RecordMessage;
$00DE	$2080			CALL	_recordmessage
;SpeechController.ppas,96 :: 		end
$00DF	$291A			GOTO	SpeechController_L_57
;SpeechController.ppas,99 :: 		else if ((PORTB.4=1) and (PORTA.5=1)) or ((PrevPortA5=0) and (PORTA.5=1)) then
$00E0	$	SpeechController_L_56:
$00E0	$3000			MOVLW	0
$00E1	$1A06			BTFSC	PORTB, 4
$00E2	$3001			MOVLW	1
$00E3	$00F1			MOVWF	STACK_1
$00E4	$0871			MOVF	STACK_1, 0
$00E5	$3A01			XORLW	1
$00E6	$30FF			MOVLW	255
$00E7	$1D03			BTFSS	STATUS, Z
$00E8	$3000			MOVLW	0
$00E9	$00F2			MOVWF	STACK_2
$00EA	$3000			MOVLW	0
$00EB	$1A85			BTFSC	PORTA, 5
$00EC	$3001			MOVLW	1
$00ED	$00F1			MOVWF	STACK_1
$00EE	$0871			MOVF	STACK_1, 0
$00EF	$3A01			XORLW	1
$00F0	$30FF			MOVLW	255
$00F1	$1D03			BTFSS	STATUS, Z
$00F2	$3000			MOVLW	0
$00F3	$00F0			MOVWF	STACK_0
$00F4	$0870			MOVF	STACK_0, 0
$00F5	$0572			ANDWF	STACK_2, 0
$00F6	$00F3			MOVWF	STACK_3
$00F7	$0824			MOVF	_main_local_prevporta5, 0
$00F8	$3A00			XORLW	0
$00F9	$30FF			MOVLW	255
$00FA	$1D03			BTFSS	STATUS, Z
$00FB	$3000			MOVLW	0
$00FC	$00F2			MOVWF	STACK_2
$00FD	$3000			MOVLW	0
$00FE	$1A85			BTFSC	PORTA, 5
$00FF	$3001			MOVLW	1
$0100	$00F1			MOVWF	STACK_1
$0101	$0871			MOVF	STACK_1, 0
$0102	$3A01			XORLW	1
$0103	$30FF			MOVLW	255
$0104	$1D03			BTFSS	STATUS, Z
$0105	$3000			MOVLW	0
$0106	$00F0			MOVWF	STACK_0
$0107	$0872			MOVF	STACK_2, 0
$0108	$05F0			ANDWF	STACK_0, 1
$0109	$0873			MOVF	STACK_3, 0
$010A	$04F0			IORWF	STACK_0, 1
$010B	$0870			MOVF	STACK_0, 0
$010C	$1903			BTFSC	STATUS, Z
$010D	$291A			GOTO	SpeechController_L_61
$010E	$	SpeechController_L_60:
;SpeechController.ppas,101 :: 		PORTB.3:=1; // Busy.
$010E	$	SpeechController_L_63:
$010E	$1586			BSF	PORTB, 3
$010F	$	SpeechController_L_64:
;SpeechController.ppas,102 :: 		PlayMessage;
$010F	$2099			CALL	_playmessage
;SpeechController.ppas,103 :: 		repeat until PORTB.4=0;
$0110	$	SpeechController_L_65:
$0110	$	SpeechController_L_66:
$0110	$3000			MOVLW	0
$0111	$1A06			BTFSC	PORTB, 4
$0112	$3001			MOVLW	1
$0113	$00F1			MOVWF	STACK_1
$0114	$0871			MOVF	STACK_1, 0
$0115	$3A00			XORLW	0
$0116	$1D03			BTFSS	STATUS, Z
$0117	$2919			GOTO	SpeechController_L_68
$0118	$	SpeechController_L_69:
$0118	$291A			GOTO	SpeechController_L_67
$0119	$	SpeechController_L_68:
$0119	$2910			GOTO	SpeechController_L_65
$011A	$	SpeechController_L_67:
;SpeechController.ppas,104 :: 		end;
$011A	$	SpeechController_L_61:
$011A	$	SpeechController_L_62:
$011A	$	SpeechController_L_57:
;SpeechController.ppas,106 :: 		PORTB.3:=0; // Busy.
$011A	$1186			BCF	PORTB, 3
$011B	$	SpeechController_L_71:
;SpeechController.ppas,108 :: 		PrevPortA5:=PORTA.5;
$011B	$3000			MOVLW	0
$011C	$1A85			BTFSC	PORTA, 5
$011D	$3001			MOVLW	1
$011E	$00F1			MOVWF	STACK_1
$011F	$0871			MOVF	STACK_1, 0
$0120	$00A4			MOVWF	_main_local_prevporta5
;SpeechController.ppas,109 :: 		end;
$0121	$28C4			GOTO	SpeechController_L_51
;SpeechController.ppas,110 :: 		end.
$0122	$2922			GOTO	$
